### PR TITLE
BUG: postcss module generates wrong hashes

### LINKED ISSUE #972: BUG: postcss module generates wrong hashes
This a 🐛 bug report

### 🎛 Configuration (.babelrc, package.json, cli command)

postcss.config.js
```js
module.exports = {
  "modules": true,
  "plugins": {
    "autoprefixer": {
      "grid": true,
      "browsers": [
        ">1%",
        "last 2 versions",
        "not ie < 10"
      ],
      "flexbox": "no-2009"
    },
    "postcss-modules": {
      "generateScopedName": "[local]__[hash:base64:4]"
    }
  }
}
```

package.json
```js
{
  "name": "react-project",
  "version": "1.0.0",
  "description": "Small test",
  "main": "index.js",
  "scripts": {
    "start": "parcel public/index.html -p 4000 --no-cache",
    "build": "parcel build public/index.html --out-dir build --no-cache --public-url ./",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {},
  "author": "",
  "license": "ISC",
  "homepage": "",
  "dependencies": {
    "apollo-boost": "^0.1.2",
    "babel-eslint": "^7.2.3",
    "classnames": "^2.2.5",
    "graphql": "^0.13.1",
    "react": "^16.2.0",
    "react-apollo": "^2.0.4",
    "react-dom": "^16.2.0",
    "react-loadable": "^5.3.1",
    "react-router-dom": "^4.2.2"
  },
  "devDependencies": {
    "autoprefixer": "^8.1.0",
    "babel-core": "^6.26.0",
    "babel-plugin-module-resolver": "^3.1.0",
    "babel-preset-react-app": "^3.1.1",
    "eslint": "^4.18.2",
    "eslint-config-react-app": "^2.1.0",
    "eslint-plugin-flowtype": "^2.46.1",
    "eslint-plugin-import": "^2.9.0",
    "eslint-plugin-jsx-a11y": "^5.1.1",
    "eslint-plugin-react": "^7.7.0",
    "node-sass": "^4.7.2",
    "postcss-modules": "^1.1.0",
    "postcss-scss": "^1.0.4"
  }
}
```

.babelrc
```js
{
  "plugins": [
    ["module-resolver", {
      "root": [
        "./src/**/components"
      ],
      "alias": {}
    }]
  ],
  "presets": [
    "react-app"
  ]
}
```
### 🤔 Expected Behavior

Classnames in generated .css file should have hash which is 4 chars long and :global classname should not contain hash

### 😯 Current Behavior

Seems working correctly after restarting parcel.
Example:
`.page-header {}` is converted to `.page-header__1x8y {}` and `:global .app-root` is converted to `.app-root {}`

Classnames are generated incorrectly after changing and saving css file
`.page-header {}` is converted to `._page-header__1x8y_1dxnl_1 {}` and `:global .app-root` is converted to `._app-root_1dxnl_12`

When saving again then classnames are converted as shown below
`.page-header {}` -> `._page-header__1x8y_15rqa_1 {}` 
`:global .app-root` -> `._app-root_15rqa_12`

### 🔦 Context

This is blocker bug.

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.62
| Node             | 8.1.3
| npm/Yarn         | npm 5.7.1
| Operating System | macOS High Sierra

### PR DESCRIPTION
**Pull request by kidandcat**
Fix #972
Close #2865

# ↪️ Pull Request

## ✔️ PR Todo

- [ ] Added/updated unit tests for this change
- [ ] Filled out test instructions (In case there aren't any unit tests)
- [ ] Included links to related issues/PRs

### CODE REVIEW

**Comment by EvilHacker** [comment]
This is a duplicate fix for #2865.
I'm fine either way this issue is resolved.

**Comment by czytelny** [comment]
Hi, any clues when new version including this patch will be released? It's a kind of a blocker :)

**Comment by waspeer** [comment]
How can I use this patch? Do I have to wait for a new release? When is it coming?

**Comment by devongovett** [comment]
It's released in v1.12.4.

**Pull request merged**
