### PR TITLE
Remove sass url loader, move url resolving to PostCSS

### LINKED ISSUE #316: Url() without quotes is not supported in sass
According to https://developer.mozilla.org/en-US/docs/Web/CSS/url there are three formats. 
```sass
div#test {
  background-image: url(./images/test.jpg)
}
```
```js
{
  "name": "parcel-demo",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "parcel index.html"
  },
  "author": "Dustin Deus",
  "license": "ISC",
  "devDependencies": {
    "autoprefixer": "^7.2.3",
    "babel-preset-env": "^1.6.1",
    "node-sass": "^4.7.2",
    "postcss-modules": "^1.1.0",
    "uglify-es": "^3.2.2"
  }
}
```

## Exptected behaviour
`./images/test.jpg` should be in `dist` folder
## Current behaviour
`./images/test.jpg` is not in `dist` folder

Parcel: 1.2.0
Windows 10

### PR DESCRIPTION
**Pull request by DeMoorJasper**
This PR moves url resolving to PostCSS instead of relying on SASS to work.

Figured it might be worth it as it has been a pretty stale issue on the SASS end for a lil while now.

Closes #316

### CODE REVIEW

**Comment by devongovett** [comment]
Won't this be slower since it will have to reparse the generated css?

**Comment by DeMoorJasper** [comment]
@devongovett probably, but at least it works.
It doesn't seem like the sass maintainers are gonna solve this issue any time soon, we can always change it back once they do solve it.

**Comment by DeMoorJasper** [comment]
@devongovett probably, but at least it works.
It doesn't seem like the sass maintainers are gonna solve this issue any time soon, we can always change it back once they do solve it.

**Comment by devongovett** [comment]
I take it dart-sass has the same issue? Maybe we can just contribute?

**Comment by DeMoorJasper** [comment]
Yes dart-sass has the same issue (as it's implementation tries to be identical to node-sass, it's just a little stricter and 100% JS, which makes it more stable in case of our workerfarm setup), not sure if it's a feature or an actual bug.
From the issue we have it seems to be a feature they haven't fully worked out yet from a design perspective although I'm not sure.

This seemed like the cleanest way to implement a hotfix for the meantime.

**Comment by DeMoorJasper** [comment]
Found the issue where they're discussing the url loader design https://github.com/sass/sass/issues/2535

**Comment by devongovett** [comment]
ok sure, but even if they are re-designing it seems like a bug that it works when quoted but not when unquoted...

I will merge this for now, but let's keep an eye on that sass issue and revert once they figure it out so we regain some performance.

**Pull request merged**
