### PR TITLE
Add typechecking to default parcelconfig

### PR DESCRIPTION
**Pull request by DeMoorJasper**
# ↪️ Pull Request

This PR enabled TS typechecking by default. This is probably more expected behaviour than the current silent behaviour.

Related #4022

## ✔️ PR Todo

- [x] Added/updated unit tests for this change
- [x] Filled out test instructions (In case there aren't any unit tests)
- [x] Included links to related issues/PRs

### CODE REVIEW

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>packages/benchmarks/kitchen-sink ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 7.68s | +238.00ms |
| Cached | 3.93s | +57.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/parcel.ff215454.webp | 102.94kb | +0.00b | 255.00ms | +61.00ms ⚠️ |
| dist/modern/parcel.76ee4591.webp | 102.94kb | +0.00b | 264.00ms | +71.00ms ⚠️ |
| dist/legacy/index.js | 520.00b | +0.00b | 569.00ms | +34.00ms ⚠️ |
| dist/modern/index.js | 453.00b | +0.00b | 563.00ms | +33.00ms ⚠️ |
| dist/modern/index.css | 29.00b | +0.00b | 1.38s | +85.00ms ⚠️ |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/parcel.ff215454.webp | 102.94kb | +0.00b | 418.00ms | +403.00ms ⚠️ |
| dist/modern/parcel.76ee4591.webp | 102.94kb | +0.00b | 417.00ms | +404.00ms ⚠️ |
| dist/legacy/index.js | 520.00b | +0.00b | 423.00ms | +403.00ms ⚠️ |
| dist/modern/index.js | 453.00b | +0.00b | 417.00ms | +402.00ms ⚠️ |
| dist/legacy/index.css | 29.00b | +0.00b | 417.00ms | +404.00ms ⚠️ |
| dist/modern/index.css | 29.00b | +0.00b | 415.00ms | +402.00ms ⚠️ |

</p></details>

<details><summary>packages/benchmarks/react-hn ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 11.74s | -711.00ms 🚀 |
| Cached | 4.14s | -8.00ms |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/module/index.js | 34.29kb | +0.00b | 16.00ms | +5.00ms ⚠️ |
| dist/main/index.js | 34.27kb | +0.00b | 22.00ms | +6.00ms ⚠️ |

</p></details>

<details><summary>packages/benchmarks/ak-editor ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 3.43m | -565.00ms |
| Cached | 6.39s | +113.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.js | 2.33mb | +6.00b ⚠️ | 1.99m | +127.00ms |
| dist/media-viewer.81fbeba4.js | 87.54kb | +0.00b | 8.92s | +1.87s ⚠️ |
| dist/card.c0473744.js | 76.79kb | +0.00b | 8.92s | +1.87s ⚠️ |
| dist/ResourcedEmojiComponent.2d80adbd.js | 2.25kb | +0.00b | 5.63s | -1.39s 🚀 |
| dist/esm.976debcc.js | 178.00b | +0.00b | 5.52s | -1.45s 🚀 |
| dist/dropzone.976debcc.js | 177.00b | +1.00b ⚠️ | 1.99m | +1.36m ⚠️ |
| dist/clipboard.976debcc.js | 177.00b | +1.00b ⚠️ | 39.67s | +1.06s |
| dist/browser.976debcc.js | 177.00b | +1.00b ⚠️ | 1.33m | +40.91s ⚠️ |
| dist/editorView.976debcc.js | 177.00b | -1.00b 🚀 | 39.20s | -22.58s 🚀 |
| dist/media-card-analytics-error-boundary.976debcc.js | 176.00b | -5.00b 🚀 | 41.10s | -1.30m 🚀 |
| dist/16.976debcc.js | 174.00b | -5.00b 🚀 | 39.67s | -270.00ms |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.js | 2.33mb | +6.00b ⚠️ | 385.00ms | -17.00ms |
| dist/pdfRenderer.85e56a51.js | 1.11mb | +0.00b | 247.00ms | -13.00ms 🚀 |
| dist/smartMediaEditor.678dca17.js | 601.49kb | +0.00b | 175.00ms | -14.00ms 🚀 |
| dist/ui.ab1a2648.js | 73.71kb | +0.00b | 129.00ms | -14.00ms 🚀 |
| dist/smartMediaEditor.25b0ed57.js | 67.35kb | +0.00b | 129.00ms | -14.00ms 🚀 |
| dist/quote.88bfdca4.js | 936.00b | +0.00b | 137.00ms | -7.00ms 🚀 |
| dist/panel.23cd7224.js | 788.00b | +0.00b | 137.00ms | -7.00ms 🚀 |
| dist/table.4ace5843.js | 780.00b | +0.00b | 136.00ms | -7.00ms 🚀 |
| dist/panel-success.6a7b97d7.js | 728.00b | +0.00b | 138.00ms | -7.00ms 🚀 |
| dist/simpleHasher.884d4eb6.js | 446.00b | +0.00b | 123.00ms | -15.00ms 🚀 |
| dist/esm.976debcc.js | 176.00b | +2.00b ⚠️ | 162.00ms | -2.00ms |
| dist/media-card-analytics-error-boundary.976debcc.js | 176.00b | +2.00b ⚠️ | 160.00ms | -1.00ms |
| dist/dropzone.976debcc.js | 176.00b | +2.00b ⚠️ | 157.00ms | -2.00ms |
| dist/clipboard.976debcc.js | 176.00b | +2.00b ⚠️ | 157.00ms | -1.00ms |
| dist/browser.976debcc.js | 176.00b | +2.00b ⚠️ | 156.00ms | -2.00ms |
| dist/16.976debcc.js | 176.00b | +2.00b ⚠️ | 144.00ms | -5.00ms |
| dist/editorView.976debcc.js | 176.00b | +2.00b ⚠️ | 122.00ms | -3.00ms |

</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/255196869571904009)**

**Comment by DeMoorJasper** [comment]
Gonna close this...

**Comment by uglycoyote** [comment]
@DeMoorJasper it's not clear from looking at this why it was closed?

**Comment by DeMoorJasper** [comment]
@uglycoyote it had gotten too much merge conflicts and I doubt it would've ever gotten merged. From the issue it seems there's almost just as much people who want this as don't want this

**Comment by astegmaier** [comment]
@DeMoorJasper - I think you're referring to #4022, right? My reading of that (very long, very contentious) thread was that there were at least two issues being discussed:

1. Whether to use `tsc` instead of `babel` to do the actual transpilation
2. Having parcel check for typescript semantic errors by default (i.e. this PR)

It seemed like a lot of folks who were new to parcel didn't understand this distinction at first (until [this comment](https://github.com/parcel-bundler/parcel/issues/4022#issuecomment-597304918) helped clarify toward the end of the discussion).

It seems accurate to say that issue 1 was very contentious because there are some very solid performance-related reasons to prefer babel. For issue number 2, it seemed more one-sided in favor of turning on semantic checking by default (although not 100% unanimous). I'd love to see a wider discussion around [this comment](https://github.com/parcel-bundler/parcel/issues/4022#issuecomment-597988422), which posed the question directly.

My two-cents as a heavy typescript user is that I pretty much always want to get semantic type error feedback from my build tool, so it would be great to have this be the default. This is for two main reasons:
1. I come from a background of having used `tsc`, `webpack` (with `fork-ts-webpack-checker-plugin` and `ts-loader`) and `create-react-app` on various projects, all of which do this. (This is more of a habit/subjective expectation, but I suspect most of parcel's typescript users will share a similar background).
2. As [this comment](https://github.com/parcel-bundler/parcel/issues/4022#issuecomment-579624565) points out, VSCode and other editors won't report errors on files that are not open, and don't seem likely to support this in the future.

**Comment by DeMoorJasper** [comment]
@astegmaier You’re right opinions were very mixed, personally I don’t care which one is preferred as it’s probably a good idea to run tsc in ci builds anyway. (For typechecking)

The main reason for closing this was merge conflicts as I have enough PRs that need rebasing and have a higher chance of getting merged soonish

**Comment by astegmaier** [comment]
> The main reason for closing this was merge conflicts as I have enough PRs that need rebasing and have a higher chance of getting merged soonish

Yeah no worries. If the discussion develops and we get everyone on board with the idea of turning this on by default, I'm happy to take care of the PR.

**Comment by uglycoyote** [comment]
Thanks for the replies.  I didn't mean to cause a firestorm and I know there's a bit of a debate about this contentious issue on #4022, which I have replied on a few times.  But I was curious because it the effort to change the default behaviour was started by someone who's a primary contributor and then abruptly stopped without an explanation.  

Upon reading this, since the "gonna close this" comment was one day after posting the benchmarks, It made me wonder if the performance numbers in the benchmarks are what clinched the decision to close it, but it sound like it was other issues.  

I looked at the benchmarks but there were too many numbers and I didn't know what the format of the report was, I could not really tell whether they said something interesting about the performance implications of this change.  I'm aware that performance is the big argument in favour of leaving it the way it was (with no use of typechecking) but had not seen any figures about what the impact of enabling typechecking was by default.

**Comment by astegmaier** [comment]
Correct me if I'm wrong, but I don't think turning on `@parcel/validator-typescript` by default (what I called "issue 2" above) should impact the performance of the main build, because validators only run after the bundle graph is finished. See here:

https://github.com/parcel-bundler/parcel/blob/7c0aa3d2b9cd4a8d3cb6135e6b07d05f33406389/packages/core/core/src/Parcel.js#L268-L284

(It's a different story for using @parcel/transformer-typescript-tsc` over babel during the transform phase - see [this comment](https://github.com/parcel-bundler/parcel/issues/4022#issuecomment-578571713)).

**Comment by devongovett** [comment]
Please continue this discussion on #4022 rather than on this closed PR.

**Pull request closed without merging**
