### PR TITLE
change Uglify to Terser

### LINKED ISSUE #1381: New dependency name: uglify-es => terser #1
* 🙋 feature request*

There has been development on a new fork of uglify-es, which is now called terser and has its own package!

    "terser": "^3.7.3"

Please upgrade to our new version.

### PR DESCRIPTION
**Pull request by DeMoorJasper**
Uglify-ES has been discontinued and Terser is a continuation of this package. This PR changes to Terser

Close #1381

### CODE REVIEW

**Comment by devongovett** [comment]
hmm... I'm thinking of just switching to babel-minify. Most of the time we already process the asset with babel, so stringifying and re-parsing for uglify is probably not faster than just using babel-minify. And we can help contribute perf fixes to babel-minify where needed.

**Comment by devongovett** [comment]
I've been experimenting with that for scope hoisting btw.

**Comment by kzc** [comment]
> Most of the time we already process the asset with babel, so stringifying and re-parsing for uglify is probably not faster than just using babel-minify.

That's fine of course, but be aware that @fabiosantoscode just recently added ES6+ ESTree support in `@fabiosantoscode/uglify-es` (also present in`terser`). You might give that a spin before deciding.

**Comment by kzc** [comment]
`babel-minify` is much faster than it used to be, but there's still a noticeable perf and size difference:

```
$ terser -V
terser 3.7.5

# both mangle and compress enabled
$ /usr/bin/time terser d3.js -mc | gzip | wc -c
        6.03 real         7.04 user         0.17 sys
   70954

# only mangle enabled
$ /usr/bin/time terser d3.js -m | gzip | wc -c
        1.44 real         1.62 user         0.06 sys
   72730
```

     '0.5.0-alpha.01eac1c3': '2018-05-17T23:39:29.993Z' 

```
$ babel-minify -V
0.5.0-alpha.01eac1c3

$ /usr/bin/time babel-minify d3.js | gzip | wc -c
       14.17 real        14.45 user         0.20 sys
   72238
```
I imagine a mangle-only run of `babel-minify` would also be comparably faster, but I don't know how to configure it.

**Comment by kzc** [comment]
> I think we should focus our efforts around improving babel-minify

Absolutely - do whatever you think makes sense for your project. 

> avoid an additional generate + parse step in order to get from babel to uglify.

`terser` is just a maintained fork of `uglify-es`. An extra generate/parse step for ES6+ would not be required in `terser` as was the case in `uglify-es` because `terser` supports converting babel-compatible ES6+ ESTree AST to `terser` AST and back again, which is comparatively quick by comparison.

> That only made it into babel 7, so you may not be seeing it in your benchmarks if you're running 6 

`babel-minify` timing was made using latest babel 7 beta and latest alpha minify transforms:

```
├─┬ babel-minify@0.5.0-alpha.01eac1c3
│ ├─┬ @babel/core@7.0.0-beta.47
│ │ ├─┬ @babel/code-frame@7.0.0-beta.47
...
```
Looking beyond AST conversion, some algorithm(s) in `babel-minify` may still have O(N^2) complexity judging by slower timings with larger inputs:

```
$ /usr/bin/time terser app.js -mc | gzip | wc -c
       21.08 real        22.41 user         0.35 sys
  400385
```
```
$ /usr/bin/time babel-minify app.js | gzip | wc -c
       76.05 real        76.75 user         0.63 sys
  406098
```

But I'm sure with enough effort someone will be able to identify these remaining bottlenecks to benefit all `babel-minify` users.

**Comment by devongovett** [comment]
btw, you can explicitly disable that behavior by calling `path.skip()` after replacing/inserting a node that doesn't need to be processed further. Maybe doing that in a few key places would help.

**Comment by kzc** [comment]
@fathyb That's interesting. If that's the case, is there any way to effectively limit the number of passes in `babel-minify`? You get greatly diminishing returns after a couple of passes in a minifier. 

BTW, there are still a number of ESTree (a.k.a. "spidermonkey") AST conversion issues in `terser` for ES6+ code to be worked out. Probably just a few tweaks are required. No one is using this functionality at the moment. Should you change your mind and decide to use it, feel free to report any issues to the `terser` project.

**Comment by devongovett** [comment]
I tried to use https://www.npmjs.com/package/babel-to-estree and then uglify's converter from estree early on but it was really buggy since babel's ast is so different, so we switched to converting to a string and re-parsing.

**Comment by DeMoorJasper** [comment]
@fathyb resolved all merge conflicts. This PR should be ready to be merged, apparently the issue regarding name squatting has been resolved.

**Comment by kzc** [comment]
I appreciate that the plan is to replace `uglify-es` with `babel-minify`, but I don't see any harm in this drop-in replacement pull request in the meantime.

`uglify-es` has been unmaintained for several months and has a number of significant bugs which have been corrected by `terser`. I'm surprised that Parcel users haven't encountered them.

**Comment by fathyb** [comment]
We all have a direct interest in letting babel-minify and Terser compete for better size and speed. By letting users to choose which one to use we make comparing each other more easy and thus encourage competition.

@devongovett what do you think of merging this and implement babel-minifiy and Terser on the scope-hoisting PR? We could use babel-minify by default for speed and let user switch to Terser by using a `.uglifyrc` or `.terserrc`.

**Comment by kzc** [comment]
Competition is always good. But I'd encourage this project to perform timings on real-life scenarios before choosing a default minifier. Very few bother to change the defaults in practise - particularly for a zero config bundler.

**Comment by Morgul** [comment]
> uglify-es has been unmaintained for several months and has a number of significant bugs which have been corrected by terser. I'm surprised that Parcel users haven't encountered them.

@kzc Actually, I've run into a few bugs that seemed `uglify-es` related. The 'fix' for me was to turn off mangling in parcel; a terrible "work around". (#1294, and #1363 are two off the top of my head.) I would be really interested to know if this merge request would just solve those issues.

**Comment by kzc** [comment]
>  I would be really interested to know if this merge request would just solve those issues.

Dozens of bugs have been fixed in `terser`. Either test against this PR directly, or use a `yarn` alias to replace `uglify-es` with `terser`. Google to find out how.

**Pull request merged**
