### PR TITLE
Fix #2786 (links in HTML files in sub directories)

### LINKED ISSUE #2786: wrong relative links in sub directory when a relative public url is specified
# 🐛 bug report
This bug is related to the issue https://github.com/parcel-bundler/parcel/issues/2774
and also to this pull request: https://github.com/parcel-bundler/parcel/pull/2740

If you specify the parameter `--public-url ./` when calling the parcel cli (like it is described in the doc for the cli) the relative links (e.g. hrefs) are relative to the root directory and not relative to the sub directory in which the bundle/html file is located.

[repro-html-in-subdir.zip](https://github.com/parcel-bundler/parcel/files/2962165/repro-html-in-subdir.zip)

```
src
├── subdir1
│   ├── subdirpage.html
│   ├── subdirpage.js
│   └── subdirpage2.html
└── index.html
```

## 🎛 Configuration (.babelrc, package.json, cli command)

See attached project above.

```
{
  "name": "repro-html-in-subdir",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "clean": "rm -rf .cache node_modules dist",
    "start": "parcel serve src/index.html --global Global",
    "build": "parcel build src/index.html --detailed-report --log-level 4 --no-source-maps --no-minify --public-url ./"
  },
  "devDependencies": {
    "parcel-bundler": "1.x"
  }
}
```
## 🤔 Expected Behavior

After you call `yarn build` in the output directory `dist` there is the file `subdir1/subdirpage.html`.
The content of the file should be:
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sub Directory Page</title>
</head>
<body>
    <h1>Sub Directory Page</h1>

    <a href="subdirpage2.html">subdirpage2.html</a>

    <script src="../subdirpage.7501a095.js"></script>
</body>
</html>
```
The bundle resulting from the file `subdir1/subdirpage.js` is `subdirpage.7501a095.js` which currently is located in the root dist folder.
The file `subdirpage2.html` is located in the same folder as `subdirpage.html` the the relative link should reflect this fact.

## 😯 Current Behavior

The content of the bundled file `subdir1/subdirpage.html` is the following:
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sub Directory Page</title>
</head>
<body>
    <h1>Sub Directory Page</h1>

    <a href="subdir1/subdirpage2.html">subdirpage2.html</a>

    <script src="subdirpage.7501a095.js"></script>
</body>
</html>
```

As you see the URL of the href to the file `subdirpage2.html` which is in the same folder as `subdirpage.html` is wrong (does not point to the current folder).
Also the link to the bundled JavaScript file `subdirpage.7501a095.js` which is located in the root dist folder does not point to the parent folder.

## 💁 Possible Solution

In my opinion in the method `Asset.replaceBundleNames()` ([`/packages/core/parcel-bundler/src/Asset.js`](https://github.com/parcel-bundler/parcel/blob/parcel-bundler%401.12.1/packages/core/parcel-bundler/src/Asset.js#L260)) the relative URL should be calculated based on the directory of the parent bundle path (like the path which is calculated here:
https://github.com/parcel-bundler/parcel/blob/parcel-bundler%401.12.1/packages/core/parcel-bundler/src/Bundle.js#L162).
The parent bundle in the example above is `subdir1/subdirpage.html`.
This should be only be done if the replaced bundle path is relative and the value of the publicURL option is a relative url (like `./`).

```
replaceBundleNames(bundleNameMap) {
...
...
        for (let [name, map] of bundleNameMap) {
          newValue = newValue
            .split(name)
            .join(this.makeBundlePathRelativeToParentBundle(map));
        }
...
...
}

  makeBundlePathRelativeToParentBundle(bundlePath) {
    if (path.isAbsolute(bundlePath)) {
      return bundlePath;
    }
    // if this.options.publicURL is relative also return bundlePath
    
    const parentBundleRelativePath = // get relative path of this.parentBundle (something like this.parentBundle.getHashedBundleName()??)
    const parentBundleRelativeDir =
      path.dirname(parentBundleRelativePath) || '.';
    const relativeBundlePath = path.relative(
      parentBundleRelativeDir,
      bundlePath
    );
    return relativeBundlePath;
  }
```

## 🔦 Context

We as a dev team want to structure our web application by putting HTML files and JavaScript files of parts of the page into sub directories. This is currently only possible for JavaScript files but not for HTML file because of this bug.
The example project attached to this issue is an abstract representation of our web application.

## 💻 Code Sample

[repro-html-in-subdir.zip](https://github.com/parcel-bundler/parcel/files/2962165/repro-html-in-subdir.zip)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.1 |
| Node             | v10.13.0
| npm/Yarn         | Yarn 1.13.0
| Operating System | Ubuntu 18.10

### PR DESCRIPTION
**Pull request by codingphil**
# ↪️ Pull Request

Fixes bug #2786 

See description of the bug above.

Now in `Asset.replaceBundleNames()` for each bundle of which the URL is inserted into asset content the a URL relative to its parent bundle is calculated so the URL is correct when the bundled output is deployed. This is only done when a relative public URL is specified in the options.

## 🚨 Test instructions

See added integration tests in `packages/core/integration-tests/test/html.js`

## ✔️ PR Todo

- [x] Added/updated unit tests for this change
- [x] Filled out test instructions (In case there aren't any unit tests)
- [x] Included links to related issues/PRs

### CODE REVIEW

**Comment by mischnic** [comment]
Not sure if this is correct, but tests are failing on Windows (likely `\` instead of `/`) - maybe you need to use the functions at `path.posix.*` instead of `path.*`.

**Comment by codingphil** [comment]
> Not sure if this is correct, but tests are failing on Windows (likely `\` instead of `/`) - maybe you need to use the functions at `path.posix.*` instead of `path.*`.

The path stored in the bundle object is always OS dependent which is OK in my opinion.
However, the link in the asset (HTML file) should always use unix-style directory separators in the URLs. With the first commit f73912d only for relative paths the directory separator was converted to unix-style but not for the absolute paths. The behavior for the absolute paths did not change.
With the commit 3c9f776 the URLs now always use unix-style directory separators in URLs.

**Comment by codingphil** [comment]
Now the test "elm should produce a basic Elm bundle" is failing and I'm not sure about the cause.
It says "The binary data at /home/vsts/.elm/0.19.0/package/elm/browser/1.0.0/objs.dat is corrupt."
https://dev.azure.com/devongovett/devongovett/_build/results?buildId=1352&view=ms.vss-test-web.build-test-results-tab

**Comment by mischnic** [comment]
You can ignore the elm test

**Pull request closed without merging**
