### PR TITLE
add @parcel/transformer-reason

### PR DESCRIPTION
**Pull request by abdullahtariq1171**
# ↪️ Pull Request

This PR tries to add reason plugin for transforms. Fixes https://github.com/parcel-bundler/parcel/issues/3359

Todo:
- [x] Compiling Reason to JavaScript with bsb-js
- [ ] Collecting dependencies as included files so Parcel watches them (Parcel 1 does not currently do this properly)

## ✔️ PR Todo

- [ ] Added/updated unit tests for this change
- [ ] Filled out test instructions (In case there aren't any unit tests)
- [ ] Included links to related issues/PRs

### CODE REVIEW

**Comment by abdullahtariq1171** [comment]
I'm not exactly sure how gonna collect dependencies as included files, any help would be very useful.

**Comment by mischnic** [comment]
I have no experience with bucklescript, but the `bsb-js` was last updated one year ago.
The official docs talk about `bs-platform` (https://bucklescript.github.io/docs/en/installation) and to not use an integration with a bundler 😕 (https://bucklescript.github.io/docs/en/interop-with-js-build-systems#popular-js-build-systems)

**Comment by abdullahtariq1171** [comment]
yes, `bsb-js` is just a wrapper on top of `bs-platform`.

I've thinking about this, we can detect the dependencies using regex but since we use `bsb-js`, and it doesn't return any information. So how we going to actually collect these dependencies. 

cc: @devongovett 

---

Also here is previous discussion https://github.com/parcel-bundler/parcel/pull/342, might be helpful some questions.

**Comment by gugahoa** [comment]
Hi all, maybe this PR could take inspiration from the new react-hooks template for bsb found here: https://github.com/BuckleScript/bucklescript/blob/3fe3e854f8a0d31691d396e5a41e728f58f2f6cd/jscomp/bsb/templates/react-hooks/watcher.js

It shows how to do a simply watcher.

**Comment by DeMoorJasper** [comment]
@gugahoa it's more than just watching we need to know all the files that are being compiled/bundled for cache invalidation as well. Unless we simply disable cache for reason, but that's not really optimal.

**Comment by gugahoa** [comment]
@DeMoorJasper What would be the impact of disabling cache for reason?

**Comment by DeMoorJasper** [comment]
@gugahoa it would be a lot slower to build reason

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mischnic** [comment]
bsb seems to generate a file listing all dependencies of a source file: https://bucklescript.github.io/docs/en/interop-with-js-build-systems#getting-projects-dependencies

But you need to explicitly specify source folders in the `bsconfig.json` file. bsb really doesn't want to be integrated into another build system.

**Comment by gugahoa** [comment]
@mischnic @DeMoorJasper 
So in simple terms, a good enough reason plugin would:
- Run bsb in watch mode with websocket
- Listen to websocket to be notified on change
- On notifiy, <somehow> discover the changed file
- Find the .mlast.d of that file and invalidate those files

Is that it?

**Comment by DeMoorJasper** [comment]
@abdullahtariq1171 could you update this PR to be more complete as requested?

**Comment by abdullahtariq1171** [comment]
hey guys I'm sorry I won't be able to work on this. Anyone want's to grab this from here would be welcomed.

**Pull request closed without merging**
