### PR TITLE
Add tsconfig path customization

### PR DESCRIPTION
**Pull request by antongolub**
# ↪️ Pull Request 
Adds custom `tsconfig` path through CLI. Refers to  #1251

## 💻 Examples

```
NODE_ENV=production parcel build --tsconfig tsconfig.rhino.json
```

## ✔️ PR Todo

- [x] Added/updated unit tests for this change
- [ ] Filled out test instructions (In case there aren't any unit tests)
- [x] Included links to related issues/PRs

### CODE REVIEW

**Comment by devongovett** [comment]
I don't think we should add typescript specific options to Parcel's CLI. What problem are you trying to solve? Normally tsconfig is resolved based on the location of your typescript files. Why doesn't this work for you?

**Comment by antongolub** [comment]
In our case we use different build strategies for a single `src/main` to generate several runtime-specific bundles ("nodejs10", "rhino", "browser1", "browser2", ...). The current CLI API requires additional directories, but we'd like to keep [maven dir contract](https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html) as much as possible.

**Comment by sushruth** [comment]
@devongovett I think this is more of a bundler problem than typescript problem. Just having a way to specify which `tsconfig.RANDOM_NAME.json` to use for which target could be a great feature and looking at  `packages/utils/ts-utils/src/loadTSConfig.js`, looks like an easy feature to provide without breaking many things. This is mostly to tell the bundler simply what file to use.

**Comment by mmunte-impeo** [comment]
This is badly needed. Those who use typescript on large and complex projects will sure know why it is important to be able to have multiple tsconfig files. 

I really hope this PR is completed. I have evaluated parcel for a simple project and like it a lot. But my larger projects would require this PRs feature.

**Comment by DeMoorJasper** [comment]
Parcel 1 no longer accepts new features, therefore I'll close this. Also not sure if this is the way to do this, maybe we can find a better way to configure this for Parcel 2?

**Comment by elzii** [comment]
I'll chime in with a common use case:

Often in developing plugins for applications that provide a webview, I will want:

1. A `tsconfig.webview.json`config
2. A `tsconfig.plugin.json` config
3. A no-frills dev bundler for the webview, to not be beholden to constantly restarting the app (think Sketch for example), for which Parcel is a good choice.

Relying on it just to detect `tsconfig.json` leaves you at the mercy of the other bundlers...

**Pull request closed without merging**
