### PR TITLE
Throw error when asset.package is used and remove deasync

### PR DESCRIPTION
**Pull request by nerdbeere**
Hello there,

this PR removes the `deasync` dependency as suggested in https://github.com/parcel-bundler/parcel/issues/2214

I understand that this introduces a breaking change but I needed it fixed for a project of mine so feel free to close the PR if you like.

For People who need that fix can either use `git+https://git@github.com/nerdbeere/parcel.git#1.x` in their `package.json` or use the temporary package `parcel-bundler-without-deasync`.

### CODE REVIEW

**Comment by DeMoorJasper** [comment]
I don’t think any plugins still use the old field so this should be fine afaik

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by devongovett** [comment]
This is technically a breaking change which means we cannot release this until Parcel 2 (which won't need this anyway).

FYI looks like deasync was updated 10 days ago, so perhaps we just need to upgrade it in parcel?

**Comment by nerdbeere** [comment]
@devongovett You are right, it is a breaking api change. So why not release a 2.0.0 containing this fix?

**Comment by devongovett** [comment]
We don't do breaking changes without a really good reason, and this is not one. Can you fix the issue without removing deasync?

**Comment by DeMoorJasper** [comment]
@devongovett doing a pr to this repo (https://github.com/abbr/deasync-bin) with the binaries for Node 11 should probably solve the issues with deasync, as it did when we had a similar issue with node 10 support.

**Pull request closed without merging**
