### PR TITLE
Support <script type="module"> when serving with HMR

### LINKED ISSUE #4773: Specifying type="module" for script tag breaks HMR
# 🐛 bug report

When I add a type="module" attribute in a script tag in my index.html, the HMR fails when parcel wants to reload the page on saving changes to the index.html file.

In the browser the error is the following
```
HMRRuntime.js:56 Uncaught TypeError: Cannot read property 'parcelRequire' of undefined
    at HMRRuntime.js:56
    at Array.forEach (<anonymous>)
    at WebSocket.ws.onmessage (HMRRuntime.js:53)
```

## 🎛 Configuration

No configuration, just a html file like the following

```html
<!DOCTYPE html>
<html>
	<head>
		<script src="./index.js" type="module"></script>
	</head>
	<body>
		<div>test</div>
	</body>
</html>
```

### PR DESCRIPTION
**Pull request by oliverdunk**
# ↪️ Pull Request

Hot Module Replacement was failing when a `<script type="module">` was present on the
page. Building for development now ignores the type attribute, allowing HMR to be
used. The attribute is preserved when using the parcel build command.

In development, scripts with the `nomodule` attribute are now removed entirely. This is under the assumption a `<script type="module">` is also present, which will run in all browsers since the type was removed.

Resolves #4773 

## Thought Process

I discussed a solution with @mischnic in https://github.com/parcel-bundler/parcel/issues/4773. The plan was to remove type="module" scripts, under the assumption a nomodule script would be present, and to remove the nomodule attribute so that script ran in all scenarios. I decided to do things the other way around, because:

- Tests like [this one](https://github.com/parcel-bundler/parcel/blob/v2/packages/core/integration-tests/test/integration/html-inline-js-shared/index.html#L7) use module scripts alone and expect them to remain. It'd be fiddly to change this expectation.
- I can imagine someone new to Parcel adding a `<script type="module">` without the `nomodule` counterpart. Keeping module scripts and stripping the type means the one script they've added won't disappear.

I also chose to add the `defer` attribute, as suggested [here](https://github.com/parcel-bundler/parcel/issues/1401#issuecomment-656171260). This makes sense because it makes our script more closely resemble the fact that this is [added by default](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#attr-defer) on module scripts.

I came across https://github.com/parcel-bundler/parcel/pull/2872, but I believe that applied in production, making it a more significant change. This MR is limited to development builds, as HMR is now the only thing broken by module scripts - scripts with type="module" work in production just fine.

## 🚨 Test instructions

Run the new integration tests.

You can also copy the react-hmr project from `packages/examples`, add `type="module"` to the script, and check that HMR works when running `parcel serve`.

## ✔️ PR Todo

- [x] Added/updated unit tests for this change
- [x] Filled out test instructions (In case there aren't any unit tests)
- [x] Included links to related issues/PRs

### CODE REVIEW

**Comment by oliverdunk** [comment]
@mischnic I'd love some feedback here. Is it something you could look at, or is there someone else that might be better?

**Comment by mischnic** [comment]
After some discussion, we think that removing `nomodule` scripts and removing `type="module"` should only be done if there are actually two corresponding module/nomodule tags. 😬 

This should be doable without traversing twice by keeping adding the script tags to a list and modifying/removing/`addDependency()` them after traversal is done.

> I also chose to add the defer attribute

👍

**Comment by oliverdunk** [comment]
@mischnic Thanks for taking a look, that sounds like fair feedback. Happy to make the changes, I should be able to get to those towards the end of the week.

**Comment by oliverdunk** [comment]
Hey @mischnic - I'm sorry for leaving this one a crazy amount of time. I should be close to being able to finish this off - but, just to confirm beforehand, does this MR still make sense and would you still approach it in the same way?

**Comment by mischnic** [comment]
https://github.com/parcel-bundler/parcel/pull/5398 is going to change how `<script type=module>` is handled: with that PR, `<script type=module>` is turned into two script tags by Parcel, so the user doesn't specify two module/nomodule scripts. This would simply handling this in dev mode (simply remove `type=module`). We should probably wait until that PR is merged?

**Comment by devongovett** [comment]
This shouldn't be needed anymore

**Pull request closed without merging**
