### PR TITLE
Fix(transformer/elm): handle elm error properly without errors property

### LINKED ISSUE #8263: Elm code with Debug.log fails with Javascript error
# 🐛 bug report
I have forgotten to delete the `Debug.log` code on elm and the build failed with javascript error.

Inside my elm code I had 
```
 case x of 
   ...

  OnChange value ->
      let
          _ =
               Debug.log "Test" value
      in
      .....

```
## 🎛 Configuration (.babelrc, package.json, cli command)

package.json

```
"devDependencies": {
        "@parcel/packager-raw-url": "^2.3.2",
        "@parcel/transformer-elm": "^2.3.2",
        "@parcel/transformer-webmanifest": "^2.3.2",
        "@vercel/node": "^1.15.0",
        "vercel": "^24.0.0"
    },
```

## 🤔 Expected Behavior

Show error that the code is running with `Debug` and its not allowed?

## 😯 Current Behavior

```
@parcel/transformer-elm: Cannot read property 'flatMap' of undefined

  TypeError: Cannot read property 'flatMap' of
  undefined
      at Object.transform
  (/Users/{path/to/project}/node_modules/@parcel/transformer-elm/lib/ElmTransformer.js:170:48)
      at async Transformation.runTransformer
  (/Users/{path/to/project}//node_modules/@parcel/core/lib/Transformation.js:653:5)
      at async Transformation.runPipeline
  (/Users/{path/to/project}//node_modules/@parcel/core/lib/Transformation.js:402:36)
      at async Transformation.runPipelines
  (/Users/{path/to/project}//node_modules/@parcel/core/lib/Transformation.js:265:40)
      at async Transformation.run
  (/Users/{path/to/project}//node_modules/@parcel/core/lib/Transformation.js:183:21)
      at async Child.handleRequest
  (/Users/{path/to/project}//node_modules/@parcel/workers/lib/child.js:217:9)

```

## 💁 Possible Solution
Prevent building if there are any `Debug`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  v2
| Node             | v14.119.1
| npm/Yarn         | Yarn v1.22.18
| Operating System | MacOs Monterey

### PR DESCRIPTION
**Pull request by Shinyaigeek**
# ↪️ Pull Request

Fixes: #8263 

Hi team! long time to see.

I investigated #8263 issue, and I noticed this bug is caused because `error` object thrown by  `compileToString` module does not necessarily have `.errors` property. I make a fix to handle such a case.

## 💻 Examples

use `Debug.log` and build it with production mode.

## 🚨 Test instructions

make a unit test to check such a case.

## ✔️ PR Todo

- [x] Added/updated unit tests for this change
- [ ] ~Filled out test instructions (In case there aren't any unit tests)~
- [x] Included links to related issues/PRs

### CODE REVIEW

**Review by mischnic — APPROVED** [review]
Thanks!

**Comment by devongovett** [comment]
Is this still needed now that #8076 is merged? I tried the test and it seemed to pass against v2.

**Comment by Shinyaigeek** [comment]
Oh, sure. As @devongovett said, this change is not needed because #8076 merged. The same as this change is done in https://github.com/parcel-bundler/parcel/pull/8076/files#diff-087bd115f321d7345bbe411da8a4734cf827c1af5af408b74e206f9cd485d305R73-R76.

**Comment by Shinyaigeek** [comment]
so I closed this PR. anyway, thank you for review and help!

**Comment by devongovett** [comment]
No worries! Thanks for the PR, and sorry for the duplication.

**Pull request closed without merging**
