### PR TITLE
Add --reload flag

### LINKED ISSUE #289: 🙋 Regular Browser Reload on File Save
🙋

Hi there! I'd like to start exploring Parcel as a workflow for creative coding (WebGL, Canvas2D, etc). I'm trying to migrate some programs I've written for non-HMR workflow to this new HMR workflow, and I'm hitting huge performance issues since the code (which is doing things like creating a WebGL/Canvas context) was not designed to be re-run multiple times.

### 🎛 Configuration 

Take a simple program like this:

```js
const canvas = document.createElement('canvas');
const ctx = canvas.getContext('2d');

document.body.appendChild(canvas);
```

### 🤔 Expected Behavior

I'd like to develop with the same way that a JS file runs/loads in the browser (i.e. once, not many times). If possible, I'd like a way to replace JavaScript HMR with a simple `window.location.reload()` functionality. However, other features (like CSS) should still use HMR / inject without hard reload.

### 😯 Current Behavior

Currently the above code, when saved several times, will create several canvas elements in the body.

### 💁 Possible Solution

A way of turning on/off regular hot reload. I am assuming this may already exist, but I couldn't find it, so perhaps it's more an issue of documentation?

### PR DESCRIPTION
**Pull request by mischnic**
# ↪️ Pull Request

Add a flag to always fully reload the page.

Closes #289

After merging:
- Add a comment about this flag and close: #2675, #2606, #2455, as workaround for #2509
- Add to docs

## 🚨 Test instructions

`parcel index.html --reload` will fully reload the page if some JS is changed (instead of merely re-executing it).

## ✔️ PR Todo

- [ ] Added/updated unit tests for this change
- [x] Filled out test instructions (In case there aren't any unit tests)
- [x] Included links to related issues/PRs

### CODE REVIEW

**Comment by devongovett** [comment]
Is this an alternative to #2676?

**Comment by mischnic** [comment]
> Is this an alternative to #2676?

I'm not sure if this is actually useful with that other one merged.
I somewhat wrote about that in the issue: https://github.com/parcel-bundler/parcel/issues/289#issuecomment-466706957

**Comment by mischnic** [comment]
> Is this an alternative to #2676?

Actually, that one doesn't work in 100% of cases.

**Comment by devongovett** [comment]
I do think page reloading should probably be the default unless you accept the HMR update, as proposed by #2676. HMR *not* working seems to be more common than working. You need to write your code in a specific way in order for HMR to work most of the time. I think if you don't opt in then we should just reload the page by default.

**Comment by mischnic** [comment]
> You need to write your code in a specific way in order for HMR to work most of the time.

With current React/Preact code, it works perfectly as it is right now (re-executing JS). What would I have to do the reenable that?
```js
if(module.hot){
	module.hot.accept(() => "dummy");
}

**Comment by devongovett** [comment]
> With current React/Preact code, it works perfectly as it is right now

Sometimes, in very simple apps, yes. But if you do anything more complicated, like have global state in redux, etc., then it won't always work properly.

Yeah, you'd need to do what you said above. You can just `module.hot.accept()` as well - the function isn't required.

I believe this is also required by webpack, or it will just reload the page, so we'd be matching their behavior.

**Comment by mischnic** [comment]
> I believe this is also required by webpack, or it will just reload the page, so we'd be matching their behavior.

👍  -> #2676

**Pull request closed without merging**
