### PR TITLE
Webextension fixes

### LINKED ISSUE #7952: Web Extension Transformer: esmodule-helpers.js fails to load
- Follows https://github.com/parcel-bundler/parcel/pull/7050

# 🐛 bug report

My options page isn't being built correctly. Opening the options page in the browser results into this line failing:

```js
var parcelHelpers = require("@parcel/transformer-js/src/esmodule-helpers.js");
```

and the console error:

```
options.6f3d3386.js:63 Uncaught Error: Cannot find module '8ISrk'
    at newRequire (options.6f3d3386.js:61:19)
    at newRequire (options.6f3d3386.js:45:18)
    at localRequire (options.6f3d3386.js:84:35)
    at Object.3fApi.webextension-polyfill (options.6f3d3386.js:146:21)
    at newRequire (options.6f3d3386.js:71:24)
    at options.6f3d3386.js:122:5
    at options.6f3d3386.js:145:3
```

## 🎛 Configuration (.babelrc, package.json, cli command)

```json
{
	"extends": "@parcel/config-webextension"
}
```
```json
	"browserslist": [
		"last 1 Chrome version",
		"last 1 Firefox version"
	],
```

## 💻 Code Sample

The content of `options.js` is just:

```js
import browser from 'webextension-polyfill';
```

and part of the output is:

```js
})({"3fApi":[function(require,module,exports) {
var parcelHelpers = require("@parcel/transformer-js/src/esmodule-helpers.js");
var _webextensionPolyfill = require("webextension-polyfill");
var _webextensionPolyfillDefault = parcelHelpers.interopDefault(_webextensionPolyfill);

},{"webextension-polyfill":"kPFTQ","@parcel/transformer-js/src/esmodule-helpers.js":"8ISrk"}],"kPFTQ":[function(require,module,exports) {
```

Full example in https://github.com/fregante/browser-extension-template/pull/75/files

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.1049
| parcel/config-webextension | 2.4.2-nightly.2674 |
| Node             | v16.4.2
| npm/Yarn         | 7.18.1
| Operating System | macOS 11

### LINKED ISSUE #7953: Web Extension Transformer: a broken `web_accessible_resources` field is added
- Follows https://github.com/parcel-bundler/parcel/pull/7050

# 🐛 bug report

When building a web extension, it seems that the hosts specified in the content scripts are copied to the `web_accessible_resources` field, even if unnecessary, breaking the manifest altogether in some cases.

## 🎛 Configuration (.babelrc, package.json, cli command)

No custom configuration. It happens on both build and watch.

## 🤔 Expected Behavior

No `web_accessible_resources` unless required:

```json
{
	"name": "Awesome Extension",
	"version": "0.0.0",
	"manifest_version": 3,
	"content_scripts": [
		{
			"matches": ["https://github.com/fregante/browser-extension-template/*"],
			"css": ["manifest.b7514168.css"]
		}
	]
}
```

or at least use a supported origin glob:

```json
{
	"name": "Awesome Extension",
	"version": "0.0.0",
	"manifest_version": 3,
	"content_scripts": [
		{
			"matches": ["https://github.com/fregante/browser-extension-template/*"],
			"css": ["manifest.b7514168.css"]
		}
	],
	"web_accessible_resources": [
		{
			"matches": ["https://github.com/*"],
			"extension_ids": [],
			"resources": []
		}
	]
}
```
## 😯 Current Behavior

```json
{
	"name": "Awesome Extension",
	"version": "0.0.0",
	"manifest_version": 3,
	"content_scripts": [
		{
			"matches": ["https://github.com/fregante/browser-extension-template/*"],
			"css": ["manifest.b7514168.css"]
		}
	],
	"web_accessible_resources": [
		{
			"matches": ["https://github.com/fregante/browser-extension-template/*"],
			"extension_ids": [],
			"resources": []
		}
	]
}
```

## 💻 Code Sample

Input manifest:

```json
{
	"name": "Awesome Extension",
	"version": "0.0.0",
	"manifest_version": 3,
	"content_scripts": [
		{
			"matches": [ "https://github.com/fregante/browser-extension-template/*" ],
			"css": [ "content.css" ]
		}
	]
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.1049
| parcel/config-webextension | 2.4.2-nightly.2674 |
| Node             | v16.4.2
| npm/Yarn         | 7.18.1
| Operating System | macOS 11

### PR DESCRIPTION
**Pull request by 101arrowz**
# ↪️ Pull Request

Don't use shared dependencies for manifest children, allow `browser_specific_settings`, and fix `web_accessible_resources` generation for the web extension config.

Fixes #7952
Fixes #7953 (mostly)
Fixes https://github.com/parcel-bundler/parcel/pull/7050#issuecomment-1099085684 (we should support this key since it's sometimes mandatory in Firefox)

### CODE REVIEW

**Review by devongovett — APPROVED** [review]

**Comment by devongovett** [comment]
Looks good, can you fix the linter?

**Comment by 101arrowz** [comment]
This broke a few things actually, let me try to fix first.

EDIT: It looks like parallel priority doesn't actually work reliably for repackaging. It only seems to update when you add the first  CSS asset, and doesn't work at all for other asset types.

**Comment by 101arrowz** [comment]
@devongovett I think we're going to need a new type of invalidation for packagers to properly support web extensions. The only reason adding CSS into JS works when the parent is an HTML is due to the CSS packager concatenating assets into a single bundle. Maybe `invalidateOnBundleChange(bundle, { children?: boolean })` or something. For this packager we'd need to invalidate whenever any recursive child OR sibling OR recursive child of a sibling was invalidated, which might be a bit tough to implement...

**Comment by 101arrowz** [comment]
Doing all of the changes to actually fix the packager will actually take substantially more time so I'll mark this as ready for review again and will submit a separate PR to potentially revamp packager caching later. At the moment everything still works, just not for hot reload.

I'm thinking that since the bundle graph is provided in its entirety to each packager, package requests should also include the hash of the bundle graph in their IDs (which makes hashing the bundle redundant) or at least there should be a way to invalidate the cache from the packager.

**Comment by 101arrowz** [comment]
Just realized this now breaks importing stuff from content scripts but I'm not going to be able to fix for a few days, plus I don't want to overload you guys with so many PRs.

**Comment by Stvad** [comment]
getting the following with latest nightly now, is that the issue you refer to @101arrowz or should I report a separate one? :
```
Error: Cannot read properties of undefined (reading 'hashReferences')

  TypeError: Cannot read properties of undefined (reading 'hashReferences')
  at getBundlesIncludedInHash
  (/Users/vlad/coding/experiments/embed-fragments/node_modules/@parcel/core/lib/requests/WriteBundlesRequest.js:147:47)
  at getBundlesIncludedInHash
  (/Users/vlad/coding/experiments/embed-fragments/node_modules/@parcel/core/lib/requests/WriteBundlesRequest.js:151:7)
  at assignComplexNameHashes
  (/Users/vlad/coding/experiments/embed-fragments/node_modules/@parcel/core/lib/requests/WriteBundlesRequest.js:140:105)
  at Object.run
  (/Users/vlad/coding/experiments/embed-fragments/node_modules/@parcel/core/lib/requests/WriteBundlesRequest.js:115:5)
  at async RequestTracker.runRequest
  (/Users/vlad/coding/experiments/embed-fragments/node_modules/@parcel/core/lib/RequestTracker.js:725:20)
  at async Object.run
  (/Users/vlad/coding/experiments/embed-fragments/node_modules/@parcel/core/lib/requests/ParcelBuildRequest.js:74:20)
  at async RequestTracker.runRequest
  (/Users/vlad/coding/experiments/embed-fragments/node_modules/@parcel/core/lib/RequestTracker.js:725:20)
  at async Parcel._build
  (/Users/vlad/coding/experiments/embed-fragments/node_modules/@parcel/core/lib/Parcel.js:397:11)
  at async Parcel._startNextBuild
  (/Users/vlad/coding/experiments/embed-fragments/node_modules/@parcel/core/lib/Parcel.js:298:24)
  at async $b0fd219fea43bcac$export$2e2bcd8739ae039._runFn
  (/Users/vlad/coding/experiments/embed-fragments/node_modules/@parcel/utils/lib/index.js:32427:13)
```

**Comment by 101arrowz** [comment]
That issue is probably just a caching bug (at least I had that issue before and it started working after I cleared my cache). If not, refer to #4145.

**Comment by Stvad** [comment]
Trying this again in v4.5 and clearing cache (`rm -rf .parcel-cache/`) didn't help, will explore that issue, though at a glance does not seem to have a consistent solution =\

**Pull request merged**
