### PR TITLE
postcss-modules: make getJSON customizable

### PR DESCRIPTION
**Pull request by Epimodev**
# ↪️ Pull Request

In `postcss-modules` plugin, there is `getJSON` option which give the possibility to run some instructions with exported classes.
In my case, I want to use this feature to generate TypeScript definition files when I change my css/scss files. And we can imagine other use cases of this feature.

But when we define `getJSON` in `postcss.config.js` we overwrite the `getJSON` of parcel which set classNames in css assets, so css modules doesn't work anymore in the application.

The goal of this PR is to avoid overwrite the behavior of parcel when we define `getJSON` in `postcss.config.js`.

## 💻 Examples

posrtcss.config.js
```js
module.exports = {
  modules: true,
  plugins: {
    autoprefixer: {},
    'postcss-modules': {
      generateScopedName: '[local]___[hash:base64:5]',
      getJSON: (filename, json) => {
        const classNames = Object.keys(json);
        return writeTypings(filename, classNames);
      },
    },
  },
};
```

css file `style.css`:
```css
.button {
  padding: 10px;
  background: green;
  color: white;
  border-radius: 3px;
}
```

js File:
```js
import style from './style.css';

console.log(style); // expect `{ button: "button___1MgdH" }` but display `{}`
```

## 🚨 Test instructions

- `git clone git@github.com:Epimodev/react-parcel-boilerplate.git` it will avoid set up a parcel project from scratch
- `git checkout feat/write-css-types` checkout the branch where I configure postcss to generate TS definition of css files with `getJSON` option
- `yarn` to install dependencies
- `yarn link "parcel-bundler"` to use local version of parcel
- `yarn start --no-cache` will start a dev server on port 1234
- once the app is started you can open it in your browser
  - if you use current version of parcel, buttons shouldn't have any style and the console should display `STYLE {}`
  - if you use my forked version, buttons should be green and the console should display `STYLE {button: "button___1MgdH"}`

## ✔️ PR Todo

- [ ] Added/updated unit tests for this change (I didn't find any unit test about postcss)
- [x] Filled out test instructions (In case there aren't any unit tests)
- [ ] Included links to related issues/PRs (I didn't find related issues/PRs)

### CODE REVIEW

**Comment by garthenweb** [comment]
@Epimodev Just in case you didn't saw it before: As I had the exact same use case I build a plugin that should fulfill your need: https://www.npmjs.com/package/parcel-plugin-css-modules-type-generator Maybe it is useful for you as well :)

**Comment by Epimodev** [comment]
@garthenweb I didn't know this plugin exists, thanks a lot 👍   
I've just tried it and it seems working perfectly. So I'll use it.

I still think we should be able to use `getJSON` option without overwrite css asset behavior.

**Comment by DeMoorJasper** [comment]
@Epimodev Could you port this PR over to the v2 branch, as there's a plugin for this in Parcel 1 I don't think we should add this functionality as Parcel 1 is in maintenance mode.

**Comment by Epimodev** [comment]
No problem to port this over v2.
I will try during next days.

**Pull request closed without merging**
