### PR TITLE
Bump serialize-to-js

### LINKED ISSUE #4042: serialize-to-js security alerts are back... again
I was trying out v2 and I'm getting security alerts from npm regarding the use of `serialize-to-js` inside `@parcel/utils` package. I noticed that there were previous discussions about these at #3882, #3597 and #3514. Associated vulnerabilities can be found here: https://snyk.io/test/npm/parcel/2.0.0-alpha.3.2?tab=issues

I believe simply bumping the version to `^3.0.0` would fix the issues since `@parcel/utils` is not using `deserialize()` and stop the barrage of audit alerts.

### PR DESCRIPTION
**Pull request by mischnic**
I really hope this is the last time we are forced to do this.

Closes #4042

### CODE REVIEW

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>packages/benchmarks/kitchen-sink ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 6.41s | +33.00ms |
| Cached | 3.41s | +66.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/parcel.ff215454.webp | 102.94kb | +0.00b | 157.00ms | -8.00ms 🚀 |
| dist/modern/parcel.76ee4591.webp | 102.94kb | +0.00b | 155.00ms | -9.00ms 🚀 |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/parcel.ff215454.webp | 102.94kb | +0.00b | 358.00ms | +345.00ms ⚠️ |
| dist/modern/parcel.76ee4591.webp | 102.94kb | +0.00b | 357.00ms | +345.00ms ⚠️ |
| dist/legacy/index.js | 519.00b | +0.00b | 363.00ms | +345.00ms ⚠️ |
| dist/modern/index.js | 452.00b | +0.00b | 357.00ms | +344.00ms ⚠️ |
| dist/legacy/index.css | 29.00b | +0.00b | 357.00ms | +344.00ms ⚠️ |
| dist/modern/index.css | 29.00b | +0.00b | 355.00ms | +343.00ms ⚠️ |

</p></details>

<details><summary>packages/benchmarks/react-hn ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 9.10s | +231.00ms |
| Cached | 3.34s | -93.00ms |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/module/index.js | 34.33kb | +0.00b | 280.00ms | +211.00ms ⚠️ |
| dist/main/index.js | 34.31kb | +0.00b | 285.00ms | +211.00ms ⚠️ |

</p></details>

<details><summary>packages/benchmarks/ak-editor ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 2.89m | -1.28s |
| Cached | 5.78s | -10.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.js | 2.33mb | +4.00b ⚠️ | 1.68m | -1.26s |
| dist/EmojiPickerComponent.6fc09ddc.js | 105.94kb | +0.00b | 40.78s | -2.39s 🚀 |
| dist/Toolbar.93d205ef.js | 105.59kb | +0.00b | 55.91s | -14.85s 🚀 |
| dist/media-viewer.81fbeba4.js | 87.56kb | +0.00b | 6.74s | +723.00ms ⚠️ |
| dist/card.c0473744.js | 76.88kb | +0.00b | 6.74s | +723.00ms ⚠️ |
| dist/ui.ab1a2648.js | 73.75kb | +0.00b | 42.52s | -2.56s 🚀 |
| dist/component.10b390dc.js | 46.04kb | +0.00b | 36.49s | -2.54s 🚀 |
| dist/DatePicker.0242ec52.js | 27.54kb | +0.00b | 39.78s | -3.61s 🚀 |
| dist/EmojiPickerComponent.e7c7bb11.js | 26.86kb | +0.00b | 39.78s | -3.38s 🚀 |
| dist/popup.a41a3cbc.js | 22.35kb | +0.00b | 35.71s | -2.43s 🚀 |
| dist/popup.aac4042c.js | 21.82kb | +0.00b | 35.71s | -2.42s 🚀 |
| dist/popup.0bcf5c74.js | 20.84kb | +0.00b | 35.71s | -2.42s 🚀 |
| dist/workerHasher.d7e20c98.js | 11.57kb | +0.00b | 41.91s | -2.62s 🚀 |
| dist/EmojiTypeAheadComponent.1c09c30d.js | 10.44kb | +0.00b | 41.92s | -2.33s 🚀 |
| dist/component.a26e593f.js | 5.62kb | +0.00b | 36.65s | -2.59s 🚀 |
| dist/component.8fa44754.js | 3.38kb | +0.00b | 36.49s | -2.64s 🚀 |
| dist/EmojiUploadComponent.0460cc59.js | 2.92kb | +0.00b | 39.78s | -3.61s 🚀 |
| dist/component.ab65829f.js | 2.30kb | +0.00b | 36.65s | -2.59s 🚀 |
| dist/ResourcedEmojiComponent.2d80adbd.js | 2.25kb | +0.00b | 6.71s | +711.00ms ⚠️ |
| dist/media-picker-analytics-error-boundary.0f11d632.js | 1.85kb | +0.00b | 35.73s | -2.45s 🚀 |
| dist/16.dcacbe5c.js | 1.69kb | +0.00b | 36.87s | -2.71s 🚀 |
| dist/date.cfe6153f.js | 1.63kb | +0.00b | 37.08s | -2.70s 🚀 |
| dist/16.de3f3184.js | 1.63kb | +0.00b | 36.75s | -2.65s 🚀 |
| dist/images.c60a97a9.js | 1.57kb | +0.00b | 37.15s | -2.74s 🚀 |
| dist/feedback.01d7bcf7.js | 1.53kb | +0.00b | 37.53s | -2.60s 🚀 |
| dist/workerHasher.854262ce.js | 1.49kb | +0.00b | 41.91s | -2.62s 🚀 |
| dist/status.e3ed4764.js | 1.35kb | +0.00b | 37.43s | -2.61s 🚀 |
| dist/list-number.dbe744df.js | 1.35kb | +0.00b | 37.25s | -2.68s 🚀 |
| dist/16.f54dac28.js | 1.34kb | +0.00b | 36.85s | -2.68s 🚀 |
| dist/16.8f0e8fe1.js | 1.29kb | +0.00b | 36.65s | -2.67s 🚀 |
| dist/16.43b62c01.js | 1.29kb | +0.00b | 36.76s | -2.67s 🚀 |
| dist/code.092e0137.js | 1.28kb | +0.00b | 37.06s | -2.73s 🚀 |
| dist/16.b17a4d30.js | 1.27kb | +0.00b | 36.97s | -2.72s 🚀 |
| dist/16.51bbc68e.js | 1.24kb | +0.00b | 36.96s | -2.73s 🚀 |
| dist/component.8351f228.js | 1.23kb | +0.00b | 36.47s | -2.57s 🚀 |
| dist/link.6fa27bb2.js | 1.20kb | +0.00b | 37.25s | -2.68s 🚀 |
| dist/heading6.3996fe48.js | 1.19kb | +0.00b | 37.53s | -2.60s 🚀 |
| dist/16.385d3ff5.js | 1.19kb | +0.00b | 36.95s | -2.70s 🚀 |
| dist/heading3.9fea5413.js | 1.18kb | +0.00b | 37.53s | -2.59s 🚀 |
| dist/16.b3ce4050.js | 1.16kb | +0.00b | 36.75s | -2.65s 🚀 |
| dist/16.e37bbe6b.js | 1.15kb | +0.00b | 36.95s | -2.70s 🚀 |
| dist/16.f7fe274a.js | 1.14kb | +0.00b | 37.06s | -2.71s 🚀 |
| dist/emoji.c4bc5355.js | 1.12kb | +0.00b | 37.15s | -2.73s 🚀 |
| dist/16.ac2ff83f.js | 1.10kb | +0.00b | 36.86s | -2.71s 🚀 |
| dist/16.4c652b29.js | 1.10kb | +0.00b | 36.76s | -2.67s 🚀 |
| dist/16.24165259.js | 1.09kb | +0.00b | 36.75s | -2.68s 🚀 |
| dist/16.74510c56.js | 1.09kb | +0.00b | 36.85s | -2.68s 🚀 |
| dist/16.97c5bdf9.js | 1.09kb | +0.00b | 36.85s | -2.72s 🚀 |
| dist/16.a79db876.js | 1.09kb | +0.00b | 36.65s | -2.60s 🚀 |
| dist/heading5.2f045997.js | 1.07kb | +0.00b | 37.53s | -2.59s 🚀 |
| dist/16.6f8ac62a.js | 1.05kb | +0.00b | 36.65s | -2.61s 🚀 |
| dist/expand.13380081.js | 1.05kb | +0.00b | 39.78s | -2.23s 🚀 |
| dist/16.3e36da0b.js | 1.01kb | +0.00b | 36.95s | -2.74s 🚀 |
| dist/heading2.2194210a.js | 1.00kb | +0.00b | 37.43s | -2.64s 🚀 |
| dist/mention.9fdad24e.js | 983.00b | +0.00b | 37.25s | -2.70s 🚀 |
| dist/fallback.305c8864.js | 982.00b | +0.00b | 37.43s | -2.64s 🚀 |
| dist/heading4.63d1ca06.js | 978.00b | +0.00b | 37.53s | -2.59s 🚀 |
| dist/layout.6f66c2da.js | 964.00b | +0.00b | 37.15s | -2.74s 🚀 |
| dist/divider.160f3108.js | 942.00b | +0.00b | 37.15s | -2.71s 🚀 |
| dist/quote.88bfdca4.js | 938.00b | +0.00b | 37.35s | -2.65s 🚀 |
| dist/action.146450ba.js | 921.00b | +0.00b | 37.06s | -2.73s 🚀 |
| dist/decision.06254b93.js | 900.00b | +0.00b | 37.15s | -2.71s 🚀 |
| dist/panel-warning.59c8ef3f.js | 893.00b | +0.00b | 37.35s | -2.64s 🚀 |
| dist/list.4f623de3.js | 872.00b | +0.00b | 37.25s | -2.69s 🚀 |
| dist/heading1.65fb8482.js | 866.00b | +0.00b | 37.43s | -2.64s 🚀 |
| dist/panel-error.c2479698.js | 793.00b | +0.00b | 37.25s | -2.70s 🚀 |
| dist/panel.23cd7224.js | 790.00b | +0.00b | 37.35s | -2.65s 🚀 |
| dist/table.4ace5843.js | 782.00b | +0.00b | 37.43s | -2.61s 🚀 |
| dist/panel-success.6a7b97d7.js | 730.00b | +0.00b | 37.36s | -2.63s 🚀 |
| dist/panel-note.5ff85bdc.js | 729.00b | +0.00b | 37.35s | -2.63s 🚀 |
| dist/simpleHasher.884d4eb6.js | 450.00b | +0.00b | 41.91s | -3.16s 🚀 |
| dist/esm.976debcc.js | 180.00b | +0.00b | 6.65s | +715.00ms ⚠️ |
| dist/dropzone.976debcc.js | 179.00b | +1.00b ⚠️ | 11.38s | -26.76s 🚀 |
| dist/clipboard.976debcc.js | 179.00b | +1.00b ⚠️ | 36.47s | -2.56s 🚀 |
| dist/browser.976debcc.js | 179.00b | +1.00b ⚠️ | 55.91s | +16.87s ⚠️ |
| dist/editorView.976debcc.js | 179.00b | -1.00b 🚀 | 35.71s | -21.30s 🚀 |
| dist/media-card-analytics-error-boundary.976debcc.js | 178.00b | -5.00b 🚀 | 37.06s | +26.61s ⚠️ |
| dist/16.976debcc.js | 176.00b | -5.00b 🚀 | 36.46s | -3.31s 🚀 |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.js | 2.33mb | +4.00b ⚠️ | 265.00ms | +12.00ms |
| dist/pdfRenderer.85e56a51.js | 1.11mb | +0.00b | 166.00ms | +22.00ms ⚠️ |
| dist/smartMediaEditor.678dca17.js | 602.09kb | +0.00b | 117.00ms | +13.00ms ⚠️ |
| dist/popup.cc1a1fa6.js | 286.25kb | +0.00b | 157.00ms | +18.00ms ⚠️ |
| dist/EmojiPickerComponent.6fc09ddc.js | 105.94kb | +0.00b | 112.00ms | +12.00ms ⚠️ |
| dist/Toolbar.93d205ef.js | 105.59kb | +0.00b | 109.00ms | +13.00ms ⚠️ |
| dist/media-viewer.81fbeba4.js | 87.56kb | +0.00b | 156.00ms | +21.00ms ⚠️ |
| dist/card.c0473744.js | 76.88kb | +0.00b | 157.00ms | +21.00ms ⚠️ |
| dist/ui.ab1a2648.js | 73.75kb | +0.00b | 111.00ms | +14.00ms ⚠️ |
| dist/smartMediaEditor.25b0ed57.js | 67.38kb | +0.00b | 110.00ms | +14.00ms ⚠️ |
| dist/component.10b390dc.js | 46.04kb | +0.00b | 141.00ms | +15.00ms ⚠️ |
| dist/DatePicker.0242ec52.js | 27.54kb | +0.00b | 110.00ms | +12.00ms ⚠️ |
| dist/EmojiPickerComponent.e7c7bb11.js | 26.86kb | +0.00b | 111.00ms | +13.00ms ⚠️ |
| dist/popup.a41a3cbc.js | 22.35kb | +0.00b | 146.00ms | +19.00ms ⚠️ |
| dist/popup.aac4042c.js | 21.82kb | +0.00b | 144.00ms | +17.00ms ⚠️ |
| dist/popup.0bcf5c74.js | 20.84kb | +0.00b | 144.00ms | +17.00ms ⚠️ |
| dist/js.16f29da2.js | 16.29kb | +0.00b | 147.00ms | +18.00ms ⚠️ |
| dist/popup.e0094d89.js | 12.82kb | +0.00b | 146.00ms | +18.00ms ⚠️ |
| dist/workerHasher.d7e20c98.js | 11.57kb | +0.00b | 109.00ms | +13.00ms ⚠️ |
| dist/EmojiTypeAheadComponent.1c09c30d.js | 10.44kb | +0.00b | 110.00ms | +13.00ms ⚠️ |
| dist/card.f99e1597.js | 5.92kb | +0.00b | 147.00ms | +18.00ms ⚠️ |
| dist/component.a26e593f.js | 5.62kb | +0.00b | 140.00ms | +15.00ms ⚠️ |
| dist/index.css | 3.38kb | +0.00b | 98.00ms | +13.00ms ⚠️ |
| dist/component.8fa44754.js | 3.38kb | +0.00b | 141.00ms | +16.00ms ⚠️ |
| dist/png-chunks-extract.3d8d8594.js | 3.33kb | +0.00b | 146.00ms | +18.00ms ⚠️ |
| dist/EmojiUploadComponent.0460cc59.js | 2.92kb | +0.00b | 110.00ms | +12.00ms ⚠️ |
| dist/component.ab65829f.js | 2.30kb | +0.00b | 140.00ms | +15.00ms ⚠️ |
| dist/ResourcedEmojiComponent.2d80adbd.js | 2.25kb | +0.00b | 154.00ms | +21.00ms ⚠️ |
| dist/media-picker-analytics-error-boundary.0f11d632.js | 1.85kb | +0.00b | 142.00ms | +14.00ms ⚠️ |
| dist/card.2c902906.js | 1.73kb | +0.00b | 148.00ms | +18.00ms ⚠️ |
| dist/16.dcacbe5c.js | 1.69kb | +0.00b | 135.00ms | +15.00ms ⚠️ |
| dist/date.cfe6153f.js | 1.63kb | +0.00b | 128.00ms | +11.00ms ⚠️ |
| dist/16.de3f3184.js | 1.63kb | +0.00b | 139.00ms | +16.00ms ⚠️ |
| dist/feedback.01d7bcf7.js | 1.53kb | +0.00b | 111.00ms | +13.00ms ⚠️ |
| dist/workerHasher.854262ce.js | 1.49kb | +0.00b | 109.00ms | +12.00ms ⚠️ |
| dist/status.e3ed4764.js | 1.35kb | +0.00b | 114.00ms | +13.00ms ⚠️ |
| dist/list-number.dbe744df.js | 1.35kb | +0.00b | 117.00ms | +13.00ms ⚠️ |
| dist/16.f54dac28.js | 1.34kb | +0.00b | 137.00ms | +16.00ms ⚠️ |
| dist/16.8f0e8fe1.js | 1.29kb | +0.00b | 139.00ms | +15.00ms ⚠️ |
| dist/16.43b62c01.js | 1.29kb | +0.00b | 138.00ms | +16.00ms ⚠️ |
| dist/code.092e0137.js | 1.28kb | +0.00b | 129.00ms | +12.00ms ⚠️ |
| dist/16.b17a4d30.js | 1.27kb | +0.00b | 130.00ms | +13.00ms ⚠️ |
| dist/16.51bbc68e.js | 1.24kb | +0.00b | 130.00ms | +12.00ms ⚠️ |
| dist/component.8351f228.js | 1.23kb | +0.00b | 141.00ms | +15.00ms ⚠️ |
| dist/link.6fa27bb2.js | 1.20kb | +0.00b | 117.00ms | +12.00ms ⚠️ |
| dist/heading6.3996fe48.js | 1.19kb | +0.00b | 111.00ms | +12.00ms ⚠️ |
| dist/16.385d3ff5.js | 1.19kb | +0.00b | 130.00ms | +11.00ms ⚠️ |
| dist/heading3.9fea5413.js | 1.18kb | +0.00b | 112.00ms | +12.00ms ⚠️ |
| dist/16.b3ce4050.js | 1.16kb | +0.00b | 138.00ms | +15.00ms ⚠️ |
| dist/16.e37bbe6b.js | 1.15kb | +0.00b | 130.00ms | +12.00ms ⚠️ |
| dist/16.f7fe274a.js | 1.14kb | +0.00b | 129.00ms | +12.00ms ⚠️ |
| dist/16.ac2ff83f.js | 1.10kb | +0.00b | 136.00ms | +15.00ms ⚠️ |
| dist/16.4c652b29.js | 1.10kb | +0.00b | 137.00ms | +15.00ms ⚠️ |
| dist/16.24165259.js | 1.09kb | +0.00b | 138.00ms | +15.00ms ⚠️ |
| dist/16.74510c56.js | 1.09kb | +0.00b | 137.00ms | +15.00ms ⚠️ |
| dist/16.97c5bdf9.js | 1.09kb | +0.00b | 136.00ms | +15.00ms ⚠️ |
| dist/16.a79db876.js | 1.09kb | +0.00b | 139.00ms | +15.00ms ⚠️ |
| dist/heading5.2f045997.js | 1.07kb | +0.00b | 111.00ms | +12.00ms ⚠️ |
| dist/16.6f8ac62a.js | 1.05kb | +0.00b | 140.00ms | +16.00ms ⚠️ |
| dist/expand.13380081.js | 1.05kb | +0.00b | 111.00ms | +12.00ms ⚠️ |
| dist/card.aae6ebb9.js | 1.04kb | +0.00b | 151.00ms | +21.00ms ⚠️ |
| dist/16.3e36da0b.js | 1.01kb | +0.00b | 130.00ms | +12.00ms ⚠️ |
| dist/heading2.2194210a.js | 1.00kb | +0.00b | 112.00ms | +12.00ms ⚠️ |
| dist/mention.9fdad24e.js | 983.00b | +0.00b | 116.00ms | +12.00ms ⚠️ |
| dist/fallback.305c8864.js | 982.00b | +0.00b | 113.00ms | +12.00ms ⚠️ |
| dist/heading4.63d1ca06.js | 978.00b | +0.00b | 112.00ms | +13.00ms ⚠️ |
| dist/divider.160f3108.js | 942.00b | +0.00b | 130.00ms | +12.00ms ⚠️ |
| dist/quote.88bfdca4.js | 938.00b | +0.00b | 114.00ms | +12.00ms ⚠️ |
| dist/action.146450ba.js | 921.00b | +0.00b | 129.00ms | +13.00ms ⚠️ |
| dist/decision.06254b93.js | 900.00b | +0.00b | 128.00ms | +12.00ms ⚠️ |
| dist/panel-warning.59c8ef3f.js | 893.00b | +0.00b | 115.00ms | +13.00ms ⚠️ |
| dist/list.4f623de3.js | 872.00b | +0.00b | 116.00ms | +12.00ms ⚠️ |
| dist/heading1.65fb8482.js | 866.00b | +0.00b | 113.00ms | +13.00ms ⚠️ |
| dist/panel-error.c2479698.js | 793.00b | +0.00b | 115.00ms | +12.00ms ⚠️ |
| dist/panel.23cd7224.js | 790.00b | +0.00b | 114.00ms | +12.00ms ⚠️ |
| dist/table.4ace5843.js | 782.00b | +0.00b | 113.00ms | +12.00ms ⚠️ |
| dist/media-viewer-analytics-error-boundary.dd752a9e.js | 779.00b | +0.00b | 152.00ms | +22.00ms ⚠️ |
| dist/panel-success.6a7b97d7.js | 730.00b | +0.00b | 115.00ms | +12.00ms ⚠️ |
| dist/panel-note.5ff85bdc.js | 729.00b | +0.00b | 115.00ms | +12.00ms ⚠️ |
| dist/simpleHasher.884d4eb6.js | 450.00b | +0.00b | 109.00ms | +13.00ms ⚠️ |
| dist/esm.976debcc.js | 179.00b | +1.00b ⚠️ | 153.00ms | +21.00ms ⚠️ |
| dist/media-card-analytics-error-boundary.976debcc.js | 179.00b | +1.00b ⚠️ | 147.00ms | +18.00ms ⚠️ |
| dist/dropzone.976debcc.js | 179.00b | +1.00b ⚠️ | 143.00ms | +17.00ms ⚠️ |
| dist/clipboard.976debcc.js | 179.00b | +1.00b ⚠️ | 143.00ms | +17.00ms ⚠️ |
| dist/browser.976debcc.js | 179.00b | +1.00b ⚠️ | 142.00ms | +16.00ms ⚠️ |
| dist/16.976debcc.js | 179.00b | +1.00b ⚠️ | 130.00ms | +13.00ms ⚠️ |
| dist/editorView.976debcc.js | 179.00b | +1.00b ⚠️ | 108.00ms | +13.00ms ⚠️ |

</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/255650120378352129)**

**Comment by nnmrts** [comment]
When will this be released?

**Comment by DeMoorJasper** [comment]
@nnmrts this will get released on the nightly at midnight and on the next alpha which has no release date yet.

**Comment by nnmrts** [comment]
@DeMoorJasper The automatic nightly release is a new thing, added today, right? Really great idea, thanks!

So, I know that i can `npm install` alpha version by typing
```
npm install --save-dev parcel@next
```

but will I be able to do the same kind of thing with the nightly release? Or are the nightlies just GitHub tag "releases"?

**Comment by mischnic** [comment]
I will be `npm install --save-dev parcel@nightly`

**Comment by nnmrts** [comment]
NICE! I actually tried that today, haha.

Alright, now it's the final countdown to get rid of my security alerts. xD

Thank you very much!

**Pull request merged**
