### PR TITLE
Don't fail when HTML tags are implied

### LINKED ISSUE #6672: Parcel 2: @parcel/transformer-html: Source indices must be monotonic
# 🐛 bug report

I upgraded to Parcel 2 but everytime I try to run `npm run dev` like I used to on the old version, I get an error stating `@parcel/transformer-html: Source indices must be monotonic`
## 🎛 Configuration (.babelrc, package.json, cli command)

```js
package.json
{
  "name": "chatmurcianysweb",
  "version": "1.0.0",
  "main": "public/index.js",
  "scripts": {
    "dev": "parcel serve public/index.html",
    "build": "parcel build public/index.html"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@giphy/js-components": "^3.0.2",
    "bindings": "^1.5.0",
    "firebase-functions": "^3.7.0",
    "node-internet-radio": "^0.2.0"
  },
  "devDependencies": {
    "parcel": "^2.0.0-beta.3.1"
  },
  "keywords": [],
  "description": ""
}
```

## 🤔 Expected Behavior

I expect the build to run successfully
## 😯 Current Behavior

I get the following error when I run `npm run dev`:
```
> chatmurcianysweb@1.0.0 dev
> parcel serve public/index.html

Server running at http://localhost:1234
× Build failed.

@parcel/transformer-html: Source indices must be monotonic

  Error: Source indices must be monotonic
  at i.getPosition (D:\WebProjects\ChatMurcianysWeb\node_modules\posthtml-parser\dist\chunk.T6SARJYH.js:1:209)       
  at Object.y [as onclosetag] (D:\WebProjects\ChatMurcianysWeb\node_modules\posthtml-parser\dist\index.js:1:1252)    
  at Parser.closeCurrentTag
  (D:\WebProjects\ChatMurcianysWeb\node_modules\posthtml-parser\node_modules\htmlparser2\lib\Parser.js:237:87)       
  at Parser.onclosetag
  (D:\WebProjects\ChatMurcianysWeb\node_modules\posthtml-parser\node_modules\htmlparser2\lib\Parser.js:210:22)       
  at Tokenizer.emitToken
  (D:\WebProjects\ChatMurcianysWeb\node_modules\posthtml-parser\node_modules\htmlparser2\lib\Tokenizer.js:896:23)    
  at Tokenizer.stateInClosingTagName
  (D:\WebProjects\ChatMurcianysWeb\node_modules\posthtml-parser\node_modules\htmlparser2\lib\Tokenizer.js:253:18)    
  at Tokenizer.parse
  (D:\WebProjects\ChatMurcianysWeb\node_modules\posthtml-parser\node_modules\htmlparser2\lib\Tokenizer.js:652:22)    
  at Tokenizer.write
  (D:\WebProjects\ChatMurcianysWeb\node_modules\posthtml-parser\node_modules\htmlparser2\lib\Tokenizer.js:123:14)    
  at Parser.write
  (D:\WebProjects\ChatMurcianysWeb\node_modules\posthtml-parser\node_modules\htmlparser2\lib\Parser.js:339:24)       
  at w (D:\WebProjects\ChatMurcianysWeb\node_modules\posthtml-parser\dist\index.js:1:1828)
```

## 💁 Possible Solution
I have no idea what the error means

## 🔦 Context
I am unable to update my website because of this issue

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |2.0.0-beta.3.1
| Node             |v14.17.4
| npm/Yarn         |7.20.3
| Operating System |Windows 10 Home 20H2

### PR DESCRIPTION
**Pull request by thewilkybarkid**
# ↪️ Pull Request

Fixes https://github.com/parcel-bundler/parcel/issues/6672.

~Currently just failing test cases, as it's dependent on https://github.com/posthtml/posthtml-parser/pull/80.~

## 💻 Examples

See https://github.com/parcel-bundler/parcel/issues/6672.

## 🚨 Test instructions

Test cases included.

## ✔️ PR Todo

- [x] Added/updated unit tests for this change
- [x] Filled out test instructions (In case there aren't any unit tests)
- [x] Included links to related issues/PRs

### CODE REVIEW

**Comment by thewilkybarkid** [comment]
`posthtml-parser` has a new release; I've just tried an upgrade locally but unfortunately still hit a 'Source indices must be monotonic' message in 'should support meta tags'. I'm away for the week now so won't be able to take a look until next weekend; but I'm keen for this to be fixed so if anyone could take a look and solve it that'd be great.

**Comment by thewilkybarkid** [comment]
Managed to take a look, and it's the _SVG_ in the test rather than the HTML, which is curious.

**Comment by thewilkybarkid** [comment]
Seems to be something to do with self-closing tags and a lack of whitespace. Can get around this for now by disabling `sourceLocations` in the SVGTransformer since it's not needed, but there will need to be a bugfix upstream.

Edit: Opened https://github.com/fb55/htmlparser2/issues/941.

**Comment by thewilkybarkid** [comment]
Opened https://github.com/fb55/htmlparser2/issues/941 for the `posthtml-parser` error message.

**Review by devongovett — APPROVED** [review]

**Pull request merged**
