### PR TITLE
add dependencies referenced by posthtml-include

### LINKED ISSUE #488: 🙋 Watch pre-transform HTML files
Consider a posthtml setup like the test case where `index.html` includes `other.html` https://github.com/parcel-bundler/parcel/blob/e0e231e359223343c0333013aeac4e4952fa7324/test/integration/posthtml/index.html

### 🤔 Expected Behavior

When I save a change to `other.html` while running `parcel index.html`, the page updates.

### 😯 Current Behavior

Parcel does not identify a change because it is not watching `other.html`, only `index.html`.

### 🌍 Your Environment=

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |  1.4.1
| Node             |  v9.3.0
| npm/Yarn         | 1.3.2
| Operating System | MacOS

### PR DESCRIPTION
**Pull request by jdanyow**
fixes #488 
closes #1226

:rotating_light: note: works with config like this:
https://github.com/parcel-bundler/parcel/blob/e7df99decb2484d08b4f613ec6dc2ebe4bf9e969/test/integration/posthtml-assets/.posthtmlrc.js#L1-L7

not like this:
https://github.com/parcel-bundler/parcel/blob/e7df99decb2484d08b4f613ec6dc2ebe4bf9e969/test/integration/posthtml/.posthtmlrc.js#L1-L7

### CODE REVIEW

**Comment by jdanyow** [comment]
Sounds good to me, I've update the PR.

**Comment by devongovett** [comment]
cool, looks like the test is failing though

**Comment by jdanyow** [comment]
hmm- will rebase and try again... passing for me locally.

**Comment by jdanyow** [comment]
ok rebased- it's passing now.  There's a vue test that's failing though: "should produce a vue bundle using preprocessors"

**Pull request merged**
