### PR TITLE
Extension: Importers View and separate LSP protocol package

### PR DESCRIPTION
**Pull request by mischnic**
I guess the big question is: is this where you'd expect that "Focus in importers view" menu item? Does it better fit somewhere else?

Also
- refactors the protocol definitions into a separate package (and as a file that is both valid TS and Flow).
- add more VS Code tasks so that pressing F5 will now run every necessary tsc watch script.

https://user-images.githubusercontent.com/4586894/210656010-dbdc9a74-59e9-44cf-a0fa-c8a6b2a12a38.mov

### CODE REVIEW

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>Kitchen Sink ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 1.38s | +3.00ms |
| Cached | 317.00ms | -13.00ms |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/parcel.7cdb0fad.webp | 102.94kb | +0.00b | 82.00ms | -144.00ms 🚀 |
| dist/legacy/parcel.7cdb0fad.webp | 102.94kb | +0.00b | 83.00ms | -144.00ms 🚀 |
| dist/modern/parcel.7cdb0fad.webp | 102.94kb | +0.00b | 82.00ms | -144.00ms 🚀 |

</p></details>

<details><summary>React HackerNews ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 8.86s | -66.00ms |
| Cached | 394.00ms | -2.00ms |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

*No bundle changes detected.*

</p></details>

<details><summary>AtlasKit Editor ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 1.44m | -954.00ms |
| Cached | 1.94s | +61.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/refractor.a33d61f8.js | 599.70kb | +0.00b | 1.10m | +9.25s ⚠️ |
| dist/media-viewer-analytics-error-boundary.6847f80f.js | 3.43kb | +0.00b | 1.10m | +9.25s ⚠️ |
| dist/ro.82d888a1.js | 633.00b | +0.00b | 54.57s | +14.81s ⚠️ |
| dist/index.html | 167.00b | +0.00b | 1.10m | +29.00s ⚠️ |

#### Cached Bundles

*No bundle changes detected.*

</p></details>

<details><summary>Three.js ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 6.44s | +57.00ms |
| Cached | 235.00ms | -10.00ms |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

*No bundle changes detected.*

</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/353409712752951895)**

**Review by devongovett — APPROVED** [review]

**Comment by devongovett** [comment]
> where you'd expect that "Focus in importers view" menu item?

I don't think I would ever think to search for it. Can it just always be up to date when you switch files if it's expanded? Should there be a button in the bottom toolbar for Parcel actions like the one Flow has?

**Comment by mischnic** [comment]
> Can it just always be up to date when you switch files if it's expanded

But there is always one root file in that tree. And you might want to keep that root and take a look at the children without the view changing? Or are you thinking of something else? (So first of all that, and also not doing unnecessary work)

**Comment by devongovett** [comment]
Ah yeah that makes sense. I think a button in the toolbar might be good though.

**Pull request merged**
