### PR TITLE
Adding support for <amp-img src=”path/to/img.jpg”>

### PR DESCRIPTION
**Pull request by honey32**
I enabled finding dependency of src attribute in <amp-img> tag.
Otherwise, that tag won't work.

I've made an issue [here(#2622)](https://github.com/parcel-bundler/parcel/issues/2622).

# ↪️ Pull Request

If I write as below
```html
<amp-img src="/path/to/image.jpg">
```
the path to image didn't seem to be recognized as a dependency.
So, I added a portion of code to treat `src` attribute of `<amp-img>` tag in the same way as one of `` tag is treated.

## 💻 Examples

https://github.com/honey32/snippet-of-parcel-bug

## ✔️ PR Todo

- [ ] Added/updated unit tests for this change

### CODE REVIEW

**Comment by honey32** [comment]
You mean I should do one of these ?
- add an example under packages/examples/
- modify html example in that directory to include `<amp-img>`

**Comment by DeMoorJasper** [comment]
@honey32 no I mean an integration test

You can find the integration tests for html here: https://github.com/parcel-bundler/parcel/blob/v2/packages/core/integration-tests/test/html.js

**Comment by honey32** [comment]
I'm sorry.
I'm not familiar with testing and it seems too difficult for now, so could you or anyone do that please?
If not, I'll manage to do this for a week.

**Comment by DeMoorJasper** [comment]
@honey32 sure I'll approve the PR for now and might add a test later, would've just been better to prevent this from breaking in the future

**Comment by DeMoorJasper** [comment]
@honey32 sure I'll approve the PR for now and might add a test later, would've just been better to prevent this from breaking in the future

**Comment by honey32** [comment]
Thank you very much.

**Pull request merged**
