### PR TITLE
Add swc optimizer

### PR DESCRIPTION
**Pull request by mischnic**
This just adds the plugin, I didn't change the config (so similar to the esbuild optimizer)

Essentially using `@swc/core` instead of `terser`.

### CODE REVIEW

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>Kitchen Sink ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 2.17s | +99.00ms |
| Cached | 272.00ms | +6.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/parcel.7cdb0fad.webp | 102.94kb | +0.00b | 692.00ms | +48.00ms ⚠️ |
| dist/legacy/parcel.7cdb0fad.webp | 102.94kb | +0.00b | 693.00ms | +48.00ms ⚠️ |
| dist/modern/parcel.7cdb0fad.webp | 102.94kb | +0.00b | 693.00ms | +49.00ms ⚠️ |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/index.html | 826.00b | +0.00b | 1.15s | +76.00ms ⚠️ |
| dist/modern/index.html | 749.00b | +0.00b | 1.15s | +77.00ms ⚠️ |

</p></details>

<details><summary>React HackerNews ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 10.72s | +371.00ms |
| Cached | 446.00ms | -15.00ms |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

*No bundle changes detected.*

</p></details>

<details><summary>AtlasKit Editor ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 1.15m | +3.00ms |
| Cached | 1.59s | -72.00ms |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

*No bundle changes detected.*

</p></details>

<details><summary>Three.js ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 7.13s | +23.00ms |
| Cached | 375.00ms | +32.00ms ⚠️ |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

*No bundle changes detected.*

</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/314091114358374977)**

**Comment by devongovett** [comment]
Have you tested it on anything? Any early results?

**Comment by mischnic** [comment]
ak-editor  (total size of distdir with 98 JS bundles)

```
time parcel2c build . --no-source-maps | cat

swc:  8.530mb
24.535s

terser: 8.484mb
40s

esbuild: 9.027mb
18.3s

without an optimizer: 22.639mb
15.706s
```


Errors I ran into when trying to minify swc:
- https://github.com/swc-project/swc/issues/2605
- https://github.com/swc-project/swc/issues/2614

**Comment by mischnic** [comment]
I've updated the timings with the actual values now.

Merging this would make testing easier, you can then easily add it into any existing project. And because it uses `@swc/core` from npm, any bugs that are fixed upstream in swc can be pulled in by bumping the project's lockfile.

**Review by devongovett — APPROVED** [review]
Seems fine to merge as an experimental plugin. A little disappointed that the perf difference vs terser isn't more though...

**Review by devongovett — APPROVED** [review]

**Pull request merged**
