### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by DeMoorJasper**
# ↪️ Pull Request

Redid the test fixes based on the more complete #2842

Closes #2842

## ✔️ PR Todo

- [x] Added/updated unit tests for this change
- [x] Filled out test instructions (In case there aren't any unit tests)
- [x] Included links to related issues/PRs

### CODE REVIEW

**Comment by DeMoorJasper** [comment]
For some reason Node 6 keeps failing randomly

**Comment by mischnic** [comment]
Maybe reenabling the `spec` reporter for the integration tests gives a clue why it fails without an error:
https://github.com/parcel-bundler/parcel/blob/4100b9e7bd9cae5ffcd35ec0868988c20db779a3/packages/core/integration-tests/test/mochareporters.json#L2

**Comment by mischnic** [comment]
@devongovett This would "update" babel to the latest version, was #2819 resolved? Will the correct `core-js` package be used if it's specified as a dependency by Parcel (version 2)? Or might some other hoisted version (3, might cause errors) be bundled?

**Comment by DeMoorJasper** [comment]
For some magical reason everything passed 🎉🎉🎉

**Pull request merged**
