### PR TITLE
Replace module.require in scope hoisting

### LINKED ISSUE #2841: Tree shaking enabled results in a script that has ReferenceError on line 1 (precompiled purescript source)
# 🐛 bug report

running the following script

`spago build &&  rm -rf  ..//dist/* && parcel build index.html --no-source-maps --public-url ./ --out-dir ../dist`

results in a script that has `ReferenceError: module is undefined` on line 1 of the output. 

this is precompiled purescript input -> which just means it's a commonjs module (with it's own commonjs dependancies) being imported into the following script:
```
import Main from './output/Main';

function main() {
  const body = document.querySelector('body');
  Array.from(body.children).forEach(element => {
    body.removeChild(element);
  });
  const environment = process.env.ENVIRONMENT;
  const apiUrl = process.env.API_URL;
  Main.main(environment)(apiUrl)();
}

main();
```

the entry point is an html file that uses the js script above.

## 🎛 Configuration (.babelrc, package.json, cli command)

no babel configuration,  cli command is `parcel build index.html --no-source-maps --public-url ./ --out-dir ../dist`

## 🤔 Expected Behavior

it should replicate the behavior without tree shaking, which is the code should run without errors introduced by the bundling  process
## 😯 Current Behavior

`ReferenceError: module is undefined` on line 1 of the output

## 🔦 Context

this increases the bundle size of our output by 400kb +

## 🌍 Your Environment
Linux, 64 bit,  xubuntu 18.04

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.11
| Node             | 10.15.1
| npm/Yarn         | 6.4.1
| Operating System |  xubuntu 18.04

### PR DESCRIPTION
**Pull request by mischnic**
# ↪️ Pull Request

When scope hoisting, the check `if (typeof module !== "undefined" && module.require)` to determine whether the script is running on Node creates a non-working bundle, because `typeof module` is replaced by a string and this if check also fails:
https://github.com/parcel-bundler/parcel/blob/636bb50baeae15730c3b91cd3b58b457c31f7200/packages/core/parcel-bundler/src/scope-hoisting/hoist.js#L98-L107
This causes the asset to not be wrapped and so `module` isn't being declared (causing `Uncaught ReferenceError: module is not defined`)

This replace `module.require` with `null` in the browser (as is done for server other `module` properties).

Closes #2841

## 🚨 Test instructions

Not sure how to add this as a test, because `module` is actually being declared as a global by `run` test function.

```js
//index.js
const {getEnv} = require("./env.js");
console.log(getEnv());

//env.js
exports.getEnv = function () {
	if (typeof module !== "undefined" && module.require) {
		return "Node";
	} else {
		return "Browser";
	}
};
```

[REPL Link](https://parcel-repl-jooc3ak4v.now.sh/#JTdCJTIyY3VycmVudFByZXNldCUyMiUzQSUyMkphdmFzY3JpcHQlMjIlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIybWluaWZ5JTIyJTNBZmFsc2UlMkMlMjJzY29wZUhvaXN0JTIyJTNBdHJ1ZSUyQyUyMnNvdXJjZU1hcHMlMjIlM0FmYWxzZSUyQyUyMmNvbnRlbnRIYXNoJTIyJTNBZmFsc2UlMkMlMjJicm93c2Vyc2xpc3QlMjIlM0ElMjIlMjIlMkMlMjJwdWJsaWNVcmwlMjIlM0ElMjIlMjIlMkMlMjJ0YXJnZXQlMjIlM0ElMjJicm93c2VyJTIyJTJDJTIyZ2xvYmFsJTIyJTNBJTIyJTIyJTdEJTJDJTIyYXNzZXRzJTIyJTNBJTVCJTVCJTIyaW5kZXguanMlMjIlMkMlMjJjb25zdCUyMCU3QmdldEVudiU3RCUyMCUzRCUyMHJlcXVpcmUoJTVDJTIyLiUyRmVudi5qcyU1QyUyMiklM0IlNUNuJTVDbmNvbnNvbGUubG9nKGdldEVudigpKSUzQiUyMiUyQzElNUQlMkMlNUIlMjJlbnYuanMlMjIlMkMlMjJleHBvcnRzLmdldEVudiUyMCUzRCUyMGZ1bmN0aW9uJTIwKCklMjAlN0IlNUNuJTVDdGlmJTIwKHR5cGVvZiUyMG1vZHVsZSUyMCElM0QlM0QlMjAlNUMlMjJ1bmRlZmluZWQlNUMlMjIlMjAlMjYlMjYlMjBtb2R1bGUucmVxdWlyZSklMjAlN0IlNUNuJTVDdCU1Q3RyZXR1cm4lMjAlNUMlMjJOb2RlJTVDJTIyJTNCJTVDbiU1Q3QlN0QlMjBlbHNlJTIwJTdCJTVDbiU1Q3QlNUN0cmV0dXJuJTIwJTVDJTIyQnJvd3NlciU1QyUyMiUzQiU1Q24lNUN0JTdEJTVDbiU3RCgpJTNCJTIyJTVEJTVEJTdE) (Open console to see the error as well)

## ✔️ PR Todo

- [ ] Added/updated unit tests for this change
- [x] Filled out test instructions (In case there aren't any unit tests)
- [x] Included links to related issues/PRs

### CODE REVIEW

**Comment by mischnic** [comment]
> This replace `module.require` with `null` in the browser

I'm not even sure if that's what we want to do

Is `if (typeof module !== "undefined" && module.require)` the "canonical" way to check for Node?

**Comment by devongovett** [comment]
Could you add a test?

**Comment by devongovett** [comment]
`module.require` appears not to be implemented by webpack, so I'd say replacing it with null is fine.

**Comment by mischnic** [comment]
@devongovett You did what I mentioned in my last comment:
adding a test as you did passes even without the changes to `hoist.js` because `module` is actually defined in the test environment: https://github.com/parcel-bundler/parcel/blob/a50ddd5ee18bbf2a70033fb118e6ec3a93a4ed97/packages/core/test-utils/src/utils.js#L230-L238

**Pull request merged**
