### PR TITLE
Keep folder structure and filename

### PR DESCRIPTION
**Pull request by zeakd**
Hi. this PR is related to #433 

This PR does two things.

1. keep filepath (folder structure and filename) 
2. dist folder can be served as it is

### CODE REVIEW

**Comment by devongovett** [comment]
See also #307.

**Comment by TheBlackBolt** [comment]
What is the status on this pull request? Also where can I view upcoming release dates?

**Comment by pauldariye** [comment]
Is there update on when this will land?

**Comment by zeakd** [comment]
@TheBlackBolt #307 It seems like they use hashed name for output files because of unique name.  IMO hashed filename that currently used is not usable if parcel keep filename.

**Comment by dbrw** [comment]
IMO this feature is actually a must have.
It is very convenient to have the original directory structure and file names.

**Comment by marcklei** [comment]
Also really need this feature. +1
I will try this branch in my project and share my experience.

**Comment by Chathula** [comment]
waiting for this PR!  this is a must!

**Comment by Slapbox** [comment]
Agreed. Not having this is really causing me problems. You can work around not having it, but it's not a good workflow at all.

**Comment by bricss** [comment]
I'm going `bananas` without this feature.

**Comment by devongovett** [comment]
Should be solved by #1025 which retains filenames and folder structure for linked files, and content hashes static assets. Please help test using the master branch - a release will hopefully come next week!

**Comment by alexpi** [comment]
So, if I understand correctly, it is not possible to keep folder structure for static assets?

**Comment by MindaugasNarbutas** [comment]
same question about keeping folder structure for build? is there any progress?

**Comment by DeMoorJasper** [comment]
Please open up a new issue to discuss this.

**Pull request closed without merging**
