### PR TITLE
Retain image EXIF data in the transformer

### PR DESCRIPTION
**Pull request by thewilkybarkid**
# ↪️ Pull Request

Following https://github.com/parcel-bundler/parcel/pull/6624#discussion_r677170694 I created a test for #6445.

Turns out that the transformer strips EXIF data, which probably isn't meant (should be in https://github.com/parcel-bundler/parcel/pull/6624).

So, this keeps EXIF data, as well as testing the consumption of the image orientation.

The test image comes from https://www.galloway.me.uk/2012/01/uiimageorientation-exif-orientation-sample-images/

## 💻 Examples

See https://github.com/parcel-bundler/parcel/issues/6444.

## ✔️ PR Todo

- [x] Added/updated unit tests for this change
- [x] Filled out test instructions (In case there aren't any unit tests)
- [x] Included links to related issues/PRs

### CODE REVIEW

**Review by DeMoorJasper — APPROVED** [review]

**Review by devongovett — APPROVED** [review]

**Comment by devongovett** [comment]
Seems ok, though not exactly sure what the use case is. The image optimizer should strip this for prod builds.

**Comment by mischnic** [comment]
If you have an image that is rotated via EXIF (not in the actual image data), then applying the image transformer would previously output an image that has a different orientation than the original.

**Comment by DeMoorJasper** [comment]
> If you have an image that is rotated via EXIF (not in the actual image data), then applying the image transformer would previously output an image that has a different orientation than the original.

@mischnic that should already be handled by the `image.rotate()` in the image transformer

**Comment by thewilkybarkid** [comment]
> Seems ok, though not exactly sure what the use case is.

I was just adding a missing test case, wasn't expecting to see the transformer strip EXIF data (so only images that are resized etc lose it).

> The image optimizer should strip this for prod builds.

Yep, I've added another test case for this. (Also stopped the optimizer from running on non-prod builds too.)

**Comment by devongovett** [comment]
Sorry I missed this was getting merged. Should we check that metadata doesn't get added in production builds? The optimizer should strip it out, but only for JPEG and PNGs.

**Comment by KevinDillaerts** [comment]
Hello all, I seem to have a similar issue still running Parcel 2.
Below are the versions I'm running:

`"devDependencies": {
    "@parcel/packager-raw-url": "^2.0.1",
    "@parcel/transformer-sass": "^2.0.1",
    "@parcel/transformer-webmanifest": "^2.0.1",
    "parcel": "^2.0.1",
    "posthtml-include": "^1.7.1",
    "sharp": "^0.29.3"
  },`

I have some images in portrait mode that work fine on localhost, however after build when running serve these are rotated.
In the out folder I can see these files have been rotated, so I assume this is related to the issue with the transformer as well.
This is the localhost result:
localhost

And this is from 'serve':
serve

Here are the images in question, the first one is the original file I have in my src folder, the second what ends up in the out folder:
riks_cafe_004(src folder)
riks_cafe_004(out folder)


Other portrait mode images I'm using work fine, so this seems to be related to these aspect ratios.
I did resize these earlier running an Automator script I use where the longest side gets scaled to 1000px.
This works fine for the other images on the site, as these were all running from the same script.

**Pull request merged**
