### PR TITLE
Change inline-requires to only run when optimizing

### PR DESCRIPTION
**Pull request by marcins**
# ↪️ Pull Request

Just some minor cleanup.

Changes the plugin so that rather than always running in production mode, will instead only run when doing an optimized build.

Also removes some of the verbose logging, replacing measurement with tracing.

Fixes the example config in `README.md`.

## 🚨 Test instructions

Tested manually that it still works with prod builds.

## ✔️ PR Todo

- [n/a ] Added/updated unit tests for this change
- [x] Filled out test instructions (In case there aren't any unit tests)
- [x] Included links to related issues/PRs

### CODE REVIEW

**Review by mattcompiles — APPROVED** [review]
Nice one

**Comment by mischnic** [comment]
Previously `options.mode !== 'production'` coincidentally also ensured `scopeHoist == true` for most cases. But you should probably add a test for scope hoisting explicitly, that should fix the tests

**Comment by mischnic** [comment]
As far as I understand it, the optimizer only works with scope-hoisting, so checking `bundle.env.scopeHoisting` would probably be good as well. But you probably simply never use it in that situation 🤷‍♂️

**Comment by marcins** [comment]
> As far as I understand it, the optimizer only works with scope-hoisting, so checking `bundle.env.scopeHoisting` would probably be good as well. But you probably simply never use it in that situation 🤷‍♂️

It works regardless of scope hoisting or not - it's actually probably _less effective_ with scope hoisting because there's fewer `parcelRequire` calls to defer. A more "complete" solution would also need to handle scope hoisted assets and defer their execution too.

**Pull request merged**
