### PR TITLE
Add "copy to clipboard" functionality to parcel-cli

### PR DESCRIPTION
**Pull request by yeskunall**
As per https://github.com/parcel-bundler/parcel/pull/185#issuecomment-350607109. There's just one problem, however:

screen shot 2017-12-12 at 7 24 01 pm

... yeah. The logger writes (almost) the same info. 😬

Thoughts?

### CODE REVIEW

**Comment by devongovett** [comment]
@yeskunall cool! maybe rather than having two messages in the terminal we could just add to the existing "Server running at http://localhost:1234" message?

**Comment by yeskunall** [comment]
@devongovett I would have already done that, but the second message comes from `Server.js`, and I see no easy way of adding it to that message.

The only way I can think of is explicitly passing the `command` param from here:

https://github.com/parcel-bundler/parcel/blob/b7b2991d69b960d9f2951828b8145a6d9396ee4e/bin/cli.js#L94

... into the server object created in `Server#serve`. 😓

Then print the appropriate message according to what the value of `command.open` is.

**Comment by ykpythemind** [comment]
Whenever I run parcel command, my clipboard is overwritten?? 
I don't think it's a good idea 🤔

**Comment by DeMoorJasper** [comment]
This should probably be an option, because it might get annoying for people who have anything in their clipboard.
But i guess this is kinda the same as what --open was aiming for, to make going to that location easier?

**Comment by yeskunall** [comment]
I feel like we're adding way too many options. It's all about saving a few key strokes. So I say we either opt to keep it as it is, or we don't introduce this change at all.

@DeMoorJasper yeah, it is. But I would rather keep this over `--open`. I would never use that option, but I _would_ like this one. This is obviously open for discussion.

**Comment by DeMoorJasper** [comment]
Imo this is more of a choice between --open or --copy for the user, so it wouldn't add any option it would just supply a choice

**Comment by brandon93s** [comment]
With the availability of `--open` and the desire not to fiddle with the users clipboard, we're going to hold off on this for now.

**Pull request closed without merging**
