### PR TITLE
Upgrade Flow to 0.161.0

### PR DESCRIPTION
**Pull request by wbinnssmith**
Changes: https://github.com/facebook/flow/releases/tag/v0.161.0

Flow seems to lose refinement in a case where it inferred a variable was constlike before. Updated to use a const in its place.

Test Plan: `yarn flow check`

### CODE REVIEW

**Comment by wbinnssmith** [comment]
Anecdotally, performance seems improved for our most complex files 🙂

**Comment by mischnic** [comment]
What about this instead?

```js
    let asset = bundle.traverse((node, _, actions) => {
      if (
        node.type === 'dependency' &&
        node.value.specifier === '@parcel/service-worker'
      ) {
        let asset = bundleGraph.getResolvedAsset(node.value, bundle);
        actions.stop();
        return asset;
      }
    });

    if (!asset) {
      return [];
    }
```

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>Kitchen Sink ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 2.37s | +30.00ms |
| Cached | 355.00ms | +1.00ms |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/parcel.7cdb0fad.webp | 102.94kb | +0.00b | 749.00ms | +49.00ms ⚠️ |
| dist/legacy/parcel.7cdb0fad.webp | 102.94kb | +0.00b | 750.00ms | +48.00ms ⚠️ |
| dist/modern/parcel.7cdb0fad.webp | 102.94kb | +0.00b | 749.00ms | +47.00ms ⚠️ |
| dist/legacy/index.html | 826.00b | +0.00b | 1.25s | +69.00ms ⚠️ |
| dist/modern/index.html | 749.00b | +0.00b | 1.25s | +70.00ms ⚠️ |

</p></details>

<details><summary>React HackerNews ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 11.58s | +98.00ms |
| Cached | 525.00ms | -13.00ms |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

*No bundle changes detected.*

</p></details>

<details><summary>AtlasKit Editor ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 1.27m | -189.00ms |
| Cached | 1.85s | -55.00ms |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.eb6cbeab.js | 1.78mb | -4.00b 🚀 | 22.00s | -87.00ms |
| dist/index.49b5ed00.js | 694.70kb | +15.00b ⚠️ | 58.53s | -841.00ms |
| dist/editorView.418f4b80.js | 594.84kb | +0.00b | 57.90s | +13.81s ⚠️ |
| dist/popup.0f5cf550.js | 209.67kb | +0.00b | 57.90s | +13.81s ⚠️ |
| dist/EmojiPickerComponent.7be0e8bb.js | 146.67kb | +0.00b | 35.65s | +11.51s ⚠️ |
| dist/Toolbar.ce05f6f5.js | 107.23kb | +0.00b | 57.90s | +13.81s ⚠️ |
| dist/card.d9addeb6.js | 62.67kb | +0.00b | 58.52s | +14.43s ⚠️ |
| dist/Modal.ccb975dd.js | 45.33kb | +0.00b | 57.91s | +13.82s ⚠️ |
| dist/esm.34bf650d.js | 33.15kb | +0.00b | 35.65s | +11.51s ⚠️ |
| dist/DatePicker.b6911783.js | 22.98kb | +0.00b | 35.65s | +11.51s ⚠️ |
| dist/js.0f0bb621.js | 17.25kb | +0.00b | 57.90s | +13.82s ⚠️ |
| dist/ui.ad8251e1.js | 14.94kb | +0.00b | 57.91s | +13.82s ⚠️ |
| dist/smartMediaEditor.74af10c8.js | 13.25kb | +0.00b | 57.90s | +13.81s ⚠️ |
| dist/dropzone.0d183115.js | 12.15kb | +0.00b | 57.90s | +13.81s ⚠️ |
| dist/card.45f850d6.js | 5.77kb | +0.00b | 58.52s | +14.43s ⚠️ |
| dist/EmojiPickerComponent.55e0a64c.js | 3.73kb | +0.00b | 57.91s | +13.82s ⚠️ |
| dist/png-chunks-extract.94b5b9fc.js | 3.58kb | +0.00b | 57.90s | +13.82s ⚠️ |
| dist/dropzone.a10cce43.js | 3.29kb | +0.00b | 57.90s | +13.81s ⚠️ |
| dist/Modal.7f4c60b3.js | 3.15kb | +0.00b | 58.52s | +14.43s ⚠️ |
| dist/clipboard.f917539f.js | 2.93kb | +0.00b | 57.90s | +13.81s ⚠️ |
| dist/ResourcedEmojiComponent.78f6ddfc.js | 2.12kb | +0.00b | 57.91s | +13.82s ⚠️ |
| dist/feedback.e18b45f0.js | 1.77kb | +0.00b | 35.65s | +11.51s ⚠️ |
| dist/browser.09200cd5.js | 1.69kb | +0.00b | 57.90s | +13.81s ⚠️ |
| dist/workerHasher.567cfc57.js | 1.63kb | +0.00b | 35.65s | +11.51s ⚠️ |
| dist/heading6.b3b946d1.js | 1.51kb | +0.00b | 35.65s | +11.52s ⚠️ |
| dist/heading5.e617db66.js | 1.38kb | +0.00b | 35.65s | +11.52s ⚠️ |
| dist/expand.1f17de7f.js | 1.29kb | +0.00b | 35.65s | +11.51s ⚠️ |
| dist/media-card-analytics-error-boundary.75fac461.js | 1.12kb | +0.00b | 57.90s | +13.81s ⚠️ |
| dist/media-picker-analytics-error-boundary.cfe02cc6.js | 966.00b | +0.00b | 57.90s | +13.81s ⚠️ |
| dist/media-card-analytics-error-boundary.b1a780f3.js | 962.00b | +0.00b | 58.52s | +14.43s ⚠️ |
| dist/simpleHasher.2a6e12b6.js | 643.00b | +0.00b | 57.91s | +13.82s ⚠️ |

</p></details>

<details><summary>Three.js ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 8.09s | -51.00ms |
| Cached | 472.00ms | -1.00ms |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

*No bundle changes detected.*

</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/311593132487606848)**

**Comment by wbinnssmith** [comment]
> What about this instead?
> 
> ```js
>     let asset = bundle.traverse((node, _, actions) => {
>       if (
>         node.type === 'dependency' &&
>         node.value.specifier === '@parcel/service-worker'
>       ) {
>         let asset = bundleGraph.getResolvedAsset(node.value, bundle);
>         actions.stop();
>         return asset;
>       }
>     });
> 
>     if (!asset) {
>       return [];
>     }
> ```

Clever. I like it 🙂

**Review by mischnic — APPROVED** [review]

**Review by devongovett — APPROVED** [review]

**Pull request merged**
