### PR TITLE
Use babel7 polyfill

### PR DESCRIPTION
**Pull request by codejamninja**
`@babel/polyfill` should be used instead of `babel-polyfill` for compatibility with babel7.

### CODE REVIEW

**Comment by codejamninja** [comment]
This failed because there was a network error on the server. The tests are actually all passing 👍

**Comment by DeMoorJasper** [comment]
Would be nicer if we would be using `useBuiltIns: "usage"` for preset env

**Comment by codejamninja** [comment]
Does `useBuiltIns` work for browser applications? Also, until you support `useBuiltInts` can you use the correct polyfill. The old polyfill is breaking the code and the unit tests.

**Comment by icopp** [comment]
`useBuiltIns` is intended for both node and the browser... See use of `targets` in the [docs](https://babeljs.io/docs/en/usage).

**Comment by devongovett** [comment]
This is handled in the babel7 branch

**Comment by sigerello** [comment]
@devongovett, any assumptions when `useBuiltIns: "usage"` will be supported on master?

**Pull request closed without merging**
