### PR TITLE
Fixes less files imported dependencies not watched

### PR DESCRIPTION
**Pull request by gmougeolle**
# ↪️ Pull Request

This PR adapts the LessTransformer to allow it to include imported files to the asset's included files, resulting in those files being watched properly.

## 💻 Examples

Take a `.less` file that imports other files (using less without CSS Modules, it's very common to have a single file acting as an entrypoint) :

```less
//index.less
import "other.less";
```

```less
//other.less
body {
    background: red;
}
```

If you run `yarn parcel index.less`, the first build works, but any further change to the `other.less` file will remain unnoticed by the bundler, requiring a change to the `index.less` file in order to take changes into account. Others have reported this as well in #5299.

This PR is inspired by the SASS Transformer which does this by default.

## 🚨 Test instructions

I'm not sure whether the watcher part of Parcel supports this kind of tests (I didn't find anything about this in the documentation). The SASS transformer does not include any kind of tests about this case.

## ✔️ PR Todo

- [] Added/updated unit tests for this change
- [] Filled out test instructions (In case there aren't any unit tests)
- [x] Included links to related issues/PRs

### CODE REVIEW

**Comment by mischnic** [comment]
Does Less read sourcemap comments? In that case, that array could refer to non-existent (or irrelevant) files.

**Comment by gmougeolle** [comment]
I did some quick testing and after trying to reference other less files in different ways (content strings, comments), it didn't end up in the sourcemap file list. However I couldn't find the code responsible for parsing this in the less compiler source so take that with a grain of salt.
Is there a utility in the Parcel core that could check that the file exists as an additional security mesure ? In the meantime, I've published a `parcel-transformer-more` package that simply add those lines for those who want to test it with their code.

**Comment by mischnic** [comment]
Yeah, either `output.imports` or we could also track this ourselves in `resolvePathPlugin` (not sure if `output.imports` is the resolved or unresolved path).

**Comment by devongovett** [comment]
Was this possibly fixed by #5625? See the changes [here](https://github.com/parcel-bundler/parcel/pull/5625/files#diff-8e49c8d44b06d801d9f372ea303a129551a0e8d86e90639084bfdc4a36c19caf)

**Comment by mischnic** [comment]
Your examples appears to work now even without these changes

**Pull request closed without merging**
