### PR TITLE
Move astring babel generator into seperate package

### PR DESCRIPTION
**Pull request by DeMoorJasper**
# ↪️ Pull Request

Move the babel astring generator into a seperate package this will make it easier to re-use outside of Parcel.

Full disclosure, I wanna use this in the codesandbox bundler to make it a bit faster. Seemed better to collaborate on this than to copy-paste

## ✔️ PR Todo

- [x] Added/updated unit tests for this change
- [x] Filled out test instructions (In case there aren't any unit tests)
- [x] Included links to related issues/PRs

### CODE REVIEW

**Comment by mischnic** [comment]
It's not actually used anymore, should we just remove it (= you can create a new separate npm package with the code)?

**Comment by DeMoorJasper** [comment]
@mischnic interesting, didn't notice we stopped using it, was there a reason for it?

**Comment by mischnic** [comment]
So the only case where it could be used is when the Babel transformer runs. But if you use Babel only for some custom plugin (flow, css-in-js) and don't transpile JSX, then astring fails because it doesn't support JSX. (And there's also https://github.com/parcel-bundler/parcel/issues/6115, but that's a regular bug)

https://parcel.height.app/T-1052

**Comment by DeMoorJasper** [comment]
Aha that makes sense, thanks Niklas. Will copy it into a new package separate from Parcel

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>Kitchen Sink ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 1.69s | -81.00ms |
| Cached | 380.00ms | -31.00ms 🚀 |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/index.html | 701.00b | +0.00b | 811.00ms | -58.00ms 🚀 |
| dist/modern/index.html | 701.00b | +0.00b | 811.00ms | -58.00ms 🚀 |
| dist/legacy/index.b007599d.css | 77.00b | +0.00b | 811.00ms | -58.00ms 🚀 |
| dist/modern/index.2ce90b9c.css | 77.00b | +0.00b | 811.00ms | -58.00ms 🚀 |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/modern/parcel.d5807e82.webp | 102.94kb | +0.00b | 56.00ms | +4.00ms ⚠️ |
| dist/legacy/index.a6466710.js | 2.00kb | +0.00b | 82.00ms | +11.00ms ⚠️ |
| dist/modern/index.841e7a6e.js | 2.00kb | +0.00b | 82.00ms | +11.00ms ⚠️ |
| dist/legacy/index.html | 701.00b | +0.00b | 83.00ms | +12.00ms ⚠️ |
| dist/modern/index.html | 701.00b | +0.00b | 82.00ms | +11.00ms ⚠️ |
| dist/legacy/index.b007599d.css | 77.00b | +0.00b | 82.00ms | +11.00ms ⚠️ |
| dist/modern/index.2ce90b9c.css | 77.00b | +0.00b | 82.00ms | +11.00ms ⚠️ |

</p></details>

<details><summary>React HackerNews ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 10.94s | -71.00ms |
| Cached | 585.00ms | -91.00ms 🚀 |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.js | 491.15kb | +0.00b | 85.00ms | -9.00ms 🚀 |
| dist/PermalinkedComment.0c75a695.js | 4.19kb | +0.00b | 85.00ms | -8.00ms 🚀 |
| dist/UserProfile.031c1548.js | 1.56kb | +0.00b | 85.00ms | -8.00ms 🚀 |
| dist/NotFound.c3254f12.js | 417.00b | +0.00b | 85.00ms | -8.00ms 🚀 |
| dist/logo.24c8bf9e.png | 274.00b | +0.00b | 55.00ms | -5.00ms 🚀 |

</p></details>

<details><summary>AtlasKit Editor ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 1.22m | +1.64s |
| Cached | 2.87s | -91.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.477d69d4.js | 2.60mb | +7.00b ⚠️ | 28.52s | +89.00ms |
| dist/EmojiPickerComponent.341c7c17.js | 147.28kb | +0.00b | 56.54s | +10.40s ⚠️ |
| dist/Modal.3ed1bb10.js | 45.31kb | +15.00b ⚠️ | 28.46s | +102.00ms |
| dist/heading2.689c1725.js | 1.32kb | +0.00b | 28.77s | -16.74s 🚀 |
| dist/index.html | 119.00b | +0.00b | 24.02s | -3.98s 🚀 |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.2d667946.js | 2.60mb | +10.00b ⚠️ | 159.00ms | +22.00ms ⚠️ |
| dist/pdf.worker.19255c11.js | 727.98kb | +0.00b | 219.00ms | +14.00ms ⚠️ |
| dist/editorView.05156164.js | 594.99kb | +0.00b | 244.00ms | +22.00ms ⚠️ |
| dist/pdfRenderer.cb376b35.js | 411.56kb | +0.00b | 219.00ms | +14.00ms ⚠️ |
| dist/popup.4185c395.js | 209.85kb | +0.00b | 233.00ms | +22.00ms ⚠️ |
| dist/Toolbar.3aeb097b.js | 107.27kb | +0.00b | 244.00ms | +21.00ms ⚠️ |
| dist/media-viewer.ea85a336.js | 74.99kb | +0.00b | 219.00ms | +14.00ms ⚠️ |
| dist/card.77a4ddf8.js | 60.71kb | +0.00b | 237.00ms | +22.00ms ⚠️ |
| dist/Modal.3ed1bb10.js | 45.31kb | +15.00b ⚠️ | 164.00ms | +23.00ms ⚠️ |
| dist/component.ed43d342.js | 37.59kb | +0.00b | 162.00ms | +20.00ms ⚠️ |
| dist/component.8f31584d.js | 24.95kb | +0.00b | 206.00ms | +63.00ms ⚠️ |
| dist/js.85def1c2.js | 17.33kb | +0.00b | 165.00ms | +22.00ms ⚠️ |
| dist/smartMediaEditor.bda395b3.js | 13.25kb | +0.00b | 240.00ms | +22.00ms ⚠️ |
| dist/dropzone.4bd58ed3.js | 12.15kb | +0.00b | 235.00ms | +22.00ms ⚠️ |
| dist/media-viewer.b1bdbe97.js | 4.51kb | +0.00b | 220.00ms | +15.00ms ⚠️ |
| dist/media-viewer.9cc3198b.js | 3.98kb | +0.00b | 219.00ms | +14.00ms ⚠️ |
| dist/png-chunks-extract.26a58e9e.js | 3.58kb | +0.00b | 167.00ms | +24.00ms ⚠️ |
| dist/index.1201181a.css | 3.46kb | +0.00b | 247.00ms | +21.00ms ⚠️ |
| dist/dropzone.9159a21f.js | 3.29kb | +0.00b | 233.00ms | +21.00ms ⚠️ |
| dist/Modal.97b7b979.js | 3.15kb | +0.00b | 162.00ms | +22.00ms ⚠️ |
| dist/clipboard.b54b4f8e.js | 2.93kb | +0.00b | 235.00ms | +22.00ms ⚠️ |
| dist/16.ca688077.js | 2.36kb | +0.00b | 159.00ms | +21.00ms ⚠️ |
| dist/card.1653aa06.js | 2.06kb | +0.00b | 221.00ms | +12.00ms ⚠️ |
| dist/date.13837189.js | 1.86kb | +0.00b | 169.00ms | +23.00ms ⚠️ |
| dist/images.a51e31c2.js | 1.80kb | +0.00b | 172.00ms | +23.00ms ⚠️ |
| dist/feedback.a4084b43.js | 1.77kb | +0.00b | 185.00ms | +23.00ms ⚠️ |
| dist/16.b8c83009.js | 1.75kb | +0.00b | 219.00ms | +20.00ms ⚠️ |
| dist/browser.ae1801c7.js | 1.69kb | +0.00b | 236.00ms | +22.00ms ⚠️ |
| dist/16.f48613ba.js | 1.68kb | +0.00b | 219.00ms | +21.00ms ⚠️ |
| dist/workerHasher.a70276d4.js | 1.63kb | +0.00b | 239.00ms | +23.00ms ⚠️ |
| dist/list-number.494da4e7.js | 1.59kb | +0.00b | 174.00ms | +23.00ms ⚠️ |
| dist/status.8783408d.js | 1.59kb | +0.00b | 180.00ms | +23.00ms ⚠️ |
| dist/code.677bd70c.js | 1.51kb | +0.00b | 169.00ms | +24.00ms ⚠️ |
| dist/heading6.2df789d9.js | 1.51kb | +0.00b | 184.00ms | +23.00ms ⚠️ |
| dist/heading3.99e77e15.js | 1.49kb | +0.00b | 182.00ms | +23.00ms ⚠️ |
| dist/link.eecf8ee1.js | 1.43kb | +0.00b | 173.00ms | +23.00ms ⚠️ |
| dist/16.0f105e82.js | 1.40kb | +0.00b | 219.00ms | +20.00ms ⚠️ |
| dist/heading5.c9eff376.js | 1.38kb | +0.00b | 183.00ms | +22.00ms ⚠️ |
| dist/emoji.e0bb5bdd.js | 1.36kb | +0.00b | 171.00ms | +23.00ms ⚠️ |
| dist/16.24ecf6d5.js | 1.35kb | +0.00b | 219.00ms | +20.00ms ⚠️ |
| dist/16.fe096c73.js | 1.33kb | +0.00b | 244.00ms | +21.00ms ⚠️ |
| dist/16.9c0dd14e.js | 1.33kb | +0.00b | 161.00ms | +22.00ms ⚠️ |
| dist/heading2.689c1725.js | 1.32kb | +0.00b | 182.00ms | +23.00ms ⚠️ |
| dist/16.f6f07bdf.js | 1.29kb | +0.00b | 219.00ms | +20.00ms ⚠️ |
| dist/expand.c97517e7.js | 1.29kb | +0.00b | 186.00ms | -11.00ms 🚀 |
| dist/heading4.a48496c5.js | 1.27kb | +0.00b | 183.00ms | +23.00ms ⚠️ |
| dist/16.abb96752.js | 1.25kb | +0.00b | 219.00ms | +20.00ms ⚠️ |
| dist/16.8a916ec3.js | 1.22kb | +0.00b | 160.00ms | +21.00ms ⚠️ |
| dist/16.5ab0c52f.js | 1.21kb | +0.00b | 219.00ms | +20.00ms ⚠️ |
| dist/16.17b379b7.js | 1.20kb | +0.00b | 167.00ms | +23.00ms ⚠️ |
| dist/mention.7513d265.js | 1.20kb | +0.00b | 175.00ms | +23.00ms ⚠️ |
| dist/layout.a2215d1e.js | 1.18kb | +0.00b | 172.00ms | +22.00ms ⚠️ |
| dist/Modal.71b21a38.js | 1.17kb | +0.00b | 164.00ms | +21.00ms ⚠️ |
| dist/16.dc7fba57.js | 1.16kb | +0.00b | 219.00ms | +20.00ms ⚠️ |
| dist/heading1.53882705.js | 1.16kb | +0.00b | 181.00ms | +23.00ms ⚠️ |
| dist/16.4947d5d2.js | 1.16kb | +0.00b | 160.00ms | +21.00ms ⚠️ |
| dist/divider.61f72909.js | 1.16kb | +0.00b | 171.00ms | +24.00ms ⚠️ |
| dist/quote.ac356b63.js | 1.15kb | +0.00b | 179.00ms | +23.00ms ⚠️ |
| dist/16.61848cd9.js | 1.15kb | +0.00b | 219.00ms | +20.00ms ⚠️ |
| dist/16.f88600cd.js | 1.15kb | +0.00b | 219.00ms | +20.00ms ⚠️ |
| dist/16.3457832f.js | 1.15kb | +0.00b | 219.00ms | +20.00ms ⚠️ |
| dist/action.03622130.js | 1.13kb | +0.00b | 168.00ms | +23.00ms ⚠️ |
| dist/component.0faea072.js | 1.12kb | +0.00b | 159.00ms | +22.00ms ⚠️ |
| dist/decision.e8963abf.js | 1.12kb | +0.00b | 170.00ms | +23.00ms ⚠️ |
| dist/panel-warning.d87689fa.js | 1.11kb | +0.00b | 178.00ms | +23.00ms ⚠️ |
| dist/16.71584d67.js | 1.11kb | +0.00b | 159.00ms | +21.00ms ⚠️ |
| dist/list.452d2378.js | 1.08kb | +0.00b | 174.00ms | +22.00ms ⚠️ |
| dist/16.d79d0001.js | 1.07kb | +0.00b | 219.00ms | +20.00ms ⚠️ |
| dist/panel-error.2d1266a1.js | 1.01kb | +0.00b | 176.00ms | +23.00ms ⚠️ |
| dist/panel.2fa2f198.js | 1.01kb | +0.00b | 178.00ms | +23.00ms ⚠️ |
| dist/table.5143dd29.js | 1022.00b | +0.00b | 180.00ms | +23.00ms ⚠️ |
| dist/panel-success.8c4cf740.js | 978.00b | +0.00b | 177.00ms | +23.00ms ⚠️ |
| dist/panel-note.aa22bfaa.js | 974.00b | +0.00b | 176.00ms | +23.00ms ⚠️ |
| dist/media-viewer-analytics-error-boundary.c51589b7.js | 964.00b | +0.00b | 220.00ms | +11.00ms |
| dist/media-picker-analytics-error-boundary.da55e63c.js | 964.00b | +0.00b | 234.00ms | +22.00ms ⚠️ |
| dist/media-card-analytics-error-boundary.a9392a91.js | 960.00b | +0.00b | 238.00ms | +22.00ms ⚠️ |
| dist/simpleHasher.5278a07e.js | 641.00b | +0.00b | 239.00ms | +22.00ms ⚠️ |
| dist/index.html | 119.00b | +0.00b | 112.00ms | +31.00ms ⚠️ |

</p></details>

<details><summary>Three.js ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 7.67s | +103.00ms |
| Cached | 595.00ms | +36.00ms ⚠️ |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/Three.js | 579.69kb | +0.00b | 73.00ms | +6.00ms ⚠️ |

</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/300186538253222410)**

**Pull request closed without merging**
