### PR TITLE
feat(cli): Add --global option in commonOptions in cli

### PR DESCRIPTION
**Pull request by marosca**
# ↪️ Pull Request
With this pr I want to add --global option to cli like this other pr that was merge into Parcel1 code:
https://github.com/parcel-bundler/parcel/pull/453/files

The purpose is to reestablish the functionality of having access globally to the exports

### CODE REVIEW

**Comment by mischnic** [comment]
With your change, the option would do nothing - to actually make it work:

1. It needs to be added here as well:
https://github.com/parcel-bundler/parcel/blob/3a4e13fa424ef7c17dfc3d52ee1638a61dd58fdf/packages/core/types/index.js#L210
and
https://github.com/parcel-bundler/parcel/blob/3a4e13fa424ef7c17dfc3d52ee1638a61dd58fdf/packages/core/types/index.js#L214-L229
2. Needs to be added to the cli handling:
https://github.com/parcel-bundler/parcel/blob/3a4e13fa424ef7c17dfc3d52ee1638a61dd58fdf/packages/core/parcel/src/cli.js#L305-L321
3. Actually set in in the `JSPackager` (just like in the PR you linked):
https://github.com/parcel-bundler/parcel/blob/3a4e13fa424ef7c17dfc3d52ee1638a61dd58fdf/packages/packagers/js/src/JSPackager.js#L188
4. We need to figure something out for scope-hoisting, probably in this function: 
https://github.com/parcel-bundler/parcel/blob/3a4e13fa424ef7c17dfc3d52ee1638a61dd58fdf/packages/shared/scope-hoisting/src/formats/global.js#L69

**Comment by marosca** [comment]
Thanks for your help
For this comment (We need to figure something out for scope-hoisting, probably in this function:) I dont know what I have to do exactly.

**Comment by mischnic** [comment]
> I dont know what I have to do exactly.

I'll have to think about it a bit more, but `${global} = ${entry.meta.exportsIdentifier}` should be inserted if the global option is used and if `bundle` is the main bundle (not sure how to determine that) in `packages/shared/scope-hoisting/src/formats/global.js#generateExports`.

Will report back once I have found a solution.

**Comment by marosca** [comment]
Really, thank you very much. In our project we need to have global access to exports and we do it with Parcel1. We are interested in using Parcel2 but we miss that functionality.

We greatly appreciate your help

**Comment by devongovett** [comment]
I don't think this should necessarily be exposed as a CLI option, especially now that we have multiple targets. Perhaps it should be part of the target config in package.json? Should we make this part of a more general UMD output format?

**Comment by jbaiter** [comment]
> I'll have to think about it a bit more, but ${global} = ${entry.meta.exportsIdentifier} should be inserted if the global option is used and if bundle is the main bundle (not sure how to determine that) in packages/shared/scope-hoisting/src/formats/global.js#generateExports.
>
> Will report back once I have found a solution.

Has there been progress on this? We're relying on this feature as well and would love to try out Parcel v2 :-)

**Comment by mischnic** [comment]
Superseded by #7240

**Pull request closed without merging**
