### PR TITLE
[WIP] Keep file names

### PR DESCRIPTION
**Pull request by ssuman**
This commit when applied should allow builds to keep their original name in their build outputs.
#280

### CODE REVIEW

**Comment by devongovett** [comment]
This won't work for cases where there are multiple files with the same name, since parcel outputs a flat dist folder.

e.g. if I have `app/a/index.js` and `app/b/index.js`, `dist/index.js` would be generated twice. That's why parcel generates the output filenames as a hash.

**Comment by ssuman** [comment]
@devongovett Maintaining relative folder names should work right ? 

```
dist/app/a/index.js
dist/app/b/index.js
```

**Comment by zeakd** [comment]
Are there any updates in this pr?

**Comment by bricss** [comment]
Yes, please!

**Comment by devongovett** [comment]
Should be solved by #1025 which retains filenames and folder structure for linked files, and content hashes static assets. Please help test using the master branch - a release will hopefully come next week!

**Pull request closed without merging**
