### PR TITLE
Transform Graphviz files

### PR DESCRIPTION
**Pull request by thewilkybarkid**
# ↪️ Pull Request

Transforms Graphviz files (`.gv` or the alternative `.dot`) into SVGs.

## 💻 Examples

With a HTML file containing:

```html
<object data="graph.gv"></object>
```

and a Graphviz file containing:

```gv
digraph graphname {
    a -> b -> c;
    b -> d;
}
```

which is turned into an SVG files like:

```svg
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
 "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<!-- Generated by graphviz version 2.47.3 (20210621.0720)
 -->
<!-- Title: graphname Pages: 1 -->
<svg width="134pt" height="188pt"
 viewBox="0.00 0.00 134.00 188.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 184)">
<title>graphname</title>
<polygon fill="white" stroke="transparent" points="-4,4 -4,-184 130,-184 130,4 -4,4"/>
<!-- a -->
<g id="node1" class="node">
<title>a</title>
<ellipse fill="none" stroke="black" cx="63" cy="-162" rx="27" ry="18"/>
<text text-anchor="middle" x="63" y="-157.8" font-family="Times,serif" font-size="14.00">a</text>
</g>
<!-- b -->
<g id="node2" class="node">
<title>b</title>
<ellipse fill="none" stroke="black" cx="63" cy="-90" rx="27" ry="18"/>
<text text-anchor="middle" x="63" y="-85.8" font-family="Times,serif" font-size="14.00">b</text>
</g>
<!-- a&#45;&gt;b -->
<g id="edge1" class="edge">
<title>a&#45;&gt;b</title>
<path fill="none" stroke="black" d="M63,-143.7C63,-135.98 63,-126.71 63,-118.11"/>
<polygon fill="black" stroke="black" points="66.5,-118.1 63,-108.1 59.5,-118.1 66.5,-118.1"/>
</g>
<!-- c -->
<g id="node3" class="node">
<title>c</title>
<ellipse fill="none" stroke="black" cx="27" cy="-18" rx="27" ry="18"/>
<text text-anchor="middle" x="27" y="-13.8" font-family="Times,serif" font-size="14.00">c</text>
</g>
<!-- b&#45;&gt;c -->
<g id="edge2" class="edge">
<title>b&#45;&gt;c</title>
<path fill="none" stroke="black" d="M54.65,-72.76C50.29,-64.28 44.85,-53.71 39.96,-44.2"/>
<polygon fill="black" stroke="black" points="42.99,-42.44 35.3,-35.15 36.77,-45.64 42.99,-42.44"/>
</g>
<!-- d -->
<g id="node4" class="node">
<title>d</title>
<ellipse fill="none" stroke="black" cx="99" cy="-18" rx="27" ry="18"/>
<text text-anchor="middle" x="99" y="-13.8" font-family="Times,serif" font-size="14.00">d</text>
</g>
<!-- b&#45;&gt;d -->
<g id="edge3" class="edge">
<title>b&#45;&gt;d</title>
<path fill="none" stroke="black" d="M71.35,-72.76C75.71,-64.28 81.15,-53.71 86.04,-44.2"/>
<polygon fill="black" stroke="black" points="89.23,-45.64 90.7,-35.15 83.01,-42.44 89.23,-45.64"/>
</g>
</g>
</svg>
```

## ✔️ PR Todo

- [x] Added/updated unit tests for this change
- [x] Filled out test instructions (In case there aren't any unit tests)
- [x] Included links to related issues/PRs

### CODE REVIEW

**Comment by thewilkybarkid** [comment]
Unfortunately, the `@hpcc-js/wasm` library is quite large but does seem to be the most used/maintained Graphviz WASM library.

**Comment by thewilkybarkid** [comment]
It's possible someone might want to retain the GV format for use with [d3-graphviz](https://github.com/magjac/d3-graphviz) or similar, but needs paths updating in the file. It might be better to require an `as` query string parameter like the image transformer (even if only `?as=svg` is required for the moment).

**Comment by thewilkybarkid** [comment]
My usage of this is related to https://github.com/parcel-bundler/parcel/pull/6535, as use of `stylesheet` in a Graphviz is turned into an `xml-stylesheet` processing instruction.

**Comment by DeMoorJasper** [comment]
Not entirely sure if this should be part of this monorepo, maybe this should be a third party plugin?
Not entirely sure how large our scope should be for official plugins as in the end we'll be responsible for maintaining these, what do you think @devongovett & @mischnic ?

**Comment by mischnic** [comment]
I've been wondering the same. I think this can be very useful for e.g. blog posts with diagrams, but we have to draw the line somewhere.

**Comment by thewilkybarkid** [comment]
No problem with making it standalone, but do need the API to be more stable though...

**Comment by thewilkybarkid** [comment]
Since there's now an RC (🥳 ) I'll release this independently and close this PR.

**Comment by mischnic** [comment]
👍

**Comment by thewilkybarkid** [comment]
[parcel-transformer-graphviz](https://www.npmjs.com/package/parcel-transformer-graphviz) now available.

**Pull request closed without merging**
