### PR TITLE
Convert request tracker node types to numbers

### PR DESCRIPTION
**Pull request by mattcompiles**

### CODE REVIEW

**Comment by mischnic** [comment]
Since all of these `typeof FILE_NAME` are all `number`s to Flow, maybe try if using single-char strings helps with the graph size

**Comment by JakeLane** [comment]
Ran a quick local benchmark comparing chars and numbers:
```
const { serialize } = require("v8");
const { writeFile } = require("fs/promises");

const main = async () => {
  const numbers = [];
  const chars = [];

  for (let i = 0; i < 2 ** 25; i += 1) {
    numbers.push({
      type: 0,
    });
    chars.push({
      type: "0",
    });
  }

  console.log("numbers", serialize(numbers).length);
  console.log("chars", serialize(chars).length);
};

main();
```

Prints out:
```
numbers 369098765
chars 40265319
```

Single chars are 9.09% larger

**Comment by mattcompiles** [comment]
Fixed the types but there's some issues with the integration tests still. Will look into it.

**Comment by mattcompiles** [comment]
Closing in favour of #9412

**Pull request closed without merging**
