### PR TITLE
Show warning message when entry file not provided (#1797)

### LINKED ISSUE #1797: Should default to index.html, or show an error
# 🙋 feature request

## 🤔 Expected Behavior

parcel should default to using index.html, or error out.

## 😯 Current Behavior
1. I have a project with index.html
1. I type "parcel" not "parcel index.html"
1. parcel starts up happily
1. but when i load the site, i get nothing.

## Expected
1. I have a project with index.html
1. I type "parcel" not "parcel index.html"

either
* parcel starts up happily by using index.html by default.
or
* parcel throws an error.

### PR DESCRIPTION
**Pull request by rajikaimal**
Fixes #1797

### CODE REVIEW

**Comment by DeMoorJasper** [comment]
They are still checking it, but it shouldn't throw a warning. Parcel can be used without entrypoint it's optional, it should just throw a user friendly error if it can't find one.

**Comment by mohsen1** [comment]
@rajikaimal I think @DeMoorJasper means `package.json` main field, not a file named `pkg.json` :)

**Comment by rajikaimal** [comment]
@mohsen1 Yeah that's what I meant by `pkg.json`. 

@DeMoorJasper Isn't a warning log the best for this scenario, rather than an error log?

**Comment by DeMoorJasper** [comment]
Users of parcel are allowed to use non explicit entrypoints at their own risk, we can log the entrypoints if that's really necessary.

But the most important thing is if parcel can't resolve an entrypoint it should throw a nice error, otherwise users think it's a parcel bug or something. Because users expect too much magic.

**Comment by jchiatt** [comment]
@DeMoorJasper Is this what you're looking for?

~~~js
 for (let entry of this.entryFiles) {
          try {
            let asset = await this.resolveAsset(entry);
            this.buildQueue.add(asset);
            this.entryAssets.add(asset);
          } catch (err) {
            const errMsg = `Failed to load entrypoint. ${err}`
            logger.error(errMsg);
            process.exit(1);
          }
        }
~~~

**Comment by DeMoorJasper** [comment]
Sort of the process.exit seems a bit hacky to me though as in the catch of build we already have something similar

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rajikaimal** [comment]
@jchiatt Hey, did you test the code with `try-catch`? This didn't resolve the bug for me.

**Comment by DeMoorJasper** [comment]
@rajikaimal what bug?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rajikaimal** [comment]
Execution doesn't go to catch block at all.

**Comment by DeMoorJasper** [comment]
That’s strange than it can resolve it right?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DeMoorJasper** [comment]
I've opened a PR with what I had in mind, see #1848

**Pull request closed without merging**
