### PR TITLE
adding support for node 10?

### PR DESCRIPTION
**Pull request by Jimexist**
Do we want to add node version 10 support?

### CODE REVIEW

**Comment by Jimexist** [comment]
i don't think the test failures are due to my changes. any way to stabilize the tests?

**Comment by Jimexist** [comment]
@devongovett done!

**Comment by Jimexist** [comment]
still don't know why the CI fails

**Comment by devongovett** [comment]
Yeah it's a bit flakey. Seems like some of the rust tests are failing currently.

**Pull request merged**
