### PR TITLE
Strip `type="module"` from output <scripts> tags

### PR DESCRIPTION
**Pull request by twome**
# ↪️ Pull Request

This addresses the feature request in  #1401. Because Parcel assumes a non-strict non-module execution context for its output ES5, running the output from a `type="module"` script tag will hit a ReferenceError when `parcelRequire` tries to implicitly define itself as a global variable using undeclared assignment. With this, users won't need to know/remember to only use vanilla <script> tags in their source HTML. 

## 💻 Examples

See #2809's use-case.

## 🚨 Test instructions

[New test](https://github.com/parcel-bundler/parcel/pull/2872/files#diff-728d2fc29ee35fbd3dee59dfdc80d85dR798): `html -> should strip 'type' attribute from ES-module and plain script tags`

Same repro as as #2809's. Only errors on macOS 10.14.2 are `should produce a basic kotlin bundle` (no local Java). Only [error from CI](https://dev.azure.com/devongovett/devongovett/_build/results?buildId=1581&view=logs&jobId=520d356b-b8e2-5387-8fcd-807640ab874e&taskId=bc978590-48aa-5958-925c-56704fd94fd3&lineStart=244&lineEnd=245&colStart=1&colEnd=1) is:

```
2019-03-30T07:38:15.1147470Z parcel-bundler:   1 failing
2019-03-30T07:38:15.1158420Z parcel-bundler:   1) babel
2019-03-30T07:38:15.1159230Z parcel-bundler:        "before all" hook:
2019-03-30T07:38:15.1160400Z parcel-bundler:      SyntaxError: unknown: Identifier 'T' has already been declared (29:5)
```

Is this different from the CI results from the current official master? I can't find any way to see those CI results in the GitHub / Azure Pipelines UIs, and when I tried to reset all my changes from the old version of this PR to trigger the CI tests, GitHub automatically closed the PR 😅!

## ✔️ PR Todo

- [x] Added/updated unit tests for this change
- [x] Filled out test instructions (In case there aren't any unit tests)
- [x] Included links to related issues/PRs

### CODE REVIEW

**Comment by devongovett** [comment]
lgtm. could you add a test?

**Comment by twome** [comment]
Hmm, test's failing for `type="module"` *and* `type="text/javascript"`; I've gotta go out now but I'll have another look tomorrow

**Comment by twome** [comment]
Seems the issue was HTMLAsset's generate() was returning out of each walk step for script tags if they didn't have internal content (why is why the test was failing for type="text/javascript" too). 

Locally I'm only getting the same kotlin error as before, plus the new passing test. 👍

**Comment by mischnic** [comment]
This PR should fix the babel CI error: #2842

**Comment by nickolay** [comment]
Note: PR #2842 that was blocking this from landing was superseded by #2990, which is now merged.

**Comment by DeMoorJasper** [comment]
Gonna close this as modules are supported in Parcel 2 and parcel 1 is in maintenance mode and I don't think this PR will ever get merged unfortunately

**Pull request closed without merging**
