### PR TITLE
Fix resolveOptions to use project root instead of disk root (#7271)

### LINKED ISSUE #8846: Autoinstall gets confused by symlinks and things break badly
Hi everybody, I'm having an issue which I think might in part be a bug in Parcel, so I thought I'd ask and potentially report here. I have a somewhat involved setup, but I think I can figure out a reasonable approximation. Consider the following folder structure:

```
shared/
  uploads/
    image.jpg
releases/
  1/
    site/
      index.html
      uploads -> absolute symlink to shared/uploads
    node_modules/
    package.json
current -> absolute symlink to releases/1
```

The `index.html` file contains this: ``.

When I run `parcel build "site/**/*.html"` within `current` (which really means within `releases/1`), weird things happen. Some are quite understandable, some less so:

 - Parcel resolves `uploads/image.jpg` to the real absolute path to `shared/uploads/image.jpg`
 - Then it tries to resolve `sharp` from the image's absolute path, which obviously fails, because `node_modules` and `package.json` are on a different subtree of the project structure
 - Then it tries to autoinstall `sharp` and gets stuck on that

I understand everything that happens up to the moment Parcel tries autoinstalling `sharp` - it's logical why module resolution would need to resolve things relative to the _real_ path of the source file instead of the symlink that led to it, and while it does throw quite a wrench in my setup, I'll figure out a way to work around it somehow (although I'm quite open to suggestions!).

But the really unsettling thing is what happens _during_ the attempt to install `sharp`. Not only does the build get stuck, but _something_ happens somewhere within there that causes my `node_modules` to get (at least partially) deleted - when I kill the Parcel build, I don't even _have_ a `parcel` directory within `node_modules` anymore (and quite a few others are missing as well).

I've found [this issue](https://github.com/parcel-bundler/parcel/issues/7271), which seems related, but it appears the consensus there is a rogue `package.json` somewhere up the directory tree - and I've checked for this, and found no such file on my system (nor `package-lock.json`, nor `yarn.lock`, nor `node_modules`, for that matter; neither in the tree leading up to the project directory, nor in `$HOME`). The Node installation on my system is owned by `root` and not writable for anyone else, so the `npm install` which Parcel is running behind the scenes can't be attempting to install the package globally (it would fail instantly if it did).

I don't know if there's anything to be done about this within Parcel, really - the only idea I had was that Parcel could attempt to resolve build tools like `sharp` from the current working directory, if resolving them from the file which needs them fails - and it could be argued that they're really a dependency of the _build tool_, ie. Parcel or one of Parcel's transformers, not the files they're supposed to work on - but I understand if that's not desirable. I thought I'd at least write this down in case somebody runs into the same issue. Again, if anyone has any tips on how to solve situations like these, I'm all ears!

Parcel: 2.8.3, NPM: 9.5.0, Node: 18.14.1, OS: Ubuntu Server 22.04, not that I think any of that matters in this situation.

EDIT: To be clear, the aspect I think might _possibly_ be a Parcel bug is the fact that autoinstalling a dependency deletes files it shouldn't delete - I know it's very likely not Parcel itself doing that, but seeing as Parcel _is_ triggering the process which is actually responsible, I think it is worth considering adding a check in Parcel for some of the common situations which might cause this to happen.

### PR DESCRIPTION
**Pull request by Kasea**
Relates to (and closes?) #7271 (and similar)
Closes #8846 

Changes resolveOptions function to use `path.parse().dir` as opposed to `path.parse().root` see [docs for more information](https://nodejs.org/api/path.html#pathparsepath).

With the old code, it would resolve to `C:/`, `D:/`, ... etc instead of the root we're interested in. This caused it to climb the tree as opposed to descend it, which causes numerous problems.

In my case it would break my pnpm monorepo setup when trying to run/build with parcel. It would select my monorepo root (the first case of a `lock` file from `D:/`). I noticed I could solve it by putting _any_ `yarn.lock` or `package-lock.json` inside of my app folder and it would select the correct root and build and start properly. This is due to the array `LOCK_FILE_NAMES` having `pnpm-lock.yaml` last.

## 💻 Examples

├─apps
│  └─examples
│      ├─package-lock.json
├─pnpm-lock.yaml
└─pnpm-workspace.yaml

### CODE REVIEW

**Comment by Kasea** [comment]
@mischnic think it would be possible to have this released for next minor release? I'm fairly sure it should be a "patch" release, but some people might've done weird hacks to get around this issue, so don't want to go and potentially break those.

**Comment by Kasea** [comment]
Sratch my previous comment, I no longer have any interest in Parcel; it's broken beyond repair.

I will leave the PR up in case someone wants to try and salvage this project

**Comment by devongovett** [comment]
Sorry to hear that, what other issues did you have?

For this PR, I'm not sure this is right because the entry root (i.e. common directory between the entries), may not be the project root. For example, if the entries are `/path/to/project/website/pages/a.js` and `/path/to/project/website/pages/b.js`, then the common directory is `/path/to/project/src/website/pages`, and `path.parse('/path/to/project/src/website/pages').dir` is `'/path/to/project/src/website'`. But the project root should be `'/path/to/project'`. That's why we search upward from where the common path is up until we find a lock file or SCM directory, which indicates the project root.

**Comment by Kasea** [comment]
won't get into it here and going backwards makes more sense than going upwards (you won't detect random files in the tree). You're more likely to have a random package-lock going up the tree than going down as the project itself will be checked first, which also gives you the option to debug faster and actually change how things get handled without changing things outside of the project.

**Pull request closed without merging**
