### PR TITLE
Fixes for CSS transformer

### LINKED ISSUE #5985: "Error: Does not have node" when importing assets and using module/nomodule pattern
It's almost an empty project with antdesign and typescript.
Builds fine when `--no-scope-hoist` is used.

<details>
<summary>error output</summary>

```
parcel build ./src/index.html --dist-dir ../dist/client "--log-level" "verbose"

⠋ Building context.js...
Error: Does not have node eb7284955c6b0a677c6f6259e9c71f61
    at assertHasNode (/Users/typeofweb/project/node_modules/@parcel/core/lib/Graph.js:583:11)
    at AssetGraph.getNodesConnectedFrom (/Users/typeofweb/project/node_modules/@parcel/core/lib/Graph.js:181:5)
    at visitChildren (/Users/typeofweb/project/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:236:41)
    at /Users/typeofweb/project/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:231:65
Error: Does not have node 1566be9d916265373ec08f879521abf6
    at assertHasNode (/Users/typeofweb/project/node_modules/@parcel/core/lib/Graph.js:583:11)
    at AssetGraph.getNodesConnectedFrom (/Users/typeofweb/project/node_modules/@parcel/core/lib/Graph.js:181:5)
    at visitChildren (/Users/typeofweb/project/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:236:41)
    at /Users/typeofweb/project/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:231:65
Error: Does not have node 017c8302f520a2da37b7b761360a22ca
    at assertHasNode (/Users/typeofweb/project/node_modules/@parcel/core/lib/Graph.js:583:11)
    at AssetGraph.getNodesConnectedFrom (/Users/typeofweb/project/node_modules/@parcel/core/lib/Graph.js:181:5)
    at visitChildren (/Users/typeofweb/project/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:236:41)
    at /Users/typeofweb/project/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:231:65
Error: Does not have node 543a4c8efc7c7aefd3c434bc4bc820f5
    at assertHasNode (/Users/typeofweb/project/node_modules/@parcel/core/lib/Graph.js:583:11)
    at AssetGraph.getNodesConnectedFrom (/Users/typeofweb/project/node_modules/@parcel/core/lib/Graph.js:181:5)
    at visitChildren (/Users/typeofweb/project/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:236:41)
    at /Users/typeofweb/project/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:231:65
Error: Does not have node 1672f00ec0743667363a84aa031fcbfe
    at assertHasNode (/Users/typeofweb/project/node_modules/@parcel/core/lib/Graph.js:583:11)
    at AssetGraph.getNodesConnectedFrom (/Users/typeofweb/project/node_modules/@parcel/core/lib/Graph.js:181:5)
    at visitChildren (/Users/typeofweb/project/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:236:41)
    at /Users/typeofweb/project/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:231:65
Error: Does not have node b18347399b31ad52341407d3b028d2db
    at assertHasNode (/Users/typeofweb/project/node_modules/@parcel/core/lib/Graph.js:583:11)
    at AssetGraph.getNodesConnectedFrom (/Users/typeofweb/project/node_modules/@parcel/core/lib/Graph.js:181:5)
    at visitChildren (/Users/typeofweb/project/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:236:41)
    at /Users/typeofweb/project/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:231:65
Error: Does not have node c470e2256ce222263b9fbe9cdea6734a
    at assertHasNode (/Users/typeofweb/project/node_modules/@parcel/core/lib/Graph.js:583:11)
    at AssetGraph.getNodesConnectedFrom (/Users/typeofweb/project/node_modules/@parcel/core/lib/Graph.js:181:5)
    at visitChildren (/Users/typeofweb/project/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:236:41)
    at /Users/typeofweb/project/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:231:65
Error: Does not have node 93a5ff44ab9625cd2d7e10e95b19fa1b
    at assertHasNode (/Users/typeofweb/project/node_modules/@parcel/core/lib/Graph.js:583:11)
    at AssetGraph.getNodesConnectedFrom (/Users/typeofweb/project/node_modules/@parcel/core/lib/Graph.js:181:5)
    at visitChildren (/Users/typeofweb/project/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:236:41)
    at /Users/typeofweb/project/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:231:65
Error: Does not have node 6ed5d95187be657a2552f6faee478e5d
    at assertHasNode (/Users/typeofweb/project/node_modules/@parcel/core/lib/Graph.js:583:11)
    at AssetGraph.getNodesConnectedFrom (/Users/typeofweb/project/node_modules/@parcel/core/lib/Graph.js:181:5)
    at visitChildren (/Users/typeofweb/project/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:236:41)
    at /Users/typeofweb/project/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:231:65
Error: Does not have node 6ef387e49a8235392de2f6f65b568bab
    at assertHasNode (/Users/typeofweb/project/node_modules/@parcel/core/lib/Graph.js:583:11)
    at AssetGraph.getNodesConnectedFrom (/Users/typeofweb/project/node_modules/@parcel/core/lib/Graph.js:181:5)
    at visitChildren (/Users/typeofweb/project/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:236:41)
    at /Users/typeofweb/project/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:231:65
Error: Does not have node 22dd39892fea5467e1b22a0b583af1b8
    at assertHasNode (/Users/typeofweb/project/node_modules/@parcel/core/lib/Graph.js:583:11)
    at AssetGraph.getNodesConnectedFrom (/Users/typeofweb/project/node_modules/@parcel/core/lib/Graph.js:181:5)
    at visitChildren (/Users/typeofweb/project/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:236:41)
    at /Users/typeofweb/project/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:231:65
Error: Does not have node 5a9dc1c8cea032014c56033f97ec03d5
    at assertHasNode (/Users/typeofweb/project/node_modules/@parcel/core/lib/Graph.js:583:11)
    at AssetGraph.getNodesConnectedFrom (/Users/typeofweb/project/node_modules/@parcel/core/lib/Graph.js:181:5)
    at visitChildren (/Users/typeofweb/project/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:236:41)
    at /Users/typeofweb/project/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:231:65
Error: Does not have node c1d76a078ba76b28b7d3799542e430d7
    at assertHasNode (/Users/typeofweb/project/node_modules/@parcel/core/lib/Graph.js:583:11)
    at AssetGraph.getNodesConnectedFrom (/Users/typeofweb/project/node_modules/@parcel/core/lib/Graph.js:181:5)
    at visitChildren (/Users/typeofweb/project/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:236:41)
    at /Users/typeofweb/project/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:231:65
Error: Does not have node c08f8e50102228ece207ea349e465762
    at assertHasNode (/Users/typeofweb/project/node_modules/@parcel/core/lib/Graph.js:583:11)
    at AssetGraph.getNodesConnectedFrom (/Users/typeofweb/project/node_modules/@parcel/core/lib/Graph.js:181:5)
    at visitChildren (/Users/typeofweb/project/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:236:41)
    at /Users/typeofweb/project/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:231:65
Error: Does not have node a8b60b7c935263642dbec6f9b3611d3a
    at assertHasNode (/Users/typeofweb/project/node_modules/@parcel/core/lib/Graph.js:583:11)
    at AssetGraph.getNodesConnectedFrom (/Users/typeofweb/project/node_modules/@parcel/core/lib/Graph.js:181:5)
    at visitChildren (/Users/typeofweb/project/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:236:41)
    at /Users/typeofweb/project/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:231:65
Error: Does not have node 494c97bd535c41d845947208ad7f6ae7
    at assertHasNode (/Users/typeofweb/project/node_modules/@parcel/core/lib/Graph.js:583:11)
    at AssetGraph.getNodesConnectedFrom (/Users/typeofweb/project/node_modules/@parcel/core/lib/Graph.js:181:5)
    at visitChildren (/Users/typeofweb/project/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:236:41)
    at /Users/typeofweb/project/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:231:65
Error: Does not have node 20ea176fa80700456162bcd06e9ecae0
    at assertHasNode (/Users/typeofweb/project/node_modules/@parcel/core/lib/Graph.js:583:11)
    at AssetGraph.getNodesConnectedFrom (/Users/typeofweb/project/node_modules/@parcel/core/lib/Graph.js:181:5)
    at visitChildren (/Users/typeofweb/project/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:236:41)
    at /Users/typeofweb/project/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:231:65
Error: Does not have node 3fab4b6c30e9d24a7029bc03fa49341f
    at assertHasNode (/Users/typeofweb/project/node_modules/@parcel/core/lib/Graph.js:583:11)
    at AssetGraph.getNodesConnectedFrom (/Users/typeofweb/project/node_modules/@parcel/core/lib/Graph.js:181:5)
    at visitChildren (/Users/typeofweb/project/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:236:41)
    at /Users/typeofweb/project/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:231:65
Error: Does not have node 7a413cc5fdb411f011fe2af3a0b6a864
    at assertHasNode (/Users/typeofweb/project/node_modules/@parcel/core/lib/Graph.js:583:11)
    at AssetGraph.getNodesConnectedFrom (/Users/typeofweb/project/node_modules/@parcel/core/lib/Graph.js:181:5)
    at visitChildren (/Users/typeofweb/project/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:236:41)
    at /Users/typeofweb/project/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:231:65
Error: Does not have node ddde4e9799c72e10b98b53fc0701ef84
    at assertHasNode (/Users/typeofweb/project/node_modules/@parcel/core/lib/Graph.js:583:11)
    at AssetGraph.getNodesConnectedFrom (/Users/typeofweb/project/node_modules/@parcel/core/lib/Graph.js:181:5)
    at visitChildren (/Users/typeofweb/project/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:236:41)
```

</details>

<details>
<summary>package.json</summary>

```json
{
  "name": "project",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "build:client": "cd ./client && parcel build ./src/index.html --dist-dir ../dist/client",
    "postinstall": "husky install"
  },
  "devDependencies": {
    "@babel/preset-typescript": "7.13.0",
    "@parcel/babel-plugin-transform-runtime": "2.0.0-nightly.2247",
    "@parcel/transformer-less": "2.0.0-nightly.625",
    "@parcel/transformer-postcss": "2.0.0-nightly.625",
    "@testing-library/jest-dom": "5.11.9",
    "@testing-library/react": "11.2.5",
    "@testing-library/user-event": "12.8.3",
    "@types/body-parser": "1.19.0",
    "@types/express": "4.17.11",
    "@types/jest": "26.0.20",
    "@types/node": "14.14.33",
    "@types/react": "17.0.3",
    "@types/react-dom": "17.0.2",
    "@types/react-router-dom": "5.1.7",
    "@types/stoppable": "1.1.0",
    "@typescript-eslint/eslint-plugin": "4.17.0",
    "@typescript-eslint/parser": "4.17.0",
    "babel-plugin-import": "1.13.3",
    "concurrently": "6.0.0",
    "eslint": "7.21.0",
    "eslint-config-react-app": "6.0.0",
    "eslint-plugin-import": "2.22.1",
    "eslint-plugin-jest": "24.2.1",
    "eslint-plugin-jsx-a11y": "6.4.1",
    "eslint-plugin-react": "7.22.0",
    "eslint-plugin-react-hooks": "4.2.0",
    "eslint-plugin-testing-library": "3.10.1",
    "husky": "5.1.3",
    "identity-obj-proxy": "3.0.0",
    "jest": "26.6.3",
    "lint-staged": "10.5.4",
    "parcel": "2.0.0-nightly.623",
    "postcss": "8.2.8",
    "postcss-modules": "4.0.0",
    "prettier": "2.2.1",
    "ts-jest": "26.5.3",
    "ts-node-dev": "1.1.6",
    "typescript": "4.2.3",
    "typescript-plugin-css-modules": "3.2.0"
  },
  "dependencies": {
    "antd": "4.13.1",
    "axios": "0.21.1",
    "body-parser": "1.19.0",
    "clsx": "1.1.1",
    "dotenv": "8.2.0",
    "express": "4.17.1",
    "helmet": "4.4.1",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-query": "3.12.1",
    "react-router-dom": "5.2.0",
    "stoppable": "1.1.0",
    "web-vitals": "1.1.0"
  },
  "engines": {
    "node": "14.x.x",
    "npm": "7.x.x"
  },
  "alias": {
    "shared": "./shared"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```

</details>

<details>
<summary>.babelrc</summary>

```json
{
  "presets": [
    "@parcel/babel-preset-env",
    "@babel/preset-typescript",
    ["@babel/preset-react", { "runtime": "automatic" }]
  ],
  "plugins": [
    "@babel/plugin-transform-typescript",
    "@parcel/babel-plugin-transform-runtime",
    [
      "import",
      {
        "libraryName": "antd",
        "libraryDirectory": "es",
        "style": false
      }
    ]
  ]
}
```

</details>

## 🤔 Expected Behavior
The project builds with scope hoisting.

## 😯 Current Behavior
Error.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.623+7eb2b163 |
| Node             | v14.15.5 |
| npm/Yarn         | 7.5.4 |
| Operating System | macOS 11.2.3 (20D91) |

### LINKED ISSUE #7857: transformer-webextension, v3 is not supported
https://github.com/parcel-bundler/parcel/blob/d3ea25517e26242b5bf237dd1fad339dde37d3ec/packages/transformers/webextension/src/schema.js#L46

image

image

Refer doc [Welcome to Manifest V3](https://developer.chrome.com/docs/extensions/mv3/intro/)

### LINKED ISSUE #7858: Parcel + SCSS: @keyframes blocks removed from production builds by minifier, breaking animations
# 🐛 bug report

I have a very simple loading indicator component that uses CSS's @keyframes feature to animate. The @keyframes definition and `animation` rule are in an SCSS file that is imported with `import * as styles from './loader.module.scss'` in order to allow for tree-shaking. Even though the @keyframes animation is definitely being used, it appears to get pruned from the resulting minified CSS file during production builds (the development server works fine, keyframes included in the CSS).

Changing the import line to `import styles from './loader.module.scss'` to prevent tree-shaking functions as a work-around.

## 🎛 Configuration
.postcssrc
```json
{
  "modules": true,
  "plugins": {
    "postcss-modules": {
      "generateScopedName": "_[name]__[local]"
    },
  }
}
```

package.json
```json
{
  "scripts": {
    "start": "parcel src/index.html",
    "build": "parcel build src/index.html",
  },
  "dependencies": {
    "@babylonjs/core": "^4.2.2",
    "@babylonjs/gui": "^4.2.0",
    "@pixi/filter-rgb-split": "^4.1.3",
    "@reduxjs/toolkit": "^1.5.1",
    "assets": "^3.0.1",
    "babylonjs-hook": "^0.1.0",
    "buffer": "^6.0.3",
    "classnames": "^2.3.1",
    "connected-react-router": "^6.9.1",
    "follow-redirects": "^1.14.7",
    "gray-matter": "^4.0.3",
    "history": "^4.10.1",
    "normalize.css": "^8.0.1",
    "pixi.js": "^6.2.2",
    "preact": "^10.6.5",
    "preact-router": "^4.0.1",
    "react-infinite-scroll-hook": "^4.0.1",
    "react-markdown": "^7.1.2",
    "react-modal-image": "^2.5.0",
    "react-redux": "^7.2.4",
    "react-router-dom": "^5.2.0",
    "react-syntax-highlighter": "^15.5.0",
    "redux": "^4.1.2",
    "xml2js": "^0.4.23"
  },
  "devDependencies": {
    "@babel/core": "^7.17.8",
    "@babel/preset-env": "^7.15.6",
    "@babel/preset-react": "^7.14.5",
    "@babel/preset-typescript": "^7.15.0",
    "@jest/types": "^27.1.1",
    "@parcel/babel-preset-env": "^2.4.0",
    "@parcel/reporter-bundle-analyzer": "^2.4.0",
    "@parcel/transformer-glsl": "^2.4.0",
    "@parcel/transformer-sass": "^2.4.0",
    "@types/enzyme": "^3.10.5",
    "@types/history": "^4.7.8",
    "@types/jest": "^27.4.1",
    "@types/jsdom": "^16.2.3",
    "@types/react": "^17.0.42",
    "@types/react-router": "^5.1.14",
    "@types/react-router-dom": "^5.1.7",
    "@types/react-syntax-highlighter": "^13.5.2",
    "@types/redux-logger": "^3.0.8",
    "@types/redux-mock-store": "^1.0.3",
    "@types/xml2js": "^0.4.9",
    "@typescript-eslint/eslint-plugin": "^5.16.0",
    "@typescript-eslint/parser": "^5.16.0",
    "babel-jest": "^27.2.0",
    "enzyme": "^3.11.0",
    "enzyme-adapter-preact-pure": "^3.4.0",
    "enzyme-to-json": "^3.6.2",
    "eslint": "^7.32.0",
    "eslint-config-preact": "^1.1.4",
    "eslint-plugin-jest": "^26.1.2",
    "gh-pages": "^3.1.0",
    "husky": "^7.0.0",
    "identity-obj-proxy": "^3.0.0",
    "jest": "^27.2.0",
    "jest-transform-stub": "^2.0.0",
    "json-schema": ">=0.4.0",
    "lint-staged": "^11.1.2",
    "marked": "^4.0.10",
    "minimist": ">=1.2.6",
    "nanoid": "^3.3.1",
    "node-forge": ">=1.3.0",
    "parcel": "^2.4.0",
    "postcss": ">=8.4.12",
    "postcss-modules": "^4.3.1",
    "process": "^0.11.10",
    "querystring-es3": "^0.2.1",
    "react-router": "^5.2.0",
    "redux-logger": "^3.0.6",
    "redux-mock-store": "^1.5.4",
    "sass": "^1.49.9",
    "stream-browserify": "^3.0.0",
    "timers-browserify": "^2.0.12",
    "ts-jest": "^27.0.5",
    "ts-node": "^10.2.1",
    "typed-scss-modules": "^6.2.0",
    "typescript": "^4.6.2"
  }
}
```

## 🤔 Expected Behavior

When an SCSS file with a keyframes definition like below is imported and used within a component, the minifier should recognize that the keyframes definition is in use and retain it in the minified CSS file.

loader.component.tsx
```tsx
import styles from './loader.module.scss'

export const Loader = () => (
    <div className={styles.loader}>
            <span/>
    </div>
)
```

loader.module.scss
```scss
.loader {
    .span {
        animation: fade-pulse ease-in-out 1.5s infinite;
        animation-delay: $i * 250ms;
    }
}

@keyframes fade-pulse {
    0% {
        opacity: 0.3;
    }

    40% {
        opacity: 1;
    }

    80% {
        opacity: 0.3;
    }
}
```

## 😯 Current Behavior

In the dist folder, after a production build, there is no `@keyframes` definition, just the reference to it within the `.loader .span` class (e.g. `animation:_loader-module__fade-pulse 1.5s ease-in-out infinite`).

Animations only load in the development server, not the production build. This is true for all of the @keyframes animations across the app.

## 🔦 Context

I am trying to use @keyframes animations in an SCSS file with tree-shaking enabled. When I swapped my SCSS imports from `import styles...` to `import * as styles...` to enable tree-shaking, this issue flew under my radar and broke the animations in my site.

## 💻 Code Sample

My repository: https://github.com/jaxreiff/jaxreiff.github.io

## 🌍 Your Environment

This occurred both locally:

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | v2.4.0
| Node             | v16.13.1
| npm/Yarn         | v8.5.5
| Operating System | Mac OS 10.15.7

as well as using GitHub Actions to deploy to GitHub Pages.

### LINKED ISSUE #7859: Css modules `:export` not working in 2.4.0
# 🐛 bug report

The css modules specs has a section for interop with js or other css modules. More precisely, it defines an `:export` keyword that exports strings/variables (not css variables), functionally equivalent to this js:
```
module.exports = {
  "exportedKey": "exportedValue"
}
```
I am using it like this:

// cssVars.module.scss:
```
:export {
  playReqs: #f5bc62;
  playReqsBar: #faca7d;
}
```
// file.js:
```
import * as cssVars from './cssVars.module.scss';
console.log(cssVars.playReqs);
```
More details: https://github.com/css-modules/icss/blob/master/README.md#export

This works in parcel 2.3.2 but it doesn't in parcel 2.4.0.

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json deps :
```
    "@parcel/packager-raw-url": "2.4.0",
    "@parcel/transformer-html": "2.4.0",
    "@parcel/transformer-posthtml": "2.4.0",
    "@parcel/transformer-sass": "2.4.0",
    "@parcel/transformer-webmanifest": "2.4.0",
    "parcel-reporter-static-files-copy": "1.3.4",
    "parcel": "2.4.0",
    "autoprefixer": "10.4.4",
    "postcss": "8.4.12",
    "postcss-modules": "4.3.1",
    "tailwindcss": "3.0.23",
```
.parcelrc
```
{
  "extends": ["@parcel/config-default"],
  "reporters":  ["...", "parcel-reporter-static-files-copy"],
  "transformers": {
    "jsx:*.svg": ["...", "@parcel/transformer-svg-react"]
  }
}
```
.postcssrc
```
{
  "plugins": {
    "tailwindcss": {}
  }
}
```

## 🤔 Expected Behavior

`console.log(cssVars.playReqs);` above should output the value for `playReqs` defined in the css module file. It does so with parcel 2.3.2 (and all the other parcel deps on 2.3.2)

## 😯 Current Behavior

The above console log returns `undefined`.

### LINKED ISSUE #7865: Parcel 2.4.0 removes used CSS class
I have an open-source website build with 11ty and Parcel:

https://github.com/phpstan/phpstan/tree/1.5.x/website

It imports littlefoot.css in app.pcss file: https://github.com/phpstan/phpstan/blob/a6d536563486098432cb4ff2bc515feae378b0d5/website/src/app.pcss#L5

Before upgrading to 2.4.0, the littlefoot classes were part of the compiled file.

After upgrading to 2.4.0, the littlefoot classes are missing.

Bad commit: https://github.com/phpstan/phpstan/tree/690c310dfbfa9c84bf377794dcc4f66b3dc0411a/website

Good commit (after reverting the updates): https://github.com/phpstan/phpstan/tree/a6d536563486098432cb4ff2bc515feae378b0d5/website

If you build the bad commit with `yarn run build`, you'll see the littlefoot classes missing in website/dist/blog.xxxxxxxx.css.

If you build the good commit, the littlefoot classes are present in website/dist/blog.xxxxxxxx.css.

### PR DESCRIPTION
**Pull request by devongovett**
Fixes #7858. Fixes #7859. Fixes #7865. Fixes #5985.

* Ensures we don't remove unused symbols in the CSS optimizer after the packager already did that (for CSS modules processed by postcss)
* Only adds dependencies to the JS asset of a CSS module, rather than both the JS and CSS. This avoids an issue where a dependency in CSS resolves to a JS asset, which breaks bundling. In order to make this work, I also needed to solve an issue in both bundlers, where dependencies in the JS part of a CSS module were included _after_ the sibling CSS rather than before. This is solved by queuing assets to be added to sibling CSS bundles during post-order traversal rather than adding them during pre-order.
* Sets the environment before adding dependencies rather than after. Replacing the environment also affects an asset's id, which is used in dependencies. If they don't match this breaks things downstream in the bundle graph when transforming for multiple environments, causing errors like #5985.
* Uses postcss-modules to handle `:export` syntax in legacy CSS modules.

### CODE REVIEW

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>Kitchen Sink 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

<details><summary>React HackerNews ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 12.23s | +82.00ms |
| Cached | 543.00ms | -2.00ms |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

*No bundle changes detected.*

</p></details>

<details><summary>AtlasKit Editor 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

<details><summary>Three.js ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 8.65s | +31.00ms |
| Cached | 337.00ms | -7.00ms |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

*No bundle changes detected.*

</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/327511996839756372)**

**Comment by mischnic** [comment]
The first issue you mentioned is probably the wrong one?

**Comment by mischnic** [comment]
Looks good, apart from the bundlers - I have absolutely no clue how they work at this point.

> If they don't match this breaks things downstream in the bundle graph when transforming for multiple environments, causing errors like

Ideally we'd somehow prevent this from happening in the first place. And if that's not possible, maybe throw an error if you do `setEnvironment` before `addDependency` so that this doesn't go unnoticed.

**Comment by devongovett** [comment]
> Ideally we'd somehow prevent this from happening in the first place

Yeah... `setEnvironment` is really a hack. Ideally we'd replace it with something better, but not sure what.

**Comment by aminomancer** [comment]
Are you sure #7858 was fixed? I'm still experiencing the same issue on 2.8.3

**Pull request merged**
