### PR TITLE
Remove support for exporting reassigned CommonJS exports

### PR DESCRIPTION
**Pull request by wbinnssmith**
This removes support in scope hoisting for interpreting an assignment to the `exports` variable itself as an export.

In Node (and I assume CommonJS in general), `exports` is a binding local to the module, and reassigning it does not affect the module's exports. In other words, requiring a module with the contents `exports = 3` results in an empty exports object, not `3`.

Test Plan: 
* Removed support.
* Verified that test assuming this behavior is broken.
* Adjusted the test to test unwrapped `module.exports` instead, as the test doesn't reflect Node's behavior.

### CODE REVIEW

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>packages/benchmarks/kitchen-sink ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 10.92s | +1.46s ⚠️ |
| Cached | 9.19s | -62.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/parcel.ff215454.webp | 102.94kb | +0.00b | 181.00ms | -38.00ms 🚀 |
| dist/modern/parcel.76ee4591.webp | 102.94kb | +0.00b | 180.00ms | -39.00ms 🚀 |
| dist/legacy/index.js | 243.00b | +0.00b | 403.00ms | -75.00ms 🚀 |
| dist/modern/index.js | 215.00b | +0.00b | 397.00ms | -82.00ms 🚀 |
| dist/modern/index.css | 29.00b | +0.00b | 1.14s | -131.00ms 🚀 |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/index.js | 243.00b | +0.00b | 18.00ms | -1.00ms 🚀 |
| dist/legacy/index.css | 29.00b | +0.00b | 11.00ms | +1.00ms ⚠️ |
| dist/modern/index.css | 29.00b | +0.00b | 9.00ms | -1.00ms 🚀 |

</p></details>

<details><summary>packages/benchmarks/react-hn ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 14.84s | +200.00ms |
| Cached | 10.48s | +28.00ms |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/main/index.js | 34.00kb | +0.00b | 14.00ms | -2.00ms 🚀 |

</p></details>

<details><summary>packages/benchmarks/ak-editor 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/251507140895703561)**

**Comment by mischnic** [comment]
1. **modifying `exports` after reassigning it.** This doesn't fix it completely (not sure if this can even be statically analyzed) and even creates another problem with overwriting some other (and strict mode and non-Node environments in general):
```js
// input
exports.x = 2;
exports = {};
exports.y = 3; // doesn't create an export
```
```js
// output
export var x = 2;
exports = {}; // your change preserves this and will cause an error in strict mode
export var y = 3; // shouldn't be here
```

2. **`export` can't be left in the output.** Another artifact of this PR:
```js
//input
require("./other.js"); // contains `exports = {z: 3}`

exports.x = 2;
exports = {z: 3};
exports.y = 3;
```
```js
// output
// ASSET: /Users/niklas/Desktop/xyz/other.js
exports = {
  z: 3
};
export var x = 2;
exports = {
  z: 3
};
export var y = 3;
```

---

Places where `exports` could still do unexpected things:
- When a module is wrapped:
https://github.com/parcel-bundler/parcel/blob/e2ea84373758ef22da979bc7abaf9b8ca29a1f59/packages/shared/scope-hoisting/src/hoist.js#L11-L18
https://github.com/parcel-bundler/parcel/blob/e2ea84373758ef22da979bc7abaf9b8ca29a1f59/packages/shared/scope-hoisting/src/hoist.js#L20
https://github.com/parcel-bundler/parcel/blob/e2ea84373758ef22da979bc7abaf9b8ca29a1f59/packages/shared/scope-hoisting/src/hoist.js#L662-L663
- `exports` being replaced with the "real" asset's exports object
https://github.com/parcel-bundler/parcel/blob/e2ea84373758ef22da979bc7abaf9b8ca29a1f59/packages/shared/scope-hoisting/src/hoist.js#L206-L220
- `exports = ...` being replaced
https://github.com/parcel-bundler/parcel/blob/e2ea84373758ef22da979bc7abaf9b8ca29a1f59/packages/shared/scope-hoisting/src/hoist.js#L278-L285
- `exports.foo = ...` being replaced
https://github.com/parcel-bundler/parcel/blob/e2ea84373758ef22da979bc7abaf9b8ca29a1f59/packages/shared/scope-hoisting/src/hoist.js#L287-L304

**Comment by wbinnssmith** [comment]
@mischnic all good points 😄 

Just removed the rewriting of exports in assignment expressions, left the test removed, and added another for asserting the intended behavior.

**Comment by mischnic** [comment]
I can't really figure out what this actually fixes 😄 . The identifier in `exports = ...;` is replaced, but nothing else?

**Comment by wbinnssmith** [comment]
Without the changes to `hoist.js`, the exports of the added test are of type `number`.

This also removes a test that tested incorrect behavior 😄

**Pull request merged**
