### PR TITLE
fix a case where null options might cause issues

### PR DESCRIPTION
**Pull request by Jimexist**
otherwise when using 3rd party plugin this might cause issue with empty options

### CODE REVIEW

**Comment by DeMoorJasper** [comment]
Options should always be defined this isn’t gonna fix the core issue of this bug

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pke** [comment]
well, options seems to be undefined for some reason though.

**Comment by pke** [comment]
No haven't tried that yet. Would have to check out this PR branch and build the bundler myself?

**Comment by DeMoorJasper** [comment]
@pke yes

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Jimexist** [comment]
@DeMoorJasper i understand your concern. will #1587 be merged soon?

**Comment by devongovett** [comment]
@DeMoorJasper it's possible there could be a race here: https://github.com/parcel-bundler/parcel/blob/master/src/worker.js#L35. That's the only place we call `WorkerFarm.getShared` and don't pass any options. If the shared instance hasn't been created yet, it will fail.

**Comment by devongovett** [comment]
@Jimexist did #1587 work for you?

**Comment by DeMoorJasper** [comment]
@devongovett The worker always gets called from the workerfarm so once the worker reaches https://github.com/parcel-bundler/parcel/blob/master/src/worker.js#L35 it should already be set right?

Unless it gets called from a remote worker in that case that shouldn't even be happening.

#1587 should fix most of the worker dying and not being properly initialised issue, so there's a big chance it fixes this. But I have no clue as this is an issue I have never been able to reproduce. I have been able to reproduce similar errors and those have been fixed by the PR as mentioned in the PR.

**Comment by DeMoorJasper** [comment]
@devongovett Ow right that's probably the reason. Totally didn't know that addCall is being called outside of the asset processing workers.

**Comment by Jimexist** [comment]
if this PR is no longer relevant, should i close it now?

**Comment by devongovett** [comment]
Yeah, going to close it. We can tackle the fix for the problem described earlier in a separate PR, or part of #1587.

**Pull request closed without merging**
