### PR TITLE
Add bundle id to bundle hash

### PR DESCRIPTION
**Pull request by padmaia**
# ↪️ Pull Request
Currently `BundleGraph.getHash(bundle)` does not incorporate the input bundle's name or id so bundles with different ids/names can end up using the same cache entries if they contain the same assets. This becomes a problem when the cache entries contain a sourcemap url which only applies to one of the bundles. If the bundle that created the cache entry no longer exists in a subsequent build or in a completely separate build and the sourcemap url contains a hashReference, then the build will fail with `Cannot read property 'hashReferences' of undefined` because it is trying to look up the final bundle hash of a bundle that doesn't exist in the build.

A quick and safe fix is to add the bundle id to the cache key, which I've done in this PR. This may be more aggressive than necessary in some cases. We could probably introduce the notion of a `SOURCE_REF` similar to a `HASH_REF`, which to refer to the bundle's own source map and the ref would be replaced when writing to dist. I've created a follow up task for this optimization in height (T-777).

Fixes T-776

## 🚨 Test instructions
Manually confirmed it resolves `Cannot read property 'hashReferences' of undefined` in a previously broken build.

### CODE REVIEW

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>Kitchen Sink ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 8.39s | -24.00ms |
| Cached | 3.46s | +59.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/parcel.d5807e82.webp | 102.94kb | +0.00b | 220.00ms | +52.00ms ⚠️ |
| dist/modern/parcel.d5807e82.webp | 102.94kb | +0.00b | 311.00ms | -49.00ms 🚀 |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/parcel.d5807e82.webp | 102.94kb | +0.00b | 380.00ms | +169.00ms ⚠️ |
| dist/modern/parcel.d5807e82.webp | 102.94kb | +0.00b | 228.00ms | -149.00ms 🚀 |
| dist/legacy/index.45cccf70.js | 1.10kb | +0.00b | 475.00ms | +154.00ms ⚠️ |
| dist/modern/index.1964d1f6.js | 1.10kb | +0.00b | 363.00ms | -98.00ms 🚀 |
| dist/legacy/index.html | 701.00b | +0.00b | 476.00ms | +155.00ms ⚠️ |
| dist/modern/index.html | 701.00b | +0.00b | 363.00ms | -98.00ms 🚀 |
| dist/legacy/index.b3acc8eb.css | 77.00b | +0.00b | 476.00ms | +155.00ms ⚠️ |
| dist/modern/index.7bc22a8b.css | 77.00b | +0.00b | 363.00ms | -98.00ms 🚀 |

</p></details>

<details><summary>React HackerNews ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 27.79s | +390.00ms |
| Cached | 3.48s | -62.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/logo.24c8bf9e.png | 274.00b | +0.00b | 112.00ms | -64.00ms 🚀 |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.js | 478.81kb | +0.00b | 194.00ms | -88.00ms 🚀 |
| dist/PermalinkedComment.9c5ad065.js | 4.22kb | +0.00b | 193.00ms | -89.00ms 🚀 |
| dist/UserProfile.c1927888.js | 1.62kb | +0.00b | 193.00ms | -89.00ms 🚀 |
| dist/NotFound.f8a0616d.js | 387.00b | +0.00b | 274.00ms | +123.00ms ⚠️ |
| dist/logo.24c8bf9e.png | 274.00b | +0.00b | 108.00ms | -122.00ms 🚀 |

</p></details>

<details><summary>AtlasKit Editor ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 3.27m | -3.92s |
| Cached | 7.46s | +39.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/pdfRenderer.15a6a023.js | 1.11mb | +0.00b | 1.07m | +5.94s ⚠️ |
| dist/popup.6c453e3c.js | 169.96kb | +0.00b | 1.07m | +5.95s ⚠️ |
| dist/Toolbar.83ac0b6e.js | 92.34kb | +0.00b | 1.12m | +4.78s ⚠️ |
| dist/card.0313bac8.js | 52.78kb | +0.00b | 1.77m | +46.32s ⚠️ |
| dist/Modal.19ffed32.js | 41.27kb | +0.00b | 7.42s | +872.00ms ⚠️ |
| dist/component.54080a26.js | 22.50kb | +0.00b | 7.42s | +867.00ms ⚠️ |
| dist/DatePicker.0df05dac.js | 21.21kb | +0.00b | 1.05m | +50.23s ⚠️ |
| dist/dropzone.291ad844.js | 17.34kb | +0.00b | 1.77m | +46.32s ⚠️ |
| dist/smartMediaEditor.125a19a7.js | 16.93kb | +0.00b | 1.12m | +5.90s ⚠️ |
| dist/js.5733a017.js | 16.40kb | +0.00b | 7.42s | +866.00ms ⚠️ |
| dist/EmojiPickerComponent.627aca6b.js | 3.58kb | +0.00b | 13.52s | +1.30s ⚠️ |
| dist/index.ac562c80.css | 3.46kb | +0.00b | 1.14m | +5.11s ⚠️ |
| dist/png-chunks-extract.a844fdb6.js | 3.41kb | +0.00b | 7.42s | +866.00ms ⚠️ |
| dist/dropzone.3c67f0a6.js | 3.23kb | +0.00b | 40.76s | +5.59s ⚠️ |
| dist/Modal.0304b9ed.js | 3.08kb | +0.00b | 7.42s | +866.00ms ⚠️ |
| dist/clipboard.da112b6e.js | 2.75kb | +0.00b | 1.07m | +5.10s ⚠️ |
| dist/16.290b4a43.js | 2.38kb | +0.00b | 2.24s | +310.00ms ⚠️ |
| dist/EmojiUploadComponent.d54a1fc6.js | 2.18kb | +0.00b | 13.52s | -51.66s 🚀 |
| dist/card.eea6ad8c.js | 2.03kb | +0.00b | 40.75s | +5.58s ⚠️ |
| dist/date.231500d2.js | 1.73kb | +0.00b | 8.44s | +831.00ms ⚠️ |
| dist/16.d16f14ed.js | 1.73kb | +0.00b | 8.07s | +922.00ms ⚠️ |
| dist/images.80c92f5e.js | 1.67kb | +0.00b | 8.44s | +721.00ms ⚠️ |
| dist/16.1b6ca79f.js | 1.66kb | +0.00b | 7.76s | +861.00ms ⚠️ |
| dist/feedback.d5590b34.js | 1.64kb | +0.00b | 9.53s | -3.54s 🚀 |
| dist/browser.75813db0.js | 1.61kb | +0.00b | 1.07m | +5.28s ⚠️ |
| dist/workerHasher.fa198233.js | 1.54kb | +0.00b | 1.09m | +5.42s ⚠️ |
| dist/list-number.c35f9589.js | 1.46kb | +0.00b | 8.65s | +930.00ms ⚠️ |
| dist/status.8ab4226b.js | 1.46kb | +0.00b | 9.26s | +1.25s ⚠️ |
| dist/16.9ccb5b28.js | 1.38kb | +0.00b | 7.79s | -3.15s 🚀 |
| dist/code.3dd71280.js | 1.38kb | +0.00b | 8.26s | +648.00ms ⚠️ |
| dist/16.19c93285.js | 1.33kb | +0.00b | 9.80s | +2.91s ⚠️ |
| dist/16.c7751e34.js | 1.33kb | +0.00b | 7.76s | +859.00ms ⚠️ |
| dist/16.51049e2c.js | 1.32kb | +0.00b | 2.24s | +310.00ms ⚠️ |
| dist/16.18344f47.js | 1.31kb | +0.00b | 8.25s | +812.00ms ⚠️ |
| dist/link.2f4427e6.js | 1.30kb | +0.00b | 8.65s | +930.00ms ⚠️ |
| dist/heading6.fdbbdf4d.js | 1.30kb | +0.00b | 9.51s | +1.34s ⚠️ |
| dist/heading3.2113b7a1.js | 1.29kb | +0.00b | 9.50s | +1.33s ⚠️ |
| dist/16.2c4c1846.js | 1.27kb | +0.00b | 8.25s | +812.00ms ⚠️ |
| dist/emoji.93ae61d3.js | 1.23kb | +0.00b | 8.44s | +834.00ms ⚠️ |
| dist/16.d17ab186.js | 1.23kb | +0.00b | 8.07s | +922.00ms ⚠️ |
| dist/16.436f097f.js | 1.21kb | +0.00b | 2.24s | +311.00ms ⚠️ |
| dist/16.b4da0acb.js | 1.19kb | +0.00b | 10.79s | +3.64s ⚠️ |
| dist/16.02c68c4f.js | 1.18kb | +0.00b | 8.25s | +813.00ms ⚠️ |
| dist/heading5.e195aab1.js | 1.17kb | +0.00b | 9.50s | +1.33s ⚠️ |
| dist/expand.450f3aea.js | 1.16kb | +0.00b | 1.05m | +50.22s ⚠️ |
| dist/media-card-analytics-error-boundary.2323af57.js | 1.15kb | +0.00b | 40.75s | +5.58s ⚠️ |
| dist/16.b46ef690.js | 1.14kb | +0.00b | 2.24s | +311.00ms ⚠️ |
| dist/16.4e3b0235.js | 1.14kb | +0.00b | 8.07s | +922.00ms ⚠️ |
| dist/16.9ba230ea.js | 1.13kb | +0.00b | 7.76s | +859.00ms ⚠️ |
| dist/16.a37df53b.js | 1.13kb | +0.00b | 7.76s | +859.00ms ⚠️ |
| dist/16.9adb4ec7.js | 1.13kb | +0.00b | 8.07s | +922.00ms ⚠️ |
| dist/heading2.a2a1be3f.js | 1.11kb | +0.00b | 9.27s | +1.10s ⚠️ |
| dist/16.3920766f.js | 1.10kb | +0.00b | 2.23s | +310.00ms ⚠️ |
| dist/mention.4d64e059.js | 1.07kb | +0.00b | 8.66s | +809.00ms ⚠️ |
| dist/heading4.ec980e93.js | 1.06kb | +0.00b | 9.50s | +1.33s ⚠️ |
| dist/16.afcb09b6.js | 1.05kb | +0.00b | 8.08s | +641.00ms ⚠️ |
| dist/layout.52ba15f7.js | 1.05kb | +0.00b | 8.65s | +930.00ms ⚠️ |
| dist/divider.16defde6.js | 1.03kb | +0.00b | 8.44s | +831.00ms ⚠️ |
| dist/quote.aa25b83c.js | 1.02kb | +0.00b | 9.26s | +1.25s ⚠️ |
| dist/action.9aa72b39.js | 1.00kb | +0.00b | 8.25s | +816.00ms ⚠️ |
| dist/decision.20244046.js | 1010.00b | +0.00b | 8.44s | +831.00ms ⚠️ |
| dist/panel-warning.97a0e3b3.js | 1008.00b | +0.00b | 9.04s | +1.19s ⚠️ |
| dist/list.c9147a62.js | 978.00b | +0.00b | 8.65s | +930.00ms ⚠️ |
| dist/heading1.7d899ba5.js | 976.00b | +0.00b | 9.26s | +1.25s ⚠️ |
| dist/panel-error.8d11e8b7.js | 906.00b | +0.00b | 9.03s | +1.18s ⚠️ |
| dist/panel.a28c56ee.js | 897.00b | +0.00b | 9.04s | +1.03s ⚠️ |
| dist/table.5a4874ee.js | 889.00b | +0.00b | 9.26s | +1.25s ⚠️ |
| dist/panel-success.9b923e58.js | 845.00b | +0.00b | 9.03s | +1.18s ⚠️ |
| dist/panel-note.97a4d541.js | 841.00b | +0.00b | 9.03s | +1.18s ⚠️ |
| dist/media-picker-analytics-error-boundary.f8ddfee3.js | 839.00b | +0.00b | 1.07m | +5.09s ⚠️ |
| dist/media-card-analytics-error-boundary.73ba4074.js | 835.00b | +0.00b | 1.77m | +45.90s ⚠️ |
| dist/media-viewer-analytics-error-boundary.0afa7031.js | 755.00b | +0.00b | 20.32s | +1.03s ⚠️ |
| dist/EmojiPickerComponent.2e54b9c6.js | 535.00b | +0.00b | 13.52s | -51.66s 🚀 |
| dist/simpleHasher.a29b2a8e.js | 528.00b | +0.00b | 1.09m | +5.42s ⚠️ |
| dist/index.html | 119.00b | +0.00b | 7.79s | -681.00ms 🚀 |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.30c8803c.js | 2.72mb | +0.00b | 269.00ms | -31.00ms 🚀 |
| dist/pdfRenderer.15a6a023.js | 1.11mb | +0.00b | 435.00ms | -35.00ms 🚀 |
| dist/popup.6c453e3c.js | 169.96kb | +0.00b | 451.00ms | -37.00ms 🚀 |
| dist/EmojiPickerComponent.ae601247.js | 75.29kb | +0.00b | 387.00ms | -57.00ms 🚀 |
| dist/media-viewer.7079364e.js | 72.03kb | +0.00b | 423.00ms | -47.00ms 🚀 |
| dist/card.645a5c17.js | 55.01kb | +0.00b | 423.00ms | -47.00ms 🚀 |
| dist/card.0313bac8.js | 52.78kb | +0.00b | 475.00ms | -36.00ms 🚀 |
| dist/Modal.19ffed32.js | 41.27kb | +0.00b | 275.00ms | -38.00ms 🚀 |
| dist/component.d7c29980.js | 30.70kb | +0.00b | 268.00ms | -44.00ms 🚀 |
| dist/component.54080a26.js | 22.50kb | +0.00b | 287.00ms | -30.00ms 🚀 |
| dist/DatePicker.0df05dac.js | 21.21kb | +0.00b | 387.00ms | -52.00ms 🚀 |
| dist/EmojiPickerComponent.7dc0ebd0.js | 18.23kb | +0.00b | 387.00ms | -57.00ms 🚀 |
| dist/js.5733a017.js | 16.40kb | +0.00b | 275.00ms | -38.00ms 🚀 |
| dist/ui.fee77548.js | 13.97kb | +0.00b | 423.00ms | -26.00ms 🚀 |
| dist/workerHasher.1e706e77.js | 11.75kb | +0.00b | 399.00ms | -50.00ms 🚀 |
| dist/EmojiTypeAheadComponent.1990d771.js | 8.67kb | +0.00b | 399.00ms | -50.00ms 🚀 |
| dist/component.77c0f682.js | 6.05kb | +0.00b | 287.00ms | -30.00ms 🚀 |
| dist/card.383bd9bd.js | 5.61kb | +0.00b | 423.00ms | -47.00ms 🚀 |
| dist/media-viewer.59c17dad.js | 3.92kb | +0.00b | 435.00ms | -53.00ms 🚀 |
| dist/EmojiPickerComponent.627aca6b.js | 3.58kb | +0.00b | 387.00ms | -57.00ms 🚀 |
| dist/png-chunks-extract.a844fdb6.js | 3.41kb | +0.00b | 275.00ms | -42.00ms 🚀 |
| dist/dropzone.3c67f0a6.js | 3.23kb | +0.00b | 451.00ms | -41.00ms 🚀 |
| dist/Modal.0304b9ed.js | 3.08kb | +0.00b | 275.00ms | -38.00ms 🚀 |
| dist/16.290b4a43.js | 2.38kb | +0.00b | 275.00ms | -38.00ms 🚀 |
| dist/EmojiUploadComponent.d54a1fc6.js | 2.18kb | +0.00b | 399.00ms | -45.00ms 🚀 |
| dist/card.eea6ad8c.js | 2.03kb | +0.00b | 435.00ms | -53.00ms 🚀 |
| dist/ResourcedEmojiComponent.abe8596c.js | 2.00kb | +0.00b | 269.00ms | -31.00ms 🚀 |
| dist/date.231500d2.js | 1.73kb | +0.00b | 312.00ms | -82.00ms 🚀 |
| dist/16.d16f14ed.js | 1.73kb | +0.00b | 301.00ms | -57.00ms 🚀 |
| dist/images.80c92f5e.js | 1.67kb | +0.00b | 312.00ms | -82.00ms 🚀 |
| dist/16.1b6ca79f.js | 1.66kb | +0.00b | 287.00ms | -59.00ms 🚀 |
| dist/feedback.d5590b34.js | 1.64kb | +0.00b | 353.00ms | -85.00ms 🚀 |
| dist/workerHasher.6d5b22d7.js | 1.54kb | +0.00b | 399.00ms | -50.00ms 🚀 |
| dist/list-number.c35f9589.js | 1.46kb | +0.00b | 327.00ms | -95.00ms 🚀 |
| dist/status.8ab4226b.js | 1.46kb | +0.00b | 347.00ms | -80.00ms 🚀 |
| dist/16.9ccb5b28.js | 1.38kb | +0.00b | 296.00ms | -50.00ms 🚀 |
| dist/code.3dd71280.js | 1.38kb | +0.00b | 307.00ms | -75.00ms 🚀 |
| dist/16.19c93285.js | 1.33kb | +0.00b | 287.00ms | -30.00ms 🚀 |
| dist/16.c7751e34.js | 1.33kb | +0.00b | 296.00ms | -50.00ms 🚀 |
| dist/16.18344f47.js | 1.31kb | +0.00b | 307.00ms | -75.00ms 🚀 |
| dist/link.2f4427e6.js | 1.30kb | +0.00b | 327.00ms | -85.00ms 🚀 |
| dist/heading6.fdbbdf4d.js | 1.30kb | +0.00b | 353.00ms | -85.00ms 🚀 |
| dist/heading3.2113b7a1.js | 1.29kb | +0.00b | 348.00ms | -84.00ms 🚀 |
| dist/16.2c4c1846.js | 1.27kb | +0.00b | 306.00ms | -76.00ms 🚀 |
| dist/emoji.93ae61d3.js | 1.23kb | +0.00b | 312.00ms | -82.00ms 🚀 |
| dist/16.d17ab186.js | 1.23kb | +0.00b | 301.00ms | -57.00ms 🚀 |
| dist/16.b4da0acb.js | 1.19kb | +0.00b | 301.00ms | -57.00ms 🚀 |
| dist/16.02c68c4f.js | 1.18kb | +0.00b | 307.00ms | -75.00ms 🚀 |
| dist/heading5.e195aab1.js | 1.17kb | +0.00b | 353.00ms | -84.00ms 🚀 |
| dist/expand.450f3aea.js | 1.16kb | +0.00b | 353.00ms | -85.00ms 🚀 |
| dist/media-card-analytics-error-boundary.2323af57.js | 1.15kb | +0.00b | 435.00ms | -53.00ms 🚀 |
| dist/16.4e3b0235.js | 1.14kb | +0.00b | 300.00ms | -58.00ms 🚀 |
| dist/16.9ba230ea.js | 1.13kb | +0.00b | 295.00ms | -51.00ms 🚀 |
| dist/16.a37df53b.js | 1.13kb | +0.00b | 296.00ms | -50.00ms 🚀 |
| dist/16.9adb4ec7.js | 1.13kb | +0.00b | 296.00ms | -288.00ms 🚀 |
| dist/16.eafe1a11.js | 1.13kb | +0.00b | 287.00ms | -30.00ms 🚀 |
| dist/heading2.a2a1be3f.js | 1.11kb | +0.00b | 348.00ms | -84.00ms 🚀 |
| dist/component.6600f83e.js | 1.07kb | +0.00b | 268.00ms | -32.00ms 🚀 |
| dist/mention.4d64e059.js | 1.07kb | +0.00b | 327.00ms | -95.00ms 🚀 |
| dist/heading4.ec980e93.js | 1.06kb | +0.00b | 353.00ms | -79.00ms 🚀 |
| dist/16.afcb09b6.js | 1.05kb | +0.00b | 301.00ms | -58.00ms 🚀 |
| dist/layout.52ba15f7.js | 1.05kb | +0.00b | 327.00ms | -85.00ms 🚀 |
| dist/divider.16defde6.js | 1.03kb | +0.00b | 312.00ms | -82.00ms 🚀 |
| dist/quote.aa25b83c.js | 1.02kb | +0.00b | 332.00ms | -95.00ms 🚀 |
| dist/action.9aa72b39.js | 1.00kb | +0.00b | 307.00ms | -75.00ms 🚀 |
| dist/decision.20244046.js | 1010.00b | +0.00b | 312.00ms | -82.00ms 🚀 |
| dist/panel-warning.97a0e3b3.js | 1008.00b | +0.00b | 332.00ms | -95.00ms 🚀 |
| dist/list.c9147a62.js | 978.00b | +0.00b | 327.00ms | -95.00ms 🚀 |
| dist/heading1.7d899ba5.js | 976.00b | +0.00b | 348.00ms | -84.00ms 🚀 |
| dist/panel-error.8d11e8b7.js | 906.00b | +0.00b | 573.00ms | +151.00ms ⚠️ |
| dist/panel.a28c56ee.js | 897.00b | +0.00b | 332.00ms | -95.00ms 🚀 |
| dist/table.5a4874ee.js | 889.00b | +0.00b | 347.00ms | -84.00ms 🚀 |
| dist/panel-success.9b923e58.js | 845.00b | +0.00b | 332.00ms | -95.00ms 🚀 |
| dist/panel-note.97a4d541.js | 841.00b | +0.00b | 332.00ms | -90.00ms 🚀 |
| dist/media-picker-analytics-error-boundary.f8ddfee3.js | 839.00b | +0.00b | 451.00ms | -42.00ms 🚀 |
| dist/media-card-analytics-error-boundary.663369b9.js | 835.00b | +0.00b | 423.00ms | -47.00ms 🚀 |
| dist/media-card-analytics-error-boundary.73ba4074.js | 835.00b | +0.00b | 475.00ms | -36.00ms 🚀 |
| dist/media-viewer-analytics-error-boundary.0afa7031.js | 755.00b | +0.00b | 435.00ms | -53.00ms 🚀 |
| dist/EmojiPickerComponent.2e54b9c6.js | 535.00b | +0.00b | 387.00ms | -57.00ms 🚀 |
| dist/simpleHasher.16c8bf41.js | 528.00b | +0.00b | 399.00ms | -50.00ms 🚀 |
| dist/index.html | 119.00b | +0.00b | 269.00ms | -31.00ms 🚀 |

</p></details>

<details><summary>Three.js x4 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/278135676635972104)**

**Comment by devongovett** [comment]
Should we add a test for this?

**Review by devongovett — APPROVED** [review]
Merging as a temp solution

**Comment by mischnic** [comment]
Can you add a short comment saying that this is temporary and briefly why it's needed?

**Pull request merged**
