### PR TITLE
Bugfix/dynamic hoist

### PR DESCRIPTION
**Pull request by jeanfortheweb**
Bugfix for #790 and possible #802.
There has been changes made since 1.4.1 which unfortunately fixed the issue only partially.
This time, I made the PR for the master, since the "freeze" issue since 1.5.1 for at least virtual windows machines has been found, but will be opened in a separate case.

### CODE REVIEW

**Comment by jeanfortheweb** [comment]
There are two HTML tests failing on appveyor which do not fail local.
Also, my code changes do not intersect with these tests. Any suggestions?

**Comment by DeMoorJasper** [comment]
I can confirm that the tests fail on windows, the first html test results in a bundle that lacks the JS bundle

**Comment by jeanfortheweb** [comment]
Guess I may should take a look at it, since my other PR is building multiple times without any issues...

**Comment by devongovett** [comment]
It is actually possible and correct for an asset to appear in more than one bundle. For example, imagine you had `a.html` and `b.html` and they import `a.js` and `b.js` respectively. If both `a.js` and `b.js` import `c.js`, then `c.js` should appear in the bundled output for both `a.js` and `b.js`. This PR would  change that behavior so that it would only appear in one of the two - which would break the other page.

Can you provide more details and possibly a reduced test case on the exact duplication you are seeing?

**Comment by jeanfortheweb** [comment]
I will check your fear through tests. I was thinking that a different HTML file will get it's own tree, since they have independent entry points. But it shouldn't be too complicated to create a test case for this. With this patch I was able to reduce the bundle output by almost 5MB while maintaining it's functionality.

**Pull request closed without merging**
