### PR TITLE
Add Markdown support — v2

### PR DESCRIPTION
**Pull request by kirillrogovoy**
# ↪️ Markdown support — v2

Implements what originally was asked in https://github.com/parcel-bundler/parcel/issues/2274.

New features:
- [Front matter](https://www.npmjs.com/package/front-matter) support
- Templating support via [Mustache](https://github.com/janl/mustache.js/) templates
- Specifying options for Marked via `marked.config.js`
- Specifying options for Marked via Front matter attributes

**See integration tests for examples.**

I'll be happy to write the docs for Markdown support once we settle on these changes.

## ✔️ PR Todo

- [x] Added/updated unit tests for this change
- [x] Filled out test instructions (In case there aren't any unit tests)
- [x] Included links to related issues/PRs

### CODE REVIEW

**Comment by kirillrogovoy** [comment]
cc @LandonSchropp @Benjmhart

**Comment by kirillrogovoy** [comment]
cc @tomfinney — should solve your issue here: https://github.com/parcel-bundler/parcel/pull/2538#issuecomment-478325570

@mischnic @devongovett Hey!
I know the project's been intense, but could you give a rough estimate on when you would be able to look at the changes?

Maybe there's something inherently wrong with this PR and you would send me back to the workbench having spent just a minute? 😅

**Comment by mischnic** [comment]
Parcel 1 is feature-locked because of the ongoing development of Parcel 2. So this is very unlikely to be merged.

**Comment by kirillrogovoy** [comment]
@mischnic Thanks for your reply!

1. Does that mean that I could get it merged into v2 somehow?
2. If the issue is the breaking changes, why did https://github.com/parcel-bundler/parcel/pull/2538 get into master then? 🙂 It did contain breaking changes for how we treat Markdown files. This PR is just finishing what I've started there.

**Comment by tomfinney** [comment]
@kirillrogovoy the front matter stuff looks dope.

It seems weird that this would not get merged into 1.x.x as the initial version of markdown processing was merged in. One my projects is currently locked to a specific version of Parcel prior to that because the update broke how I parsed meta data from the markdown files. Seems weird to let that in but to not then tie up all the loose threads.

**Comment by DeMoorJasper** [comment]
@kirillrogovoy it could get merged into v2. Although it’s probably better to wait untill we’ve figured out html for v2

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kirillrogovoy** [comment]
I don't mind waiting for v2. Although I'm still concerned with what @tomfinney and I mentioned.

We *already* have Markdown support *in master*, but it's very limited.

It made sense to not merge the preceding PR (#2538) due to the feature lock, but it makes less sense to not get it finished since we did merge it.

**Comment by DeMoorJasper** [comment]
gonna close this due to Parcel 1 not receiving any new features

**Pull request closed without merging**
