### PR TITLE
Clean up old MemoryFS instances in the tests

### PR DESCRIPTION
**Pull request by devongovett**
Let's see if this speeds up the tests. For me, they've been pretty fast. @mischnic @wbinnssmith you mentioned they were slow for you. Does this help?

Close T-865

### CODE REVIEW

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>Kitchen Sink 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

<details><summary>React HackerNews ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 8.51s | -26.00ms |
| Cached | 398.00ms | -8.00ms |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

*No bundle changes detected.*

</p></details>

<details><summary>AtlasKit Editor 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

<details><summary>Three.js ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 6.07s | +51.00ms |
| Cached | 359.00ms | +11.00ms |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

*No bundle changes detected.*

</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/303338026787930688)**

**Comment by AGawrys** [comment]
Hey 👋  I wasn't experiencing slowness with the tests before, but I pulled down this branch and ran it and found it was roughly the same time as v2  (fix memoryfs leak: **450.00**s vs v2: **450.92**s) So this means it's probably not regressing!

**Comment by wbinnssmith** [comment]
> Hey 👋 I wasn't experiencing slowness with the tests before, but I pulled down this branch and ran it and found it was roughly the same time as v2 (fix memoryfs leak: **450.00**s vs v2: **450.92**s) So this means it's probably not regressing!

Has there been an improvement in memory usage for you?

**Comment by thebriando** [comment]
Integration tests are still taking 25min for me 😕 . Did this work for you @lettertwo ?

**Comment by AGawrys** [comment]
> > Hey 👋 I wasn't experiencing slowness with the tests before, but I pulled down this branch and ran it and found it was roughly the same time as v2 (fix memoryfs leak: **450.00**s vs v2: **450.92**s) So this means it's probably not regressing!
> 
> Has there been an improvement in memory usage for you?

Nope. Looks just about the same on our internal app for both CPU and memory usage

**Comment by lettertwo** [comment]
@joeyslater tipped me off to the fact that tests run about 2-3x slower after `yarn build-native` compared to `yarn build-native-release`. When running tests with native release builds, they run in the **7-8** min (~**450**s) range instead of **20** min+ for me, which seems to align more with @AGawrys numbers.

With that said, I am getting roughly equivalent test run times on both v2 and this branch.

**Comment by thebriando** [comment]
`yarn build-native-release` also fixed the slowness for me 👍 

The integration test suite takes about ~5min to complete locally compared to the 20+ minutes I was getting before

**Pull request closed without merging**
