### PR TITLE
Update swc

### LINKED ISSUE #6282: Double whammy issue: new parcel can't hit targets and gets confused by calling a function #get
# 🐛 bug report

I was able to create simple input code which makes double wrong output!

1. SWC thinks newest firefox supports private class fields which it does not
2. Parcel produces invalid output both when running `parcel serve` and `parcel build` if a class contains a private method called `#get`.

## 🎛 Configuration (.babelrc, package.json, cli command)

Please see attached .zip file

## Sample code

```
class myclass {
  #get(){
    console.log("Hi from a method with a private identifier called #get");
  }
  constructor(){
    this.#get();
  }
}

const instance = new myclass();
```

## 🤔 Expected Behavior

The same (or identically behaving) output as good old `2.0.0-nightly.650+dc79abcd` gives me:
```
! function() {
  var t = 0;

  function e(e) {
    return "__private_" + t++ + "_" + e
  }
  var r = e("get");

  function n() {
    console.log("Hi from a method with a private identifier called #get")
  }
  new class {
    constructor() {
      Object.defineProperty(this, r, {
        value: n
      }), ((t, e) => {
        if (!Object.prototype.hasOwnProperty.call(t, e)) throw new TypeError("attempted to use private field on non-instance");
        return t
      })(this, r)[r]()
    }
  }
}();
```

-> logs `Hi from a method with a private identifier called #get` to the console when ran

## 😯 Current Behavior

```
new class {
  #get() {
    console.log("Hi from a method with a private identifier called #get")
  }
  constructor() {
    (function(t, e) {
      if (!e.has(t)) throw new TypeError("attempted to get private field on non-instance");
      return e.get(t).value
    })(this, _get).call(this)
  }
};
```

In firefox (which was my build target) -> ` Uncaught SyntaxError: private fields are not currently supported`
In chrome: `VM450:9 Uncaught ReferenceError: _get is not defined`

## 💁 Possible Solution

Make it work correctly like it did before.

## 🔦 Context

I was, after already reporting multiple issues with the new SWC thing just by trying to use it and read the code, finally daring to run just a portion of the output code and it failed lol.

## 💻 Code Sample

[parcel-hashtag-get.zip](https://github.com/parcel-bundler/parcel/files/6475197/parcel-hashtag-get.zip)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |2.0.0-nightly.660+177f8eec|
| Node             |v16.1.0|
| npm/Yarn         |yarn 1.22.10|
| Operating System |macOS 10.15.7 (19H1030)|

### LINKED ISSUE #6296: Parcel 2: another SWC regression: getters with non-boring names yield: `@parcel/transformer-js: Expected ,, got string literal (🍊)`
# 🐛 bug report

Getters that are named with string-names make parcel fail building.

Take i.e. this input code:
```
const juice = {
  get "🍊"() {
    return "😋";
  },
};
console.log(juice['🍊']);
```

## 🎛 Configuration (.babelrc, package.json, cli command)

Please see attached .zip file

## 🤔 Expected Behavior

```
console.log({get"🍊"(){return"😋"}}["🍊"]);
```

(returns `😋` when ran)

## 😯 Current Behavior

```
daniel@Daniels-MacBook-Pro parcel-cant-get % npm run build

> build
> parcel build src/main.ts --log-level verbose --detailed-report 100 --target modern

🚨 Build failed.
@parcel/transformer-js: Expected ,, got string literal (🍊)
/private/tmp/parcel-cant-get/src/main.ts:2:7
  1 | const juice = {
> 2 |   get "🍊"() {
>   |       ^^^^
  3 |     return "😋";
  4 |   },
daniel@Daniels-MacBook-Pro parcel-cant-get % 
```

## 💁 Possible Solution

Revert to the behavior of 650 where it worked.

## 🔦 Context

I have an object that looks like this:
```
const localisations = {
  // stuff is here
  get "de-CH"(){
    return localisation['de-DE'];
  }
};
```

And since the swc update it no longer works. Version 650 still does it fine.

## 💻 Code Sample

[parcel-cant-get.zip](https://github.com/parcel-bundler/parcel/files/6492694/parcel-cant-get.zip)

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |2.0.0-nightly.671+06bdb1fb|
| Node             |v16.1.0|
| npm/Yarn         |npm v7.11.2|
| Operating System |10.15.7 (19H1030)|

### PR DESCRIPTION
**Pull request by mischnic**
Closes https://github.com/parcel-bundler/parcel/issues/6282
Closes #6296

### CODE REVIEW

**Review by DeMoorJasper — APPROVED** [review]

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>Kitchen Sink 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

<details><summary>React HackerNews 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

<details><summary>AtlasKit Editor 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

<details><summary>Three.js 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/298844481670611465)**

**Comment by mischnic** [comment]
Tests are broken because a TS file with
```ts
console.log('Hello Parcel!')
```
is transformed by swc into
```ts
console.log('Hello Parcel!')
export {};
```
after https://github.com/swc-project/swc/issues/1698.

-> https://github.com/swc-project/swc/issues/1706

**Comment by danieltroger** [comment]
NOOOOOOOOOOOOO yet another day without a nightly where my private class fields don't throw errors 😟

**Comment by mischnic** [comment]
A workaround is adding a Babel config with `@parcel/babel-preset-env` (so that it's not swc which transpiles it).

I'll update the failing test so that we can merge this if it's not fixed in swc today.

**Comment by danieltroger** [comment]
> I'll update the failing test so that we can merge this if it's not fixed in swc today.

Thanks! But yo, adding babel-preset-env actually works!

But I just discovered https://github.com/parcel-bundler/parcel/issues/6296 so the thing I'd need to update for (having a person that doesn't have parcel installed install it and do some QA for me) doesn't work anyways lol.

**Pull request merged**
