### PR TITLE
Changed some JS to be IE11 compatible.

### LINKED ISSUE #6502: Bundle contains non IE11 compatible code
# 🐛 bug report

Bundle contains lots of non IE11 compatible code, even with `"browserslist": ["IE 11"]`.

## 🎛 Configuration (.babelrc, package.json, cli command)

Empty project, just a dummy index.html + index.js.

package.json
`"browserslist": ["IE 11"]`

CLI
`npx parcel serve .\index.html`

## 🤔 Expected Behavior

Bundle should run in IE11.

## 😯 Current Behavior

Syntax error in IE11. Bundle contains multiple non IE11-code. This is some injected boilerplate code and does not originate from my simple index.js.

Some examples from the bundle:

IE doesn't like the trailing comma:

```
      modules[name][0].call(
        module.exports,
        localRequire,
        module,
        module.exports,
        this,
      );
```

Arrow function:
```
let assets = data.assets.filter((asset)=>asset.envHash === HMR_ENV_HASH
```

IE doesn't support `for of`:

```
for (let ansiDiagnostic of data.diagnostics.ansi){
```

## 💁 Possible Solution

Bundle should be free of non IE11. If this is injected boilerplate, that code should be compatible with IE11. Either by changing the boilerplate template or by running it through some transpilation.

## 🔦 Context

N/A

## 💻 Code Sample

I think my examples above are enough to find the issue. If not, I'm happy to push a simple repro.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | @next
| Node             | 16
| npm/Yarn         |7.13
| Operating System |Win10

### PR DESCRIPTION
**Pull request by hallsbyra**
# ↪️ Pull Request

Partial fix for #6502

Had to revert changes done by `yarn format` to `dev-prelude.js` since it would re-introduce trailing commas that break IE11 compatibility. Maybe these files should be excluded from `yarn format` somehow?

## ✔️ PR Todo

- [ ] Added/updated unit tests for this change - N/A
- [ ] Filled out test instructions (In case there aren't any unit tests) - N/A
- [X] Included links to related issues/PRs

### CODE REVIEW

**Comment by mischnic** [comment]
> Had to revert changes done by yarn format to dev-prelude.js since it would re-introduce trailing commas that break IE11 compatibility. Maybe these files should be excluded from yarn format somehow?

That should already be handled by this:
https://github.com/parcel-bundler/parcel/blob/d1e0a1a0781d65fdfb84354e52ed85313717bc4b/.prettierrc#L9-L11

**Comment by mischnic** [comment]
When building this with `parcel build a.js`:
```js
// a.js
console.log(require("./b.js"));

// b.js
module.exports.x = 123;
```

the output contains arrow functions:
```js
(function () {
...
parcelRequire.register("fPYqQ", function(module, exports) {

$parcel$export(module.exports, "x", () => $b87a7ef68e90c5ee$export$10b1f2ceae7ab64e, (v) => $b87a7ef68e90c5ee$export$10b1f2ceae7ab64e = v);
var $b87a7ef68e90c5ee$export$10b1f2ceae7ab64e;
$b87a7ef68e90c5ee$export$10b1f2ceae7ab64e = 123;

});


console.log((parcelRequire("fPYqQ")));
```
This is what I mentioned in the second part of https://github.com/parcel-bundler/parcel/issues/6502#issuecomment-871333088

**Comment by hallsbyra** [comment]
Ok, thanks. Took care of that second part of https://github.com/parcel-bundler/parcel/issues/6502#issuecomment-871333088 in latest commit.

**Comment by devongovett** [comment]
Maybe we should do this based on the environment so we don't have to ship larger output to modern browsers?

**Comment by aminya** [comment]
> Maybe we should do this based on the environment so we don't have to ship larger output to modern browsers?

Yes, please! I do not want to support IE11. It's better to break the websites for IE11 users, so they start to think about upgrading.

**Comment by hallsbyra** [comment]
> Maybe we should do this based on the environment so we don't have to ship larger output to modern browsers?

Yes, that'd be good. This PR is now ready to merge. I suggest we merge this as it is to get the bug fixed. Then we open a separate issue/PR with an improvement to the current behavior. Keeping PRs small is good.

**Comment by danieltroger** [comment]
Sounds good @hallsbyra. I vote for merging.

**Comment by danieltroger** [comment]
@mischnic what is blocking this from being merged?

**Comment by aminya** [comment]
Its regressions for those who don't want to support IE11:
https://github.com/parcel-bundler/parcel/pull/6532#issuecomment-871534264

**Comment by danieltroger** [comment]
@aminya that's not a reason to not merge this. It's like saying you don't want firefighters to put out the burning house of your neighbour because it would wake you up.

You get like 50 bytes extra, while my efforts to support older browsers stop being in vain. It doesn't break anything for you, while it fixes something for me. And I agree that we should use arrow functions in modern browsers. I think terser converts them anyways if you use the right options.

**Comment by aminya** [comment]
You can run this in the meantime.
```
    "ie11": "babel dist --out-dir dist --config-file ./babel.ie11.config.json",
```

babel.ie11.config.json
```
{
  "targets": {
    "ie": "11"
  }
}
```

**Comment by danieltroger** [comment]
Thanks @aminya. Running that on parcel's output will also transpiled all core-js polyfills, is there any indication showing it will work? I'll probably try it later on but I give it a 40% success rate because I read in some of @zloirock's issues that that messes with some core-js Symbol.iterator implementation

**Comment by mischnic** [comment]
> You get like 50 bytes extra, while my efforts to support older browsers stop being in vain. It doesn't break anything for you, while it fixes something for me. And I agree that we should use arrow functions in modern browsers.

If you have a large bundle with 3000 of these export declarations, this change will make it 14*3000=42kb larger (even when minified).

> I think terser converts them anyways if you use the right options.

Terser cannot do this safely (= by default), it requires `unsafe_arrows: true`

**Comment by hallsbyra** [comment]
> Yes, please! I do not want to support IE11. It's better to break the websites for IE11 users, so they start to think about upgrading.

Dropping support for IE11 is indeed an option. But that decision is out of scope of this PR. I suggest that is discussed somewhere else, and keep this PR as the bug fix it is intended to be.

**Comment by mischnic** [comment]
Doesn't IE 11 not really support `let`? Can you replace them with `var` in the various files you already touched?

**Comment by hallsbyra** [comment]
> Doesn't IE 11 not really support `let`? Can you replace them with `var` in the various files you already touched?

`let` works in IE except in `for`-loops. (https://caniuse.com/?search=let) I reviewed the code and could not find any such cases.

**Comment by danieltroger** [comment]
@hallsbyra it might work in IE11 but it doesn't work on older androids. You'd do me a favor if you'd changed it in the screenshot that I sent [here](https://github.com/parcel-bundler/parcel/issues/6502#issuecomment-882620767).

**Comment by aminya** [comment]
Instead of transforming all of these manually, there could be a babel transformer that runs on the final output when you select something ancient like IE11. 

A babel transformer that runs on the final output is useful in general (see [this](https://github.com/parcel-bundler/parcel/issues/5590#issuecomment-865657074) as an example)

**Comment by hallsbyra** [comment]
@danieltroger , I replaced the `let`s.

@aminya , a transformer would be great, but I'm not versed enough in the codebase to do it myself.

**Comment by danieltroger** [comment]
@hallsbyra TYSM for replacing the `let`s. Can't wait for this to get merged.

@aminya FYI I tried babel but couldn't find a browserslist query for this userAgent: `Mozilla/5.0 (Linux; Android 5.0.2; Android SDK built for x86_64 Build/LSY66K) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/37.0.0.0 Mobile Safari/537.36`.
I tried `android 5` (which is accurate) - it still had `let`, `android 3` which still had `let`, `ChromeAndroid 37` which babel didn't support and a couple more.

I manually replaced all `let ` with `var ` in the file and everything ran flawlessly (!). Apparently my bundle doesn't contain any wrapped assets where the arrow function bug comes to show.

**Comment by devongovett** [comment]
Hey, hope you don't mind me pushing to your branch. I made 3 changes:

1. Rather than removing use of arrow functions completely for all targets, we now detect whether they are supported in the target environment and only fall back to normal functions if necessary. This should result in smaller bundles for a majority of builds.
2. Rather than manually fixing issues in runtime helpers, transpile them with babel before publishing. In this case the transpilation required is very minor (mainly let -> var and fixing trailing commas) so it doesn't have much of an effect on build size. Eventually we might do this within the parcel build itself, but right now we don't transpile node_modules.
3. Added linting for IE 11 compatibility in files that don't get transpiled - right now just the dev prelude. This should prevent future regressions.

**Comment by danieltroger** [comment]
Yay, that's amazing!

**Review by devongovett — APPROVED** [review]

**Pull request merged**
