### PR TITLE
Fix recursive dependencies

### LINKED ISSUE #463: Circular Dependencies issue
**Choose one:** this is a 🐛 bug report.

### 🎛 Configuration (.babelrc, package.json, cli command)

Two files: `index.html` and `about.html`:
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Document</title>
</head>
<body>
  
  <a href="./index.html">Home</a>
  <a href="./about.html">About</a>

</body>
</html>
```

### 🤔 Expected Behavior

Parcel bundler should overcome circular dependencies. (Although I am not sure how 🤔)

### 😯 Current Behavior

```
Server running at http://localhost:1234
🚨  Maximum call stack size exceeded
    at md5 (/Users/Bariotis/Dev/develop/parcel-bootstrap/node_modules/parcel-bundler/src/utils/md5.js:3:13)
    at HTMLAsset.generateBundleName (/Users/Bariotis/Dev/develop/parcel-bootstrap/node_modules/parcel-bundler/src/Asset.js:170:12)
    at Bundler.createBundleTree (/Users/Bariotis/Dev/develop/parcel-bootstrap/node_modules/parcel-bundler/src/Bundler.js:396:46)
    at Bundler.createBundleTree (/Users/Bariotis/Dev/develop/parcel-bootstrap/node_modules/parcel-bundler/src/Bundler.js:413:12)
    at Bundler.createBundleTree (/Users/Bariotis/Dev/develop/parcel-bootstrap/node_modules/parcel-bundler/src/Bundler.js:413:12)
    at Bundler.createBundleTree (/Users/Bariotis/Dev/develop/parcel-bootstrap/node_modules/parcel-bundler/src/Bundler.js:413:12)
    at Bundler.createBundleTree (/Users/Bariotis/Dev/develop/parcel-bootstrap/node_modules/parcel-bundler/src/Bundler.js:413:12)
    at Bundler.createBundleTree (/Users/Bariotis/Dev/develop/parcel-bootstrap/node_modules/parcel-bundler/src/Bundler.js:413:12)
    at Bundler.createBundleTree (/Users/Bariotis/Dev/develop/parcel-bootstrap/node_modules/parcel-bundler/src/Bundler.js:413:12)
    at Bundler.createBundleTree (/Users/Bariotis/Dev/develop/parcel-bootstrap/node_modules/parcel-bundler/src/Bundler.js:413:12)
```
### 💁 Possible Solution

Parcel bundler should not try to parse a dependency that has already parsed before (again I am not sure if this is possible).

### 💻 Code Sample

https://github.com/kbariotis/parcel-bootstrap-pug

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.4.1 |
| Node             | 8.9.6 |
| npm         | 5.5.1 |
| Operating System | OSX High Sierra |

### PR DESCRIPTION
**Pull request by shawwn**
Closes #463

### CODE REVIEW

**Comment by shawwn** [comment]
Nope, this doesn't work yet. Trying again...

**Comment by shawwn** [comment]
Ok, ready for review. Recursive dependencies work.

**Comment by ipmb** [comment]
This fixes recursive dependencies for me, but breaks my JS build. I expect to get roughly the same output from: `parcel serve --no-cache --no-hmr index.html` and `parcel build --no-minify --no-cache index.js` where `index.html` has a dependence on `index.js`.

Using `serve` an additional copy of `index.js` is injected into the output, overwriting part of the `process/browser.js` that gets included in the build.

**Comment by devongovett** [comment]
This seems like a fairly complex solution. How about something like this instead:

```diff
-  createBundleTree(asset, dep, bundle) {
+  createBundleTree(asset, dep, bundle, parentBundles = new Set) {
     if (dep) {
       asset.parentDeps.add(dep);
     }
@@ -381,7 +383,14 @@ class Bundler extends EventEmitter {
           this.moveAssetToBundle(asset, commonBundle);
           return;
         }
-      } else return;
+      } else {
+        return;
+      }
+
+      // Detect circular bundles
+      if (parentBundles.has(asset.parentBundle)) {
+        return;
+      }
     }
 
     // Create the root bundle if it doesn't exist
@@ -411,12 +420,15 @@ class Bundler extends EventEmitter {
     }
 
     asset.parentBundle = bundle;
+    parentBundles.add(bundle);
 
     for (let dep of asset.dependencies.values()) {
       let assetDep = asset.depAssets.get(dep.name);
-      this.createBundleTree(assetDep, dep, bundle);
+      this.createBundleTree(assetDep, dep, bundle, parentBundles);
     }
 
+    parentBundles.delete(bundle);
```

This way, we add the bundle to a set of parent bundles, and pass that to the recursive calls. Then we can just check if the asset's parentBundle is already in there, which means it's circular. Seems to pass the test you added here.

**Comment by ipmb** [comment]
@devongovett with your diff, I get one giant HTML output that appears to contain the HTML for every page in the bundle. Attached is the patch I applied.
[parentBundleCheck-patch.txt](https://github.com/parcel-bundler/parcel/files/1613676/parentBundleCheck-patch.txt)

**Comment by devongovett** [comment]
@ipmb hmm, that's strange. any way you can provide an example that reproduces the issue?

**Comment by shawwn** [comment]
Ready to merge.

@ipmb This PR should fix your project.

**Comment by ipmb** [comment]
Latest changes fix the issues I was seeing. 🎉

**Comment by devongovett** [comment]
Closed in favor of #548

**Pull request closed without merging**
