### PR TITLE
Kotlin Transformer

### LINKED ISSUE #3356: Parcel 2: Kotlin transformer
Create the `@parcel/transformer-kotlin` package in `packages/transforms/kotlin`. This package is a Parcel 2 transform plugin for Kotlin. It should be based on the `KotlinAsset` from Parcel 1.

The `@parcel/transformer-kotlin` package is responsible for the following things:

* Compiling Kotlin to JS with `@jetbrains/kotlinc-js-api`
* Collecting all files referenced in the code so that Parcel watches them (not currently supported in Parcel 1)
* Generating source maps

### PR DESCRIPTION
**Pull request by DeMoorJasper**
# ↪️ Pull Request

Updated version of #3444

Closes #3356

## ✔️ PR Todo

- [x] Added/updated unit tests for this change
- [x] Filled out test instructions (In case there aren't any unit tests)
- [x] Included links to related issues/PRs

### CODE REVIEW

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>packages/benchmarks/kitchen-sink 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

<details><summary>packages/benchmarks/react-hn ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 15.92s | -170.00ms |
| Cached | 10.03s | +30.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/main/index.js | 34.53kb | +0.00b | 1.91s | -630.00ms 🚀 |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/main/index.js | 34.53kb | +0.00b | 14.00ms | -1.00ms 🚀 |
| dist/module/index.js | 34.33kb | +0.00b | 11.00ms | -1.00ms 🚀 |

</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/247757519800238606)**

**Comment by mischnic** [comment]
How do you plan to solve the `addDependency` problem (that Kotlin doesn't expose files that should be watched)?

**Comment by DeMoorJasper** [comment]
@mischnic I just fixed the various map issues of this transformer, was just looking into if kotlin provides any amount of metadata. Otherwise we'd probably have to just not support it I guess, there's no way to do it reliably without the addDep thing

**Comment by DeMoorJasper** [comment]
I have no clue how the resolution works for kotlin and it seems like there's no real way to get the deps

**Pull request closed without merging**
