### PR TITLE
fix issues with sass importers

### LINKED ISSUE #5275: Support tilde ~ in Sass Transformer
# 🙋 feature request

Support the `@import '~path/to/styles.scss'` syntax.

## 🤔 Expected Behavior

It should resolved from `node_modules`, it was working this way in Parcel v1.

## 😯 Current Behavior

```
Error: The @import path "~path/to/styles" is using webpack specific syntax, which isn't supported by Parcel.

To @import files from node_modules, use "path/to/styles"
```

The error message is actually incorrect. The tilde syntax is not only from Webpack, VScode also supports it: here's the demo:

IGMC5dbA4i

## 💁 Possible Solution

Add the tilde ~ support.

## 🔦 Context

https://github.com/sweetalert2/sweetalert2-parcel-demo/blob/master/styles.scss

### LINKED ISSUE #6002: @parcel/transformer-sass: Fails to resolve path to node module
# 🐛 bug report

In the newly released parcel 2.0.0-beta.2 (and nightly builds before that) transformer-sass can’t resolve paths to installed node modules.

The error looks similar to https://github.com/parcel-bundler/parcel/issues/5813 but happens on build and serve.

## 🎛 Configuration (.babelrc, package.json, cli command)

package.json
```js
"dependencies": {
    "autoprefixer": "~10.2.5",
    "core-js": "~3.9.1",
    "foundation-sites": "6.6.3",
    "husky": "~5.1.3",
    "jquery": "~3.6.0",
    "motion-ui": "~2.0.3",
    "parcel": "2.0.0-beta.2",
    "postcss": "~8.2.7",
    "sass": "~1.32.8",
  },
  // automatically added by parcel:
  "devDependencies": {
    "@babel/core": "^7.13.10",
    "@parcel/transformer-sass": "2.0.0-beta.2"
  }
```

.scssrc
```js
{
  "includePaths": ["node_modules"]
}
```

In my scss files, I'm importing scss files from foundation-sites, e.g.
```scss
@import "foundation-sites/scss/global";
```

## 🤔 Expected Behavior

I expect the scss file to be included (used to still work with parcel 2.0.0-beta.1).

## 😯 Current Behavior

`yarn parcel serve` and `yarn parcel build` throw an error. No css file is build.

```
Build failed.
@parcel/transformer-sass: Got unexpected null
   ╷
19 │ @import "foundation-sites/scss/global";
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  scss/main.scss 19:9  root stylesheet
Error: Got unexpected null
   ╷
19 │ @import "foundation-sites/scss/global";
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  scss/main.scss 19:9  root stylesheet
    at Object._newRenderError (/var/code/themes/mo-foundation-base/node_modules/sass/sass.dart.js:13537:19)
    at Object._wrapException (/var/code/themes/mo-foundation-base/node_modules/sass/sass.dart.js:13374:16)
    at _render_closure1.call$2 (/var/code/themes/mo-foundation-base/node_modules/sass/sass.dart.js:80373:21)
    at _RootZone.runBinary$3$3 (/var/code/themes/mo-foundation-base/node_modules/sass/sass.dart.js:27269:18)
    at _FutureListener.handleError$1 (/var/code/themes/mo-foundation-base/node_modules/sass/sass.dart.js:25797:19)
    at _Future__propagateToListeners_handleError.call$0 (/var/code/themes/mo-foundation-base/node_modules/sass/sass.dart.js:26094:49)
    at Object._Future__propagateToListeners (/var/code/themes/mo-foundation-base/node_modules/sass/sass.dart.js:4543:77)
    at _Future._completeError$2 (/var/code/themes/mo-foundation-base/node_modules/sass/sass.dart.js:25927:9)
    at _AsyncAwaitCompleter.completeError$2 (/var/code/themes/mo-foundation-base/node_modules/sass/sass.dart.js:25270:12)
    at Object._asyncRethrow (/var/code/themes/mo-foundation-base/node_modules/sass/sass.dart.js:4292:17)
```

On previous tries the error message was "Failed to resolve" with an identical stack trace.

## 💁 Possible Solution

Maybe scss files need to be imported differently now? 

## 🔦 Context

The issue makes any recent version of parcel 2 unusable for us. We need to be able to import scss files from other node modules.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.2
| Node             | 12.19.0
| npm/Yarn         | yarn 1.22.5
| Operating System | Ubuntu 20.10

### PR DESCRIPTION
**Pull request by DeMoorJasper**
# ↪️ Pull Request

Added support for webpack/sass specific syntax back and also add support for the underscore prefix that is used for sass libraries quite often.

Closes #6002 and Closes #5275

## ✔️ PR Todo

- [x] Added/updated unit tests for this change
- [x] Filled out test instructions (In case there aren't any unit tests)
- [x] Included links to related issues/PRs

### CODE REVIEW

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>Kitchen Sink 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

<details><summary>React HackerNews ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 9.48s | -271.00ms |
| Cached | 432.00ms | +12.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/logo.1e014c76.png | 274.00b | +0.00b | 218.00ms | -12.00ms 🚀 |

#### Cached Bundles

*No bundle changes detected.*

</p></details>

<details><summary>AtlasKit Editor 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

<details><summary>Three.js ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 6.71s | -182.00ms |
| Cached | 402.00ms | +19.00ms |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

*No bundle changes detected.*

</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/304987579011301952)**

**Comment by devongovett** [comment]
Apparently ~ is also deprecated in webpack: https://webpack.js.org/loaders/sass-loader/#resolving-import-at-rules

**Review by devongovett — APPROVED** [review]

**Comment by rb-ntnx** [comment]
@DeMoorJasper @devongovett 

I landed here after facing same issue while using  "parcel": "^2.3.2" !
We are using in house design system library (wrapper around Ant Design)  with our react project .

I got following error:

```Server running at http://localhost:1234
🚨 Build failed.

@parcel/transformer-less: The @import path "~antd/lib/style/index.less" is using
webpack specific syntax, which isn't supported by Parcel.

To @import files from node_modules, use "antd/lib/style/index.less"```

Do I need some special configuration to enable the support for ~ imports ?

**Comment by crazyair** [comment]
https://github.com/parcel-bundler/parcel/blob/v2/packages/transformers/less/src/LessTransformer.js#L116

**Pull request merged**
