### PR TITLE
Add TypeScript types

### LINKED ISSUE #3912: [Parcel 2] Typescript Definitions
# 🙋 feature request

Type definitions for this package, whether they'd be included in the package or in @types/parcel.

## 🤔 Expected Behavior

Import types from `@types/parcel` :
```
import Parcel from 'parcel'
```

## 😯 Current Behavior
Import has squiggly lines of death explaining that there are no types.

`@types/parcel` exists:
```
import Parcel from 'parcel'
```

`@types/parcel-bundler` exists:
```
import Parcel from 'parcel-bundler'
```

## 💁 Possible Solution

Generate types using [`flow-to-typescript` package](https://github.com/bcherny/flow-to-typescript). Unsure on any restrictions in the project.

## 🔦 Context

I want to test out this package, but will be using typescript strictly. I'm using the bundler API to prerender static HTML pages for a react application.

### PR DESCRIPTION
**Pull request by 101arrowz**
# ↪️ Pull Request

Adds TypeScript typings to (as far as I can tell) Parcel's entire public API. I haven't checked the validity of these since a few weeks ago; any corrections are welcome. Of note is that this addition documents much of `@parcel/core` with rich comments. These additions will help TypeScript users (and JS users in most IDEs) to have much better autocomplete and more clarity with types. In addition, the types massively facilitate the creation of a Parcel plugin.

FIxes #3912.

## 💻 Examples

```ts
import { Transformer } from '@parcel/plugin'; // well typed
// Generic type allows for well-defined AST and config types
export default new Transformer({
  // the method and its parameters have full typing
  parse({ asset }) {
    return whatever;
  },
  transform({ asset, config }) {
    // No more typing out long names and hoping to catch typos
    // Since most IDEs don't support Flow, TS types help write correct code faster
    asset.addIncludedFile(...);
  }
})
```
## 🚨 Test instructions

N/A for the most part (maybe add a linter in the future?)

## ✔️ PR Todo

- [x] <strike>Added/updated unit tests for this change</strike> N/A
- [x] Filled out test instructions (In case there aren't any unit tests)
- [x] Included links to related issues/PRs

### CODE REVIEW

**Comment by 101arrowz** [comment]
The cause of the failing tests is the removal of `@parcel/watcher`'s `flow-libs` entry. The official repo has accepted flow types already, so updating `@parcel/watcher` and republishing the package with the types should be enough to fix them.

**Comment by devongovett** [comment]
Thanks for working on this! Did you try auto-generating these from the flow types? I believe there are some tools that might be able to do that, and would make it easier for us to keep up to date.

**Comment by 101arrowz** [comment]
I tried auto generation, but I couldn't get it set up properly on Parcel. I'll try again now, but some of the things in these types definitely can't be auto-generated (e.g. generic types for AST in `Transformer`).

**Comment by wbinnssmith** [comment]
I believe the flow-typed project uses [flowgen](https://github.com/joarwilk/flowgen) to generate their types. Might be worth a try.

**Pull request closed without merging**
