### PR TITLE
Make builds deterministic 

### PR DESCRIPTION
**Pull request by termhn**
Fix/improvement based on #735 

Makes asset ids the last 5 characters of the md5 hash of the path of that asset.

### CODE REVIEW

**Comment by termhn** [comment]
wip... still looking to improve this and pass all the tests

**Comment by termhn** [comment]
Alright this passes tests now. Main downside is that it could increase minified file sizes a small amount and it may very slightly affect performance, maybe noticeable for projects with a very large number of assets.

**Comment by jeanfortheweb** [comment]
I had a similar approach a few days ago, but I used the Asset name itself since it's already the absolute asset path itself which should be perfect for unique ID's. Anyway, I also discovered that assets are forced to be unique created inside the bundler, therefore the current ID generation should already deterministic as long as the assets do not change. If that's not the case, then the files are not getting read in the same order every time. 

At least I would think about moving the asset creation from Bundler.js:259 (on 1.4.1) to the Asset itself using a factory pattern. Guess that would make it a lot easier to reason about.

**Comment by termhn** [comment]
That's what I did originally, but they change across different machines/operating systems. Using a normalized relative path seems to be the best options as far as that goes. See #735 for discussion/my findings about why this isn't happening--ultimately I reached a similar conclusion to you. Something's going on where assets are being loaded multiple times and not always in the same order which is why the current system doesn't work properly.. possibly because of the way workers are used to parallelize the work.

**Comment by jeanfortheweb** [comment]
Just a guess but it shouldn't happen as load time, since this is happening in the main thread on the bundler... hmmm, well if the loading order depending on the native file system layer can't be deterministic then these IDs will also never be while I still actually like the simplicity of numeric IDs.

If we move the asset creation onto a static factory function on the asset class itself, we could store the already loaded asset on a map there.

**Pull request closed without merging**
