### PR TITLE
[WIP] Fix HMR failure with js error on load

### LINKED ISSUE #879: 🐛Uncaught Error: Cannot find module '21'
### 🎛 Configuration (.babelrc, package.json, cli command)

.babelrc:
```json
{
  "presets": ["env"],
  "plugins": [
    ["babel-plugin-root-import", {
      "rootPathSuffix": "js",
      "rootPathPrefix": "@"
    }]
  ]
}
```

package.json:
```json
{
  "name": "hwm-parcel",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "makmm",
  "license": "MIT",
  "dependencies": {
    "babel-polyfill": "^6.26.0",
    "babel-preset-env": "^1.6.1"
  },
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-plugin-root-import": "^5.1.0"
  }
}
```

### 🤔 Expected Behavior

Run `$ parcel index.html`, go to `localhost:1234`, change something in the code and the browser should get the new code and load it

### 😯 Current Behavior

Run `$ parcel index.html`, go to `localhost:1234`, **console shows correct sourcemaps:** 
image

change something in the code and this error comes up:
image

Refresh, now sourcemaps are broken:
image

### 💁 Possible Solution

No idea! <.<

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.6.2 |
| Node             | 9.5.0 |
| npm         | 5.6.0 |
| Operating System | Debian sid |

### PR DESCRIPTION
**Pull request by mischnic**
`global.require` isn't defined if a childBundle called by newRequire throws an error.
This causes an error on HMR update.

More details in https://github.com/parcel-bundler/parcel/issues/879#issuecomment-368519400

fixes #879

### CODE REVIEW

**Comment by mischnic** [comment]
Tests fail because errors from require don't bubble up anymore.
```js
  try {
    // We expect browser-resolve to replace fs with an empty module, so readFileSync will be undefined
    return require('fs').readFileSync(__dirname + '/package.json')
  }
  catch(_) {
    return 'test-pkg-ignore-fs-ok'
  }
```

**Comment by wzrdtales** [comment]
loocking forward to this

**Comment by wzrdtales** [comment]
@mischnic localRequire needs the same fix, since it bares the same problem

**Comment by mischnic** [comment]
@devongovett Could you take a look on how to fix this correctly?

**Comment by FDiskas** [comment]
:incoming_envelope: waiting for the fix also

**Comment by devongovett** [comment]
Due to move to monorepo which rewrote the git history, this PR was automatically closed. Please open a new PR against master with your changes. You can do a diff against the `1.x` branch to see them. Sorry about that!

**Pull request closed without merging**
