### PR TITLE
Packager: loadConfig

### PR DESCRIPTION
**Pull request by mischnic**
# ↪️ Pull Request

Based on cache-key (like the bundler) until it's made a request. However: should the loading happen in a worker? Two options:
- currently: main thread: load config, send config over to worker on a cache miss
- all in a worker: load config, calculate cache key, return key to main thread

## ✔️ PR Todo

- [x] ~Determine where to run `loadConfig`~ Run in worker
	- Consideration: can we prevent sending over the bundle graph to a work if it's preventable?
- [x] Test Perf of cached builds?

### CODE REVIEW

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>Kitchen Sink ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 5.75s | -279.00ms |
| Cached | 2.10s | +51.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/parcel.d5807e82.webp | 102.94kb | +0.00b | 256.00ms | -28.00ms 🚀 |
| dist/modern/parcel.d5807e82.webp | 102.94kb | +0.00b | 256.00ms | -31.00ms 🚀 |
| dist/legacy/index.42516b4a.js | 1.10kb | +0.00b | 1.55s | -89.00ms 🚀 |
| dist/modern/index.8a1ced31.js | 1.10kb | +0.00b | 1.55s | -90.00ms 🚀 |
| dist/legacy/index.html | 701.00b | +0.00b | 715.00ms | +40.00ms ⚠️ |
| dist/modern/index.html | 701.00b | +0.00b | 711.00ms | +38.00ms ⚠️ |
| dist/modern/index.e480862d.css | 77.00b | +0.00b | 1.43s | -98.00ms 🚀 |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/parcel.d5807e82.webp | 102.94kb | +0.00b | 196.00ms | +47.00ms ⚠️ |
| dist/modern/parcel.d5807e82.webp | 102.94kb | +0.00b | 195.00ms | +45.00ms ⚠️ |
| dist/legacy/index.42516b4a.js | 1.10kb | +0.00b | 408.00ms | +41.00ms ⚠️ |
| dist/modern/index.8a1ced31.js | 1.10kb | +0.00b | 407.00ms | +41.00ms ⚠️ |
| dist/legacy/index.html | 701.00b | +0.00b | 409.00ms | +41.00ms ⚠️ |
| dist/modern/index.html | 701.00b | +0.00b | 407.00ms | +41.00ms ⚠️ |
| dist/legacy/index.0e158b6b.css | 77.00b | +0.00b | 408.00ms | +41.00ms ⚠️ |
| dist/modern/index.e480862d.css | 77.00b | +0.00b | 407.00ms | +41.00ms ⚠️ |

</p></details>

<details><summary>React HackerNews ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 26.59s | +601.00ms |
| Cached | 2.19s | -5.00ms |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/logo.24c8bf9e.png | 274.00b | +0.00b | 202.00ms | +17.00ms ⚠️ |

</p></details>

<details><summary>AtlasKit Editor ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 2.61m | -4.58s |
| Cached | 4.55s | -56.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.e8555081.js | 2.73mb | +9.00b ⚠️ | 1.43m | -3.65s |
| dist/card.ce67dc35.js | 55.09kb | +0.00b | 12.94s | -739.00ms 🚀 |
| dist/component.59edff1f.js | 30.78kb | +0.00b | 2.59s | +287.00ms ⚠️ |
| dist/dropzone.812039de.js | 17.27kb | +0.00b | 52.07s | -37.65s 🚀 |
| dist/ui.cee430a3.js | 13.97kb | +0.00b | 12.91s | -769.00ms 🚀 |
| dist/workerHasher.65b8a1b7.js | 11.78kb | +0.00b | 12.24s | -622.00ms 🚀 |
| dist/card.4ac5c1b2.js | 5.61kb | +0.00b | 14.01s | -1.03s 🚀 |
| dist/dropzone.2f1a1e17.js | 3.23kb | +0.00b | 28.54s | -1.45s 🚀 |
| dist/Modal.2835744c.js | 3.08kb | +0.00b | 4.84s | +1.06s ⚠️ |
| dist/16.d1b8e6f7.js | 2.38kb | +0.00b | 2.58s | +300.00ms ⚠️ |
| dist/card.cadccd96.js | 2.03kb | +0.00b | 15.57s | -14.29s 🚀 |
| dist/ResourcedEmojiComponent.d9a49606.js | 2.00kb | +0.00b | 4.84s | +1.06s ⚠️ |
| dist/16.86a8c7d4.js | 1.66kb | +0.00b | 7.14s | +452.00ms ⚠️ |
| dist/list-number.4632b459.js | 1.46kb | +0.00b | 7.01s | -39.64s 🚀 |
| dist/status.cccf04be.js | 1.46kb | +0.00b | 46.98s | +40.02s ⚠️ |
| dist/16.c1ed07f8.js | 1.33kb | +0.00b | 7.14s | +452.00ms ⚠️ |
| dist/16.a4b392c2.js | 1.32kb | +0.00b | 2.57s | +289.00ms ⚠️ |
| dist/link.d12cc130.js | 1.30kb | +0.00b | 7.01s | -39.64s 🚀 |
| dist/16.e60b4d77.js | 1.21kb | +0.00b | 2.57s | +289.00ms ⚠️ |
| dist/media-card-analytics-error-boundary.6a25b970.js | 1.15kb | +0.00b | 28.54s | -1.45s 🚀 |
| dist/16.2096b9f3.js | 1.14kb | +0.00b | 2.57s | +289.00ms ⚠️ |
| dist/16.ecf8a702.js | 1.13kb | +0.00b | 7.14s | +452.00ms ⚠️ |
| dist/16.da43aa07.js | 1.13kb | +0.00b | 7.13s | +451.00ms ⚠️ |
| dist/heading2.e219309a.js | 1.11kb | +0.00b | 46.98s | +40.02s ⚠️ |
| dist/16.dd07505e.js | 1.10kb | +0.00b | 4.84s | +1.06s ⚠️ |
| dist/component.40194190.js | 1.07kb | +0.00b | 4.84s | +1.06s ⚠️ |
| dist/mention.b1828447.js | 1.07kb | +0.00b | 7.01s | -39.64s 🚀 |
| dist/list.057cb664.js | 978.00b | +0.00b | 7.01s | -39.64s 🚀 |
| dist/heading1.fa66b375.js | 976.00b | +0.00b | 46.98s | +40.02s ⚠️ |
| dist/table.b35545be.js | 889.00b | +0.00b | 46.98s | +40.02s ⚠️ |
| dist/media-picker-analytics-error-boundary.553055f6.js | 837.00b | +0.00b | 30.53s | -20.19s 🚀 |
| dist/media-card-analytics-error-boundary.964206cc.js | 833.00b | +0.00b | 12.91s | -769.00ms 🚀 |
| dist/simpleHasher.f8e69464.js | 528.00b | +0.00b | 12.90s | -773.00ms 🚀 |
| dist/simpleHasher.32d9352e.js | 528.00b | +0.00b | 1.43m | +33.91s ⚠️ |
| dist/index.html | 119.00b | +0.00b | 766.00ms | -88.00ms 🚀 |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.e8555081.js | 2.73mb | +0.00b | 479.00ms | +67.00ms ⚠️ |
| dist/pdfRenderer.cd742f5e.js | 1.11mb | -3.00b 🚀 | 456.00ms | +47.00ms ⚠️ |
| dist/editorView.ae59b49f.js | 585.98kb | +0.00b | 456.00ms | +47.00ms ⚠️ |
| dist/popup.4a66e15e.js | 170.62kb | +0.00b | 456.00ms | +47.00ms ⚠️ |
| dist/EmojiPickerComponent.bab709db.js | 97.89kb | +0.00b | 457.00ms | +47.00ms ⚠️ |
| dist/Toolbar.33a83ae3.js | 92.34kb | +0.00b | 456.00ms | +47.00ms ⚠️ |
| dist/media-viewer.a8f3a476.js | 72.02kb | +0.00b | 456.00ms | +47.00ms ⚠️ |
| dist/card.ce67dc35.js | 55.09kb | +0.00b | 456.00ms | +46.00ms ⚠️ |
| dist/card.1007a95f.js | 52.86kb | +0.00b | 456.00ms | +47.00ms ⚠️ |
| dist/Modal.e3bd77d0.js | 41.40kb | +0.00b | 478.00ms | +67.00ms ⚠️ |
| dist/component.59edff1f.js | 30.78kb | +0.00b | 478.00ms | +67.00ms ⚠️ |
| dist/component.37867f50.js | 22.51kb | +0.00b | 478.00ms | +66.00ms ⚠️ |
| dist/DatePicker.cbe44a9b.js | 21.17kb | +0.00b | 457.00ms | +47.00ms ⚠️ |
| dist/EmojiPickerComponent.898d8be6.js | 18.23kb | +0.00b | 457.00ms | +47.00ms ⚠️ |
| dist/dropzone.812039de.js | 17.27kb | +0.00b | 456.00ms | +47.00ms ⚠️ |
| dist/smartMediaEditor.c0ff7bfa.js | 16.87kb | +0.00b | 456.00ms | +47.00ms ⚠️ |
| dist/js.48be70a4.js | 16.40kb | +0.00b | 478.00ms | +67.00ms ⚠️ |
| dist/ui.cee430a3.js | 13.97kb | +0.00b | 456.00ms | +46.00ms ⚠️ |
| dist/workerHasher.65b8a1b7.js | 11.78kb | +0.00b | 456.00ms | +46.00ms ⚠️ |
| dist/EmojiTypeAheadComponent.9af6e5fc.js | 8.67kb | +0.00b | 457.00ms | +47.00ms ⚠️ |
| dist/component.11476a92.js | 6.05kb | +0.00b | 478.00ms | +66.00ms ⚠️ |
| dist/card.4ac5c1b2.js | 5.61kb | +0.00b | 456.00ms | +47.00ms ⚠️ |
| dist/media-viewer.bc661bce.js | 3.92kb | +0.00b | 456.00ms | +47.00ms ⚠️ |
| dist/EmojiPickerComponent.624bf3f4.js | 3.58kb | +0.00b | 457.00ms | +47.00ms ⚠️ |
| dist/index.393afe59.css | 3.46kb | +0.00b | 456.00ms | +47.00ms ⚠️ |
| dist/png-chunks-extract.8d15a914.js | 3.41kb | +0.00b | 478.00ms | +67.00ms ⚠️ |
| dist/dropzone.2f1a1e17.js | 3.23kb | +0.00b | 456.00ms | +47.00ms ⚠️ |
| dist/Modal.2835744c.js | 3.08kb | +0.00b | 478.00ms | +67.00ms ⚠️ |
| dist/clipboard.0244488f.js | 2.75kb | +0.00b | 456.00ms | +47.00ms ⚠️ |
| dist/16.d1b8e6f7.js | 2.38kb | +0.00b | 478.00ms | +67.00ms ⚠️ |
| dist/EmojiUploadComponent.88a444df.js | 2.18kb | +0.00b | 457.00ms | +47.00ms ⚠️ |
| dist/card.cadccd96.js | 2.03kb | +0.00b | 456.00ms | +47.00ms ⚠️ |
| dist/ResourcedEmojiComponent.d9a49606.js | 2.00kb | +0.00b | 479.00ms | +68.00ms ⚠️ |
| dist/date.d49e64f8.js | 1.73kb | +0.00b | 477.00ms | +66.00ms ⚠️ |
| dist/16.f40c1329.js | 1.73kb | +0.00b | 478.00ms | +66.00ms ⚠️ |
| dist/images.80270b1f.js | 1.67kb | +0.00b | 458.00ms | +47.00ms ⚠️ |
| dist/16.86a8c7d4.js | 1.66kb | +0.00b | 478.00ms | +66.00ms ⚠️ |
| dist/feedback.8b7c7928.js | 1.64kb | +0.00b | 457.00ms | +47.00ms ⚠️ |
| dist/browser.16c438d4.js | 1.61kb | +0.00b | 456.00ms | +47.00ms ⚠️ |
| dist/workerHasher.9bb425b1.js | 1.54kb | +0.00b | 457.00ms | +47.00ms ⚠️ |
| dist/workerHasher.f66f00c7.js | 1.54kb | +0.00b | 456.00ms | +47.00ms ⚠️ |
| dist/list-number.4632b459.js | 1.46kb | +0.00b | 456.00ms | +45.00ms ⚠️ |
| dist/status.cccf04be.js | 1.46kb | +0.00b | 457.00ms | +46.00ms ⚠️ |
| dist/16.cff410ff.js | 1.38kb | +0.00b | 478.00ms | +66.00ms ⚠️ |
| dist/code.af9ca2b3.js | 1.38kb | +0.00b | 477.00ms | +66.00ms ⚠️ |
| dist/16.c1ed07f8.js | 1.33kb | +0.00b | 478.00ms | +66.00ms ⚠️ |
| dist/16.6603f2f3.js | 1.33kb | +0.00b | 478.00ms | +66.00ms ⚠️ |
| dist/16.a4b392c2.js | 1.32kb | +0.00b | 478.00ms | +67.00ms ⚠️ |
| dist/16.249c644a.js | 1.31kb | +0.00b | 477.00ms | +66.00ms ⚠️ |
| dist/link.d12cc130.js | 1.30kb | +0.00b | 456.00ms | +45.00ms ⚠️ |
| dist/heading6.4c4017db.js | 1.30kb | +0.00b | 457.00ms | +47.00ms ⚠️ |
| dist/heading3.93606b9c.js | 1.29kb | +0.00b | 457.00ms | +47.00ms ⚠️ |
| dist/16.ab5c0088.js | 1.27kb | +0.00b | 478.00ms | +67.00ms ⚠️ |
| dist/emoji.e603e70e.js | 1.23kb | +0.00b | 458.00ms | +47.00ms ⚠️ |
| dist/16.afee1494.js | 1.23kb | +0.00b | 478.00ms | +66.00ms ⚠️ |
| dist/16.e60b4d77.js | 1.21kb | +0.00b | 479.00ms | +68.00ms ⚠️ |
| dist/16.7c7a40c9.js | 1.19kb | +0.00b | 478.00ms | +67.00ms ⚠️ |
| dist/16.06d5a67b.js | 1.18kb | +0.00b | 477.00ms | +66.00ms ⚠️ |
| dist/heading5.dde15cec.js | 1.17kb | +0.00b | 457.00ms | +47.00ms ⚠️ |
| dist/expand.6889aead.js | 1.16kb | +0.00b | 457.00ms | +47.00ms ⚠️ |
| dist/media-card-analytics-error-boundary.6a25b970.js | 1.15kb | +0.00b | 456.00ms | +47.00ms ⚠️ |
| dist/16.2096b9f3.js | 1.14kb | +0.00b | 479.00ms | +68.00ms ⚠️ |
| dist/16.f040d62d.js | 1.14kb | +0.00b | 478.00ms | +66.00ms ⚠️ |
| dist/16.ecf8a702.js | 1.13kb | +0.00b | 478.00ms | +66.00ms ⚠️ |
| dist/16.1b342686.js | 1.13kb | +0.00b | 478.00ms | +66.00ms ⚠️ |
| dist/16.2e7f52c6.js | 1.13kb | +0.00b | 478.00ms | +66.00ms ⚠️ |
| dist/16.da43aa07.js | 1.13kb | +0.00b | 478.00ms | +66.00ms ⚠️ |
| dist/heading2.e219309a.js | 1.11kb | +0.00b | 457.00ms | +46.00ms ⚠️ |
| dist/16.dd07505e.js | 1.10kb | +0.00b | 479.00ms | +68.00ms ⚠️ |
| dist/component.40194190.js | 1.07kb | +0.00b | 479.00ms | +68.00ms ⚠️ |
| dist/mention.b1828447.js | 1.07kb | +0.00b | 457.00ms | +46.00ms ⚠️ |
| dist/heading4.5316f6f2.js | 1.06kb | +0.00b | 457.00ms | +47.00ms ⚠️ |
| dist/16.317b9164.js | 1.05kb | +0.00b | 478.00ms | +67.00ms ⚠️ |
| dist/layout.ac6734f9.js | 1.05kb | +0.00b | 457.00ms | +46.00ms ⚠️ |
| dist/divider.d2be55a1.js | 1.03kb | +0.00b | 457.00ms | +46.00ms ⚠️ |
| dist/quote.f4e09143.js | 1.02kb | +0.00b | 457.00ms | +46.00ms ⚠️ |
| dist/action.cb287eb0.js | 1.00kb | +0.00b | 477.00ms | +66.00ms ⚠️ |
| dist/decision.91f3af14.js | 1010.00b | +0.00b | 477.00ms | +66.00ms ⚠️ |
| dist/panel-warning.68b04096.js | 1008.00b | +0.00b | 457.00ms | +46.00ms ⚠️ |
| dist/list.057cb664.js | 978.00b | +0.00b | 456.00ms | +45.00ms ⚠️ |
| dist/heading1.fa66b375.js | 976.00b | +0.00b | 457.00ms | +46.00ms ⚠️ |
| dist/panel-error.c4b05f6f.js | 906.00b | +0.00b | 456.00ms | +45.00ms ⚠️ |
| dist/panel.9dbc048e.js | 897.00b | +0.00b | 457.00ms | +46.00ms ⚠️ |
| dist/table.b35545be.js | 889.00b | +0.00b | 457.00ms | +46.00ms ⚠️ |
| dist/panel-success.7eb0809a.js | 845.00b | +0.00b | 457.00ms | +46.00ms ⚠️ |
| dist/panel-note.ec8386b7.js | 841.00b | +0.00b | 457.00ms | +46.00ms ⚠️ |
| dist/media-picker-analytics-error-boundary.553055f6.js | 837.00b | +0.00b | 456.00ms | +47.00ms ⚠️ |
| dist/media-card-analytics-error-boundary.964206cc.js | 833.00b | +0.00b | 456.00ms | +47.00ms ⚠️ |
| dist/media-card-analytics-error-boundary.57503222.js | 833.00b | +0.00b | 456.00ms | +47.00ms ⚠️ |
| dist/media-viewer-analytics-error-boundary.bbe40a02.js | 757.00b | +0.00b | 456.00ms | +47.00ms ⚠️ |
| dist/EmojiPickerComponent.a968dafe.js | 535.00b | +0.00b | 457.00ms | +47.00ms ⚠️ |
| dist/simpleHasher.f8e69464.js | 528.00b | +0.00b | 456.00ms | +46.00ms ⚠️ |
| dist/simpleHasher.32d9352e.js | 528.00b | +0.00b | 456.00ms | +47.00ms ⚠️ |
| dist/index.html | 119.00b | +0.00b | 481.00ms | +55.00ms ⚠️ |

</p></details>

<details><summary>Three.js x4 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/273293860736598540)**

**Comment by padmaia** [comment]
Originally I was thinking that I implemented checking the cache key in the main process in order to avoid serializing and sending the graph to the worker if it wasn't going to end up using it, but it looks like we create the shared reference regardless 🤷‍♀️ We could easily do that conditionally but ideally we will be able to avoid the serialization cost by implementing the graph in Rust (being explored right now but looks promising). Now that we are incorporating the config into the cache key it's probably best to do all that in the worker where the config would be used so we don't have to load it twice which can be costly in some cases (e.g. Babel since it not only loads the static config but all of the plugins too). I doubt it hurt performance but let's keep an eye on the performance tests to make sure.

**Comment by padmaia** [comment]
Also if we are checking the cache keys in the workers it makes sense to just write the bundles from there too.

**Comment by mischnic** [comment]
> Also if we are checking the cache keys in the workers it makes sense to just write the bundles from there too.

I think this doesn't work because we need to call `assignComplexNameHashes` between writing to cache and writing to disk.

**Comment by mischnic** [comment]
ak-editor, cached build with no changes:

```
v2
build . --no-minify --no-source-maps  8.11s user 1.39s system 178% cpu 5.318 total
build . --no-minify --no-source-maps  7.46s user 1.19s system 182% cpu 4.743 total
build . --no-minify --no-source-maps  8.14s user 1.38s system 182% cpu 5.205 total
build . --no-minify --no-source-maps  8.16s user 1.18s system 180% cpu 5.165 total


packager-loadConfig
build . --no-minify --no-source-maps  7.68s user 1.10s system 190% cpu 4.594 total
build . --no-minify --no-source-maps  8.79s user 1.31s system 193% cpu 5.214 total
build . --no-minify --no-source-maps  8.32s user 1.26s system 192% cpu 4.979 total
build . --no-minify --no-source-maps  8.36s user 1.29s system 192% cpu 5.017 total
```

**Review by padmaia — APPROVED** [review]
Looks good!

**Pull request merged**
