### PR TITLE
Fix sourceMappingURL for bundles with multiple entry points [CSS]

### PR DESCRIPTION
**Pull request by rynpsc**
# ↪️ Pull Request

Fixes incorrect sourcemap URL's when you have multiple entry points.

Related issue https://github.com/parcel-bundler/parcel/issues/2851

## 💻 Examples

Given the followong CLI command

`parcel build src/a/style.css src/b/style.css`

The following files are produced

```
dist/a/style.css /*# sourceMappingURL=/style.css.map */
dist/b/style.css /*# sourceMappingURL=/style.css.map */
```

The sourcemap URLs are incorrect they should be `/a/style.css.map` and `/b/style.css.map`.

With the fix in place we instead get:

```
dist/a/style.css /*# sourceMappingURL=/a/style.css.map */
dist/b/style.css /*# sourceMappingURL=/b/style.css.map */
```

The same issue was previously fixed with JavaScript sourcemaps https://github.com/parcel-bundler/parcel/pull/2645

## ✔️ PR Todo

- [x] Added/updated unit tests for this change
- [x] Filled out test instructions (In case there aren't any unit tests)
- [x] Included links to related issues/PRs

### CODE REVIEW

**Comment by rynpsc** [comment]
Have updated desciptions and added tests. Currently failing due to https://github.com/parcel-bundler/parcel/pull/2842.

**Comment by mischnic** [comment]
Now consistent with the logic in `JSPackager.js` 👍

**Comment by rynpsc** [comment]
@mischnic Noticed the check for the sourcemap comment was using JS syntax rather than CSS.

**Comment by mischnic** [comment]
> Noticed the check for the sourcemap comment was using JS syntax rather than CSS.

We really need to get CI working again.

Very picky comment: could you rename the vars in that test? (from `jsOutput`)

**Comment by sammckay10** [comment]
Has this been merged?!?

**Comment by mmcc** [comment]
I'm running into this exact issue and it appears this was approved, but closed instead of merged (unless I'm mistaken). Was that an accident?

**Pull request closed without merging**
