### PR TITLE
Tree shake dynamic imports

### PR DESCRIPTION
**Pull request by mischnic**
# ↪️ Pull Request

Closes https://github.com/parcel-bundler/parcel/issues/4318

These patterns are picked up by the transformer:
```js
let { x: y } = await import("./b.js");

({ x } = await import("./b.js"));

import("./b.js").then(({ a: b }) => console.log(b));

let ns = await import("./b.js");
console.log(ns.foo);

import("./b.js").then((ns) => console.log(ns.foo));
```

This works for tree shaking as well as excluding whole subgraphs via the bundler & symbol-propagation.

<br>

This also automatically throws errors if you try to import something that is guaranteed to be missing:

Bildschirmfoto 2020-11-19 um 23 50 07

### TODO:

- [x] Test for error message

### CODE REVIEW

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>Kitchen Sink ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 9.37s | -160.00ms |
| Cached | 2.06s | -100.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/parcel.d5807e82.webp | 102.94kb | +0.00b | 332.00ms | +39.00ms ⚠️ |
| dist/modern/parcel.d5807e82.webp | 102.94kb | +0.00b | 218.00ms | -99.00ms 🚀 |
| dist/modern/index.c851b754.js | 1.10kb | +0.00b | 3.02s | -198.00ms 🚀 |
| dist/modern/index.html | 701.00b | +0.00b | 3.18s | -181.00ms 🚀 |
| dist/modern/index.a76d6f77.css | 77.00b | +0.00b | 2.84s | -219.00ms 🚀 |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/parcel.d5807e82.webp | 102.94kb | +0.00b | 1.46s | -241.00ms 🚀 |
| dist/modern/parcel.d5807e82.webp | 102.94kb | +0.00b | 1.46s | -195.00ms 🚀 |
| dist/legacy/index.79101d60.js | 1.10kb | +0.00b | 1.73s | -124.00ms 🚀 |
| dist/modern/index.c851b754.js | 1.10kb | +0.00b | 1.73s | -87.00ms 🚀 |
| dist/legacy/index.html | 701.00b | +0.00b | 1.69s | -129.00ms 🚀 |
| dist/modern/index.html | 701.00b | +0.00b | 1.69s | -128.00ms 🚀 |
| dist/legacy/index.b6f8331e.css | 77.00b | +0.00b | 1.69s | -128.00ms 🚀 |
| dist/modern/index.a76d6f77.css | 77.00b | +0.00b | 1.53s | -188.00ms 🚀 |

</p></details>

<details><summary>React HackerNews ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 34.12s | -2.50s 🚀 |
| Cached | 2.09s | +23.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.js | 478.31kb | -4.92kb 🚀 | 14.72s | -412.00ms |
| dist/NotFound.efcc5e9b.js | 532.00b | +0.00b | 1.23s | -156.00ms 🚀 |
| dist/logo.24c8bf9e.png | 274.00b | +0.00b | 143.00ms | -42.00ms 🚀 |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.js | 478.31kb | -4.92kb 🚀 | 1.43s | +41.00ms |

</p></details>

<details><summary>AtlasKit Editor 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | 1.98m | +1.88m ⚠️ |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.cc40525d.js | 2.30mb | -18.17kb 🚀 | 1.70m | +1.68m ⚠️ |
| dist/pdfRenderer.c185dd8c.js | 1.11mb | +0.00b | 1.12m | +1.10m ⚠️ |
| dist/editorView.30cf4b8b.js | 587.39kb | +0.00b | 1.70m | +1.68m ⚠️ |
| dist/popup.36a19e03.js | 169.21kb | +148.00b ⚠️ | 1.12m | +1.10m ⚠️ |
| dist/EmojiPickerComponent.8d912556.js | 139.08kb | -747.00b 🚀 | 14.33s | +13.36s ⚠️ |
| dist/Toolbar.a86f03bd.js | 92.41kb | +0.00b | 1.22m | +1.21m ⚠️ |
| dist/media-viewer.02ddb3dd.js | 72.87kb | +0.00b | 21.54s | +20.53s ⚠️ |
| dist/card.12fe47e2.js | 53.81kb | +0.00b | 18.43s | +17.42s ⚠️ |
| dist/card.3a64ad9b.js | 51.57kb | +0.00b | 1.15m | +1.13m ⚠️ |
| dist/Modal.9b903897.js | 38.79kb | +0.00b | 7.91s | +7.16s ⚠️ |
| dist/component.42a949b6.js | 30.87kb | +0.00b | 4.59s | +3.69s ⚠️ |
| dist/esm.74ff7b72.js | 27.74kb | +263.00b ⚠️ | 16.04s | +15.06s ⚠️ |
| dist/component.22b0fde0.js | 22.51kb | +0.00b | 7.91s | +7.12s ⚠️ |
| dist/DatePicker.6f5e2cdb.js | 21.03kb | +0.00b | 14.33s | +13.35s ⚠️ |
| dist/smartMediaEditor.bcfaaa75.js | 16.93kb | +0.00b | 1.20m | +1.18m ⚠️ |
| dist/js.0c4ce585.js | 16.55kb | +0.00b | 7.91s | +7.12s ⚠️ |
| dist/dropzone.1f90c7da.js | 16.12kb | +0.00b | 1.15m | +1.13m ⚠️ |
| dist/ui.74b088fb.js | 14.11kb | +0.00b | 18.43s | +17.41s ⚠️ |
| dist/workerHasher.a22a1398.js | 11.90kb | +0.00b | 16.03s | +15.06s ⚠️ |
| dist/component.601a47de.js | 6.27kb | +0.00b | 8.68s | +7.90s ⚠️ |
| dist/card.fbae841f.js | 5.76kb | +0.00b | 18.43s | +17.42s ⚠️ |
| dist/media-viewer.09780698.js | 4.01kb | +0.00b | 21.54s | +20.52s ⚠️ |
| dist/EmojiPickerComponent.3548646f.js | 3.56kb | +0.00b | 16.04s | +15.03s ⚠️ |
| dist/png-chunks-extract.08e8af36.js | 3.55kb | +0.00b | 7.91s | +7.12s ⚠️ |
| dist/index.a3f66c21.css | 3.46kb | +0.00b | 1.24m | +1.23m ⚠️ |
| dist/dropzone.76b98afb.js | 3.44kb | +0.00b | 1.08m | +1.06m ⚠️ |
| dist/Modal.fca4b016.js | 3.15kb | +0.00b | 4.59s | +3.69s ⚠️ |
| dist/clipboard.ceeb8f8c.js | 2.97kb | +0.00b | 1.15m | +1.13m ⚠️ |
| dist/16.29c076d0.js | 2.49kb | +0.00b | 4.79s | +4.04s ⚠️ |
| dist/ResourcedEmojiComponent.cc7f53a2.js | 2.15kb | +0.00b | 18.43s | +17.41s ⚠️ |
| dist/card.b48be6f2.js | 2.15kb | +0.00b | 21.55s | +20.50s ⚠️ |
| dist/date.65bb6f77.js | 1.96kb | +0.00b | 1.70m | +1.68m ⚠️ |
| dist/images.f4282212.js | 1.90kb | +0.00b | 9.09s | +8.18s ⚠️ |
| dist/feedback.946661fe.js | 1.86kb | +0.00b | 14.32s | +13.34s ⚠️ |
| dist/16.6d4b938b.js | 1.86kb | +0.00b | 8.50s | +7.64s ⚠️ |
| dist/browser.43520266.js | 1.82kb | +0.00b | 1.70m | +1.68m ⚠️ |
| dist/16.07e17d98.js | 1.79kb | +0.00b | 55.92s | +55.09s ⚠️ |
| dist/workerHasher.0325314f.js | 1.75kb | +0.00b | 16.03s | +15.06s ⚠️ |
| dist/workerHasher.01f92ec8.js | 1.75kb | +0.00b | 1.15m | +1.14m ⚠️ |
| dist/list-number.605d56ab.js | 1.68kb | +0.00b | 9.09s | +8.15s ⚠️ |
| dist/status.69eb06af.js | 1.68kb | +0.00b | 9.74s | +8.80s ⚠️ |
| dist/code.3c7bf0dd.js | 1.61kb | +0.00b | 8.76s | +7.87s ⚠️ |
| dist/link.72eaa0b1.js | 1.53kb | +0.00b | 9.09s | +8.18s ⚠️ |
| dist/heading6.7a56e9b9.js | 1.53kb | +0.00b | 14.32s | +13.35s ⚠️ |
| dist/heading3.44db9957.js | 1.51kb | +0.00b | 9.88s | +8.94s ⚠️ |
| dist/16.2ac6f1f7.js | 1.51kb | +0.00b | 8.25s | +7.38s ⚠️ |
| dist/16.24210346.js | 1.46kb | +0.00b | 8.68s | +7.85s ⚠️ |
| dist/16.c087bab3.js | 1.46kb | +0.00b | 8.25s | +7.42s ⚠️ |
| dist/emoji.7fac1ca5.js | 1.45kb | +0.00b | 9.09s | +8.18s ⚠️ |
| dist/16.72a1f2e3.js | 1.45kb | +0.00b | 4.59s | +3.69s ⚠️ |
| dist/16.7871a52d.js | 1.44kb | +0.00b | 8.76s | +7.88s ⚠️ |
| dist/16.1a8644cf.js | 1.40kb | +0.00b | 8.76s | +7.88s ⚠️ |
| dist/heading5.7de42d71.js | 1.40kb | +0.00b | 9.88s | +8.91s ⚠️ |
| dist/expand.b1f08bc4.js | 1.38kb | +0.00b | 14.32s | +13.34s ⚠️ |
| dist/16.a1a8e6ae.js | 1.36kb | +0.00b | 8.50s | +7.62s ⚠️ |
| dist/16.abea8c40.js | 1.34kb | +0.00b | 4.59s | +3.69s ⚠️ |
| dist/heading2.b89a5450.js | 1.33kb | +0.00b | 9.88s | +8.94s ⚠️ |
| dist/16.29a7e88c.js | 1.32kb | +0.00b | 8.50s | +7.62s ⚠️ |
| dist/16.c7ded95d.js | 1.31kb | +0.00b | 8.76s | +7.87s ⚠️ |
| dist/media-card-analytics-error-boundary.ff849aa7.js | 1.30kb | +0.00b | 40.82s | +39.77s ⚠️ |
| dist/mention.51f20c83.js | 1.29kb | +0.00b | 9.42s | +8.48s ⚠️ |
| dist/heading4.f718f48c.js | 1.29kb | +0.00b | 9.88s | +8.93s ⚠️ |
| dist/Modal.df7b74de.js | 1.28kb | +0.00b | 7.91s | +7.12s ⚠️ |
| dist/16.0b71835a.js | 1.27kb | +0.00b | 4.59s | +3.69s ⚠️ |
| dist/layout.85f4f10e.js | 1.27kb | +0.00b | 9.09s | +8.18s ⚠️ |
| dist/16.4d524300.js | 1.27kb | +0.00b | 8.50s | +7.64s ⚠️ |
| dist/16.82077efb.js | 1.26kb | +0.00b | 8.25s | +7.42s ⚠️ |
| dist/16.d881cb16.js | 1.26kb | +0.00b | 8.25s | +7.38s ⚠️ |
| dist/16.ae604df2.js | 1.26kb | +0.00b | 8.25s | +7.38s ⚠️ |
| dist/16.1a3f7446.js | 1.26kb | +0.00b | 8.68s | +7.85s ⚠️ |
| dist/divider.a3b503cc.js | 1.25kb | +0.00b | 1.70m | +1.68m ⚠️ |
| dist/quote.07ebf058.js | 1.25kb | +0.00b | 9.74s | +8.81s ⚠️ |
| dist/component.9bdd6688.js | 1.23kb | +0.00b | 4.79s | +4.04s ⚠️ |
| dist/action.ad8dc9b0.js | 1.23kb | +0.00b | 8.76s | +7.87s ⚠️ |
| dist/16.7ed14d80.js | 1.23kb | +0.00b | 4.79s | +4.04s ⚠️ |
| dist/decision.0401e313.js | 1.21kb | +0.00b | 1.70m | +1.68m ⚠️ |
| dist/panel-warning.736ed649.js | 1.21kb | +0.00b | 9.74s | +8.81s ⚠️ |
| dist/16.e5321925.js | 1.18kb | +0.00b | 8.50s | +7.62s ⚠️ |
| dist/list.2f77057e.js | 1.18kb | +0.00b | 9.42s | +8.48s ⚠️ |
| dist/heading1.edaa8b50.js | 1.18kb | +0.00b | 9.88s | +8.94s ⚠️ |
| dist/panel-error.a4fdbb96.js | 1.11kb | +0.00b | 9.42s | +8.48s ⚠️ |
| dist/panel.4c093c14.js | 1.10kb | +0.00b | 9.74s | +8.81s ⚠️ |
| dist/table.70f6910c.js | 1.09kb | +0.00b | 9.74s | +8.79s ⚠️ |
| dist/media-picker-analytics-error-boundary.87a6efed.js | 1.05kb | +0.00b | 1.08m | +1.06m ⚠️ |
| dist/panel-success.d387a630.js | 1.05kb | +0.00b | 9.42s | +8.49s ⚠️ |
| dist/media-card-analytics-error-boundary.71c67c81.js | 1.05kb | +0.00b | 18.43s | +17.41s ⚠️ |
| dist/media-card-analytics-error-boundary.3605963d.js | 1.05kb | +0.00b | 1.15m | +1.14m ⚠️ |
| dist/panel-note.639e3cf0.js | 1.05kb | +0.00b | 9.42s | +8.48s ⚠️ |
| dist/media-viewer-analytics-error-boundary.cd02e050.js | 995.00b | +0.00b | 21.55s | +20.53s ⚠️ |
| dist/simpleHasher.7d3e36e5.js | 755.00b | +0.00b | 16.03s | +15.04s ⚠️ |
| dist/simpleHasher.a0d51de0.js | 755.00b | +0.00b | 1.20m | +1.18m ⚠️ |
| dist/index.html | 119.00b | +0.00b | 6.64s | +6.07s ⚠️ |

</p></details>

<details><summary>Three.js x4 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/282660149135409676)**

**Review by devongovett — APPROVED** [review]
Looks good. Should we also handle statically analyzable member expressions for dynamic import assignments/then calls like we now do for namespace imports?

```js
let x = await import('x');
x.foo();

import('x').then(x => x.foo());
```

**Comment by mischnic** [comment]
> Should we also handle statically analyzable member expressions for dynamic import assignments/then calls like we now do for namespace imports?

Done

**Review by devongovett — APPROVED** [review]
Looks good aside from the .only

**Pull request merged**
