### PR TITLE
handle app store url scheme

### PR DESCRIPTION
**Pull request by jdanyow**
saw this in the chat: https://parcel-bundler.slack.com/archives/C8B26V8RF/p1514579681000034

### CODE REVIEW

**Comment by leonardosnt** [comment]
Related: https://github.com/parcel-bundler/parcel/issues/437

Why not use `/^[\w-+.]*:/i` ? (or `^[a-z][\w-+.]*:`) It will handle more use cases.
> The scheme, consisting of a sequence of characters beginning with a letter and followed by any combination of letters, digits, plus (+), period (.), or hyphen (-)

https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Syntax

**Comment by hkwid** [comment]
According to here https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml
URI schema can include numbers like `z39.50`.

How about `/^[a-z][a-z0-9\+-\.]*:/i`?

BTW, for integration test, we can add `<a href="itms-apps://...">App Store Link</a>` to `test/integration/html/index.html`

```html
...
  <a href="tel:+33636757575">Tel link</a>
  <a href="itms-apps://itunes.apple.com/en/app/awesomeApp/id1234567890">App Store Link</a>
  <script src="index.js"></script>
...
```

**Comment by leonardosnt** [comment]
`\w` already cover alphanumeric (a-z0-9)

**Comment by hkwid** [comment]
@leonardosnt I guess `\w` is included `A-Z` too. URI schema seems like must be lowercase.

> Although schemes are case-insensitive, the canonical form is lowercase and documents that specify schemes must do so with lowercase letters. It is followed by a colon (:). Examples of popular schemes include http(s), ftp, mailto, file, data, and irc. URI schemes should be registered with the Internet Assigned Numbers Authority (IANA), although non-registered schemes are used in practice.
[https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Syntax](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier#Syntax)

**Comment by leonardosnt** [comment]
Yeah, you are right. \w also includes underscore. `a-z0-9` is better

**Pull request merged**
