### PR TITLE
Parcel 2: TypeScript Transformer

### PR DESCRIPTION
**Pull request by DeMoorJasper**
# ↪️ Pull Request

TS Transformer ported from Parcel 1 to Parcel 2

Not sure if we actually wanna implement it this way though, as Babel now supports TS and it would probably be a bit faster to create and transform the ast using babel/ts

Perhaps we should have both?

## ✔️ PR Todo

- [ ] Added/updated unit tests for this change
- [ ] Filled out test instructions (In case there aren't any unit tests)
- [ ] Included links to related issues/PRs

### CODE REVIEW

**Comment by mischnic** [comment]
> TS Transformer ported from Parcel 1 to Parcel 2
> 
> Not sure if we actually wanna implement it this way though, as Babel now supports TS and it would probably be a bit faster to create and transform the ast using babel/ts

One major misconception in the past was that Parcel doesn't do typechecking, I guess this won't be changed?

**Comment by DeMoorJasper** [comment]
@mischnic Parcel doesn't do typechecking. However it would be cool to have this feature in Parcel 2, that's the only reason I can think of to use ts-compiler

**Comment by devongovett** [comment]
@fathyb what do you think? I know people have been asking for [better typescript support](https://github.com/parcel-bundler/parcel/issues/1378), and one of those asks is support for actual type checking. I kinda think that type checking and linting (e.g. eslint) could be handled in a similar way: we compile synchronously, but type check/lint in the background. That way you don't have to wait as long for builds when you're just hacking, but have the type checking/linting information available if you want it. Thoughts?

**Comment by mischnic** [comment]
Coming from #2039, Parcel 1 basically ignored the `target` and `module` option in tsconfig.json.
I think it would be better for performance and DX to not run Babel after Typescript (by default), so that these option actually work (at least `target`, no sure about `module`).

**Comment by timfish** [comment]
Just be aware that if you use Babel with separate type checking, there is currently no support for:
- [`const enum`](https://github.com/babel/babel/issues/8741)
- `emitDecoratorMetadata` not supported out of the box

**Pull request closed without merging**
