### PR TITLE
Only serialize single AdjacencyList in graphs

### PR DESCRIPTION
**Pull request by thebriando**
# ↪️ Pull Request

Currently we serialize two AdjacencyLists in our graphs but we noticed a significant improvement when we only serialize a single AdjacencyList and derive one from the other.

## 💻 Examples

Serialization times and graph sizes from a large project:

* Serialize both adjacency lists (current behavior)
```
Bundle Graph Serialize Time: 1088 ms
Bundle Graph Serialize with Write Time: 1226 ms
Bundle Graph Deserialize Time: 1103 ms
Bundle Graph Deserialize and Write Time: 1442 ms
Bundle Graph Serialized Memory: 74.47 mb

Request Graph Serialize Time: 2765 ms
Request Graph Serialize with Write Time: 7583 ms
Request Graph Deserialize Time: 3387 ms
Request Graph Deserialize and Write Time: 4664 ms
Request Graph Serialized Memory: 205.81 mb
```

* Serialize `outboundEdges` and derive `inboundEdges` from `outboundEdges`
```
Bundle Graph Serialize Time: 774 ms
Bundle Graph Serialize with Write Time: 944 ms
Bundle Graph Deserialize Time: 1000 ms
Bundle Graph Deserialize and Write Time: 1418 ms
Bundle Graph Serialized Memory: 67.28 mb

Request Graph Serialize Time: 1870 ms
Request Graph Serialize with Write Time: 6169 ms
Request Graph Deserialize Time: 3082 ms
Request Graph Deserialize and Write Time: 4051 ms
Request Graph Serialized Memory: 166.88 mb
```

* Serialize `getAllEdges()`
```
Bundle Graph Serialize Time: 733 ms
Bundle Graph Serialize with Write Time: 914 ms
Bundle Graph Deserialize Time: 1026 ms
Bundle Graph Deserialize and Write Time: 1337 ms
Bundle Graph Serialized Memory: 73.00 mb

Request Graph Serialize Time: 3612 ms
Request Graph Serialize with Write Time: 7923 ms
Request Graph Deserialize Time: 3562 ms
Request Graph Deserialize and Write Time: 4137 ms
Request Graph Serialized Memory: 203.12 mb
```
## ✔️ PR Todo

- [ ] Added/updated unit tests for this change
- [ ] Filled out test instructions (In case there aren't any unit tests)
- [ ] Included links to related issues/PRs

### CODE REVIEW

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>Kitchen Sink ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 7.95s | -136.00ms |
| Cached | 487.00ms | +19.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/parcel.d5807e82.webp | 102.94kb | +0.00b | 463.00ms | -96.00ms 🚀 |
| dist/modern/parcel.d5807e82.webp | 102.94kb | +0.00b | 569.00ms | +86.00ms ⚠️ |
| dist/legacy/index.76ce4b0c.js | 1.12kb | +0.00b | 883.00ms | -64.00ms 🚀 |
| dist/modern/index.b43fcc94.js | 1.12kb | +0.00b | 630.00ms | +82.00ms ⚠️ |
| dist/legacy/index.html | 701.00b | +0.00b | 475.00ms | -87.00ms 🚀 |
| dist/modern/index.html | 701.00b | +0.00b | 627.00ms | +100.00ms ⚠️ |
| dist/legacy/index.44edca46.css | 77.00b | +0.00b | 883.00ms | -65.00ms 🚀 |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/parcel.d5807e82.webp | 102.94kb | +0.00b | 63.00ms | -23.00ms 🚀 |
| dist/legacy/index.76ce4b0c.js | 1.12kb | +0.00b | 79.00ms | -7.00ms 🚀 |
| dist/modern/index.b43fcc94.js | 1.12kb | +0.00b | 71.00ms | -14.00ms 🚀 |
| dist/legacy/index.html | 701.00b | +0.00b | 81.00ms | -5.00ms 🚀 |
| dist/modern/index.html | 701.00b | +0.00b | 79.00ms | -7.00ms 🚀 |
| dist/legacy/index.44edca46.css | 77.00b | +0.00b | 79.00ms | -7.00ms 🚀 |
| dist/modern/index.0bc656bc.css | 77.00b | +0.00b | 79.00ms | -6.00ms 🚀 |

</p></details>

<details><summary>React HackerNews ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 23.32s | -575.00ms |
| Cached | 784.00ms | +9.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.js | 477.81kb | +0.00b | 7.64s | -464.00ms 🚀 |
| dist/NotFound.f3269ae7.js | 542.00b | +0.00b | 324.00ms | +44.00ms ⚠️ |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/NotFound.f3269ae7.js | 542.00b | +0.00b | 120.00ms | -45.00ms 🚀 |

</p></details>

<details><summary>AtlasKit Editor ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 2.48m | -674.00ms |
| Cached | 3.31s | +55.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/popup.119ff481.js | 171.12kb | +0.00b | 15.34s | -1.62s 🚀 |
| dist/EmojiPickerComponent.c4358f76.js | 139.84kb | +0.00b | 11.20s | +626.00ms ⚠️ |
| dist/Toolbar.0c83bb49.js | 100.68kb | +0.00b | 15.51s | -1.08s 🚀 |
| dist/media-viewer.ebcb5e1e.js | 73.43kb | +0.00b | 11.53s | -787.00ms 🚀 |
| dist/card.df70c9b7.js | 54.67kb | +0.00b | 9.02s | -2.02s 🚀 |
| dist/card.1d931b4c.js | 52.43kb | +0.00b | 12.51s | -949.00ms 🚀 |
| dist/Modal.558fb5db.js | 39.59kb | +0.00b | 3.76s | -732.00ms 🚀 |
| dist/component.ad27194c.js | 31.05kb | +0.00b | 3.96s | +2.09s ⚠️ |
| dist/esm.e3419f0a.js | 27.83kb | +0.00b | 8.97s | -855.00ms 🚀 |
| dist/component.f25dcadb.js | 22.80kb | +0.00b | 3.76s | -725.00ms 🚀 |
| dist/DatePicker.faca45d0.js | 21.38kb | +0.00b | 8.92s | +1.82s ⚠️ |
| dist/smartMediaEditor.21f91ed8.js | 16.96kb | +0.00b | 15.39s | -1.08s 🚀 |
| dist/js.8167e2d5.js | 16.55kb | +0.00b | 3.76s | -725.00ms 🚀 |
| dist/dropzone.3ae9a030.js | 16.15kb | +0.00b | 15.08s | -1.59s 🚀 |
| dist/ui.15dd7acd.js | 14.30kb | +0.00b | 8.94s | -1.94s 🚀 |
| dist/workerHasher.bc6346e1.js | 11.90kb | +0.00b | 6.39s | -3.42s 🚀 |
| dist/component.677fad45.js | 6.23kb | +0.00b | 4.28s | +920.00ms ⚠️ |
| dist/card.3a4028bd.js | 5.74kb | +0.00b | 11.31s | -894.00ms 🚀 |
| dist/media-viewer.f15e56f4.js | 4.01kb | +0.00b | 10.03s | -2.33s 🚀 |
| dist/EmojiPickerComponent.4991ddd4.js | 3.68kb | +0.00b | 6.38s | -795.00ms 🚀 |
| dist/png-chunks-extract.608f438d.js | 3.56kb | +0.00b | 3.76s | -725.00ms 🚀 |
| dist/dropzone.d1e8004d.js | 3.46kb | +0.00b | 10.72s | -1.27s 🚀 |
| dist/index.ece3a13e.css | 3.46kb | +0.00b | 16.57s | -888.00ms 🚀 |
| dist/Modal.08282ab6.js | 3.23kb | +0.00b | 989.00ms | -2.08s 🚀 |
| dist/clipboard.6a6e5fbd.js | 3.00kb | +0.00b | 15.25s | -1.51s 🚀 |
| dist/16.b6ca7fd0.js | 2.50kb | +0.00b | 989.00ms | -879.00ms 🚀 |
| dist/ResourcedEmojiComponent.5046c0ff.js | 2.19kb | +0.00b | 7.34s | -3.53s 🚀 |
| dist/date.a69000aa.js | 1.97kb | +0.00b | 4.38s | -418.00ms 🚀 |
| dist/images.ece03ae5.js | 1.91kb | +0.00b | 4.38s | -564.00ms 🚀 |
| dist/feedback.facaac2e.js | 1.87kb | +0.00b | 5.92s | -1.15s 🚀 |
| dist/16.a9ea9b41.js | 1.86kb | +0.00b | 4.08s | -513.00ms 🚀 |
| dist/browser.8883c452.js | 1.85kb | +0.00b | 12.48s | -957.00ms 🚀 |
| dist/workerHasher.31326e89.js | 1.77kb | +0.00b | 8.91s | -893.00ms 🚀 |
| dist/workerHasher.d607e0b8.js | 1.77kb | +0.00b | 12.51s | -979.00ms 🚀 |
| dist/list-number.d4568b49.js | 1.69kb | +0.00b | 4.54s | -401.00ms 🚀 |
| dist/status.6595d133.js | 1.69kb | +0.00b | 4.70s | -499.00ms 🚀 |
| dist/code.efde0f48.js | 1.61kb | +0.00b | 4.26s | -540.00ms 🚀 |
| dist/link.5be155be.js | 1.54kb | +0.00b | 4.54s | -401.00ms 🚀 |
| dist/heading6.5a6082c8.js | 1.53kb | +0.00b | 4.82s | -525.00ms 🚀 |
| dist/heading3.1c92891c.js | 1.52kb | +0.00b | 4.82s | -511.00ms 🚀 |
| dist/16.07ccad90.js | 1.51kb | +0.00b | 4.08s | -482.00ms 🚀 |
| dist/16.02056ae6.js | 1.47kb | +0.00b | 3.91s | -655.00ms 🚀 |
| dist/emoji.b5624cf5.js | 1.46kb | +0.00b | 4.38s | -972.00ms 🚀 |
| dist/16.b7da7bde.js | 1.45kb | +0.00b | 989.00ms | -879.00ms 🚀 |
| dist/16.00100306.js | 1.44kb | +0.00b | 4.26s | -989.00ms 🚀 |
| dist/16.bdd61d2d.js | 1.41kb | +0.00b | 4.26s | -989.00ms 🚀 |
| dist/heading5.88bc6249.js | 1.41kb | +0.00b | 4.82s | -511.00ms 🚀 |
| dist/expand.4a483eb0.js | 1.39kb | +0.00b | 8.91s | +1.83s ⚠️ |
| dist/16.2a21d3f4.js | 1.34kb | +0.00b | 989.00ms | -879.00ms 🚀 |
| dist/heading2.22de70fe.js | 1.34kb | +0.00b | 4.82s | -512.00ms 🚀 |
| dist/16.c9db7e6b.js | 1.32kb | +0.00b | 4.26s | -989.00ms 🚀 |
| dist/mention.c44b48ed.js | 1.30kb | +0.00b | 4.54s | -552.00ms 🚀 |
| dist/heading4.a2524c70.js | 1.29kb | +0.00b | 4.82s | -511.00ms 🚀 |
| dist/Modal.44e980e0.js | 1.29kb | +0.00b | 3.76s | -725.00ms 🚀 |
| dist/16.9e97e787.js | 1.28kb | +0.00b | 989.00ms | -879.00ms 🚀 |
| dist/16.acff901d.js | 1.27kb | +0.00b | 4.08s | -513.00ms 🚀 |
| dist/component.233c7a65.js | 1.26kb | +0.00b | 3.96s | +888.00ms ⚠️ |
| dist/16.828b958e.js | 1.26kb | +0.00b | 4.08s | -482.00ms 🚀 |
| dist/16.b9b1643b.js | 1.26kb | +0.00b | 4.08s | -586.00ms 🚀 |
| dist/divider.ed7ccd2e.js | 1.26kb | +0.00b | 4.38s | -427.00ms 🚀 |
| dist/quote.b6d8bffb.js | 1.25kb | +0.00b | 4.70s | -499.00ms 🚀 |
| dist/media-card-analytics-error-boundary.ff0177b3.js | 1.25kb | +0.00b | 9.35s | -2.66s 🚀 |
| dist/action.01ec8983.js | 1.24kb | +0.00b | 4.26s | -538.00ms 🚀 |
| dist/16.458399e0.js | 1.23kb | +0.00b | 3.96s | +888.00ms ⚠️ |
| dist/decision.c48f9f1e.js | 1.22kb | +0.00b | 4.38s | -418.00ms 🚀 |
| dist/list.2dfe3f18.js | 1.19kb | +0.00b | 4.54s | -408.00ms 🚀 |
| dist/heading1.cc82b077.js | 1.19kb | +0.00b | 4.70s | -514.00ms 🚀 |
| dist/panel-error.7454ebc0.js | 1.12kb | +0.00b | 4.54s | -553.00ms 🚀 |
| dist/panel.fc70749c.js | 1.11kb | +0.00b | 4.70s | -499.00ms 🚀 |
| dist/table.77df779b.js | 1.10kb | +0.00b | 4.70s | -499.00ms 🚀 |
| dist/media-picker-analytics-error-boundary.49b32f4d.js | 1023.00b | +0.00b | 15.04s | -1.60s 🚀 |
| dist/media-card-analytics-error-boundary.9a500f44.js | 1019.00b | +0.00b | 8.95s | -2.04s 🚀 |
| dist/media-card-analytics-error-boundary.b884d580.js | 1019.00b | +0.00b | 12.51s | -957.00ms 🚀 |
| dist/media-viewer-analytics-error-boundary.83da5db2.js | 1015.00b | +0.00b | 10.06s | -1.71s 🚀 |
| dist/simpleHasher.79137cb4.js | 767.00b | +0.00b | 6.38s | -3.45s 🚀 |
| dist/simpleHasher.2c5206fd.js | 767.00b | +0.00b | 13.06s | -1.63s 🚀 |
| dist/index.html | 119.00b | +0.00b | 3.04s | +1.01s ⚠️ |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.e48a72e5.js | 2.46mb | -6.00b 🚀 | 665.00ms | +63.00ms ⚠️ |
| dist/card.1d931b4c.js | 52.43kb | +0.00b | 700.00ms | +36.00ms ⚠️ |
| dist/Modal.558fb5db.js | 39.59kb | +0.00b | 665.00ms | +63.00ms ⚠️ |
| dist/component.ad27194c.js | 31.05kb | +0.00b | 665.00ms | +63.00ms ⚠️ |
| dist/component.f25dcadb.js | 22.80kb | +0.00b | 555.00ms | -46.00ms 🚀 |
| dist/js.8167e2d5.js | 16.55kb | +0.00b | 555.00ms | -46.00ms 🚀 |
| dist/component.677fad45.js | 6.23kb | +0.00b | 555.00ms | -47.00ms 🚀 |
| dist/png-chunks-extract.608f438d.js | 3.56kb | +0.00b | 555.00ms | -46.00ms 🚀 |
| dist/Modal.08282ab6.js | 3.23kb | +0.00b | 545.00ms | -48.00ms 🚀 |
| dist/clipboard.6a6e5fbd.js | 3.00kb | +0.00b | 700.00ms | +36.00ms ⚠️ |
| dist/16.b6ca7fd0.js | 2.50kb | +0.00b | 545.00ms | -47.00ms 🚀 |
| dist/16.a9ea9b41.js | 1.86kb | +0.00b | 572.00ms | -39.00ms 🚀 |
| dist/browser.8883c452.js | 1.85kb | +0.00b | 700.00ms | +36.00ms ⚠️ |
| dist/16.89d45d15.js | 1.80kb | +0.00b | 564.00ms | -42.00ms 🚀 |
| dist/16.07ccad90.js | 1.51kb | +0.00b | 572.00ms | -39.00ms 🚀 |
| dist/16.00f25203.js | 1.47kb | +0.00b | 564.00ms | -42.00ms 🚀 |
| dist/16.02056ae6.js | 1.47kb | +0.00b | 564.00ms | -43.00ms 🚀 |
| dist/16.b7da7bde.js | 1.45kb | +0.00b | 545.00ms | -47.00ms 🚀 |
| dist/16.bdd61d2d.js | 1.41kb | +0.00b | 581.00ms | -31.00ms 🚀 |
| dist/16.fa5f411c.js | 1.36kb | +0.00b | 581.00ms | -30.00ms 🚀 |
| dist/16.2a21d3f4.js | 1.34kb | +0.00b | 545.00ms | -47.00ms 🚀 |
| dist/16.d10db5a3.js | 1.32kb | +0.00b | 581.00ms | -30.00ms 🚀 |
| dist/Modal.44e980e0.js | 1.29kb | +0.00b | 555.00ms | -46.00ms 🚀 |
| dist/16.9e97e787.js | 1.28kb | +0.00b | 545.00ms | -47.00ms 🚀 |
| dist/16.acff901d.js | 1.27kb | +0.00b | 572.00ms | -39.00ms 🚀 |
| dist/component.233c7a65.js | 1.26kb | +0.00b | 665.00ms | +63.00ms ⚠️ |
| dist/16.015dfb9d.js | 1.26kb | +0.00b | 564.00ms | -42.00ms 🚀 |
| dist/16.828b958e.js | 1.26kb | +0.00b | 578.00ms | -33.00ms 🚀 |
| dist/16.b9b1643b.js | 1.26kb | +0.00b | 572.00ms | -39.00ms 🚀 |
| dist/16.ec84a250.js | 1.26kb | +0.00b | 564.00ms | -42.00ms 🚀 |
| dist/16.458399e0.js | 1.23kb | +0.00b | 665.00ms | +63.00ms ⚠️ |
| dist/16.90358f40.js | 1.18kb | +0.00b | 581.00ms | -31.00ms 🚀 |
| dist/media-viewer-analytics-error-boundary.83da5db2.js | 1015.00b | +0.00b | 700.00ms | +35.00ms |
| dist/index.html | 119.00b | +0.00b | 546.00ms | +38.00ms ⚠️ |

</p></details>

<details><summary>Three.js ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 19.34s | -380.00ms |
| Cached | 622.00ms | -0.00ms |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/Three.js | 580.60kb | +0.00b | 108.00ms | -7.00ms 🚀 |

</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/295145169684005384)**

**Comment by mischnic** [comment]
Interesting, I remember Will saying some time ago that he investigated this and found that deriving one list from the other was slower than deserializing both.

**Comment by thebriando** [comment]
> Interesting, I remember Will saying some time ago that he investigated this and found that deriving one list from the other was slower than deserializing both.

😮   @wbinnssmith when was this?

**Comment by wbinnssmith** [comment]
I had eyeballed a few traces and cold build measurements and at the time it seemed that the current strategy (serializing both lists) outperformed what we had at the time (serializing an edge list). This is neither of those approaches, and it's more scientific, so I'm inclined to trust these results 😄

**Review by wbinnssmith — APPROVED** [review]
Awesome work 🙂

**Comment by thebriando** [comment]
Any thoughts before I merge? 🙂  @devongovett

**Pull request merged**
