### PR TITLE
Move testing to Github actions

### PR DESCRIPTION
**Pull request by DeMoorJasper**
# ↪️ Pull Request

This PR creates a GitHub Action that implements all steps that the Azure Devops pipeline had.

If we want to go this route we have to figure out why windows is not using babel-register as it should, besides that this PR implements the pipeline pretty much completely

### CODE REVIEW

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>Kitchen Sink ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 6.40s | +108.00ms |
| Cached | 2.34s | +52.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/parcel.d5807e82.webp | 102.94kb | +0.00b | 263.00ms | +86.00ms ⚠️ |
| dist/modern/parcel.d5807e82.webp | 102.94kb | +0.00b | 267.00ms | +89.00ms ⚠️ |
| dist/legacy/index.42516b4a.js | 1.10kb | +0.00b | 1.59s | +630.00ms ⚠️ |
| dist/modern/index.8a1ced31.js | 1.10kb | +0.00b | 1.59s | +1.07s ⚠️ |
| dist/legacy/index.html | 701.00b | +0.00b | 612.00ms | -260.00ms 🚀 |
| dist/modern/index.html | 701.00b | +0.00b | 610.00ms | -260.00ms 🚀 |
| dist/modern/index.e480862d.css | 77.00b | +0.00b | 1.38s | -147.00ms 🚀 |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/parcel.d5807e82.webp | 102.94kb | +0.00b | 290.00ms | +104.00ms ⚠️ |
| dist/modern/parcel.d5807e82.webp | 102.94kb | +0.00b | 289.00ms | +103.00ms ⚠️ |
| dist/legacy/index.42516b4a.js | 1.10kb | +0.00b | 513.00ms | +92.00ms ⚠️ |
| dist/modern/index.8a1ced31.js | 1.10kb | +0.00b | 512.00ms | +91.00ms ⚠️ |
| dist/legacy/index.html | 701.00b | +0.00b | 515.00ms | +92.00ms ⚠️ |
| dist/modern/index.html | 701.00b | +0.00b | 512.00ms | +91.00ms ⚠️ |
| dist/legacy/index.0e158b6b.css | 77.00b | +0.00b | 513.00ms | +92.00ms ⚠️ |
| dist/modern/index.e480862d.css | 77.00b | +0.00b | 512.00ms | +91.00ms ⚠️ |

</p></details>

<details><summary>React HackerNews ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 29.48s | +596.00ms |
| Cached | 2.35s | -55.00ms |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.js | 478.42kb | +0.00b | 292.00ms | -80.00ms 🚀 |
| dist/PermalinkedComment.c85d137d.js | 4.22kb | +0.00b | 290.00ms | -75.00ms 🚀 |
| dist/UserProfile.30e15baf.js | 1.62kb | +0.00b | 290.00ms | -74.00ms 🚀 |
| dist/NotFound.5aa6b041.js | 387.00b | +0.00b | 290.00ms | -75.00ms 🚀 |
| dist/logo.24c8bf9e.png | 274.00b | +0.00b | 240.00ms | -34.00ms 🚀 |

</p></details>

<details><summary>AtlasKit Editor ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 2.81m | -12.26s 🚀 |
| Cached | 5.11s | -108.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.4ca65e68.js | 2.73mb | -6.00b 🚀 | 1.61m | -7.04s 🚀 |
| dist/EmojiPickerComponent.bab709db.js | 97.89kb | +0.00b | 12.58s | -840.00ms 🚀 |
| dist/Toolbar.33a83ae3.js | 92.34kb | +0.00b | 57.94s | -45.59s 🚀 |
| dist/card.1007a95f.js | 52.86kb | +0.00b | 1.61m | +40.17s ⚠️ |
| dist/Modal.e3bd77d0.js | 41.40kb | +0.00b | 7.25s | +1.44s ⚠️ |
| dist/component.59edff1f.js | 30.78kb | +0.00b | 2.68s | +322.00ms ⚠️ |
| dist/component.37867f50.js | 22.51kb | +0.00b | 7.25s | +1.45s ⚠️ |
| dist/js.48be70a4.js | 16.40kb | +0.00b | 7.25s | +1.45s ⚠️ |
| dist/workerHasher.65b8a1b7.js | 11.78kb | +0.00b | 13.87s | -42.49s 🚀 |
| dist/EmojiTypeAheadComponent.9af6e5fc.js | 8.67kb | +0.00b | 12.89s | -43.47s 🚀 |
| dist/component.11476a92.js | 6.05kb | +0.00b | 7.25s | +1.45s ⚠️ |
| dist/EmojiPickerComponent.624bf3f4.js | 3.58kb | +0.00b | 53.58s | +42.46s ⚠️ |
| dist/index.393afe59.css | 3.46kb | +0.00b | 1.15m | +1.12m ⚠️ |
| dist/png-chunks-extract.8d15a914.js | 3.41kb | +0.00b | 7.25s | +1.45s ⚠️ |
| dist/Modal.2835744c.js | 3.08kb | +0.00b | 6.14s | +796.00ms ⚠️ |
| dist/16.d1b8e6f7.js | 2.38kb | +0.00b | 2.69s | +337.00ms ⚠️ |
| dist/EmojiUploadComponent.88a444df.js | 2.18kb | +0.00b | 12.89s | -43.47s 🚀 |
| dist/card.cadccd96.js | 2.03kb | +0.00b | 31.05s | +13.71s ⚠️ |
| dist/ResourcedEmojiComponent.d9a49606.js | 2.00kb | +0.00b | 6.09s | +742.00ms ⚠️ |
| dist/date.d49e64f8.js | 1.73kb | +0.00b | 7.80s | +1.38s ⚠️ |
| dist/16.f40c1329.js | 1.73kb | +0.00b | 7.66s | +1.39s ⚠️ |
| dist/images.80270b1f.js | 1.67kb | +0.00b | 7.89s | +1.36s ⚠️ |
| dist/16.86a8c7d4.js | 1.66kb | +0.00b | 8.20s | -577.00ms 🚀 |
| dist/feedback.8b7c7928.js | 1.64kb | +0.00b | 11.13s | +4.09s ⚠️ |
| dist/workerHasher.9bb425b1.js | 1.54kb | +0.00b | 12.89s | -43.47s 🚀 |
| dist/workerHasher.f66f00c7.js | 1.54kb | +0.00b | 1.61m | +40.00s ⚠️ |
| dist/list-number.4632b459.js | 1.46kb | +0.00b | 7.99s | +1.38s ⚠️ |
| dist/status.cccf04be.js | 1.46kb | +0.00b | 8.21s | +1.30s ⚠️ |
| dist/16.cff410ff.js | 1.38kb | +0.00b | 7.47s | +1.42s ⚠️ |
| dist/code.af9ca2b3.js | 1.38kb | +0.00b | 7.80s | +1.38s ⚠️ |
| dist/16.c1ed07f8.js | 1.33kb | +0.00b | 8.20s | -578.00ms 🚀 |
| dist/16.6603f2f3.js | 1.33kb | +0.00b | 7.47s | +1.42s ⚠️ |
| dist/16.a4b392c2.js | 1.32kb | +0.00b | 2.67s | +327.00ms ⚠️ |
| dist/16.249c644a.js | 1.31kb | +0.00b | 7.80s | +1.38s ⚠️ |
| dist/link.d12cc130.js | 1.30kb | +0.00b | 7.99s | +1.38s ⚠️ |
| dist/heading6.4c4017db.js | 1.30kb | +0.00b | 53.58s | +46.54s ⚠️ |
| dist/heading3.93606b9c.js | 1.29kb | +0.00b | 8.21s | +1.30s ⚠️ |
| dist/16.ab5c0088.js | 1.27kb | +0.00b | 7.66s | +1.39s ⚠️ |
| dist/emoji.e603e70e.js | 1.23kb | +0.00b | 7.89s | +1.36s ⚠️ |
| dist/16.afee1494.js | 1.23kb | +0.00b | 7.66s | +1.39s ⚠️ |
| dist/16.e60b4d77.js | 1.21kb | +0.00b | 2.67s | +327.00ms ⚠️ |
| dist/16.7c7a40c9.js | 1.19kb | +0.00b | 7.66s | +1.39s ⚠️ |
| dist/16.06d5a67b.js | 1.18kb | +0.00b | 7.80s | +1.38s ⚠️ |
| dist/heading5.dde15cec.js | 1.17kb | +0.00b | 53.58s | +46.54s ⚠️ |
| dist/expand.6889aead.js | 1.16kb | +0.00b | 11.13s | +4.10s ⚠️ |
| dist/16.2096b9f3.js | 1.14kb | +0.00b | 2.67s | +327.00ms ⚠️ |
| dist/16.f040d62d.js | 1.14kb | +0.00b | 7.47s | +1.42s ⚠️ |
| dist/16.ecf8a702.js | 1.13kb | +0.00b | 8.23s | -548.00ms 🚀 |
| dist/16.1b342686.js | 1.13kb | +0.00b | 7.47s | +1.42s ⚠️ |
| dist/16.2e7f52c6.js | 1.13kb | +0.00b | 7.47s | +1.42s ⚠️ |
| dist/16.da43aa07.js | 1.13kb | +0.00b | 8.20s | -577.00ms 🚀 |
| dist/heading2.e219309a.js | 1.11kb | +0.00b | 8.21s | +1.30s ⚠️ |
| dist/16.dd07505e.js | 1.10kb | +0.00b | 6.09s | +741.00ms ⚠️ |
| dist/component.40194190.js | 1.07kb | +0.00b | 6.09s | +741.00ms ⚠️ |
| dist/mention.b1828447.js | 1.07kb | +0.00b | 7.99s | +1.38s ⚠️ |
| dist/heading4.5316f6f2.js | 1.06kb | +0.00b | 53.58s | +46.54s ⚠️ |
| dist/16.317b9164.js | 1.05kb | +0.00b | 7.66s | +1.39s ⚠️ |
| dist/layout.ac6734f9.js | 1.05kb | +0.00b | 7.89s | +1.36s ⚠️ |
| dist/divider.d2be55a1.js | 1.03kb | +0.00b | 7.89s | +1.36s ⚠️ |
| dist/quote.f4e09143.js | 1.02kb | +0.00b | 8.10s | +1.35s ⚠️ |
| dist/action.cb287eb0.js | 1.00kb | +0.00b | 7.80s | +1.38s ⚠️ |
| dist/decision.91f3af14.js | 1010.00b | +0.00b | 7.89s | +1.36s ⚠️ |
| dist/panel-warning.68b04096.js | 1008.00b | +0.00b | 8.10s | +1.35s ⚠️ |
| dist/list.057cb664.js | 978.00b | +0.00b | 7.99s | +1.38s ⚠️ |
| dist/heading1.fa66b375.js | 976.00b | +0.00b | 8.21s | +1.30s ⚠️ |
| dist/panel-error.c4b05f6f.js | 906.00b | +0.00b | 7.99s | +1.37s ⚠️ |
| dist/panel.9dbc048e.js | 897.00b | +0.00b | 8.10s | +1.35s ⚠️ |
| dist/table.b35545be.js | 889.00b | +0.00b | 8.21s | +1.30s ⚠️ |
| dist/panel-success.7eb0809a.js | 845.00b | +0.00b | 8.10s | +1.35s ⚠️ |
| dist/panel-note.ec8386b7.js | 841.00b | +0.00b | 8.10s | +1.35s ⚠️ |
| dist/media-picker-analytics-error-boundary.553055f6.js | 837.00b | +0.00b | 54.35s | +20.23s ⚠️ |
| dist/media-card-analytics-error-boundary.57503222.js | 833.00b | +0.00b | 1.61m | +40.00s ⚠️ |
| dist/EmojiPickerComponent.a968dafe.js | 535.00b | +0.00b | 12.89s | +1.77s ⚠️ |
| dist/simpleHasher.32d9352e.js | 528.00b | +0.00b | 1.61m | +40.00s ⚠️ |
| dist/index.html | 119.00b | +0.00b | 892.00ms | -1.71m 🚀 |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.4ca65e68.js | 2.73mb | +0.00b | 536.00ms | -51.00ms 🚀 |
| dist/pdfRenderer.cd742f5e.js | 1.11mb | -3.00b 🚀 | 533.00ms | -50.00ms 🚀 |
| dist/editorView.ae59b49f.js | 585.98kb | +0.00b | 532.00ms | -51.00ms 🚀 |
| dist/popup.4a66e15e.js | 170.62kb | +0.00b | 533.00ms | -50.00ms 🚀 |
| dist/EmojiPickerComponent.bab709db.js | 97.89kb | +0.00b | 534.00ms | -50.00ms 🚀 |
| dist/Toolbar.33a83ae3.js | 92.34kb | +0.00b | 532.00ms | -51.00ms 🚀 |
| dist/media-viewer.1d9322e7.js | 69.09kb | +0.00b | 533.00ms | -50.00ms 🚀 |
| dist/card.ce67dc35.js | 55.09kb | +0.00b | 533.00ms | -51.00ms 🚀 |
| dist/card.1007a95f.js | 52.86kb | +0.00b | 533.00ms | -50.00ms 🚀 |
| dist/Modal.e3bd77d0.js | 41.40kb | +0.00b | 535.00ms | -52.00ms 🚀 |
| dist/component.59edff1f.js | 30.78kb | +0.00b | 536.00ms | -51.00ms 🚀 |
| dist/component.37867f50.js | 22.51kb | +0.00b | 535.00ms | -52.00ms 🚀 |
| dist/DatePicker.cbe44a9b.js | 21.17kb | +0.00b | 534.00ms | -50.00ms 🚀 |
| dist/EmojiPickerComponent.898d8be6.js | 18.23kb | +0.00b | 534.00ms | -50.00ms 🚀 |
| dist/js.48be70a4.js | 16.40kb | +0.00b | 535.00ms | -52.00ms 🚀 |
| dist/dropzone.c8c03b6a.js | 14.36kb | +0.00b | 533.00ms | -50.00ms 🚀 |
| dist/ui.cee430a3.js | 13.97kb | +0.00b | 533.00ms | -51.00ms 🚀 |
| dist/smartMediaEditor.7ee0079c.js | 13.95kb | +0.00b | 532.00ms | -51.00ms 🚀 |
| dist/workerHasher.65b8a1b7.js | 11.78kb | +0.00b | 533.00ms | -51.00ms 🚀 |
| dist/EmojiTypeAheadComponent.9af6e5fc.js | 8.67kb | +0.00b | 533.00ms | -51.00ms 🚀 |
| dist/component.11476a92.js | 6.05kb | +0.00b | 535.00ms | -52.00ms 🚀 |
| dist/card.4ac5c1b2.js | 5.61kb | +0.00b | 533.00ms | -51.00ms 🚀 |
| dist/media-viewer.bc661bce.js | 3.92kb | +0.00b | 533.00ms | -50.00ms 🚀 |
| dist/EmojiPickerComponent.624bf3f4.js | 3.58kb | +0.00b | 534.00ms | -50.00ms 🚀 |
| dist/index.393afe59.css | 3.46kb | +0.00b | 532.00ms | -52.00ms 🚀 |
| dist/png-chunks-extract.8d15a914.js | 3.41kb | +0.00b | 535.00ms | -52.00ms 🚀 |
| dist/dropzone.2f1a1e17.js | 3.23kb | +0.00b | 533.00ms | -50.00ms 🚀 |
| dist/Modal.2835744c.js | 3.08kb | +0.00b | 535.00ms | -52.00ms 🚀 |
| dist/clipboard.0244488f.js | 2.75kb | +0.00b | 533.00ms | -50.00ms 🚀 |
| dist/16.d1b8e6f7.js | 2.38kb | +0.00b | 535.00ms | -52.00ms 🚀 |
| dist/EmojiUploadComponent.88a444df.js | 2.18kb | +0.00b | 533.00ms | -51.00ms 🚀 |
| dist/card.cadccd96.js | 2.03kb | +0.00b | 533.00ms | -50.00ms 🚀 |
| dist/ResourcedEmojiComponent.d9a49606.js | 2.00kb | +0.00b | 536.00ms | -50.00ms 🚀 |
| dist/date.d49e64f8.js | 1.73kb | +0.00b | 534.00ms | -51.00ms 🚀 |
| dist/16.f40c1329.js | 1.73kb | +0.00b | 535.00ms | -51.00ms 🚀 |
| dist/images.80270b1f.js | 1.67kb | +0.00b | 535.00ms | -51.00ms 🚀 |
| dist/16.86a8c7d4.js | 1.66kb | +0.00b | 535.00ms | -52.00ms 🚀 |
| dist/feedback.8b7c7928.js | 1.64kb | +0.00b | 533.00ms | -51.00ms 🚀 |
| dist/browser.16c438d4.js | 1.61kb | +0.00b | 533.00ms | -50.00ms 🚀 |
| dist/workerHasher.9bb425b1.js | 1.54kb | +0.00b | 533.00ms | -51.00ms 🚀 |
| dist/workerHasher.f66f00c7.js | 1.54kb | +0.00b | 533.00ms | -50.00ms 🚀 |
| dist/list-number.4632b459.js | 1.46kb | +0.00b | 533.00ms | -52.00ms 🚀 |
| dist/status.cccf04be.js | 1.46kb | +0.00b | 533.00ms | -52.00ms 🚀 |
| dist/16.cff410ff.js | 1.38kb | +0.00b | 535.00ms | -51.00ms 🚀 |
| dist/code.af9ca2b3.js | 1.38kb | +0.00b | 534.00ms | -51.00ms 🚀 |
| dist/16.c1ed07f8.js | 1.33kb | +0.00b | 535.00ms | -52.00ms 🚀 |
| dist/16.6603f2f3.js | 1.33kb | +0.00b | 535.00ms | -52.00ms 🚀 |
| dist/16.a4b392c2.js | 1.32kb | +0.00b | 536.00ms | -51.00ms 🚀 |
| dist/16.249c644a.js | 1.31kb | +0.00b | 534.00ms | -52.00ms 🚀 |
| dist/link.d12cc130.js | 1.30kb | +0.00b | 533.00ms | -52.00ms 🚀 |
| dist/heading6.4c4017db.js | 1.30kb | +0.00b | 533.00ms | -51.00ms 🚀 |
| dist/heading3.93606b9c.js | 1.29kb | +0.00b | 533.00ms | -51.00ms 🚀 |
| dist/16.ab5c0088.js | 1.27kb | +0.00b | 535.00ms | -51.00ms 🚀 |
| dist/emoji.e603e70e.js | 1.23kb | +0.00b | 535.00ms | -50.00ms 🚀 |
| dist/16.afee1494.js | 1.23kb | +0.00b | 535.00ms | -51.00ms 🚀 |
| dist/16.e60b4d77.js | 1.21kb | +0.00b | 536.00ms | -51.00ms 🚀 |
| dist/16.7c7a40c9.js | 1.19kb | +0.00b | 535.00ms | -51.00ms 🚀 |
| dist/16.06d5a67b.js | 1.18kb | +0.00b | 534.00ms | -52.00ms 🚀 |
| dist/heading5.dde15cec.js | 1.17kb | +0.00b | 533.00ms | -51.00ms 🚀 |
| dist/expand.6889aead.js | 1.16kb | +0.00b | 533.00ms | -51.00ms 🚀 |
| dist/media-card-analytics-error-boundary.6a25b970.js | 1.15kb | +0.00b | 533.00ms | -50.00ms 🚀 |
| dist/16.2096b9f3.js | 1.14kb | +0.00b | 536.00ms | -51.00ms 🚀 |
| dist/16.f040d62d.js | 1.14kb | +0.00b | 535.00ms | -51.00ms 🚀 |
| dist/16.ecf8a702.js | 1.13kb | +0.00b | 535.00ms | -52.00ms 🚀 |
| dist/16.1b342686.js | 1.13kb | +0.00b | 535.00ms | -52.00ms 🚀 |
| dist/16.2e7f52c6.js | 1.13kb | +0.00b | 535.00ms | -51.00ms 🚀 |
| dist/16.da43aa07.js | 1.13kb | +0.00b | 535.00ms | -52.00ms 🚀 |
| dist/heading2.e219309a.js | 1.11kb | +0.00b | 533.00ms | -51.00ms 🚀 |
| dist/16.dd07505e.js | 1.10kb | +0.00b | 536.00ms | -51.00ms 🚀 |
| dist/component.40194190.js | 1.07kb | +0.00b | 536.00ms | -50.00ms 🚀 |
| dist/mention.b1828447.js | 1.07kb | +0.00b | 533.00ms | -52.00ms 🚀 |
| dist/heading4.5316f6f2.js | 1.06kb | +0.00b | 533.00ms | -51.00ms 🚀 |
| dist/16.317b9164.js | 1.05kb | +0.00b | 535.00ms | -51.00ms 🚀 |
| dist/layout.ac6734f9.js | 1.05kb | +0.00b | 535.00ms | -50.00ms 🚀 |
| dist/divider.d2be55a1.js | 1.03kb | +0.00b | 534.00ms | -51.00ms 🚀 |
| dist/quote.f4e09143.js | 1.02kb | +0.00b | 533.00ms | -52.00ms 🚀 |
| dist/action.cb287eb0.js | 1.00kb | +0.00b | 534.00ms | -52.00ms 🚀 |
| dist/decision.91f3af14.js | 1010.00b | +0.00b | 534.00ms | -51.00ms 🚀 |
| dist/panel-warning.68b04096.js | 1008.00b | +0.00b | 533.00ms | -52.00ms 🚀 |
| dist/list.057cb664.js | 978.00b | +0.00b | 533.00ms | -52.00ms 🚀 |
| dist/heading1.fa66b375.js | 976.00b | +0.00b | 533.00ms | -51.00ms 🚀 |
| dist/panel-error.c4b05f6f.js | 906.00b | +0.00b | 533.00ms | -52.00ms 🚀 |
| dist/panel.9dbc048e.js | 897.00b | +0.00b | 533.00ms | -52.00ms 🚀 |
| dist/table.b35545be.js | 889.00b | +0.00b | 533.00ms | -51.00ms 🚀 |
| dist/panel-success.7eb0809a.js | 845.00b | +0.00b | 533.00ms | -52.00ms 🚀 |
| dist/panel-note.ec8386b7.js | 841.00b | +0.00b | 533.00ms | -52.00ms 🚀 |
| dist/media-picker-analytics-error-boundary.553055f6.js | 837.00b | +0.00b | 533.00ms | -50.00ms 🚀 |
| dist/media-card-analytics-error-boundary.964206cc.js | 833.00b | +0.00b | 533.00ms | -51.00ms 🚀 |
| dist/media-card-analytics-error-boundary.57503222.js | 833.00b | +0.00b | 533.00ms | -50.00ms 🚀 |
| dist/media-viewer-analytics-error-boundary.bbe40a02.js | 757.00b | +0.00b | 533.00ms | -50.00ms 🚀 |
| dist/EmojiPickerComponent.a968dafe.js | 535.00b | +0.00b | 534.00ms | -50.00ms 🚀 |
| dist/simpleHasher.f8e69464.js | 528.00b | +0.00b | 533.00ms | -51.00ms 🚀 |
| dist/simpleHasher.32d9352e.js | 528.00b | +0.00b | 532.00ms | -51.00ms 🚀 |
| dist/index.html | 119.00b | +0.00b | 538.00ms | -60.00ms 🚀 |

</p></details>

<details><summary>Three.js x4 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/271406868562182669)**

**Comment by mischnic** [comment]
Does a fail still block merging a PR?

If yes, do all of them (pull_request + push) need to be passing? With Azure, somehow only the PR jobs (not the commit jobs) were displayed in this section...

**Comment by DeMoorJasper** [comment]
@mischnic yes if anything fails the merge is blocked, this is a global setting for all checks so any check that fails blocks merge regardless of it's origin.

Personally I think this is better than Azure as you see all checks triggered by the commit. Best thing I can do if this annoys you is disable it for all branches except v2?

**Comment by mischnic** [comment]
> Best thing I can do if this annoys you is disable it for all branches except v2?

Yeah, I was thinking of adding to this to `on`:
```
branches:
	- v2
```

**Comment by DeMoorJasper** [comment]
@mischnic exactly what I was thinking, updated the config accordingly

**Review by jimbojr55 — COMMENTED** [review]
jump

**Pull request closed without merging**
