### PR TITLE
SASS add included files

### PR DESCRIPTION
**Pull request by mischnic**
# ↪️ Pull Request

Will take effect after https://github.com/parcel-bundler/parcel/issues/3708 is fixed

Closes https://github.com/parcel-bundler/parcel/issues/4127

### CODE REVIEW

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>packages/benchmarks/kitchen-sink ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 4.38s | -354.00ms 🚀 |
| Cached | 4.11s | +421.00ms ⚠️ |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/parcel.a2ee7a0b.webp | 102.94kb | +0.00b | 106.00ms | -23.00ms 🚀 |
| dist/index.js | 1.07kb | +5.00b ⚠️ | 249.00ms | -27.00ms 🚀 |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/parcel.a2ee7a0b.webp | 102.94kb | +0.00b | 482.00ms | +470.00ms ⚠️ |
| dist/index.js | 1.07kb | +5.00b ⚠️ | 488.00ms | +470.00ms ⚠️ |

</p></details>

<details><summary>packages/benchmarks/react-hn ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 9.46s | -359.00ms |
| Cached | 3.97s | -120.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.js | 64.04kb | +397.00b ⚠️ | 1.35s | -30.00ms |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.js | 64.04kb | +397.00b ⚠️ | 475.00ms | -2.00ms |

</p></details>

<details><summary>packages/benchmarks/ak-editor ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 4.92s | +390.00ms ⚠️ |
| Cached | 3.55s | -290.00ms 🚀 |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.js | 743.00b | +7.00b ⚠️ | 222.00ms | +9.00ms |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.js | 743.00b | +7.00b ⚠️ | 17.00ms | -0.00ms |

</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/257345786432455178)**

**Comment by LiadIdan** [comment]
@mischnic thanks for the quick fix! Is there a way I can use it until #3708 is fixed? I've tried to add the `--no-cache` flag, but it seems not doing much since it still generates a `.parcel-cache` folder

**Comment by mischnic** [comment]
--no-cache is indeed a workaround

You can think of that flag as "don't use the cache", but it is still created because it is used for IPC with the workers.

**Comment by LiadIdan** [comment]
Well I just tried it in nightly.105 version and it's not working :confused:

**Comment by mischnic** [comment]
`parcel build index.html --no-cache` "works"
`parcel index.html --no-cache` doesn't

**Comment by LiadIdan** [comment]
Oh got you, I looked for a way to trigger the HMR in dev mode. I guess the only option for now is to use v1?

**Pull request merged**
