### PR TITLE
Add Travis, Prettier, Contribution docs, and init Flow

### PR DESCRIPTION
**Pull request by thejameskyle**
cc @aweary

### CODE REVIEW

**Comment by thejameskyle** [comment]
@devongovett broke it into separate commits so you can review them individually if you'd like.

@aweary I added `// @flow` to a bunch of the main files, but I just put `any` in a bunch of spots. You can just search for these to fill them out

**Comment by devongovett** [comment]
@thejameskyle want to rebase? would be good to get prettier in

**Comment by thejameskyle** [comment]
I'm going to cherry pick Prettier in. There's a lot of work to get Flow in because we need to be able to run Babel.

**Comment by brandon93s** [comment]
Travis, Prettier, and Contributing.md have all landed. Getting `Flow` in with these conflicts is going to be a mess. Closing for now to clean up PRs.

**Pull request closed without merging**
