### PR TITLE
temp disable debug option - until elm compiler issue is fixed

### PR DESCRIPTION
**Pull request by Maxim-Filimonov**
See https://github.com/parcel-bundler/parcel/issues/2104#issuecomment-461707960
Waiting for https://github.com/elm/compiler/issues/1851 to be resolved.

### CODE REVIEW

**Comment by domenkozar** [comment]
@kyasu1 do you have  `Attribute` inside a `Msg`? Or something else like `Array`?

I don't think it makes sense to disable a feature due to a bug in compiler in a very edge case. 

I do think we should allow such users to opt-out, maybe with additional flag/setting to disable debugger?

**Comment by domenkozar** [comment]
There is also a possible fix in https://github.com/elm/compiler/pull/1850 that needs testing.

**Comment by kyasu1** [comment]
@domenkozar I myself not using such Msg types but the dependency packages might be. I think this bug arises pretty common when projects are getting complex and large. 

I can't test the compiler fix you mentioned, out of my skill , but it may take long time until fully tested and merged. For that period we are no able to use `parceljs` for developing if we experience that bug.

So I think disabling this option temporally is much easier and feasible at the moment. And I more like debugging with `Debug.log` than the Time travel debugger...

**Comment by domenkozar** [comment]
Note that you can downgrade to 1.10.3 for now, which didn't have debugger on. You'll need to use https://www.npmjs.com/package/parcel-plugin-elm-hot for HMR, but that's easy to wire up. Does that resolve your problem?

**Comment by kyasu1** [comment]
Thank you for telling me about the workaround, it works perfectly ! Actually this is not the issue of `parceljs`, so I do not insist to apply this patch. Hopefully the bug in `elm/compiler` will be fixed soon...

**Comment by sklirg** [comment]
Would it be possible to add a feature flag for this instead? So users can opt in/out if this at will. E.g. an env variable `PARCEL_ELM_DEBUG=bool` or a CLI flag like `--disable-debug`.

**Comment by Maxim-Filimonov** [comment]
@sklirg what's the use case of disabling it ? Beyond the compiler issue.

**Comment by sklirg** [comment]
That's exactly the use case. I'd like my code to compile without having to downgrade parcel.

Currently I monkey-patch it locally by editing the file in node modules...

**Comment by lzrski** [comment]
The env variable solution suggested by @sklirg (https://github.com/parcel-bundler/parcel/pull/2626) sounds very reasonable. There is no need to extend the CLI or even document it anywhere. It can be retired as soon as Elm compiler is fixed (which can take a long time). 

On the other hand there may be legitimate reasons to disable debugger anyway - e.g. I'm working on an app that subscribes to animation frames all the time and I'm getting hundreds of thousands of messages that take up memory and are not very useful anyway. In this case I would be happy to disable debugger even with the compiler fixed.

**Comment by Punie** [comment]
The way the elm debugger works at the moment is kinda annoying in some cases (even without accounting for the compiler bug).
It injects a `div` in the page that can cause some layout issues that can be a pain to debug.

I would be strongly in favour of a cli flag for disabling the debugger, as that is something that some people might want to do event after the compiler bug is resolved.

**Comment by sklirg** [comment]
I opened #2818 with my fix since some of you guys seemed interested in it. 👍

**Comment by Maxim-Filimonov** [comment]
@domenkozar Just thinking out loud about this. 
Would you be open to considering the possibility of allowing to pass arguments through parcel to a compiler used? 
[Similar](https://github.com/wking-io/elm-live#adding-the-debugger-during-dev) to elm-live approach to passing extra arguments to elm compiler.

This way precise customization of tool can still be possible via additional parameters without need to change parcel's code.

**Comment by DeMoorJasper** [comment]
Closing in favor of #2818

**Pull request closed without merging**
