### PR TITLE
Fix: set pragmafrag for jsx in v2

### PR DESCRIPTION
**Pull request by kirillrogovoy**
# ↪️ Pull Request

I discovered the issue while tracking down https://github.com/parcel-bundler/parcel/issues/3446 here: https://github.com/parcel-bundler/parcel/issues/3446#issuecomment-539488515.

AFAIK, the issue has been solved in v1 with https://github.com/parcel-bundler/parcel/pull/2486, so I decided to port it to v2 as is.

## ✔️ PR Todo

- [ ] Added/updated unit tests for this change
- [ ] Filled out test instructions (In case there aren't any unit tests)
- [x] Included links to related issues/PRs

### CODE REVIEW

**Comment by mischnic** [comment]
Preact 10 now has support for fragments as well, could you that as well (with autodetection just as `JSX_PRAGMA`, but for fragments with values for React and Preact)
```js
// preact
['@babel/plugin-transform-react-jsx', { pragma: 'h', pragmaFrag: 'Fragment' }],
```

**Comment by kirillrogovoy** [comment]
I guess you mean this. :)

**Comment by devongovett** [comment]
Would be great to add a test for this, if you don't mind making a followup PR. 😄

**Comment by kirillrogovoy** [comment]
Sure! Hang on for a bit.

**Pull request merged**
