### PR TITLE
Add website icon to repl

### PR DESCRIPTION
**Pull request by hai-x**
# ↪️ Pull Request

Add website icon to repl.

## ✔️ PR Todo

- [ ] Added/updated unit tests for this change
- [ ] Filled out test instructions (In case there aren't any unit tests)
- [ ] Included links to related issues/PRs

### CODE REVIEW

**Comment by hai-x** [comment]
i wonder how to preview this pr by `pr-{{PR_NUMBER}}.repl.parceljs.org` ?

**Comment by mischnic** [comment]
That is unfortunately not possible right now. For security reasons, Github Action Secrets are not available to external contributors (because you could theoretically change the GH action to extract our Vercel token used to publish that website)

**Comment by hai-x** [comment]
> That is unfortunately not possible right now. For security reasons, Github Action Secrets are not available to external contributors (because you could theoretically change the GH action to extract our Vercel token used to publish that website)

Thanks for your answer. It's okay.

**Review by mischnic — APPROVED** [review]
Thanks!

**Pull request merged**
