### PR TITLE
Make it possible to exclude a common target

### LINKED ISSUE #4035: parcel v2 - Error: Got unexpected undefined
# 🐛 bug report

While testing out parcel v2 I ran into a fatal build error with an internal-looking failure.

## 🎛 Configuration (.babelrc, package.json, cli command)

**CLI**
`parcel watch ./src/ui/index.html`

**package.json**
```json
{
  "targets": {
    "browser": {"publicUrl": "/app"}
  }
}
```

**babelrc**
```js
module.exports = {
  presets: ['@babel/preset-env'],
  plugins: [['@babel/plugin-transform-react-jsx', {pragma: 'h'}]],
};
```

## 🤔 Expected Behavior

It builds the project or provides an error message as to what is wrong with my configuration.

## 😯 Current Behavior

It fails with an internal undefined error message.

```
Error: Got unexpected undefined
    at nullthrows (/Users/patrick/Code/OpenSource/lighthouse-ci/node_modules/nullthrows/nullthrows.js:7:15)
    at RequestGraph.removeById (/Users/patrick/Code/OpenSource/lighthouse-ci/node_modules/@parcel/core/lib/Graph.js:188:40)
    at RequestTracker.untrackRequest (/Users/patrick/Code/OpenSource/lighthouse-ci/node_modules/@parcel/core/lib/RequestTracker.js:284:16)
    at AssetGraphBuilder.handleNodeRemovedFromAssetGraph (/Users/patrick/Code/OpenSource/lighthouse-ci/node_modules/@parcel/core/lib/AssetGraphBuilder.js:279:27)
    at AssetGraph.onNodeRemoved (/Users/patrick/Code/OpenSource/lighthouse-ci/node_modules/@parcel/core/lib/AssetGraphBuilder.js:107:35)
    at AssetGraph.removeNode (/Users/patrick/Code/OpenSource/lighthouse-ci/node_modules/@parcel/core/lib/AssetGraph.js:138:32)
    at AssetGraph.removeEdge (/Users/patrick/Code/OpenSource/lighthouse-ci/node_modules/@parcel/core/lib/Graph.js:215:12)
    at AssetGraph.removeNode (/Users/patrick/Code/OpenSource/lighthouse-ci/node_modules/@parcel/core/lib/Graph.js:179:14)
    at AssetGraph.removeNode (/Users/patrick/Code/OpenSource/lighthouse-ci/node_modules/@parcel/core/lib/AssetGraph.js:139:18)
    at AssetGraph.removeEdge (/Users/patrick/Code/OpenSource/lighthouse-ci/node_modules/@parcel/core/lib/Graph.js:215:12)
```

## 🔦 Context

Trying to help test out parcel v2 :)

## 💻 Code Sample

https://github.com/GoogleChrome/lighthouse-ci/tree/parcelv2/packages/server

in repo root, run `yarn` and then `yarn build:watch`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-alpha.3.2 |
| Node             | v10.15.3 |
| npm/Yarn         | 
| Operating System | macOS |

### PR DESCRIPTION
**Pull request by mischnic**
# ↪️ Pull Request

An escape hatch from out current approach of completely taking over `package.json` 😄 

Closes #4035

(yarn.lock was somehow outdated)

## 💻 Examples

```json
{
  "main": "server.js",
  "app": "dist/index.js",
  "engines": {
    "node": ">= 8.0.0"
  },
  "targets": {
    "main": false,
    "app": {}
  }
}
```

### CODE REVIEW

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>packages/benchmarks/kitchen-sink ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 5.98s | +188.00ms |
| Cached | 3.22s | +526.00ms ⚠️ |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/modern/index.css | 29.00b | +0.00b | 1.16s | +116.00ms ⚠️ |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/parcel.ff215454.webp | 102.94kb | +0.00b | 14.00ms | +3.00ms ⚠️ |
| dist/modern/parcel.76ee4591.webp | 102.94kb | +0.00b | 12.00ms | +3.00ms ⚠️ |
| dist/legacy/index.js | 519.00b | +0.00b | 19.00ms | +4.00ms ⚠️ |
| dist/modern/index.js | 452.00b | +0.00b | 14.00ms | +3.00ms ⚠️ |
| dist/legacy/index.css | 29.00b | +0.00b | 13.00ms | +3.00ms ⚠️ |
| dist/modern/index.css | 29.00b | +0.00b | 12.00ms | +3.00ms ⚠️ |

</p></details>

<details><summary>packages/benchmarks/react-hn ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 8.55s | +99.00ms |
| Cached | 3.38s | -225.00ms 🚀 |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/module/index.js | 34.33kb | +0.00b | 260.00ms | -27.00ms 🚀 |
| dist/main/index.js | 34.31kb | +0.00b | 265.00ms | -27.00ms 🚀 |

</p></details>

<details><summary>packages/benchmarks/ak-editor ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 2.72m | -5.17s |
| Cached | 5.39s | -126.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.js | 2.33mb | +4.00b ⚠️ | 1.57m | -5.36s 🚀 |
| dist/media-viewer.81fbeba4.js | 87.56kb | +0.00b | 5.56s | -921.00ms 🚀 |
| dist/card.c0473744.js | 76.88kb | +0.00b | 5.56s | -921.00ms 🚀 |
| dist/popup.e0094d89.js | 12.82kb | +0.00b | 1.57m | -5.51s 🚀 |
| dist/card.f99e1597.js | 5.92kb | +0.00b | 11.55s | -1.42s 🚀 |
| dist/ResourcedEmojiComponent.2d80adbd.js | 2.25kb | +0.00b | 5.54s | -914.00ms 🚀 |
| dist/card.2c902906.js | 1.73kb | +0.00b | 11.54s | -1.41s 🚀 |
| dist/card.aae6ebb9.js | 1.04kb | +0.00b | 11.54s | -1.41s 🚀 |
| dist/media-viewer-analytics-error-boundary.dd752a9e.js | 779.00b | +0.00b | 11.54s | -1.41s 🚀 |
| dist/esm.976debcc.js | 180.00b | +0.00b | 5.51s | -891.00ms 🚀 |
| dist/dropzone.976debcc.js | 179.00b | +1.00b ⚠️ | 10.23s | -24.21s 🚀 |
| dist/clipboard.976debcc.js | 179.00b | +1.00b ⚠️ | 36.05s | +924.00ms |
| dist/browser.976debcc.js | 179.00b | +1.00b ⚠️ | 53.77s | +18.64s ⚠️ |
| dist/editorView.976debcc.js | 179.00b | -1.00b 🚀 | 35.10s | -17.14s 🚀 |
| dist/media-card-analytics-error-boundary.976debcc.js | 178.00b | -5.00b 🚀 | 36.74s | +25.59s ⚠️ |
| dist/16.976debcc.js | 176.00b | -5.00b 🚀 | 35.57s | -102.00ms |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.js | 2.33mb | +4.00b ⚠️ | 260.00ms | +3.00ms |
| dist/pdfRenderer.85e56a51.js | 1.11mb | +0.00b | 157.00ms | -33.00ms 🚀 |
| dist/smartMediaEditor.678dca17.js | 602.09kb | +0.00b | 118.00ms | -8.00ms 🚀 |
| dist/popup.cc1a1fa6.js | 286.25kb | +0.00b | 149.00ms | -35.00ms 🚀 |
| dist/EmojiPickerComponent.6fc09ddc.js | 105.94kb | +0.00b | 113.00ms | -38.00ms 🚀 |
| dist/Toolbar.93d205ef.js | 105.59kb | +0.00b | 111.00ms | -7.00ms 🚀 |
| dist/media-viewer.81fbeba4.js | 87.56kb | +0.00b | 146.00ms | -34.00ms 🚀 |
| dist/card.c0473744.js | 76.88kb | +0.00b | 147.00ms | -34.00ms 🚀 |
| dist/ui.ab1a2648.js | 73.75kb | +0.00b | 112.00ms | -8.00ms 🚀 |
| dist/smartMediaEditor.25b0ed57.js | 67.38kb | +0.00b | 111.00ms | -8.00ms 🚀 |
| dist/component.10b390dc.js | 46.04kb | +0.00b | 138.00ms | -33.00ms 🚀 |
| dist/DatePicker.0242ec52.js | 27.54kb | +0.00b | 112.00ms | -36.00ms 🚀 |
| dist/EmojiPickerComponent.e7c7bb11.js | 26.86kb | +0.00b | 112.00ms | -37.00ms 🚀 |
| dist/popup.a41a3cbc.js | 22.35kb | +0.00b | 139.00ms | -33.00ms 🚀 |
| dist/popup.aac4042c.js | 21.82kb | +0.00b | 139.00ms | -34.00ms 🚀 |
| dist/popup.0bcf5c74.js | 20.84kb | +0.00b | 138.00ms | -34.00ms 🚀 |
| dist/js.16f29da2.js | 16.29kb | +0.00b | 140.00ms | -34.00ms 🚀 |
| dist/popup.e0094d89.js | 12.82kb | +0.00b | 139.00ms | -34.00ms 🚀 |
| dist/workerHasher.d7e20c98.js | 11.57kb | +0.00b | 110.00ms | -10.00ms 🚀 |
| dist/EmojiTypeAheadComponent.1c09c30d.js | 10.44kb | +0.00b | 111.00ms | -36.00ms 🚀 |
| dist/card.f99e1597.js | 5.92kb | +0.00b | 141.00ms | -34.00ms 🚀 |
| dist/component.a26e593f.js | 5.62kb | +0.00b | 137.00ms | -33.00ms 🚀 |
| dist/index.css | 3.38kb | +0.00b | 98.00ms | -9.00ms 🚀 |
| dist/component.8fa44754.js | 3.38kb | +0.00b | 137.00ms | -34.00ms 🚀 |
| dist/png-chunks-extract.3d8d8594.js | 3.33kb | +0.00b | 140.00ms | -34.00ms 🚀 |
| dist/EmojiUploadComponent.0460cc59.js | 2.92kb | +0.00b | 111.00ms | -37.00ms 🚀 |
| dist/component.ab65829f.js | 2.30kb | +0.00b | 137.00ms | -33.00ms 🚀 |
| dist/ResourcedEmojiComponent.2d80adbd.js | 2.25kb | +0.00b | 144.00ms | -34.00ms 🚀 |
| dist/media-picker-analytics-error-boundary.0f11d632.js | 1.85kb | +0.00b | 139.00ms | -34.00ms 🚀 |
| dist/card.2c902906.js | 1.73kb | +0.00b | 141.00ms | -34.00ms 🚀 |
| dist/16.dcacbe5c.js | 1.69kb | +0.00b | 132.00ms | -33.00ms 🚀 |
| dist/date.cfe6153f.js | 1.63kb | +0.00b | 130.00ms | -31.00ms 🚀 |
| dist/16.de3f3184.js | 1.63kb | +0.00b | 136.00ms | -33.00ms 🚀 |
| dist/images.c60a97a9.js | 1.57kb | +0.00b | 128.00ms | -29.00ms 🚀 |
| dist/feedback.01d7bcf7.js | 1.53kb | +0.00b | 113.00ms | -37.00ms 🚀 |
| dist/workerHasher.854262ce.js | 1.49kb | +0.00b | 111.00ms | -9.00ms 🚀 |
| dist/status.e3ed4764.js | 1.35kb | +0.00b | 115.00ms | -38.00ms 🚀 |
| dist/list-number.dbe744df.js | 1.35kb | +0.00b | 128.00ms | -28.00ms 🚀 |
| dist/16.f54dac28.js | 1.34kb | +0.00b | 134.00ms | -33.00ms 🚀 |
| dist/16.8f0e8fe1.js | 1.29kb | +0.00b | 136.00ms | -33.00ms 🚀 |
| dist/16.43b62c01.js | 1.29kb | +0.00b | 135.00ms | -33.00ms 🚀 |
| dist/code.092e0137.js | 1.28kb | +0.00b | 130.00ms | -27.00ms 🚀 |
| dist/16.b17a4d30.js | 1.27kb | +0.00b | 131.00ms | -28.00ms 🚀 |
| dist/16.51bbc68e.js | 1.24kb | +0.00b | 131.00ms | -29.00ms 🚀 |
| dist/component.8351f228.js | 1.23kb | +0.00b | 138.00ms | -32.00ms 🚀 |
| dist/link.6fa27bb2.js | 1.20kb | +0.00b | 128.00ms | -28.00ms 🚀 |
| dist/heading6.3996fe48.js | 1.19kb | +0.00b | 113.00ms | -37.00ms 🚀 |
| dist/16.385d3ff5.js | 1.19kb | +0.00b | 132.00ms | -29.00ms 🚀 |
| dist/heading3.9fea5413.js | 1.18kb | +0.00b | 113.00ms | -37.00ms 🚀 |
| dist/16.b3ce4050.js | 1.16kb | +0.00b | 135.00ms | -34.00ms 🚀 |
| dist/16.e37bbe6b.js | 1.15kb | +0.00b | 131.00ms | -29.00ms 🚀 |
| dist/16.f7fe274a.js | 1.14kb | +0.00b | 130.00ms | -28.00ms 🚀 |
| dist/emoji.c4bc5355.js | 1.12kb | +0.00b | 131.00ms | -26.00ms 🚀 |
| dist/16.ac2ff83f.js | 1.10kb | +0.00b | 133.00ms | -33.00ms 🚀 |
| dist/16.4c652b29.js | 1.10kb | +0.00b | 134.00ms | -34.00ms 🚀 |
| dist/16.24165259.js | 1.09kb | +0.00b | 135.00ms | -33.00ms 🚀 |
| dist/16.74510c56.js | 1.09kb | +0.00b | 134.00ms | -33.00ms 🚀 |
| dist/16.97c5bdf9.js | 1.09kb | +0.00b | 134.00ms | -33.00ms 🚀 |
| dist/16.a79db876.js | 1.09kb | +0.00b | 136.00ms | -33.00ms 🚀 |
| dist/heading5.2f045997.js | 1.07kb | +0.00b | 114.00ms | -37.00ms 🚀 |
| dist/16.6f8ac62a.js | 1.05kb | +0.00b | 137.00ms | -33.00ms 🚀 |
| dist/expand.13380081.js | 1.05kb | +0.00b | 113.00ms | -36.00ms 🚀 |
| dist/card.aae6ebb9.js | 1.04kb | +0.00b | 141.00ms | -34.00ms 🚀 |
| dist/16.3e36da0b.js | 1.01kb | +0.00b | 131.00ms | -29.00ms 🚀 |
| dist/heading2.2194210a.js | 1.00kb | +0.00b | 113.00ms | -38.00ms 🚀 |
| dist/mention.9fdad24e.js | 983.00b | +0.00b | 117.00ms | -38.00ms 🚀 |
| dist/fallback.305c8864.js | 982.00b | +0.00b | 114.00ms | -38.00ms 🚀 |
| dist/heading4.63d1ca06.js | 978.00b | +0.00b | 114.00ms | -37.00ms 🚀 |
| dist/layout.6f66c2da.js | 964.00b | +0.00b | 128.00ms | -28.00ms 🚀 |
| dist/divider.160f3108.js | 942.00b | +0.00b | 131.00ms | -27.00ms 🚀 |
| dist/quote.88bfdca4.js | 938.00b | +0.00b | 115.00ms | -38.00ms 🚀 |
| dist/action.146450ba.js | 921.00b | +0.00b | 130.00ms | -28.00ms 🚀 |
| dist/decision.06254b93.js | 900.00b | +0.00b | 130.00ms | -28.00ms 🚀 |
| dist/panel-warning.59c8ef3f.js | 893.00b | +0.00b | 116.00ms | -38.00ms 🚀 |
| dist/list.4f623de3.js | 872.00b | +0.00b | 117.00ms | -39.00ms 🚀 |
| dist/heading1.65fb8482.js | 866.00b | +0.00b | 114.00ms | -37.00ms 🚀 |
| dist/panel-error.c2479698.js | 793.00b | +0.00b | 117.00ms | -38.00ms 🚀 |
| dist/panel.23cd7224.js | 790.00b | +0.00b | 115.00ms | -39.00ms 🚀 |
| dist/table.4ace5843.js | 782.00b | +0.00b | 114.00ms | -38.00ms 🚀 |
| dist/media-viewer-analytics-error-boundary.dd752a9e.js | 779.00b | +0.00b | 142.00ms | -34.00ms 🚀 |
| dist/panel-success.6a7b97d7.js | 730.00b | +0.00b | 116.00ms | -38.00ms 🚀 |
| dist/panel-note.5ff85bdc.js | 729.00b | +0.00b | 116.00ms | -39.00ms 🚀 |
| dist/simpleHasher.884d4eb6.js | 450.00b | +0.00b | 110.00ms | -9.00ms 🚀 |
| dist/esm.976debcc.js | 179.00b | +1.00b ⚠️ | 143.00ms | -34.00ms 🚀 |
| dist/media-card-analytics-error-boundary.976debcc.js | 179.00b | +1.00b ⚠️ | 140.00ms | -34.00ms 🚀 |
| dist/dropzone.976debcc.js | 179.00b | +1.00b ⚠️ | 139.00ms | -33.00ms 🚀 |
| dist/clipboard.976debcc.js | 179.00b | +1.00b ⚠️ | 139.00ms | -32.00ms 🚀 |
| dist/browser.976debcc.js | 179.00b | +1.00b ⚠️ | 138.00ms | -33.00ms 🚀 |
| dist/16.976debcc.js | 179.00b | +1.00b ⚠️ | 130.00ms | -29.00ms 🚀 |
| dist/editorView.976debcc.js | 179.00b | +1.00b ⚠️ | 109.00ms | -8.00ms 🚀 |

</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/255530138643464713)**

**Comment by patrickhulce** [comment]
Thank you @mischnic! 🎉

**Comment by devongovett** [comment]
Not sure I really understand the usecase for this. Couldn't you just override the settings for the target if you didn't want a library?

```json
{
  "targets": {
    "main": {
      "isLibrary": false
    }
  }
}
```

**Comment by mischnic** [comment]
No, for example having `main` pointed to a server:

```json
{
  "main": "server.js",
  "app": "dist/index.html",
  "scripts": { "build": "parcel build frontend/index.html" },
  "targets": {
    "main": false,
    "app": { "engines": { "browsers": ["Chrome 50"] } }
  }
}
```
```js
// server.js
const serveStatic = require('serve-static')
 
module.exports = serveStatic('dist/');
 ```

**Pull request merged**
