### PR TITLE
Register highlight languages on demand (make Parcel 1.5 MB smaller)

### PR DESCRIPTION
**Pull request by aminya**
# ↪️ Pull Request

This pull reuqests changes the usage of `emphasize` package, which surprisingly [loads all the highligh-js languages (~1.5 MB in size)](https://github.com/wooorm/emphasize/blob/main/index.js) by default! 

After this PR, only the languages that are needed will be added on-demand, which means Parcel will be 1.5 MB smaller and load faster.

## 🚨 Test instructions
The current codeframe tests should cover this.

## ✔️ PR Todo

- [ ] Added/updated unit tests for this change
- [x] Filled out test instructions (In case there aren't any unit tests)
- [x] Included links to related issues/PRs

### CODE REVIEW

**Review by DeMoorJasper — CHANGES_REQUESTED** [review]
awesome, can you please fix flow

**Comment by aminya** [comment]
This is ready @DeMoorJasper

**Comment by aminya** [comment]
Any question about this PR? It is straightforward.

**Review by mischnic — APPROVED** [review]
@DeMoorJasper any concerns?

**Review by DeMoorJasper — APPROVED** [review]

**Pull request merged**
