### PR TITLE
HMR: Don't wait for packaging

### LINKED ISSUE #4143: Feature: Faster Than Light (FTL) reloads
# Faster Than Light (FTL) reloads
This feature request is inspired by [fuse-box v4](https://github.com/fuse-box/fuse-box).

## 🤔 Expected Behavior
The HMR reload can change from 2-3 seconds to 5-10 milliseconds.

## 😯 Current Behavior
Right now, parcel spends the same amount of time (2-3 seconds) on the HMR update regardless of what type of file is changed.

## 💁 Possible Solution
Instead of rebundling the entire tree of files for every file change - the 5 most recently worked on modules can be injected into the client directly. 

Docs from fuse-box repo:
https://github.com/fuse-box/fuse-box/blob/master/docs/cache.md

fuse-box implementation of FTL:
https://github.com/fuse-box/fuse-box/blob/master/src/FTL/FasterThanLightReload.ts

## 🔦 Context
Imagine changing a stylesheet and seeing the change applied before you are able to blink. On a 60Hz monitor, this essentially means the update might happen as soon as the next monitor refresh!

I believe parcel would deliver a massively improved developer experience if it was able to implement this feature. 

Considering fuse-box has managed to do it - it shows that this should be possible.

## 💻 Examples

React demo with fuse-box v4: https://github.com/fuse-box/react-example

### PR DESCRIPTION
**Pull request by mischnic**
We may or may not need this bailout logic: https://github.com/parcel-bundler/parcel/commit/2acf9c5bd12d5aab75b765b92a2b6f286a2c657d

Some more discussions about bailing out: https://github.com/parcel-bundler/parcel/issues/4143#issuecomment-596963165

Closes https://github.com/parcel-bundler/parcel/issues/4143

### CODE REVIEW

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>Kitchen Sink ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 2.24s | +232.00ms ⚠️ |
| Cached | 491.00ms | +84.00ms ⚠️ |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/parcel.7cdb0fad.webp | 102.94kb | +0.00b | 126.00ms | -180.00ms 🚀 |
| dist/legacy/parcel.7cdb0fad.webp | 102.94kb | +0.00b | 127.00ms | -180.00ms 🚀 |
| dist/modern/parcel.7cdb0fad.webp | 102.94kb | +0.00b | 126.00ms | -181.00ms 🚀 |
| dist/legacy/index.2c76ad23.js | 1.66kb | +0.00b | 604.00ms | +78.00ms ⚠️ |
| dist/legacy/index.8aaa89c9.js | 1.20kb | +0.00b | 604.00ms | +77.00ms ⚠️ |
| dist/modern/index.6be20f01.js | 1.13kb | +0.00b | 604.00ms | +78.00ms ⚠️ |
| dist/legacy/index.html | 826.00b | +0.00b | 820.00ms | +146.00ms ⚠️ |
| dist/modern/index.html | 749.00b | +0.00b | 818.00ms | +147.00ms ⚠️ |
| dist/legacy/index.b8ae99ba.css | 94.00b | +0.00b | 366.00ms | +47.00ms ⚠️ |
| dist/modern/index.31cedca9.css | 94.00b | +0.00b | 365.00ms | +47.00ms ⚠️ |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/parcel.7cdb0fad.webp | 102.94kb | +0.00b | 377.00ms | +24.00ms ⚠️ |
| dist/legacy/parcel.7cdb0fad.webp | 102.94kb | +0.00b | 381.00ms | +27.00ms ⚠️ |
| dist/modern/parcel.7cdb0fad.webp | 102.94kb | +0.00b | 382.00ms | +28.00ms ⚠️ |
| dist/legacy/index.b8ae99ba.css | 94.00b | +0.00b | 390.00ms | +28.00ms ⚠️ |
| dist/modern/index.31cedca9.css | 94.00b | +0.00b | 389.00ms | +29.00ms ⚠️ |

</p></details>

<details><summary>React HackerNews ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 13.69s | +516.00ms |
| Cached | 510.00ms | -77.00ms 🚀 |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.js | 486.37kb | +0.00b | 6.48s | -769.00ms 🚀 |
| dist/PermalinkedComment.46b19af5.js | 4.21kb | +0.00b | 6.48s | -770.00ms 🚀 |
| dist/UserProfile.f8cd7884.js | 1.57kb | +0.00b | 6.48s | -769.00ms 🚀 |
| dist/NotFound.960ab92b.js | 429.00b | +0.00b | 6.48s | -769.00ms 🚀 |
| dist/logo.c5bb83f1.png | 246.00b | +0.00b | 6.48s | -777.00ms 🚀 |

</p></details>

<details><summary>AtlasKit Editor ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 1.98m | -2.00s |
| Cached | 2.90s | +355.00ms ⚠️ |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

*No bundle changes detected.*

</p></details>

<details><summary>Three.js ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 8.65s | +729.00ms ⚠️ |
| Cached | 315.00ms | -56.00ms 🚀 |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/Three.js | 580.02kb | +0.00b | 5.66s | -1.00s 🚀 |

</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/347191700619264594)**

**Comment by devongovett** [comment]
We should do some testing, but I _think_ this should be ok because the dev server blocks requests until a build is complete. So if an async dep got introduced and requested immediately, it should work.

**Comment by devongovett** [comment]
I noticed in profiles that `createWriteBundlesRequest` was still running before the HMR update was actually emitted, due to it being an async function that wasn't awaited. Since `createWriteBundlesRequest` can still be pretty slow due to traversing the bundle graph and hashing, I added awaiting to the report call so we ensure the HMR update is emitted first.

**Review by devongovett — APPROVED** [review]
Did some testing and it seems ok to me!

**Pull request merged**
