### PR TITLE
[feature] Add WebManifestAsset to handle W3C webmanifest

### PR DESCRIPTION
**Pull request by niicojs**
Allow pwa site to define a manifest.webmanifest according to https://www.w3.org/TR/appmanifest/.
Currently, you have to name it like that as if you name it with .json, the JsonAsset get triggered and convert it to js.
I have another PR for that, but it's not currently working (#690)

### CODE REVIEW

**Comment by devongovett** [comment]
Awesome! Looks like there are some other fields supported by webmanifest files that we should probably be adding as dependencies as well. For example, `serviceworker.src`, `screenshots`. WDYT?

**Comment by niicojs** [comment]
sure, I'll check that

**Comment by devongovett** [comment]
Thanks, this looks great! Can you add a test as well?

**Comment by niicojs** [comment]
I've added test coverage (that's a first for me, so I hope I did it right...).
Also, I've seen #313 which I missed before. I did not create a packager myself, did I miss something?

**Comment by devongovett** [comment]
🏆

**Pull request merged**
