### PR TITLE
Bump swc

### LINKED ISSUE #6719: object key named "function" breaks JSX parsing
# 🐛 bug report

broken in 2.0.0-rc0 (was working in 2.0.0-beta2)
```
const x = <div onclick={(e) => {function: 123}}></div>;
```
With the error:
```
@parcel/transformer-js: Unexpected token `div`. Expected jsx identifier
```
This works, which seems confirm the keyword "function" is the problem:
```
const x = <div onclick={(e) => {function_: 123}}></div>;
```

FWIW when I hit this for real, it was a big block of JSX where one of the inner elements had an onclick handler which mentioned `{function: blah}` -- but the error message pointed to the opening tag of the JSX block, not the tag with the attribute (I ended up deleting one element at a time from the big block of jsx to track down the element which was causing issues).

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
    "name": "browser2",
    "dependencies": {
        "@shish2k/hyperapp-hash-state": "^2.0.6",
        "@shish2k/hyperapp-localstorage": "^1.0.0",
        "@shish2k/hyperapp-mqtt": "^1.1.2",
        "hyperapp": "^2.0.18",
        "hyperapp-fx": "^2.0.0-beta.2",
        "hyperapp-jsx-pragma": "^1.3.0"
    },
    "scripts": {
        "build": "parcel build --public-url . src/index.html",
        "watch": "parcel watch --public-url . src/index.html",
        "serve": "parcel serve --port 1234 src/index.html",
        "format": "prettier --write 'src/**/*.tsx' --tab-width 4 --trailing-comma all"
    },
    "repository": "https://github.com/calaldees/KaraKara/",
    "license": "GPL-3.0-only",
    "devDependencies": {
        "@parcel/transformer-sass": "^2.0.0-rc.0",
        "parcel": "^2.0.0-rc.0",
        "parcel-config-pwa-manifest": "0.0.9",
        "prettier": "^2.3.2"
    },
    "pwaManifest": {
        "development": {
            "disabled": true
        },
        "name": "KaraKara",
        "shortName": "KaraKara",
        "startURL": ".",
        "theme": "#e9e9e9",
        "display": "standalone",
        "orientation": "portrait",
        "generateIconOptions": {
            "baseIcon": "./src/static/favicon.svg",
            "sizes": [
                192,
                384,
                512
            ],
            "genFavicons": true
        }
    }
}

```

### LINKED ISSUE #6765: Parcel 2 doesn't know precedence of `await` or logical or assignment
# 🐛 bug report

Parcel (I think it's SWC because [babel seems to do it correctly](https://babeljs.io/repl/#?browsers=firefox%2080&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=LYQwlgdgFAlA3AKASAzgTwgYwAQDMCuWALmAPYTaiSzYDeC22ANgKZHYAOATqcGCi0QNsmcinYgA7uCIsAJgH1uvfi2wBebFJnYoyvgOwAfI5oAKPAywB0XFilJMAbiygAiIgAt-2HyGziXJAA5m4w8MKiEA6s1kykwVDaYLKK-qrWRKQAykRBEInhiAC-QA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.15.3&externalPlugins=&assumptions=%7B%7D)) doesn't do precedence correctly when using await and logical OR assignment.

## 🎛 Configuration (.babelrc, package.json, cli command)

```js
{
  "dependencies": {
    "parcel": "nightly"
  },
  "targets": {
    "modern": {
      "engines": {
        "browsers": "firefox 77"
      }
    }
  }
}

```

## 🤔 Expected Behavior

Output code: `!async function(){let o;const s=await (o||(o=Promise.resolve("this is a string")));console.log(s.toString())}();`

Eval result: `this is a string`

## 😯 Current Behavior

Output code: `!async function(){let o;const s=await o||(o=Promise.resolve("this is a string"));console.log(s.toString())}();`

Eval result: `[object Promise]`

## 💁 Possible Solution

Don't remove parentheses where that changes the code

## 🔦 Context

I happily deployed my code to production and it broke. After an hour of debugging and hating yarn berry or whatever gave me this issue when I tried to upgrade parcel:

```
🚨 Build failed.

@parcel/core: Failed to resolve 'src/test/temp-12545.tsx'

@parcel/resolver-default: The "path" argument must be of type string. Received undefined

  TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
  at new NodeError (node:internal/errors:371:5)
  at validateString (node:internal/validators:119:11)
  at Object.isAbsolute (node:path:1157:5)
  at NodeResolver.resolveModule
  ([project_dir]/.yarn/cache/@parcel-node-resolver-core-npm-2.0.0-nightly.2418-a46b40c4e1-9a61779ada.zip/node_modules/@parcel/node-resolver-core/lib/NodeResolver.js:224:25)
  at async NodeResolver.resolve
  ([project_dir]/.yarn/cache/@parcel-node-resolver-core-npm-2.0.0-nightly.2418-a46b40c4e1-9a61779ada.zip/node_modules/@parcel/node-resolver-core/lib/NodeResolver.js:137:20)
  at async ResolverRunner.resolve
  ([project_dir]/.yarn/cache/@parcel-core-npm-2.0.0-nightly.809-cffd5f51ab-eda7e37cd3.zip/node_modules/@parcel/core/lib/requests/PathRequest.js:207:22)
  at async Object.run ([project_dir]/.yarn/cache/@parcel-core-npm-2.0.0-nightly.809-cffd5f51ab-eda7e37cd3.zip/node_modules/@parcel/core/lib/requests/PathRequest.js:104:16)
  at async RequestTracker.runRequest ([project_dir]/.yarn/cache/@parcel-core-npm-2.0.0-nightly.809-cffd5f51ab-eda7e37cd3.zip/node_modules/@parcel/core/lib/RequestTracker.js:711:20)
  at async AssetGraphBuilder.runPathRequest
  ([project_dir]/.yarn/cache/@parcel-core-npm-2.0.0-nightly.809-cffd5f51ab-eda7e37cd3.zip/node_modules/@parcel/core/lib/requests/AssetGraphRequest.js:722:18)
  at async PromiseQueue._runFn ([project_dir]/.yarn/cache/@parcel-utils-npm-2.0.0-nightly.811-05dc7f2595-6b3d9e3e8a.zip/node_modules/@parcel/utils/lib/PromiseQueue.js:88:7)
```
 I have finally produced this issue report.
Similar issue: https://github.com/parcel-bundler/parcel/issues/5759

## 💻 Code Sample

```
main();

async function main() {
  let promise: Promise<string>;

  const awaited_promise = await (promise ||= Promise.resolve("this is a string"));
  console.log(awaited_promise.toString());
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           |2.0.0-nightly.809+95f5648d
| Node             |v16.7.0
| npm/Yarn         |yarn 3.0.1
| Operating System |macOS 10.15.7 (19H1323)|

### LINKED ISSUE #6766: Compound assignments transpile incorrectly
# 🐛 bug report

Compound assignments are transpiled incorrectly.

## 🎛 Configuration (.babelrc, package.json, cli command)

To reproduce, just a single input file with a simple script is required.

#### index.html

```html
<html>
    <body>    
        <script>
            var bit = 0, sum = 0
            sum += (bit ^= 1) ? 0 : 1
            sum += (bit ^= 1) ? 0 : 1
            console.log(sum)
        </script>
    </body>
</html>
```

No configuration files or anything. Only dependency is parcel.

### package.json

```json
{
  "name": "parcel-transpile-bug",
  "version": "1.0.0",
  "devDependencies": {
    "parcel": "^2.0.0-nightly.810"
  }
}
```

Then do

`npx parcel serve index.html`

or

`npx parcel build index.html`

## 🤔 Expected Behavior

Output in browser console should be `1`. (Can be verified by just pasting the contents of the <script> tag in the console.

## 😯 Current Behavior

Output in browser console is `0`.

The compound assignments are erroneously transpiled to this:

```js
sum += (bit ^= 1, 0);
sum += (bit ^= 1, 0);
```

## 🔦 Context

Don't know, but might be related to #4361?

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.810
| Node             | 14.17.5
| npm/Yarn         |6.14.14
| Operating System |Win10

### LINKED ISSUE #6802: Children of short syntax of `React.Fragment` is required to have `key` prop.
# 🐛 bug report

This code produces an error that `key` prop is omitted in `<div>`.
```js
import * as React from 'react';

export const App = () => (
    <>
        <div></div>
    </>
);
```

But this code does not.
```js
import * as React from 'react';

export const App = () => (
    <React.Fragment>
        <div></div>
    </React.Fragment>
);
```

## 🎛 Configuration (.babelrc, package.json, cli command)

I haven't created `.parcelrc` and config file for **Babel**.

`package.json`:
```json
{
  "name": "name",
  "version": "0.0.1",
  "description": "Description.",
  "scripts": {
    "start": "parcel serve src/index.html",
    "build": "parcel build src/index.html"
  },
  "author": "Me",
  "devDependencies": {
    "@parcel/transformer-less": "2.0.0-rc.0",
    "@types/react": "^17.0.19",
    "@types/react-dom": "^17.0.9",
    "parcel": "2.0.0-rc.0",
    "prettier": "^2.3.2",
    "tslib": "^2.3.1",
    "typescript": "^4.4.2",
    "typescript-plugin-css-modules": "^3.4.0"
  },
  "dependencies": {
    "@fluss/core": "^0.31.4",
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
  }
}
```

## 🤔 Expected Behavior

I suppose that the behavior of `<React.Fragment>` and `<>` should be the same.

## 😯 Current Behavior

Instead, I'm seeing in the browser this error:
```
Warning: Each child in a list should have a unique "key" prop.

Check the render method of `App`. See https://reactjs.org/link/warning-keys for more information.
div
App react-jsx-runtime.development.js:117:29
    React 6
    App App.tsx:7
    React 14
    iqQLF index.tsx:6
    newRequire index.b4af9c3f.js:71
    <anonymous> index.b4af9c3f.js:120
    <anonymous> index.b4af9c3f.js:143
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-rc.0
| Node             | 16.8.0
| npm         | 7.21.0
| Operating System | MacOS v11.5.2

### LINKED ISSUE #6928: Javascript transform breaking code in d3
# 🐛 bug report

Compiled code is changed and removing a needed if statement from d3 library
https://d3js.org/

## 🎛 Configuration (.babelrc, package.json, cli command)

No custom config. `parcel serve index.html`

## 🤔 Expected Behavior

Keep the if statement

Source
```js
for (i = 0; i < n; ++i) {
      node = nodes[i], nodeId = parentId(data[i], i, data);
      if (nodeId == null || !(nodeId += "")) {
        if (root) throw new Error("multiple roots");
        root = node;
      } else {
```

Output
```js
       for(i = 0; i < n; ++i){
            node = nodes[i], nodeId = parentId(data[i], i, data);
            // MISSING CRITICAL IF STATEMENT
            nodeId == null || (nodeId += "");
            if (root) throw new Error("multiple roots");
            root = node;
        }
```
## 💻 Code Sample

Original Source Code
```js
export default function() {
  var id = defaultId,
      parentId = defaultParentId;

  function stratify(data) {
    var d,
        i,
        n = data.length,
        root,
        parent,
        node,
        nodes = new Array(n),
        nodeId,
        nodeKey,
        nodeByKey = {};

    for (i = 0; i < n; ++i) {
      d = data[i], node = nodes[i] = new Node(d);
      if ((nodeId = id(d, i, data)) != null && (nodeId += "")) {
        nodeKey = keyPrefix + (node.id = nodeId);
        nodeByKey[nodeKey] = nodeKey in nodeByKey ? ambiguous : node;
      }
    }

    for (i = 0; i < n; ++i) {
      node = nodes[i], nodeId = parentId(data[i], i, data);
      if (nodeId == null || !(nodeId += "")) {
        if (root) throw new Error("multiple roots");
        root = node;
      } else {
        parent = nodeByKey[keyPrefix + nodeId];
        if (!parent) throw new Error("missing: " + nodeId);
        if (parent === ambiguous) throw new Error("ambiguous: " + nodeId);
        if (parent.children) parent.children.push(node);
        else parent.children = [node];
        node.parent = parent;
      }
    }

    if (!root) throw new Error("no root");
    root.parent = preroot;
    root.eachBefore(function(node) { node.depth = node.parent.depth + 1; --n; }).eachBefore(computeHeight);
    root.parent = null;
    if (n > 0) throw new Error("cycle");

    return root;
  }

  stratify.id = function(x) {
    return arguments.length ? (id = required(x), stratify) : id;
  };

  stratify.parentId = function(x) {
    return arguments.length ? (parentId = required(x), stratify) : parentId;
  };

  return stratify;
}

```

Transpiled code
```js
exports.default = function() {
    var id = defaultId, parentId = defaultParentId;
    function stratify(data) {
        var d, i, n = data.length, root, parent, node, nodes = new Array(n), nodeId, nodeKey, nodeByKey = {
        };
        for(i = 0; i < n; ++i){
            d = data[i], node = nodes[i] = new _indexJs.Node(d);
            (nodeId = id(d, i, data)) != null && (nodeId += "");
        }
        for(i = 0; i < n; ++i){
            node = nodes[i], nodeId = parentId(data[i], i, data);
            // MISSING CRITICAL IF STATEMENT
            nodeId == null || (nodeId += "");
            if (root) throw new Error("multiple roots");
            root = node;
        }
        if (!root) throw new Error("no root");
        root.parent = preroot;
        root.eachBefore(function(node1) {
            node1.depth = node1.parent.depth + 1;
            --n;
        }).eachBefore(_indexJs.computeHeight);
        root.parent = null;
        if (n > 0) throw new Error("cycle");
        return root;
    }
    stratify.id = function(x) {
        return arguments.length ? (id = _accessorsJs.required(x), stratify) : id;
    };
    stratify.parentId = function(x) {
        return arguments.length ? (parentId = _accessorsJs.required(x), stratify) : parentId;
    };
    return stratify;
};
```
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0.rc.0
| Node             | v14.17.3
| npm/Yarn         | 6.14.13
| Operating System | Mac

### PR DESCRIPTION
**Pull request by mischnic**
Closes https://github.com/parcel-bundler/parcel/issues/6802
Closes https://github.com/parcel-bundler/parcel/issues/6765
Closes https://github.com/parcel-bundler/parcel/issues/6766
Closes https://github.com/parcel-bundler/parcel/issues/6719
Closes https://github.com/parcel-bundler/parcel/issues/6928

### CODE REVIEW

**Comment by devongovett** [comment]
Sourcemaps changed maybe?

**Comment by mischnic** [comment]
v2:
Bildschirmfoto 2021-09-01 um 09 51 46

this:
Bildschirmfoto 2021-09-01 um 09 52 21

The `return` and the first quote character isn't mapped anymore

**Comment by devongovett** [comment]
hmm is this bad? @DeMoorJasper

**Comment by DeMoorJasper** [comment]
@devongovett from the screenshots it looks like the mappings are more complete now? But the text Niklas added says the opposite, so not sure? More mappings is always better (as long as they're accurate)

Looks fine to me either way, if it's less-complete we should probably file a bug report though

**Comment by devongovett** [comment]
Oh ok, I think I misread it as well.

**Comment by danieltroger** [comment]
Any progress on this?

**Comment by mischnic** [comment]
I think I misinterpreted these results as well, the sourcemap is more accurate than before. So we'll probably only need to update the test fixtures

**Comment by danieltroger** [comment]
Can confirm the sourcemaps were still wrong when I tried them out like two weeks ago so if this fixes them that'd be awesome.

**Review by findmet — CHANGES_REQUESTED** [review]
packages/transformers/js/core/Cargo.toml 
And send for approval

**Comment by mischnic** [comment]
Well, they still wrong:

Bildschirmfoto 2021-09-11 um 11 29 50

Bildschirmfoto 2021-09-11 um 11 29 56


They are mostly correct after removing `tests/test/integration/sourcemap/.babelrc`

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>Kitchen Sink ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 1.63s | +13.00ms |
| Cached | 255.00ms | -15.00ms 🚀 |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

*No bundle changes detected.*

</p></details>

<details><summary>React HackerNews ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 8.42s | -12.00ms |
| Cached | 422.00ms | +10.00ms |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

*No bundle changes detected.*

</p></details>

<details><summary>AtlasKit Editor ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 55.28s | -139.00ms |
| Cached | 1.51s | -38.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.060c360f.js | 1.78mb | +62.00b ⚠️ | 16.01s | +11.00ms |
| dist/pdfRenderer.4b496bac.js | 1.11mb | +12.00b ⚠️ | 42.15s | -519.00ms |
| dist/index.051a8d66.js | 694.71kb | +10.00b ⚠️ | 31.37s | -11.22s 🚀 |
| dist/editorView.f3e74e37.js | 594.92kb | -82.00b 🚀 | 31.37s | +37.00ms |
| dist/index.749d3cbb.js | 145.75kb | +0.00b | 31.37s | -11.22s 🚀 |
| dist/card.a2a4a158.js | 62.67kb | +0.00b | 31.37s | -11.22s 🚀 |
| dist/card.45f850d6.js | 5.77kb | +0.00b | 31.37s | -11.22s 🚀 |
| dist/Modal.7f4c60b3.js | 3.15kb | +0.00b | 31.37s | -11.22s 🚀 |
| dist/media-card-analytics-error-boundary.b1a780f3.js | 962.00b | +0.00b | 31.37s | -11.22s 🚀 |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.781e2635.js | 1.78mb | +72.00b ⚠️ | 16.06s | -302.00ms |
| dist/pdfRenderer.a6d29553.js | 1.11mb | +12.00b ⚠️ | 43.16s | -1.55s |
| dist/index.9d4aefdd.js | 694.70kb | +21.00b ⚠️ | 43.11s | -1.56s |
| dist/editorView.12a24514.js | 594.92kb | -82.00b 🚀 | 42.70s | -1.92s |
| dist/EmojiPickerComponent.25aebafd.js | 146.67kb | +0.00b | 26.47s | +8.59s ⚠️ |
| dist/Modal.8a291eba.js | 45.33kb | -15.00b 🚀 | 42.69s | -1.92s |
| dist/esm.87ccebb6.js | 33.15kb | +0.00b | 26.47s | +8.59s ⚠️ |
| dist/DatePicker.034a8928.js | 22.98kb | +0.00b | 26.47s | +8.59s ⚠️ |
| dist/js.0f0bb621.js | 17.25kb | +0.00b | 42.70s | +9.82s ⚠️ |
| dist/png-chunks-extract.94b5b9fc.js | 3.58kb | +0.00b | 42.70s | +9.82s ⚠️ |
| dist/feedback.e18b45f0.js | 1.77kb | +0.00b | 26.47s | +8.59s ⚠️ |
| dist/workerHasher.567cfc57.js | 1.63kb | +0.00b | 26.47s | +8.59s ⚠️ |
| dist/heading6.b3b946d1.js | 1.51kb | +0.00b | 26.46s | +8.59s ⚠️ |
| dist/heading5.e617db66.js | 1.38kb | +0.00b | 26.46s | +8.59s ⚠️ |
| dist/expand.1f17de7f.js | 1.29kb | +0.00b | 26.47s | +8.59s ⚠️ |

</p></details>

<details><summary>Three.js ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 5.83s | -195.00ms |
| Cached | 336.00ms | -19.00ms 🚀 |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

*No bundle changes detected.*

</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/309714461970661954)**

**Comment by mischnic** [comment]
I've removed the babelrc from that test to unblock this (and also because that most basic sourcemap test shouldn't involve babel + swc anyway)

**Review by wbinnssmith — APPROVED** [review]

**Review by devongovett — APPROVED** [review]

**Pull request merged**
