### PR TITLE
fix(typescript): use tsconfig `extends` option and watch extended config

### PR DESCRIPTION
**Pull request by Hoishin**
original PR: #2109 

## ↪️ Pull Request

Resolve the "extends" property in tsconfig.json, and watch the parents config files.

Continuation of https://github.com/parcel-bundler/parcel/pull/646, but different approach.

## 💻 Examples

In `project/tsconfig.json`:
```json
{
  "compilerOptions": {
    "foo": "bar"
  }
}
```

In `project/src/tsconfig.json`:
```json
{
  "extends": "../tsconfig",
  "compilerOptions": {
    "some": "value"
  }
}
```

Previously Parcel could not resolve the `"extends"` property. Now it resolves and watch the parent config file(s)!

## ✔️ PR Todo

- [x] Added/updated unit tests for this change
- [x] Filled out test instructions
- [x] Included links to related issues/PRs

### CODE REVIEW

**Comment by rvion** [comment]
thanks, I hope this gets merged soon

**Comment by Hoishin** [comment]
The failing test is something to do with Elm, which I don't think this PR is related to.

**Comment by Hoishin** [comment]
@devongovett @DeMoorJasper Is it OK to close this PR now that new PR solves same problem?

**Comment by DeMoorJasper** [comment]
@Hoishin yes sure

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request closed without merging**
