### PR TITLE
New faster resolver supporting absolute and tilde paths, and aliases

### LINKED ISSUE #25: Add an aliasing system that works for all asset types
Is there a way to define alias ? Like webpack config:

### LINKED ISSUE #86: 🐛 link to static html could'not be resolved, win10, parcel 1.0.3
index.html
```html
            <p>
                <a href="/src/somePathToChecker/index.html">Check</a>
            </p>
```

```
 Cannot resolve dependency './..\..\..\..\..\src\somePathToChecker\index.html'
    at C:\Users\Aleksandr_Kanunnikov\AppData\Roaming\npm\node_modules\parcel-bundler\node_modules\browser-resolve\node_modules\resolve\lib\async.js:55:21
    at load (C:\Users\Aleksandr_Kanunnikov\AppData\Roaming\npm\node_modules\parcel-bundler\node_modules\browser-resolve\node_modules\resolve\lib\async.js:69:43)
    at onex (C:\Users\Aleksandr_Kanunnikov\AppData\Roaming\npm\node_modules\parcel-bundler\node_modules\browser-resolve\node_modules\resolve\lib\async.js:92:31)
    at C:\Users\Aleksandr_Kanunnikov\AppData\Roaming\npm\node_modules\parcel-bundler\node_modules\browser-resolve\node_modules\resolve\lib\async.js:22:47


```

### LINKED ISSUE #336: 🙋 Support project-relative import paths
Projects with a deep folder structure often have import paths with lots of "../../../../../a/b/c/d/actualFile.js" in them because import paths are kind of restricted.

One workaround in webpack is to define custom aliases for the resolver, but this approach would break the zero-configuration approach of parcel.

Would it be possible to have at least an additional notation for "project-relative" imports in parcel, so that the dotdot madness at the beginning could be stopped?

### 🎛 Configuration (.babelrc, package.json, cli command)

N/A

### 😯 Current Behavior

Apparently (??) no support for project-relative import paths.

### 💁 Possible Solution

- Resolve './abc' relatibe to the current file (as is)
- Resolve '/abc' absolute to filesystem (or webroot? as is)
- Resolve 'x/abc' relative to module 'x' (as is)
- Resolve '-/abc' or '.../abc' or similar relative to current or nearest parent folder with a package.json file in it (package root)

### LINKED ISSUE #832: 🙋 Aliasing modules -- react -> preact-compat etc.
It is impossible to use parcel with preact-compat because it requires being able to alias all references to 'react' and 'react-dom' to 'preact-compat'. It is possible to do this for local package using `browser` in `package.json`, but does not work when including external React components.

### 🤔 Expected Behavior

Add an alias field in, say, `package.json`, like

```
"alias": {
    "^react$": "preact-compat",
    "react-dom$": "preact-compat",
    "react-dom/server": "preact-compat/server"
}
```

Which would then replace all references to `react` with `preact-compat` etc.

### 😯 Current Behavior

Using `browser` field, I can replace local import/requires successfully, but when importing, say `react-apollo`, it doesn't replace there.

### 🔦 Context

I know there was an issue #25 for this but it got locked and I haven't seen any further discussion about it, but this is quite inconvenient for people trying to use preact. I think it was a bad decision to completely delete all discussion about current workarounds as now people have no reference on what to do until this gets implemented natively.

### Workaround for now

The workaround I found is to make symbolic links in the `node_modules` folder so that `node_modules/react` and `node_modules/react-dom` both link to `node_modules/preact-compat`.

### PR DESCRIPTION
**Pull request by devongovett**
This replaces the `browser-resolve` and `resolve` modules with our own custom resolver which is both faster and more extendible. It especially speeds up building from cache: on one project my build time went from 4.93s to 1.40s. 

This performance increase is due to severely fewer `fs.stat` calls compared to the `resolve` implementation: for example, resolving one dependency I had in my project caused 258 `fs.stat` calls in `resolve` whereas it takes just 9 in the new resolver.

In addition to performance, there is also some new features:

1. Absolute paths (e.g. /foo) resolved relative to the project root (even from within node_modules - is this a bad idea?). Closes #336, closes #290, closes #86.
2. Tilde paths (e.g. ~/foo) resolved relative to the nearest package root in node_modules, or the project root if not in node_modules. Closes #336, closes #466.
3. Aliases are supported using a `package.alias` field in package.json. It works identically to the `browser` field, but when found in the project root package.json it applies globally rather than to only the local module. The alias field also works within node_modules, but does not apply globally. Closes #25, closes #832.

As an example, you could declare the following in your project's package.json to alias react to preact globally:

```json
{
  "alias": {
    "react": "preact-compat",
    "react-dom": "preact-compat"
  }
}
```

This can also be used to alias modules that don't exist in node_modules at all:

```json
{
  "alias": {
    "fake-module": "./some/deep/path"
  }
}
```

Now you can `require('fake-module')` and it will point to the path you've specified.

### CODE REVIEW

**Comment by JounQin** [comment]
What about alias modules under specific directory? Or it can be alias one by one?

Like: https://webpack.js.org/configuration/resolve/#resolve-modules

**Comment by devongovett** [comment]
@JounQin yeah, I don't think we are going to support something like that (similar to `NODE_PATH` environment variable). I think it's a bad idea to do this it makes it much harder to reason about where the code you read in a project is coming from. At least when you explicitly list the modules you want to alias in package.json there is one place to look for to see the mapping.

**Comment by Slapbox** [comment]
Does this support mapping of named exports? For example webpack supports this syntax:

`alias: ['nodeModuleName, exportName]


`ipcRenderer: ['electron', 'ipcRenderer']`

**Comment by devongovett** [comment]
This is a mapping of files only. If you wanted to do something like that I guess you could do it by mapping to your own file which re-exports the thing you want.

```json
{
  "alias": {
    "ipcRenderer": "./electron-ipc.js"
  }
}
```

in electron-ipc.js:

```javascript
module.exports = require('electron').ipcRenderer;
```

**Comment by Cliff122** [comment]
I have a SCSS file containing `@import "~bootstrap/scss/bootstrap";` which I import into my main `app.js` like this: `import '../scss/styles.scss'`. I still however get this error in the console when trying to compile.
`C:\Users\david\Coding\bootstrap-test\src\scss\styles.scss:1:1: File to import not found or unreadable: ~bootstrap/scss/bootstrap.`

What am I doing wrong?

**Comment by DeMoorJasper** [comment]
@Cliff122 This hasn’t been released to npm. You could link to github. ‘~bootstrap...’ should probably also be ~/bootstrap...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Cliff122** [comment]
Alright, I took your advice and cloned the repo and built it locally on my machine. But even when I run the project using that version the error still appears. It looks like the error is thown by the `node-sass` module, if that is relevant.

**Comment by DeMoorJasper** [comment]
@Cliff122 Aha! I remember a similar issue, SASS uses it's internal resolver unfortunately, as far as i'm aware, you can read up the whole discussion here: https://github.com/parcel-bundler/parcel/issues/316 it basically means it's out of parcel's control.

**Comment by Cliff122** [comment]
Ok, that makes sense. When importing directly in the javascript file however, like this: `import '~/bootstrap/scss/bootstrap.scss'`, SASS shouldn't have anything to do with resolving the path, right? When I try that though I instead get the error `C:\Users\david\Coding\bootstrap-test\src\scripts\app.js:1:7: Cannot resolve dependency '~/bootstrap/scss/bootstrap.scss'`.

**Comment by DeMoorJasper** [comment]
@Cliff122 hmmm not sure why u get an error, might be u are using it incorrectly, your import would resolve like this I think.
`~/bootstrap/scss/bootstrap.scss` => `C:\Users\david\Coding\bootstrap-test\src\bootstrap/scss/bootstrap.scss`
at least if the entrypoint is inside `C:\Users\david\Coding\bootstrap-test\src\`

**Comment by Cliff122** [comment]
Oh, my bad! I must have misread the description of the pull request. I thought tildes would resolve to the `node_modules` directory, but looking closer I realize it won't. I managed to solve it however by installing the `node-sass-tilde-importer` module from npm and creating a `.sassrc.js` file in my project directory with the following content.
```javascript
// .sassrc.js
const importer = require('node-sass-tilde-importer')

module.exports = {
  importer
}
```

**Comment by 3stacks** [comment]
Hey folks, any idea when this one will be published to npm? I'm currently pointing to latest on github and it's causing issues with importing scoped packages for me. Loving the bundler though

**Comment by ellsclytn** [comment]
Does this permit recursive module resolution within an alias? I.e. if I have `alias.bar: 'foo/bar'` in my `package.json`, can I then `import qux from 'bar/baz/qux'` and have that resolve to `foo/bar/baz/qux`? A practical case would be if someone wanted to use Lodash over Underscore, or vice-versa, and wanted to use the nested module style of import, rather than destructuring.

**Comment by ckken** [comment]
preact-compat alias in package.json is no work for me .

**Comment by devongovett** [comment]
@ellsclytn yes, it works as you describe.

@ckken this PR hasn't been released to npm yet. That should work in the next release.

**Comment by lifeiscontent** [comment]
@devongovett I can't seem to get tilde paths to work... which version of parcel is this?

**Comment by davidnagli** [comment]
@lifeiscontent It hasn’t been released yet... Big release coming soon!

**Comment by derolf** [comment]
Aliasing from HTML files using the tilde syntax doesn‘t work. Will this also come?

**Comment by derolf** [comment]
I am working on the „externals“ issue. It would be very helpful if we could move the resolution step into the parse phase. This way aliasing works from ALL assets, i.e. you could write <script src=‘react/cjs/minified.js’> in HTML.

**Comment by Brouilles** [comment]
@davidnagli An approximation for the release of this update? So excited!

**Comment by Siyfion** [comment]
Does this also allow imports for modules residing in a monorepo root node_modules folder?

i.e. Will `~/example` search up the directory tree until it finds a node modules folder containing the example module, or will it stop when it gets to the project root folder?

**Comment by wesleyboar** [comment]
[1.70 has been released](https://github.com/parcel-bundler/parcel/releases). I am very much looking forward to [some documentation](https://github.com/parcel-bundler/website/issues/132).

---

I am trying to use `~/` for protject-root-relative paths—and I am failing…

```
/omg/absolute/path/scripts/src/site/site.js:21:28: Cannot resolve dependency '~/src/site/visual/is-logged-in.js' at '/omg/absolute/path/scripts/src/site/~/src/site/visual/is-logged-in.js'
```

The nearest `package.json` is at `/omg/absolute/path/scripts/package.json`.

**Comment by freeall** [comment]
I have the same issue as @wesleyboar. I have been used to doing something like `import Foo from ~/components/Foo`. Even in node core I remember this having been a longer discussion at one point.

To me it has some great advantages:
1. It allows us to quickly write requires/imports without thinking about how many `../` we have to put first.
2. When moving code around you don't also have to look through requires/imports and change all that code, which can lead to a reason not to move code to the appropriate place.

Since you've already implemented reading `alias` from `package.json` it would feel natural to add it to that api as well as something like this:
``` json
{
  "alias": {
    "~": "./src/app/"
  }
}
```

**Comment by 3stacks** [comment]
^ Maybe submit a new issue for this. Your request might get lost in a merged PR

**Comment by Stradivario** [comment]
Any news about this ?

**Comment by goyney** [comment]
It seems that folders aliased via the package.json file are not being transpiled by babel.

```
  "alias": {
    "clone-object": "../modules/clone-object",
    ....
   }
```

Instructing babel via a .babelrc file to transpile down to es5 doesn't apply to these aliased folders. How can we make that work?

**Comment by rocinante42** [comment]
> It seems that folders aliased via the package.json file are not being transpiled by babel.
> 
> ```
>   "alias": {
>     "clone-object": "../modules/clone-object",
>     ....
>    }
> ```
> 
> Instructing babel via a .babelrc file to transpile down to es5 doesn't apply to these aliased folders. How can we make that work?

Did you solve this somehow @goyney ?

**Comment by goyney** [comment]
Yeah, we solved it by moving to Webpack. 😄

**Comment by derolf** [comment]
Me too.

**Comment by mischnic** [comment]
@derolf @goyney Can you post a more complete code sample of your problem?

**Comment by goyney** [comment]
No, I cannot. We literally switched away from Parcel over a year ago.

**Pull request merged**
