### PR TITLE
fix(transformers): errors.map is not a function

### PR DESCRIPTION
**Pull request by sweetliquid**
# ↪️ Pull Request

## ✔️ PR Todo

- [ ] Added/updated unit tests for this change
- [ ] Filled out test instructions (In case there aren't any unit tests)
- [ ] Included links to related issues/PRs

### CODE REVIEW

**Comment by Shinyaigeek** [comment]
https://github.com/parcel-bundler/parcel/blob/v2/packages/transformers/html/src/dependencies.js#L117

The errors `collectDependencies` throw seems to be only array, so errors.map should be a valid function. Is there some case that parcel throws “errors.map is not a function” error in HTMLTransformer? ( if there is, please share reproduction)

**Comment by sweetliquid** [comment]
The error is thrown by other functions called by collectDependencies like `QUERIES[i].select` in browserslist package
```js
throw new BrowserslistError(
  'Unknown version ' + version + ' of ' + name
)
```

**Comment by sweetliquid** [comment]
I think errors those are not directly thrown by `collectDependencies` can be ignored(re-thown).

**Comment by sweetliquid** [comment]
If I create the `.browserslistrc` file with any wrong content like: `xxx`, it thrown `emit error:  TypeError: errors.map is not a function` when I run parcel build

**Comment by Shinyaigeek** [comment]
Oh I see, I cannot reproduce it but I feel this can happen and this change is reasonable. Thank you !

**Review by devongovett — APPROVED** [review]

**Pull request merged**
