### PR TITLE
Put filewatcher in a worker, for better stability and performance

### LINKED ISSUE #1308: Parcel can't watch files
# 🐛 bug report
Parcel can't watch files on windows

## 🎛 Configuration (.babelrc, package.json, cli command)

```bash
> cd "c:\my project folder"
> parcel
```

## 🤔 Expected Behavior
Watch files

## 😯 Current Behavior

```
Server running at http://localhost:1234
∞  Building bundle-url.js...
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: EPERM: operation not permitted, watch 'C:\Users\Weslei\AppData\Local\Microsoft\Windows\Temporary Internet Files'
    at FSWatcher.start (fs.js:1375:26)
    at Object.fs.watch (fs.js:1412:11)
    at createFsWatchInstance (C:\Users\Weslei\AppData\Local\Yarn\config\global\node_modules\chokidar\lib\nodefs-handler.js:37:15)
    at setFsWatchListener (C:\Users\Weslei\AppData\Local\Yarn\config\global\node_modules\chokidar\lib\nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (C:\Users\Weslei\AppData\Local\Yarn\config\global\node_modules\chokidar\lib\nodefs-handler.js:229:14)
    at FSWatcher.NodeFsHandler._handleDir (C:\Users\Weslei\AppData\Local\Yarn\config\global\node_modules\chokidar\lib\nodefs-handler.js:408:19)
    at FSWatcher.<anonymous> (C:\Users\Weslei\AppData\Local\Yarn\config\global\node_modules\chokidar\lib\nodefs-handler.js:456:19)
    at FSWatcher.<anonymous> (C:\Users\Weslei\AppData\Local\Yarn\config\global\node_modules\chokidar\lib\nodefs-handler.js:461:16)
    at FSReqWrap.oncomplete (fs.js:150:5)
Emitted 'error' event at:
    at FSWatcher._handleError (C:\Users\Weslei\AppData\Local\Yarn\config\global\node_modules\chokidar\index.js:260:10)
    at createFsWatchInstance (C:\Users\Weslei\AppData\Local\Yarn\config\global\node_modules\chokidar\lib\nodefs-handler.js:39:5)
    at setFsWatchListener (C:\Users\Weslei\AppData\Local\Yarn\config\global\node_modules\chokidar\lib\nodefs-handler.js:80:15)
    [... lines matching original stack trace ...]
    at FSReqWrap.oncomplete (fs.js:150:5)
```

## 💁 Possible Solution
Adding `ignorePermissionErrors: true` in `new FSWatcher` (Watcher.js) seems to solve the problem.

## 🔦 Context
This problem appeared after upgrading from version 1.6.1 to 1.8.1

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.8.1
| Node             | 10.0.0
| npm/Yarn         | yarn 1.6.0
| Operating System | Windows 10

### LINKED ISSUE #1331: Bundler freezes since 1.8.0
# 🐛 Bug report

## 🤔 Expected Behavior

The bundler should finish the process.

## 😯 Current Behavior

Bundler freezes on build and does not finish at all. Previously I had version 1.7.0 and sometimes it was frozen as well but that was only several times and when restarted it mostly worked. After upgrade to version 1.8.1 I tried to build approx. 20 times but it did not finish at all. No changes in project. I tried version 1.8.0 and it did not work either.

## 🔦 Context

My project is just index.html with references scripts. Typescript is used in project. App based on React and Bootstrap.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | ^1.8.0 |
| Node             | 9.11.1 |
| npm         | 5.6.0 |
| Operating System | Windows 10 |

### LINKED ISSUE #1342: Parcel sometimes fails to start properly
# 🐛 bug report

He can sometimes work, sometimes he can't work.

When I remove the `scss` file it may improve, but I'm not sure if the problem is there.

Perhaps it is related to the loading mechanism of the module?

Faster processing when there are fewer modules, When the number of modules is large, the dependency is more complicated and the relationship is not handled properly, Causes the process to exit abnormally.

## 🎛 Configuration (.babelrc, package.json, cli command)

```json
{
  "name": "parcel",
  "version": "1.0.0",
  "scripts": {
    "dev": "parcel ./src/view/*.html"
  },
  "devDependencies": {
    "node-sass": "^4.9.0",
    "parcel-bundler": "^1.8.1"
  }
}

```

## 🤔 Expected Behavior

Normal start work

## 😯 Current Behavior

Sometimes quit abnormally

Comparison of loading `scss` files and removing `scss`

## 🔦 Context

```bash
parcel ./src/view/*.html
```

```bash
yarn run v1.5.1
$ parcel ./src/view/*.html
Server running at http://localhost:1234
⏳  Building hmr-runtime.js...
error An unexpected error occurred: "Command failed.
Exit signal: SIGSEGV
Command: sh
Arguments: -c parcel ./src/view/*.html
Directory: /Users/WYH/Desktop/parcel
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/Users/WYH/Desktop/parcel/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## 💻 Code Sample
`index.html :`
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="../style/index.scss">
</head>
<body>
  hello world
</body>
</html>
```
`base.scss :`
```scss
body{
  background: red;
}
```
`index.scss :`
```scss
@import './base.scss';
.btn{
    width: 100px;
    height: 38px;
    border: 1px solid #ae2616;
    color: #ae2616;
    outline: none;
    background-color: transparent;
    cursor: pointer;
}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.8.1
| Node             | 9.9.0
| npm/Yarn         | 1.5.1
| Operating System | macOS High Soerra `10.13.4`

### LINKED ISSUE #1394: Extremely slow on FAT partitions (Win 10 x64)
# 🐛 bug report

### `package.json`
```js
{
  "name": "test_parcel_vue",
  "version": "1.0.0",
  "author": "eGust",
  "license": "MIT",
  "scripts": {
    "dev": "parcel src/index.html"
  },
  "dependencies": {
    "vue": "^2.5.16"
  },
  "devDependencies": {
    "@vue/component-compiler-utils": "^1.2.1",
    "parcel": "^1.8.1",
    "pug": "^2.0.3",
    "stylus": "^0.54.5",
    "vue-hot-reload-api": "^2.3.0",
    "vue-template-compiler": "^2.5.16"
  }
}
```

## 🤔 Expected Behavior

`parcel src/index.html` should build in a few seconds. 

## 😯 Current Behavior

It will take more than 30s for first build on my exFAT partition. Once the server had started, the first time rebuild is also slow (~10s), the next will be normal (~200ms for the small demo).

I tried the same code on NTFS it usually took ~7s which is acceptable. 

I created FAT/FAT32/exFAT/NTFS ramdisks on Win10. This issue is reproducable on all FAT formats. 

I also created a vfat ramdisk on Ubuntu. `parcel src/index.html` finished in 4s. 

### About `parcel build src/index.js`
I also tried `parcel build src/index.js`  on exFAT and NTFS. 

exFAT
```
$ rm -rf .cache/ && time parcel build src/index.js
√  Built in 5.94s.

dist\index.js     63.55 KB    8.54s
dist\index.css        43 B    4.88s
dist\index.map         0 B    8.65s

real    0m7.066s
user    0m0.015s
sys     0m0.242s
```

NTFS
```
$ rm -rf .cache/ && time parcel build src/index.js
√  Built in 4.81s.

dist\index.js     63.56 KB    6.43s
dist\index.css        43 B    3.75s
dist\index.map         0 B    6.53s

real    0m5.998s
user    0m0.076s
sys     0m0.196s
```

### Steps to reproduce:
1. Create a ramdisk on Windows: `imdisk -a -s 256M -o rem -m R: -p "/FS:FAT32 /Q /Y"`
1. Make a dir and create/copy all 4 files into it.
1. `yarn` install and `yarn dev` to execute `parcel src/index.html`

### `src/App.vue`
```vue
<template lang="pug">
  #app Vue Parcel
</template>

<script>
export default {
  name: 'App',
};
</script>

<style lang="stylus">
*
  box-sizing border-box
</style>
```

### `src/index.html`
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <title>Vue Parcel</title>
  </head>
  <body>
    <div id="app"></div>
    <script src="./index.js"></script>
  </body>
</html>
```
### `src/index.js`
```js
import Vue from 'vue';
import App from './App';

new Vue({
  el: '#app',
  render: h => h(App),
});
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.8.1 |
| Node             | 8.11.1 | 
| npm/Yarn         | yarn v1.6.0 |
| Operating System | Win 10.0.17134.48 x64 |

### PR DESCRIPTION
**Pull request by DeMoorJasper**
This PR puts FSWatcher into a worker, this helps to add extra stability.

Fixes:
* Segfault error inside fsevents
* Freezing on windows
* Significant performance boost in watch mode

Some tests I've done on performance:

| Description   | With current master   | with fswatcher-child     |
| --- |---                    | ---                      |
| Very small app without cache (On Mac OS X High Sierra)   | 8.8secs               | 4secs                    |
| Small app with a lot of requires and import without cache (On windows 10) | 22secs | 7secs |

`fswatcher-child`: https://github.com/DeMoorJasper/fswatcher-child

Closes #1342 Closes #1331 Closes #1394 Closes #1357 Closes #1308

### CODE REVIEW

**Comment by DeMoorJasper** [comment]
Tests pass now, only the Cargo one fails which is unrelated to this PR

**Comment by devongovett** [comment]
hmm interesting idea. what do you think about using our existing worker infra in parcel for this?

**Comment by DeMoorJasper** [comment]
@devongovett Thought it would be a better idea to make it lightweight.
The main goal was to sandbox chokidar from parcel to prevent errors and crashes. It doesn’t need multiple workers and localworker in this case wouldn’t prevent the crashes

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by DeMoorJasper** [comment]
@devongovett I've added some benchmarks, as I've just discovered after running the inspector on a project that it also boosts dev builds on non windows machines quite a lot

**Pull request merged**
