### PR TITLE
Ignore: `url(#...)` (`behavior` property)

### LINKED ISSUE #3873: Received URL without a pathname for CSS behavior URL
Parcel version: 2.0.0-alpha.3.2

When Parcel comes across something like `behavior: url(#behavior)` in CSS files, it attempts to resolve the URL, but since it only contains a fragment (which is the behavior identifier), it throws:

```
🚨 Error: Received URL without a pathname
```

I know `behavior` was specific to older Internet Explorer releases and not supported by modern browsers, but some of these are in [dependencies](https://github.com/mapbox/mapbox.js/blob/publisher-production/theme/style.css#L155), so we have no control over how these URLs are being specified.

I was looking at writing a custom resolver to try and ignore these paths, but it seems that the `pathname` check comes before any resolvers can inspect it.

Is this a bug, or is there a way to work around this?

A possible solution for this might be to ignore the URL altogether if it contains a fragment but no pathname.

### PR DESCRIPTION
**Pull request by mischnic**
# ↪️ Pull Request

Some libraries still include these statements in their stylesheets (see issue).

Closes #3873

**Should `url(#foo)` only be allowed in a `behavior` statement or everywhere?**

## 💻 Examples

`behavior` is non standard (IE)

```css
.lvml {
	behavior: url(#default#VML);
	display: inline-block;
	position: absolute;
}
```

### CODE REVIEW

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>packages/benchmarks/kitchen-sink ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 9.43s | -161.00ms |
| Cached | 8.36s | +144.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/parcel.ff215454.webp | 102.94kb | +0.00b | 185.00ms | +30.00ms ⚠️ |
| dist/modern/parcel.76ee4591.webp | 102.94kb | +0.00b | 184.00ms | +29.00ms ⚠️ |
| dist/legacy/index.js | 243.00b | +0.00b | 432.00ms | +67.00ms ⚠️ |
| dist/modern/index.js | 215.00b | +0.00b | 427.00ms | +67.00ms ⚠️ |
| dist/legacy/index.css | 29.00b | +0.00b | 1.30s | +110.00ms ⚠️ |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/parcel.ff215454.webp | 102.94kb | +0.00b | 13.00ms | +1.00ms ⚠️ |
| dist/legacy/index.js | 243.00b | +0.00b | 17.00ms | +1.00ms ⚠️ |
| dist/modern/index.css | 29.00b | +0.00b | 11.00ms | +1.00ms ⚠️ |

</p></details>

<details><summary>packages/benchmarks/react-hn ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 13.05s | -806.00ms 🚀 |
| Cached | 9.33s | -10.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/module/index.js | 34.02kb | +0.00b | 1.86s | -111.00ms 🚀 |
| dist/main/index.js | 34.00kb | +0.00b | 1.87s | -110.00ms 🚀 |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/module/index.js | 34.03kb | +0.00b | 8.00ms | -1.00ms 🚀 |

</p></details>

<details><summary>packages/benchmarks/ak-editor 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/251115202376892938)**

**Comment by devongovett** [comment]
Got a .only in the test 😉

**Comment by mischnic** [comment]
😬

**Comment by iamyellow** [comment]
i think we need to check this on .less (maybe other asset types?)  here:
https://github.com/parcel-bundler/parcel/blob/v2/packages/transformers/less/src/LessTransformer.js#L56
(since whenever a less file has `url(#...)` we get the same error)

**Comment by pojntfx** [comment]
@iamyellow This is currently blocking Ant Design usage.

**Comment by kidandcat** [comment]
It would be great to have Ant Design usable with Parcel2 asap.

**Comment by mischnic** [comment]
Less support: https://github.com/parcel-bundler/parcel/pull/4475

**Comment by pojntfx** [comment]
@mischnic Thanks so much! This just enabled Ant Design usage: https://github.com/parcel-bundler/parcel/issues/907#issuecomment-615678300

**Pull request merged**
