### PR TITLE
chore: switch from `browserslist-rs` to `oxc-browserslist`

### PR DESCRIPTION
**Pull request by cijiugechu**
# ↪️ Pull Request

[oxc-browserslist](https://github.com/oxc-project/oxc-browserslist?tab=readme-ov-file) is a fork of [browserslist-rs](https://github.com/browserslist/browserslist-rs) with improved performance, actively maintained by [oxc-project](https://github.com/oxc-project). The following are the changes made to it after the fork:

> * reduced compilation speed from one minute to a few seconds
> * removed all unnecessary, heavy or slow dependencies: `ahash`, `chrono`, `either`, `indexmap`, `itertools`, `once_cell`, `string_cache`
> * improved some runtime performance, e.g. [improve sort method](https://github.com/oxc-project/oxc-browserslist/pull/28), [precompute versions](https://github.com/oxc-project/oxc-browserslist/pull/10)

## ✔️ PR Todo

- [ ] Added/updated unit tests for this change
- [ ] Filled out test instructions (In case there aren't any unit tests)
- [ ] Included links to related issues/PRs

### CODE REVIEW

**Comment by devongovett** [comment]
One potential downside to this is that we'd end up having two browserslist implementations (and associated data) in the binary since swc already uses browserslist-rs too. Was there any thought of contributing the changes from this fork to the upstream project?

**Comment by cijiugechu** [comment]
> One potential downside to this is that we'd end up having two browserslist implementations (and associated data) in the binary since swc already uses browserslist-rs too. Was there any thought of contributing the changes from this fork to the upstream project?

I agree with you, I will submit a PR to the upstream repository.

**Comment by mischnic** [comment]
There's an ongoing discussion here as well with other maintainers: https://github.com/swc-project/swc/pull/9014

**Comment by mischnic** [comment]
We bumped `browserslist-rs` to the supposedly faster 0.16.0 by now.

**Pull request closed without merging**
