### PR TITLE
Fix htmlnano tests

### PR DESCRIPTION
**Pull request by mischnic**
# ↪️ Pull Request

The version upgrade in https://github.com/parcel-bundler/parcel/pull/2506 seems to have changed the output regarding `collapseWhitespace`. Setting that htmlnano option to `all`  would make current tests pass, but is not always safe ([see here](https://github.com/posthtml/htmlnano#collapsewhitespace))

## ✔️ PR Todo

- [x] Added/updated unit tests for this change
- [x] Filled out test instructions (In case there aren't any unit tests)
- [ ] Included links to related issues/PRs

### CODE REVIEW

**Comment by mischnic** [comment]
> Appears this doesn't fix the tests?

Strange, it does locally.
Only some commits on master after the mentioned PR fail due to the additional newline, but not all.
Also, that PR shouldn't have changed anything regarding testing, the lockfile already contained that version. 🤔

**Comment by devongovett** [comment]
Yeah seems like it's still failing on windows

**Comment by mischnic** [comment]
> Yeah seems like it's still failing on windows

Strange:
`<!doctype html><html><head><title>Test</title></head><body> <h1>Other page</h1> </body></html>`

**Comment by DanielRuf** [comment]
Windows uses `\r\n` afaik.

**Comment by millette** [comment]
Maybe use https://nodejs.org/dist/latest-v10.x/docs/api/os.html#os_os_eol in that case?

**Comment by DanielRuf** [comment]
> Maybe use [nodejs.org/dist/latest-v10.x/docs/api/os.html#os_os_eol](https://nodejs.org/dist/latest-v10.x/docs/api/os.html#os_os_eol) in that case?

Definitely better and something what I would recommend. But this could fail in some cases but let's try it.

**Comment by DanielRuf** [comment]
Will do it probably later this week, currently checking some projects and working on a few other CI fixes.

**Pull request closed without merging**
