### PR TITLE
Simplify diagnostics

### LINKED ISSUE #5078: `codeHighlights` is sometimes an object and sometimes an array of objects
# 🐛 bug report

If I'm reading [the documentation](https://v2.parceljs.org/plugin-system/logger/#diagnosticcodeframe) right, it states that on a code frame, `codeHighlights` should be an array of code highlight objects. This seems to be true some of the time, but at other times, a code frame within a diagnostic within an error will contain `codeHighlights` whose value is a single code highlight object. This inconsistency makes handling code highlights objects on errors more complex than it really needs to be.

## 🎛 Configuration (.babelrc, package.json, cli command)

I have this set up as an isolated repo here: https://github.com/Aaronius/parcel2bug/tree/code-highlights. Just follow the readme.

.babelrc:

```
{
  "bundler": "@parcel/bundler-default",
  "transformers": {
    "*.js": ["@parcel/transformer-babel","@parcel/transformer-js"]
  },
  "runtimes": {
    "browser": ["@parcel/runtime-js"]
  },
  "packagers": {
    "*.js": "@parcel/packager-js"
  },
  "namers": ["@parcel/namer-default"],
  "resolvers": ["@parcel/resolver-default"],
  "reporters": ["@parcel/reporter-cli"]
}
```

package.json:

```
{
  "name": "parcel2bug",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "parcel": "^2.0.0-nightly.385"
  }
}
```

build call:

```
const bundler = new Parcel({
      entries: path.join(__dirname, 'src/index.js'),
      sourceMaps: false,
      patchConsole: false,
      autoinstall: false,
      scopeHoist: true,
      disableCache: true,
      inputFS,
      outputFS,
      workerFarm,
      distDir: VIRTUAL_DIST_DIR,
    });

    await bundler.run();
```

## 🤔 Expected Behavior
`codeHighlights` should always be an array.

## 😯 Current Behavior
`codeHighlights` is sometimes an object.

## 💁 Possible Solution
Always make `codeHighlights` an array.

## 🔦 Context
We're doing some custom error handling and manipulation in order to present a specifically crafted error message to users of our build service.

## 💻 Code Sample
https://github.com/Aaronius/parcel2bug/tree/code-highlights. Just follow the readme.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.385
| Node             | 12.12.0
| npm/Yarn         | npm 6.13.4
| Operating System | Mac Mojave

### PR DESCRIPTION
**Pull request by DeMoorJasper**
# ↪️ Pull Request

This PR simplifies diagnostics, so codehighlights in diagnostics are always arrays and a ThrowableDiagnostic always takes in an array of diagnostics.

This is a breaking change, I can add a legacy diagnostic option back to ThrowableDiagnostic but I thought it would be better to just fail the plugins that rely on this option to ensure they update their plugins instead.

Closes #5078

## ✔️ PR Todo

- [x] Added/updated unit tests for this change
- [x] Filled out test instructions (In case there aren't any unit tests)
- [x] Included links to related issues/PRs

### CODE REVIEW

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>Kitchen Sink ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 6.00s | +202.00ms |
| Cached | 2.08s | +55.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/parcel.d5807e82.webp | 102.94kb | +0.00b | 231.00ms | +18.00ms ⚠️ |
| dist/modern/parcel.d5807e82.webp | 102.94kb | +0.00b | 230.00ms | +17.00ms ⚠️ |
| dist/modern/index.7bc22a8b.css | 77.00b | +0.00b | 1.23s | -188.00ms 🚀 |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/parcel.d5807e82.webp | 102.94kb | +0.00b | 248.00ms | +92.00ms ⚠️ |
| dist/modern/parcel.d5807e82.webp | 102.94kb | +0.00b | 248.00ms | +92.00ms ⚠️ |
| dist/legacy/index.45cccf70.js | 1.10kb | +0.00b | 486.00ms | +144.00ms ⚠️ |
| dist/modern/index.1964d1f6.js | 1.10kb | +0.00b | 485.00ms | +144.00ms ⚠️ |
| dist/legacy/index.html | 701.00b | +0.00b | 487.00ms | +144.00ms ⚠️ |
| dist/modern/index.html | 701.00b | +0.00b | 485.00ms | +144.00ms ⚠️ |
| dist/legacy/index.b3acc8eb.css | 77.00b | +0.00b | 486.00ms | +144.00ms ⚠️ |
| dist/modern/index.7bc22a8b.css | 77.00b | +0.00b | 485.00ms | +144.00ms ⚠️ |

</p></details>

<details><summary>React HackerNews ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 27.32s | +1.39s ⚠️ |
| Cached | 2.12s | +7.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/PermalinkedComment.9c5ad065.js | 4.22kb | +0.00b | 4.97s | -5.19s 🚀 |
| dist/UserProfile.c1927888.js | 1.62kb | +0.00b | 4.97s | -5.16s 🚀 |
| dist/NotFound.f8a0616d.js | 387.00b | +0.00b | 4.97s | -5.16s 🚀 |
| dist/logo.24c8bf9e.png | 274.00b | +0.00b | 158.00ms | +10.00ms ⚠️ |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.js | 478.68kb | +0.00b | 249.00ms | -121.00ms 🚀 |
| dist/PermalinkedComment.9c5ad065.js | 4.22kb | +0.00b | 247.00ms | -121.00ms 🚀 |
| dist/UserProfile.c1927888.js | 1.62kb | +0.00b | 247.00ms | -121.00ms 🚀 |
| dist/NotFound.f8a0616d.js | 387.00b | +0.00b | 247.00ms | -121.00ms 🚀 |
| dist/logo.24c8bf9e.png | 274.00b | +0.00b | 192.00ms | -86.00ms 🚀 |

</p></details>

<details><summary>AtlasKit Editor ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 2.85m | -13.75s 🚀 |
| Cached | 4.58s | -547.00ms 🚀 |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.2180c879.js | 2.72mb | +0.00b | 1.52m | -6.54s 🚀 |
| dist/pdfRenderer.15a6a023.js | 1.11mb | +0.00b | 49.44s | -7.53s 🚀 |
| dist/editorView.e06544fb.js | 587.12kb | +0.00b | 1.26m | -10.22s 🚀 |
| dist/popup.6c453e3c.js | 169.96kb | +0.00b | 49.44s | +15.18s ⚠️ |
| dist/Toolbar.83ac0b6e.js | 92.34kb | +0.00b | 53.98s | -7.28s 🚀 |
| dist/EmojiPickerComponent.ae601247.js | 75.29kb | +0.00b | 9.45s | -1.61s 🚀 |
| dist/media-viewer.bcba38b3.js | 71.96kb | +0.00b | 13.74s | -2.62s 🚀 |
| dist/card.645a5c17.js | 55.01kb | +0.00b | 11.90s | -1.77s 🚀 |
| dist/card.0313bac8.js | 52.78kb | +0.00b | 50.78s | -8.83s 🚀 |
| dist/Modal.19ffed32.js | 41.27kb | +0.00b | 5.19s | -2.16s 🚀 |
| dist/component.d7c29980.js | 30.70kb | +0.00b | 2.18s | -1.70s 🚀 |
| dist/component.54080a26.js | 22.50kb | +0.00b | 5.19s | -2.16s 🚀 |
| dist/DatePicker.0df05dac.js | 21.21kb | +0.00b | 9.45s | -1.61s 🚀 |
| dist/EmojiPickerComponent.7dc0ebd0.js | 18.23kb | +0.00b | 9.45s | -1.61s 🚀 |
| dist/dropzone.7c704bdb.js | 17.27kb | +0.00b | 50.25s | -7.21s 🚀 |
| dist/smartMediaEditor.9623570c.js | 16.87kb | +0.00b | 52.73s | -45.00s 🚀 |
| dist/js.5733a017.js | 16.40kb | +0.00b | 5.19s | -2.16s 🚀 |
| dist/ui.fee77548.js | 13.97kb | +0.00b | 11.89s | -1.73s 🚀 |
| dist/workerHasher.1e706e77.js | 11.75kb | +0.00b | 10.24s | -1.64s 🚀 |
| dist/EmojiTypeAheadComponent.1990d771.js | 8.67kb | +0.00b | 10.23s | -1.65s 🚀 |
| dist/component.77c0f682.js | 6.05kb | +0.00b | 5.19s | -2.16s 🚀 |
| dist/card.383bd9bd.js | 5.61kb | +0.00b | 11.89s | -1.73s 🚀 |
| dist/media-viewer.59c17dad.js | 3.92kb | +0.00b | 13.74s | -2.61s 🚀 |
| dist/EmojiPickerComponent.627aca6b.js | 3.58kb | +0.00b | 9.45s | -45.10s 🚀 |
| dist/index.ac562c80.css | 3.46kb | +0.00b | 1.52m | +28.69s ⚠️ |
| dist/png-chunks-extract.a844fdb6.js | 3.41kb | +0.00b | 5.19s | -2.16s 🚀 |
| dist/dropzone.3c67f0a6.js | 3.23kb | +0.00b | 27.86s | -3.87s 🚀 |
| dist/Modal.0304b9ed.js | 3.08kb | +0.00b | 4.04s | -2.22s 🚀 |
| dist/clipboard.da112b6e.js | 2.75kb | +0.00b | 50.25s | -7.21s 🚀 |
| dist/16.290b4a43.js | 2.38kb | +0.00b | 2.18s | -1.66s 🚀 |
| dist/EmojiUploadComponent.d54a1fc6.js | 2.18kb | +0.00b | 10.23s | -1.65s 🚀 |
| dist/card.eea6ad8c.js | 2.03kb | +0.00b | 13.74s | -2.62s 🚀 |
| dist/ResourcedEmojiComponent.abe8596c.js | 2.00kb | +0.00b | 3.99s | -1.94s 🚀 |
| dist/date.231500d2.js | 1.73kb | +0.00b | 5.68s | -2.21s 🚀 |
| dist/16.d16f14ed.js | 1.73kb | +0.00b | 5.52s | -2.23s 🚀 |
| dist/images.80c92f5e.js | 1.67kb | +0.00b | 5.84s | -2.15s 🚀 |
| dist/16.1b6ca79f.js | 1.66kb | +0.00b | 6.00s | -2.07s 🚀 |
| dist/feedback.d5590b34.js | 1.64kb | +0.00b | 6.21s | -4.85s 🚀 |
| dist/browser.75813db0.js | 1.61kb | +0.00b | 50.25s | -7.21s 🚀 |
| dist/workerHasher.6d5b22d7.js | 1.54kb | +0.00b | 10.23s | -1.65s 🚀 |
| dist/workerHasher.fa198233.js | 1.54kb | +0.00b | 52.73s | -45.01s 🚀 |
| dist/list-number.c35f9589.js | 1.46kb | +0.00b | 5.97s | -2.13s 🚀 |
| dist/status.8ab4226b.js | 1.46kb | +0.00b | 51.79s | +43.60s ⚠️ |
| dist/16.9ccb5b28.js | 1.38kb | +0.00b | 5.39s | -2.15s 🚀 |
| dist/code.3dd71280.js | 1.38kb | +0.00b | 5.68s | -2.21s 🚀 |
| dist/16.19c93285.js | 1.33kb | +0.00b | 6.00s | -2.07s 🚀 |
| dist/16.c7751e34.js | 1.33kb | +0.00b | 5.39s | -2.15s 🚀 |
| dist/16.51049e2c.js | 1.32kb | +0.00b | 2.15s | -1.69s 🚀 |
| dist/16.18344f47.js | 1.31kb | +0.00b | 5.68s | -2.20s 🚀 |
| dist/link.2f4427e6.js | 1.30kb | +0.00b | 5.97s | -2.13s 🚀 |
| dist/heading6.fdbbdf4d.js | 1.30kb | +0.00b | 6.21s | -2.11s 🚀 |
| dist/heading3.2113b7a1.js | 1.29kb | +0.00b | 6.20s | -2.11s 🚀 |
| dist/16.2c4c1846.js | 1.27kb | +0.00b | 5.52s | -2.23s 🚀 |
| dist/emoji.93ae61d3.js | 1.23kb | +0.00b | 5.84s | -2.14s 🚀 |
| dist/16.d17ab186.js | 1.23kb | +0.00b | 5.52s | -2.23s 🚀 |
| dist/16.436f097f.js | 1.21kb | +0.00b | 2.15s | -1.69s 🚀 |
| dist/16.b4da0acb.js | 1.19kb | +0.00b | 5.52s | -2.22s 🚀 |
| dist/16.02c68c4f.js | 1.18kb | +0.00b | 5.68s | -2.20s 🚀 |
| dist/heading5.e195aab1.js | 1.17kb | +0.00b | 6.21s | -2.11s 🚀 |
| dist/expand.450f3aea.js | 1.16kb | +0.00b | 9.45s | -1.61s 🚀 |
| dist/media-card-analytics-error-boundary.2323af57.js | 1.15kb | +0.00b | 27.86s | -3.88s 🚀 |
| dist/16.b46ef690.js | 1.14kb | +0.00b | 2.15s | -1.69s 🚀 |
| dist/16.4e3b0235.js | 1.14kb | +0.00b | 5.39s | -2.15s 🚀 |
| dist/16.9ba230ea.js | 1.13kb | +0.00b | 6.04s | -2.30s 🚀 |
| dist/16.a37df53b.js | 1.13kb | +0.00b | 5.39s | -2.15s 🚀 |
| dist/16.9adb4ec7.js | 1.13kb | +0.00b | 5.39s | -2.15s 🚀 |
| dist/16.eafe1a11.js | 1.13kb | +0.00b | 6.00s | -2.07s 🚀 |
| dist/heading2.a2a1be3f.js | 1.11kb | +0.00b | 51.79s | +43.48s ⚠️ |
| dist/16.3920766f.js | 1.10kb | +0.00b | 3.99s | -1.94s 🚀 |
| dist/component.6600f83e.js | 1.07kb | +0.00b | 3.99s | -1.94s 🚀 |
| dist/mention.4d64e059.js | 1.07kb | +0.00b | 5.97s | -2.13s 🚀 |
| dist/heading4.ec980e93.js | 1.06kb | +0.00b | 6.21s | -2.11s 🚀 |
| dist/16.afcb09b6.js | 1.05kb | +0.00b | 5.52s | -2.23s 🚀 |
| dist/layout.52ba15f7.js | 1.05kb | +0.00b | 5.84s | -2.15s 🚀 |
| dist/divider.16defde6.js | 1.03kb | +0.00b | 5.84s | -2.14s 🚀 |
| dist/quote.aa25b83c.js | 1.02kb | +0.00b | 6.06s | -2.13s 🚀 |
| dist/action.9aa72b39.js | 1.00kb | +0.00b | 5.68s | -2.20s 🚀 |
| dist/decision.20244046.js | 1010.00b | +0.00b | 5.84s | -2.14s 🚀 |
| dist/panel-warning.97a0e3b3.js | 1008.00b | +0.00b | 6.06s | -48.40s 🚀 |
| dist/list.c9147a62.js | 978.00b | +0.00b | 5.97s | -2.13s 🚀 |
| dist/heading1.7d899ba5.js | 976.00b | +0.00b | 51.79s | +43.59s ⚠️ |
| dist/panel-error.8d11e8b7.js | 906.00b | +0.00b | 5.97s | -2.13s 🚀 |
| dist/panel.a28c56ee.js | 897.00b | +0.00b | 6.06s | -2.13s 🚀 |
| dist/table.5a4874ee.js | 889.00b | +0.00b | 51.79s | +43.59s ⚠️ |
| dist/panel-success.9b923e58.js | 845.00b | +0.00b | 6.06s | -48.40s 🚀 |
| dist/panel-note.97a4d541.js | 841.00b | +0.00b | 6.06s | -48.40s 🚀 |
| dist/media-picker-analytics-error-boundary.f8ddfee3.js | 839.00b | +0.00b | 27.86s | -3.87s 🚀 |
| dist/media-card-analytics-error-boundary.663369b9.js | 835.00b | +0.00b | 11.88s | -1.73s 🚀 |
| dist/media-card-analytics-error-boundary.73ba4074.js | 835.00b | +0.00b | 50.78s | -46.96s 🚀 |
| dist/media-viewer-analytics-error-boundary.0afa7031.js | 755.00b | +0.00b | 13.74s | -2.60s 🚀 |
| dist/EmojiPickerComponent.2e54b9c6.js | 535.00b | +0.00b | 10.23s | -1.65s 🚀 |
| dist/simpleHasher.16c8bf41.js | 528.00b | +0.00b | 11.88s | -1.73s 🚀 |
| dist/simpleHasher.a29b2a8e.js | 528.00b | +0.00b | 52.73s | -45.01s 🚀 |
| dist/index.html | 119.00b | +0.00b | 891.00ms | -2.21s 🚀 |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.2180c879.js | 2.72mb | -4.00b 🚀 | 473.00ms | -42.00ms 🚀 |
| dist/pdfRenderer.15a6a023.js | 1.11mb | +0.00b | 470.00ms | -29.00ms 🚀 |
| dist/editorView.e06544fb.js | 587.12kb | +0.00b | 469.00ms | -30.00ms 🚀 |
| dist/popup.6c453e3c.js | 169.96kb | +0.00b | 470.00ms | -30.00ms 🚀 |
| dist/Toolbar.83ac0b6e.js | 92.34kb | +0.00b | 469.00ms | -30.00ms 🚀 |
| dist/EmojiPickerComponent.ae601247.js | 75.29kb | +0.00b | 471.00ms | -40.00ms 🚀 |
| dist/media-viewer.bcba38b3.js | 71.96kb | +0.00b | 470.00ms | -29.00ms 🚀 |
| dist/card.645a5c17.js | 55.01kb | +0.00b | 470.00ms | -41.00ms 🚀 |
| dist/card.0313bac8.js | 52.78kb | +0.00b | 469.00ms | -30.00ms 🚀 |
| dist/Modal.19ffed32.js | 41.27kb | +0.00b | 472.00ms | -42.00ms 🚀 |
| dist/component.d7c29980.js | 30.70kb | +0.00b | 472.00ms | -42.00ms 🚀 |
| dist/component.54080a26.js | 22.50kb | +0.00b | 472.00ms | -42.00ms 🚀 |
| dist/DatePicker.0df05dac.js | 21.21kb | +0.00b | 471.00ms | -40.00ms 🚀 |
| dist/EmojiPickerComponent.7dc0ebd0.js | 18.23kb | +0.00b | 471.00ms | -40.00ms 🚀 |
| dist/dropzone.7c704bdb.js | 17.27kb | +0.00b | 469.00ms | -30.00ms 🚀 |
| dist/smartMediaEditor.9623570c.js | 16.87kb | +0.00b | 469.00ms | -30.00ms 🚀 |
| dist/js.5733a017.js | 16.40kb | +0.00b | 472.00ms | -42.00ms 🚀 |
| dist/ui.fee77548.js | 13.97kb | +0.00b | 470.00ms | -41.00ms 🚀 |
| dist/workerHasher.1e706e77.js | 11.75kb | +0.00b | 470.00ms | -41.00ms 🚀 |
| dist/EmojiTypeAheadComponent.1990d771.js | 8.67kb | +0.00b | 470.00ms | -41.00ms 🚀 |
| dist/component.77c0f682.js | 6.05kb | +0.00b | 472.00ms | -42.00ms 🚀 |
| dist/card.383bd9bd.js | 5.61kb | +0.00b | 470.00ms | -41.00ms 🚀 |
| dist/media-viewer.59c17dad.js | 3.92kb | +0.00b | 470.00ms | -29.00ms 🚀 |
| dist/EmojiPickerComponent.627aca6b.js | 3.58kb | +0.00b | 470.00ms | -41.00ms 🚀 |
| dist/index.ac562c80.css | 3.46kb | +0.00b | 469.00ms | -30.00ms 🚀 |
| dist/png-chunks-extract.a844fdb6.js | 3.41kb | +0.00b | 472.00ms | -42.00ms 🚀 |
| dist/dropzone.3c67f0a6.js | 3.23kb | +0.00b | 470.00ms | -30.00ms 🚀 |
| dist/Modal.0304b9ed.js | 3.08kb | +0.00b | 472.00ms | -42.00ms 🚀 |
| dist/clipboard.da112b6e.js | 2.75kb | +0.00b | 470.00ms | -30.00ms 🚀 |
| dist/16.290b4a43.js | 2.38kb | +0.00b | 472.00ms | -42.00ms 🚀 |
| dist/EmojiUploadComponent.d54a1fc6.js | 2.18kb | +0.00b | 470.00ms | -41.00ms 🚀 |
| dist/card.eea6ad8c.js | 2.03kb | +0.00b | 470.00ms | -29.00ms 🚀 |
| dist/ResourcedEmojiComponent.abe8596c.js | 2.00kb | +0.00b | 472.00ms | -42.00ms 🚀 |
| dist/date.231500d2.js | 1.73kb | +0.00b | 471.00ms | -41.00ms 🚀 |
| dist/16.d16f14ed.js | 1.73kb | +0.00b | 471.00ms | -42.00ms 🚀 |
| dist/images.80c92f5e.js | 1.67kb | +0.00b | 471.00ms | -42.00ms 🚀 |
| dist/16.1b6ca79f.js | 1.66kb | +0.00b | 472.00ms | -42.00ms 🚀 |
| dist/feedback.d5590b34.js | 1.64kb | +0.00b | 471.00ms | -40.00ms 🚀 |
| dist/browser.75813db0.js | 1.61kb | +0.00b | 470.00ms | -29.00ms 🚀 |
| dist/workerHasher.6d5b22d7.js | 1.54kb | +0.00b | 470.00ms | -41.00ms 🚀 |
| dist/workerHasher.fa198233.js | 1.54kb | +0.00b | 469.00ms | -30.00ms 🚀 |
| dist/list-number.c35f9589.js | 1.46kb | +0.00b | 471.00ms | -41.00ms 🚀 |
| dist/status.8ab4226b.js | 1.46kb | +0.00b | 471.00ms | -41.00ms 🚀 |
| dist/16.9ccb5b28.js | 1.38kb | +0.00b | 472.00ms | -41.00ms 🚀 |
| dist/code.3dd71280.js | 1.38kb | +0.00b | 471.00ms | -41.00ms 🚀 |
| dist/16.19c93285.js | 1.33kb | +0.00b | 472.00ms | -42.00ms 🚀 |
| dist/16.c7751e34.js | 1.33kb | +0.00b | 472.00ms | -42.00ms 🚀 |
| dist/16.51049e2c.js | 1.32kb | +0.00b | 472.00ms | -42.00ms 🚀 |
| dist/16.18344f47.js | 1.31kb | +0.00b | 471.00ms | -42.00ms 🚀 |
| dist/link.2f4427e6.js | 1.30kb | +0.00b | 471.00ms | -41.00ms 🚀 |
| dist/heading6.fdbbdf4d.js | 1.30kb | +0.00b | 471.00ms | -41.00ms 🚀 |
| dist/heading3.2113b7a1.js | 1.29kb | +0.00b | 471.00ms | -41.00ms 🚀 |
| dist/16.2c4c1846.js | 1.27kb | +0.00b | 471.00ms | -42.00ms 🚀 |
| dist/emoji.93ae61d3.js | 1.23kb | +0.00b | 471.00ms | -42.00ms 🚀 |
| dist/16.d17ab186.js | 1.23kb | +0.00b | 471.00ms | -42.00ms 🚀 |
| dist/16.436f097f.js | 1.21kb | +0.00b | 472.00ms | -42.00ms 🚀 |
| dist/16.b4da0acb.js | 1.19kb | +0.00b | 471.00ms | -42.00ms 🚀 |
| dist/16.02c68c4f.js | 1.18kb | +0.00b | 471.00ms | -42.00ms 🚀 |
| dist/heading5.e195aab1.js | 1.17kb | +0.00b | 471.00ms | -41.00ms 🚀 |
| dist/expand.450f3aea.js | 1.16kb | +0.00b | 471.00ms | -40.00ms 🚀 |
| dist/media-card-analytics-error-boundary.2323af57.js | 1.15kb | +0.00b | 470.00ms | -29.00ms 🚀 |
| dist/16.b46ef690.js | 1.14kb | +0.00b | 472.00ms | -42.00ms 🚀 |
| dist/16.4e3b0235.js | 1.14kb | +0.00b | 471.00ms | -42.00ms 🚀 |
| dist/16.9ba230ea.js | 1.13kb | +0.00b | 472.00ms | -42.00ms 🚀 |
| dist/16.a37df53b.js | 1.13kb | +0.00b | 472.00ms | -41.00ms 🚀 |
| dist/16.9adb4ec7.js | 1.13kb | +0.00b | 472.00ms | -41.00ms 🚀 |
| dist/16.eafe1a11.js | 1.13kb | +0.00b | 472.00ms | -42.00ms 🚀 |
| dist/heading2.a2a1be3f.js | 1.11kb | +0.00b | 471.00ms | -41.00ms 🚀 |
| dist/16.3920766f.js | 1.10kb | +0.00b | 472.00ms | -42.00ms 🚀 |
| dist/component.6600f83e.js | 1.07kb | +0.00b | 472.00ms | -42.00ms 🚀 |
| dist/mention.4d64e059.js | 1.07kb | +0.00b | 471.00ms | -41.00ms 🚀 |
| dist/heading4.ec980e93.js | 1.06kb | +0.00b | 471.00ms | -41.00ms 🚀 |
| dist/16.afcb09b6.js | 1.05kb | +0.00b | 471.00ms | -42.00ms 🚀 |
| dist/layout.52ba15f7.js | 1.05kb | +0.00b | 471.00ms | -42.00ms 🚀 |
| dist/divider.16defde6.js | 1.03kb | +0.00b | 471.00ms | -41.00ms 🚀 |
| dist/quote.aa25b83c.js | 1.02kb | +0.00b | 471.00ms | -41.00ms 🚀 |
| dist/action.9aa72b39.js | 1.00kb | +0.00b | 472.00ms | -41.00ms 🚀 |
| dist/decision.20244046.js | 1010.00b | +0.00b | 471.00ms | -41.00ms 🚀 |
| dist/panel-warning.97a0e3b3.js | 1008.00b | +0.00b | 471.00ms | -41.00ms 🚀 |
| dist/list.c9147a62.js | 978.00b | +0.00b | 471.00ms | -41.00ms 🚀 |
| dist/heading1.7d899ba5.js | 976.00b | +0.00b | 471.00ms | -41.00ms 🚀 |
| dist/panel-error.8d11e8b7.js | 906.00b | +0.00b | 471.00ms | -41.00ms 🚀 |
| dist/panel.a28c56ee.js | 897.00b | +0.00b | 471.00ms | -41.00ms 🚀 |
| dist/table.5a4874ee.js | 889.00b | +0.00b | 471.00ms | -41.00ms 🚀 |
| dist/panel-success.9b923e58.js | 845.00b | +0.00b | 471.00ms | -41.00ms 🚀 |
| dist/panel-note.97a4d541.js | 841.00b | +0.00b | 471.00ms | -41.00ms 🚀 |
| dist/media-picker-analytics-error-boundary.f8ddfee3.js | 839.00b | +0.00b | 470.00ms | -30.00ms 🚀 |
| dist/media-card-analytics-error-boundary.663369b9.js | 835.00b | +0.00b | 470.00ms | -41.00ms 🚀 |
| dist/media-card-analytics-error-boundary.73ba4074.js | 835.00b | +0.00b | 469.00ms | -30.00ms 🚀 |
| dist/media-viewer-analytics-error-boundary.0afa7031.js | 755.00b | +0.00b | 470.00ms | -29.00ms 🚀 |
| dist/EmojiPickerComponent.2e54b9c6.js | 535.00b | +0.00b | 470.00ms | -41.00ms 🚀 |
| dist/simpleHasher.16c8bf41.js | 528.00b | +0.00b | 470.00ms | -41.00ms 🚀 |
| dist/simpleHasher.a29b2a8e.js | 528.00b | +0.00b | 469.00ms | -30.00ms 🚀 |
| dist/index.html | 119.00b | +0.00b | 475.00ms | -59.00ms 🚀 |

</p></details>

<details><summary>Three.js x4 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/275277189982716429)**

**Comment by mischnic** [comment]
> breaking change

We could simply keep the old name.

**Comment by DeMoorJasper** [comment]
@mischnic that's possible, but it's still a breaking change

**Comment by mischnic** [comment]
I was rather thinking not adding `diagnostics` at all, but we are still in beta anyway, so breaking changes are "allowed"

**Comment by DeMoorJasper** [comment]
@mischnic got that, just realised this actually didn't change anything useful so changed all of it back.

**Review by mischnic — APPROVED** [review]

**Pull request merged**
