### PR TITLE
Update to PostCSS 8

### LINKED ISSUE #5152: PostCSS 8
# 🙋 feature request

Update PostCSS from 7 to 8 in `v2` branch.

## 🔦 Context

[PostCSS 8 changelog](https://github.com/postcss/postcss/releases/tag/8.0.0)

PostCSS 8 came with a new plugin API. Right now Parcel users can use new PostCSS plugins because Parcel uses PostCSS 7.

PostCSS 8 has no breaking changes for Parcel 2 since Parcel 2 already dropped Node.js 6 and 8 support.

### PR DESCRIPTION
**Pull request by mischnic**
# ↪️ Pull Request

Closes #5152

### CODE REVIEW

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>Kitchen Sink ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 8.22s | -78.00ms |
| Cached | 1.93s | -25.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/parcel.d5807e82.webp | 102.94kb | +0.00b | 215.00ms | -25.00ms 🚀 |
| dist/modern/parcel.d5807e82.webp | 102.94kb | +0.00b | 353.00ms | -90.00ms 🚀 |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/parcel.d5807e82.webp | 102.94kb | +0.00b | 1.58s | +86.00ms ⚠️ |
| dist/modern/parcel.d5807e82.webp | 102.94kb | +0.00b | 1.48s | -74.00ms 🚀 |
| dist/legacy/index.html | 701.00b | +0.00b | 1.57s | -79.00ms 🚀 |

</p></details>

<details><summary>React HackerNews ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 31.88s | +315.00ms |
| Cached | 1.91s | -3.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/logo.24c8bf9e.png | 274.00b | +0.00b | 156.00ms | +61.00ms ⚠️ |

#### Cached Bundles

*No bundle changes detected.*

</p></details>

<details><summary>AtlasKit Editor ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 3.18m | +4.42s |
| Cached | 5.20s | +156.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/pdfRenderer.15a6a023.js | 1.11mb | -6.00b 🚀 | 55.56s | +3.19s ⚠️ |
| dist/EmojiPickerComponent.ae601247.js | 75.29kb | +0.00b | 11.30s | +873.00ms ⚠️ |
| dist/Modal.19ffed32.js | 41.27kb | +0.00b | 5.60s | +376.00ms ⚠️ |
| dist/component.54080a26.js | 22.50kb | +0.00b | 5.58s | +364.00ms ⚠️ |
| dist/DatePicker.0df05dac.js | 21.21kb | +0.00b | 11.30s | +891.00ms ⚠️ |
| dist/EmojiPickerComponent.7dc0ebd0.js | 18.23kb | +0.00b | 11.30s | +873.00ms ⚠️ |
| dist/js.5733a017.js | 16.40kb | +0.00b | 5.58s | +364.00ms ⚠️ |
| dist/workerHasher.1e706e77.js | 11.75kb | +0.00b | 13.60s | +787.00ms ⚠️ |
| dist/component.77c0f682.js | 6.05kb | +0.00b | 6.08s | +331.00ms ⚠️ |
| dist/index.ac562c80.css | 3.46kb | +0.00b | 1.20m | +10.40s ⚠️ |
| dist/png-chunks-extract.a844fdb6.js | 3.41kb | +0.00b | 5.58s | +364.00ms ⚠️ |
| dist/dropzone.3c67f0a6.js | 3.23kb | +0.00b | 30.91s | -21.47s 🚀 |
| dist/Modal.0304b9ed.js | 3.08kb | +0.00b | 5.58s | +360.00ms ⚠️ |
| dist/card.eea6ad8c.js | 2.03kb | +0.00b | 30.91s | -21.47s 🚀 |
| dist/date.231500d2.js | 1.73kb | +0.00b | 6.68s | +419.00ms ⚠️ |
| dist/16.d16f14ed.js | 1.73kb | +0.00b | 6.31s | -2.87s 🚀 |
| dist/images.80c92f5e.js | 1.67kb | +0.00b | 6.80s | +427.00ms ⚠️ |
| dist/16.1b6ca79f.js | 1.66kb | +0.00b | 6.08s | +334.00ms ⚠️ |
| dist/feedback.d5590b34.js | 1.64kb | +0.00b | 11.30s | +894.00ms ⚠️ |
| dist/workerHasher.6d5b22d7.js | 1.54kb | +0.00b | 1.74m | +1.53m ⚠️ |
| dist/workerHasher.fa198233.js | 1.54kb | +0.00b | 57.23s | -44.12s 🚀 |
| dist/list-number.c35f9589.js | 1.46kb | +0.00b | 6.80s | +427.00ms ⚠️ |
| dist/status.8ab4226b.js | 1.46kb | +0.00b | 7.12s | +516.00ms ⚠️ |
| dist/16.9ccb5b28.js | 1.38kb | +0.00b | 8.39s | +2.44s ⚠️ |
| dist/code.3dd71280.js | 1.38kb | +0.00b | 6.68s | +419.00ms ⚠️ |
| dist/16.19c93285.js | 1.33kb | +0.00b | 6.08s | +335.00ms ⚠️ |
| dist/16.c7751e34.js | 1.33kb | +0.00b | 8.39s | +2.44s ⚠️ |
| dist/16.18344f47.js | 1.31kb | +0.00b | 6.52s | +384.00ms ⚠️ |
| dist/link.2f4427e6.js | 1.30kb | +0.00b | 6.80s | +428.00ms ⚠️ |
| dist/heading6.fdbbdf4d.js | 1.30kb | +0.00b | 7.25s | +535.00ms ⚠️ |
| dist/heading3.2113b7a1.js | 1.29kb | +0.00b | 7.25s | +561.00ms ⚠️ |
| dist/16.2c4c1846.js | 1.27kb | +0.00b | 6.52s | +384.00ms ⚠️ |
| dist/emoji.93ae61d3.js | 1.23kb | +0.00b | 6.68s | +423.00ms ⚠️ |
| dist/16.d17ab186.js | 1.23kb | +0.00b | 6.31s | -2.87s 🚀 |
| dist/16.b4da0acb.js | 1.19kb | +0.00b | 6.32s | -2.99s 🚀 |
| dist/16.02c68c4f.js | 1.18kb | +0.00b | 6.52s | +384.00ms ⚠️ |
| dist/heading5.e195aab1.js | 1.17kb | +0.00b | 7.25s | +559.00ms ⚠️ |
| dist/expand.450f3aea.js | 1.16kb | +0.00b | 11.30s | +894.00ms ⚠️ |
| dist/media-card-analytics-error-boundary.2323af57.js | 1.15kb | +0.00b | 30.91s | -21.47s 🚀 |
| dist/16.4e3b0235.js | 1.14kb | +0.00b | 6.31s | +366.00ms ⚠️ |
| dist/16.9ba230ea.js | 1.13kb | +0.00b | 6.08s | +335.00ms ⚠️ |
| dist/16.a37df53b.js | 1.13kb | +0.00b | 8.39s | +2.44s ⚠️ |
| dist/16.9adb4ec7.js | 1.13kb | +0.00b | 6.31s | +365.00ms ⚠️ |
| dist/16.eafe1a11.js | 1.13kb | +0.00b | 6.08s | +335.00ms ⚠️ |
| dist/heading2.a2a1be3f.js | 1.11kb | +0.00b | 7.25s | +561.00ms ⚠️ |
| dist/mention.4d64e059.js | 1.07kb | +0.00b | 6.96s | +471.00ms ⚠️ |
| dist/heading4.ec980e93.js | 1.06kb | +0.00b | 7.25s | +559.00ms ⚠️ |
| dist/16.afcb09b6.js | 1.05kb | +0.00b | 6.52s | +384.00ms ⚠️ |
| dist/layout.52ba15f7.js | 1.05kb | +0.00b | 6.80s | +426.00ms ⚠️ |
| dist/divider.16defde6.js | 1.03kb | +0.00b | 6.68s | +422.00ms ⚠️ |
| dist/quote.aa25b83c.js | 1.02kb | +0.00b | 7.12s | +516.00ms ⚠️ |
| dist/action.9aa72b39.js | 1.00kb | +0.00b | 6.53s | +393.00ms ⚠️ |
| dist/decision.20244046.js | 1010.00b | +0.00b | 6.68s | +419.00ms ⚠️ |
| dist/panel-warning.97a0e3b3.js | 1008.00b | +0.00b | 6.96s | +472.00ms ⚠️ |
| dist/list.c9147a62.js | 978.00b | +0.00b | 6.80s | +427.00ms ⚠️ |
| dist/heading1.7d899ba5.js | 976.00b | +0.00b | 7.12s | +511.00ms ⚠️ |
| dist/panel-error.8d11e8b7.js | 906.00b | +0.00b | 6.96s | +468.00ms ⚠️ |
| dist/panel.a28c56ee.js | 897.00b | +0.00b | 7.12s | +516.00ms ⚠️ |
| dist/table.5a4874ee.js | 889.00b | +0.00b | 7.12s | +516.00ms ⚠️ |
| dist/panel-success.9b923e58.js | 845.00b | +0.00b | 6.96s | +472.00ms ⚠️ |
| dist/panel-note.97a4d541.js | 841.00b | +0.00b | 6.96s | +472.00ms ⚠️ |
| dist/media-card-analytics-error-boundary.663369b9.js | 835.00b | +0.00b | 13.60s | -1.46m 🚀 |
| dist/media-card-analytics-error-boundary.73ba4074.js | 835.00b | +0.00b | 57.23s | -44.12s 🚀 |
| dist/simpleHasher.16c8bf41.js | 528.00b | +0.00b | 13.60s | +782.00ms ⚠️ |
| dist/simpleHasher.a29b2a8e.js | 528.00b | +0.00b | 57.26s | -44.09s 🚀 |
| dist/index.html | 119.00b | +0.00b | 7.41s | -899.00ms 🚀 |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.f6352c02.js | 2.72mb | +0.00b | 409.00ms | -54.00ms 🚀 |
| dist/pdfRenderer.15a6a023.js | 1.11mb | -6.00b 🚀 | 545.00ms | -86.00ms 🚀 |
| dist/editorView.e06544fb.js | 587.12kb | +0.00b | 593.00ms | -51.00ms 🚀 |
| dist/popup.6c453e3c.js | 169.96kb | +0.00b | 583.00ms | -62.00ms 🚀 |
| dist/Toolbar.83ac0b6e.js | 92.34kb | +0.00b | 593.00ms | -51.00ms 🚀 |
| dist/EmojiPickerComponent.ae601247.js | 75.29kb | +0.00b | 505.00ms | -105.00ms 🚀 |
| dist/media-viewer.bcba38b3.js | 71.96kb | +0.00b | 537.00ms | -94.00ms 🚀 |
| dist/card.645a5c17.js | 55.01kb | +0.00b | 537.00ms | -83.00ms 🚀 |
| dist/card.0313bac8.js | 52.78kb | +0.00b | 589.00ms | -56.00ms 🚀 |
| dist/Modal.19ffed32.js | 41.27kb | +0.00b | 437.00ms | -61.00ms 🚀 |
| dist/component.d7c29980.js | 30.70kb | +0.00b | 409.00ms | -53.00ms 🚀 |
| dist/component.54080a26.js | 22.50kb | +0.00b | 455.00ms | -43.00ms 🚀 |
| dist/DatePicker.0df05dac.js | 21.21kb | +0.00b | 505.00ms | -105.00ms 🚀 |
| dist/EmojiPickerComponent.7dc0ebd0.js | 18.23kb | +0.00b | 505.00ms | -105.00ms 🚀 |
| dist/dropzone.7c704bdb.js | 17.27kb | +0.00b | 588.00ms | -50.00ms 🚀 |
| dist/smartMediaEditor.9623570c.js | 16.87kb | +0.00b | 593.00ms | -51.00ms 🚀 |
| dist/js.5733a017.js | 16.40kb | +0.00b | 437.00ms | -61.00ms 🚀 |
| dist/ui.fee77548.js | 13.97kb | +0.00b | 537.00ms | -94.00ms 🚀 |
| dist/workerHasher.1e706e77.js | 11.75kb | +0.00b | 510.00ms | -109.00ms 🚀 |
| dist/EmojiTypeAheadComponent.1990d771.js | 8.67kb | +0.00b | 510.00ms | -109.00ms 🚀 |
| dist/component.77c0f682.js | 6.05kb | +0.00b | 455.00ms | -57.00ms 🚀 |
| dist/card.383bd9bd.js | 5.61kb | +0.00b | 537.00ms | -94.00ms 🚀 |
| dist/media-viewer.59c17dad.js | 3.92kb | +0.00b | 545.00ms | -86.00ms 🚀 |
| dist/EmojiPickerComponent.627aca6b.js | 3.58kb | +0.00b | 505.00ms | -105.00ms 🚀 |
| dist/png-chunks-extract.a844fdb6.js | 3.41kb | +0.00b | 437.00ms | -61.00ms 🚀 |
| dist/dropzone.3c67f0a6.js | 3.23kb | +0.00b | 583.00ms | -55.00ms 🚀 |
| dist/Modal.0304b9ed.js | 3.08kb | +0.00b | 437.00ms | -61.00ms 🚀 |
| dist/clipboard.da112b6e.js | 2.75kb | +0.00b | 583.00ms | -55.00ms 🚀 |
| dist/16.290b4a43.js | 2.38kb | +0.00b | 437.00ms | -178.00ms 🚀 |
| dist/EmojiUploadComponent.d54a1fc6.js | 2.18kb | +0.00b | 510.00ms | -110.00ms 🚀 |
| dist/card.eea6ad8c.js | 2.03kb | +0.00b | 545.00ms | -86.00ms 🚀 |
| dist/ResourcedEmojiComponent.abe8596c.js | 2.00kb | +0.00b | 409.00ms | -53.00ms 🚀 |
| dist/date.231500d2.js | 1.73kb | +0.00b | 470.00ms | -64.00ms 🚀 |
| dist/16.d16f14ed.js | 1.73kb | +0.00b | 465.00ms | -64.00ms 🚀 |
| dist/images.80c92f5e.js | 1.67kb | +0.00b | 476.00ms | -63.00ms 🚀 |
| dist/16.1b6ca79f.js | 1.66kb | +0.00b | 455.00ms | -58.00ms 🚀 |
| dist/feedback.d5590b34.js | 1.64kb | +0.00b | 498.00ms | -103.00ms 🚀 |
| dist/browser.75813db0.js | 1.61kb | +0.00b | 583.00ms | -55.00ms 🚀 |
| dist/workerHasher.6d5b22d7.js | 1.54kb | +0.00b | 510.00ms | -109.00ms 🚀 |
| dist/workerHasher.fa198233.js | 1.54kb | +0.00b | 589.00ms | -56.00ms 🚀 |
| dist/list-number.c35f9589.js | 1.46kb | +0.00b | 482.00ms | -61.00ms 🚀 |
| dist/status.8ab4226b.js | 1.46kb | +0.00b | 491.00ms | -82.00ms 🚀 |
| dist/16.9ccb5b28.js | 1.38kb | +0.00b | 460.00ms | -65.00ms 🚀 |
| dist/code.3dd71280.js | 1.38kb | +0.00b | 470.00ms | -64.00ms 🚀 |
| dist/16.19c93285.js | 1.33kb | +0.00b | 455.00ms | -58.00ms 🚀 |
| dist/16.c7751e34.js | 1.33kb | +0.00b | 460.00ms | -64.00ms 🚀 |
| dist/16.51049e2c.js | 1.32kb | +0.00b | 729.00ms | +115.00ms ⚠️ |
| dist/16.18344f47.js | 1.31kb | +0.00b | 470.00ms | -64.00ms 🚀 |
| dist/link.2f4427e6.js | 1.30kb | +0.00b | 482.00ms | -61.00ms 🚀 |
| dist/heading6.fdbbdf4d.js | 1.30kb | +0.00b | 498.00ms | -103.00ms 🚀 |
| dist/heading3.2113b7a1.js | 1.29kb | +0.00b | 493.00ms | -89.00ms 🚀 |
| dist/16.2c4c1846.js | 1.27kb | +0.00b | 465.00ms | -64.00ms 🚀 |
| dist/emoji.93ae61d3.js | 1.23kb | +0.00b | 476.00ms | -63.00ms 🚀 |
| dist/16.d17ab186.js | 1.23kb | +0.00b | 465.00ms | -64.00ms 🚀 |
| dist/16.436f097f.js | 1.21kb | +0.00b | 729.00ms | +118.00ms ⚠️ |
| dist/16.b4da0acb.js | 1.19kb | +0.00b | 465.00ms | -64.00ms 🚀 |
| dist/16.02c68c4f.js | 1.18kb | +0.00b | 470.00ms | -64.00ms 🚀 |
| dist/heading5.e195aab1.js | 1.17kb | +0.00b | 498.00ms | -103.00ms 🚀 |
| dist/expand.450f3aea.js | 1.16kb | +0.00b | 499.00ms | -102.00ms 🚀 |
| dist/media-card-analytics-error-boundary.2323af57.js | 1.15kb | +0.00b | 545.00ms | -100.00ms 🚀 |
| dist/16.b46ef690.js | 1.14kb | +0.00b | 729.00ms | +115.00ms ⚠️ |
| dist/16.4e3b0235.js | 1.14kb | +0.00b | 460.00ms | -65.00ms 🚀 |
| dist/16.9ba230ea.js | 1.13kb | +0.00b | 729.00ms | +216.00ms ⚠️ |
| dist/16.a37df53b.js | 1.13kb | +0.00b | 460.00ms | -65.00ms 🚀 |
| dist/16.9adb4ec7.js | 1.13kb | +0.00b | 460.00ms | -65.00ms 🚀 |
| dist/16.eafe1a11.js | 1.13kb | +0.00b | 455.00ms | -58.00ms 🚀 |
| dist/heading2.a2a1be3f.js | 1.11kb | +0.00b | 491.00ms | -82.00ms 🚀 |
| dist/16.3920766f.js | 1.10kb | +0.00b | 729.00ms | +119.00ms ⚠️ |
| dist/component.6600f83e.js | 1.07kb | +0.00b | 409.00ms | -53.00ms 🚀 |
| dist/mention.4d64e059.js | 1.07kb | +0.00b | 482.00ms | -61.00ms 🚀 |
| dist/heading4.ec980e93.js | 1.06kb | +0.00b | 498.00ms | -103.00ms 🚀 |
| dist/16.afcb09b6.js | 1.05kb | +0.00b | 465.00ms | -64.00ms 🚀 |
| dist/layout.52ba15f7.js | 1.05kb | +0.00b | 476.00ms | -63.00ms 🚀 |
| dist/divider.16defde6.js | 1.03kb | +0.00b | 476.00ms | -63.00ms 🚀 |
| dist/quote.aa25b83c.js | 1.02kb | +0.00b | 486.00ms | -62.00ms 🚀 |
| dist/action.9aa72b39.js | 1.00kb | +0.00b | 470.00ms | -64.00ms 🚀 |
| dist/decision.20244046.js | 1010.00b | +0.00b | 476.00ms | -62.00ms 🚀 |
| dist/panel-warning.97a0e3b3.js | 1008.00b | +0.00b | 486.00ms | -62.00ms 🚀 |
| dist/list.c9147a62.js | 978.00b | +0.00b | 482.00ms | -61.00ms 🚀 |
| dist/heading1.7d899ba5.js | 976.00b | +0.00b | 491.00ms | -82.00ms 🚀 |
| dist/panel-error.8d11e8b7.js | 906.00b | +0.00b | 482.00ms | -62.00ms 🚀 |
| dist/panel.a28c56ee.js | 897.00b | +0.00b | 486.00ms | -62.00ms 🚀 |
| dist/table.5a4874ee.js | 889.00b | +0.00b | 491.00ms | -82.00ms 🚀 |
| dist/panel-success.9b923e58.js | 845.00b | +0.00b | 486.00ms | -62.00ms 🚀 |
| dist/panel-note.97a4d541.js | 841.00b | +0.00b | 486.00ms | -62.00ms 🚀 |
| dist/media-picker-analytics-error-boundary.f8ddfee3.js | 839.00b | +0.00b | 583.00ms | -55.00ms 🚀 |
| dist/media-card-analytics-error-boundary.663369b9.js | 835.00b | +0.00b | 537.00ms | -94.00ms 🚀 |
| dist/media-card-analytics-error-boundary.73ba4074.js | 835.00b | +0.00b | 589.00ms | -56.00ms 🚀 |
| dist/media-viewer-analytics-error-boundary.0afa7031.js | 755.00b | +0.00b | 545.00ms | -86.00ms 🚀 |
| dist/EmojiPickerComponent.2e54b9c6.js | 535.00b | +0.00b | 505.00ms | -105.00ms 🚀 |
| dist/simpleHasher.16c8bf41.js | 528.00b | +0.00b | 510.00ms | -109.00ms 🚀 |
| dist/simpleHasher.a29b2a8e.js | 528.00b | +0.00b | 589.00ms | -54.00ms 🚀 |
| dist/index.html | 119.00b | +0.00b | 410.00ms | -53.00ms 🚀 |

</p></details>

<details><summary>Three.js x4 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/277178327923425804)**

**Review by aminya — APPROVED** [review]

**Comment by ai** [comment]
@mischnic New PostCSS recommends moving `postcss` to `peerDependencies`:

1. Users will be able to update PostCSS without Parcel release
2. New PostCSS 8 plugins will move `postcss` from plugin’s `dependencies` to `peerDependencies`, so anyway users will need `postcss` in their `package.json`

Will this recommendation work for Parcel 2?

**Comment by mischnic** [comment]
We require plugins from the users project, so that should work.

Or do you mean the Parcel itself should have postcss as a peerdependency? E.g. so that this call uses the user's postcss version?
https://github.com/parcel-bundler/parcel/blob/0a32ec54a2399973886fc2ca2045ebfb423c6fcf/packages/transformers/postcss/src/PostCSSTransformer.js#L103
That would be rather difficult...

**Comment by ai** [comment]
@mischnic Parcel should use `postcss` from the user’s dependencies. Right now we need to wait for the Parcel update to be able to use new PostCSS (and seems like Parcel 1 never will have PostCSS 8).

I think optional peer dependency in Parcel will solve this problem.

**Comment by ai** [comment]
Parcel auto-install feature is awesome 😍

I use Parcel for all my projects (including PostCSS website).

**Comment by mischnic** [comment]
🎉  😄

**Comment by ai** [comment]
What is the current blocker? I want to use PostCSS 8 on the PostCSS website.

**Review by DeMoorJasper — APPROVED** [review]

**Comment by mischnic** [comment]
@DeMoorJasper Should we add postcss@8 as a dependency to the integration test monorepo package?

**Comment by DeMoorJasper** [comment]
@mischnic I don't think it's necessary as it's already gonna get installed anyway by all the references it already has in various package.json's in the monorepo.

Feel free to add it though

**Comment by ai** [comment]
Any way to use this fix before next Parcel 2 beta release?

I want to update postcss.org and add a guide to [PostCSS 8 Migration guide](https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users).

**Comment by mischnic** [comment]
`yarn add parcel@nightly`

**Comment by privatenumber** [comment]
This makes Parcel 2 completely unusable if the PostCSS plugins your codebase relies on doesn't support PostCSS 8 yet.

I think adding PostCSS 8 support is great, but on the user-end it's a pretty minor improvement that blocks Parcel users from upgrading to v2.

In my case, it's [preset-env](https://github.com/csstools/postcss-preset-env/issues/191) which requires many plugin dependencies to be upgraded before it can do a PostCSS 8 release. IMO this is a pretty common PostCSS plugin to use with PostCSS so I imagine many users may encounter this blocker.

Is it possible to support both PostCSS 7 and 8 somehow?

**Comment by mischnic** [comment]
See https://github.com/parcel-bundler/parcel/issues/5152#issuecomment-694289970

> So plugins for PostCSS 7 also work with version 8?

> Yeap. But PostCSS will show a warning and about using deprecated API.

**Pull request merged**
