### PR TITLE
Purge dist dirs before bundling

### PR DESCRIPTION
**Pull request by kirillrogovoy**
# ↪️ Pull Request

Closes https://github.com/parcel-bundler/parcel/issues/3591.

## 🚨 Test instructions

```bash
parcel build index.html
touch dist/extra

parcel build index.html

ls dist # no ./extra is there
```

## ✔️ PR Todo

- [x] Added/updated unit tests for this change
- [x] Filled out test instructions (In case there aren't any unit tests)
- [x] Included links to related issues/PRs

### CODE REVIEW

**Comment by kirillrogovoy** [comment]
One caveat: the `should support transforming with postcss twice with the same result` test is broken, because it builds two bundles concurrently into the same dist directory.

So it runs into a race condition where the second bundle can't be written because the first bundle has removed the dist directory.

I think that's exactly that 1-out-of-100 case where removing the directory by default doesn't work. 

My intuitive thinking is that Parcel shouldn't probably support concurrent building into the same directory by default because it can get unpredictable in other ways too.

**Comment by mischnic** [comment]
As said in https://github.com/parcel-bundler/parcel/issues/3591, there  definitely needs to be a flag to enable/disabled this (not sure what the default should be).

> But something to consider too is that there might be big performance gains to be had using caching and not cleaning by default

I think Parcel will always (over)write these files, reading them and comparing against Parcel's output would be slower than just writing the to disk.

**Comment by DeMoorJasper** [comment]
I don't think this should be the default, probably best to make it an opt-in using a flag as mischnic mentioned

**Comment by DeMoorJasper** [comment]
Closing this due to inactivity

**Pull request closed without merging**
