### PR TITLE
Do not tree shake CSS classes when scope hoisting is disabled

### LINKED ISSUE #6780: CSS modules do not build correctly without scope hoisting
# 🐛 bug report

Running `parcel build --no-scope-hoist` causes used styles to be removed.

## 🎛 Configuration (.babelrc, package.json, cli command)

I built an example repo here that demonstrates the bug: https://github.com/asmockler/parcel-css-module-bug.

There are 2 build commands, one with scope hoisting on and the other with scope hoisting off. The build to different dist dirs to make it easier to compare the output.

## 🤔 Expected Behavior

All referenced classes from CSS modules should be included whether or not scope hoisting is turned on.

## 😯 Current Behavior

With `--no-scope-hoist`, all or almost all classes are removed during build. In a larger project where I first noticed the bug, I often wind up with just a single class in the output css. 

I will also note that it seems like the build step takes a long time on `Optimizing ModuleName.[hash].css` when it exhibits this behavior, which makes me think the styles are included and then tree-shaken, but I'm not sure. 

## 💁 Possible Solution

Really not sure -- running with `--no-optimize` doesn't seem to fix it, either, though.

## 🔦 Context

I think that with `--no-scope-hoist`, it would be ok to disable all tree-shaking from CSS modules.

## 💻 Code Sample

https://github.com/asmockler/parcel-css-module-bug

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | ^2.0.0-rc.0 |
| Node             | Observed on `14.16` and `16.0` |
| npm/Yarn         | Yarn `1.22.10` |
| Operating System | Mac OS Big Sur |

### PR DESCRIPTION
**Pull request by asmockler**
# ↪️ Pull Request

Attempt to resolve https://github.com/parcel-bundler/parcel/issues/6780

Disables CSS tree-shaking when `--no-scope-hoist` is present.

## 💻 Examples

I have an example of the bug in this repo: https://github.com/asmockler/parcel-css-module-bug

## 🚨 Test instructions

Before this change, most or all CSS from CSS modules would be tree-shaken when `--no-scope-hoist` was passed; now, all CSS should be included.

## ✔️ PR Todo

- [ ] Added/updated unit tests for this change
- [x] Filled out test instructions (In case there aren't any unit tests)
- [x] Included links to related issues/PRs

### CODE REVIEW

**Comment by devongovett** [comment]
cc. @mischnic 

I think another question is why we are storing an AST at all when scope hoisting is disabled...

**Comment by mischnic** [comment]
I would be surprised if this actually works. Because we reset `env.scopeHoist` in the CSS transformer to allow for more deduplication, this means that the CSS packager doesn't actually know if scope hoisting is enabled or not.

`asset.env.shouldScopeHoist` is always false in the packager.

**Comment by asmockler** [comment]
You're right...I thought I had fixed it, but turns out I had just broken the normal behavior 😅  what if `scopeHoist` was passed through in the CSS transformer as well?

i.e. add `shouldScopeHoist: asset.env.shouldScopeHoist,` to https://github.com/parcel-bundler/parcel/blob/v2/packages/transformers/css/src/CSSTransformer.js#L56-L63

I would be happy to add that, but I am not sure if it is going to have other consequences.

**Comment by mischnic** [comment]
My plan for this is to make `getUsedSymbols` return `Array<Symbol> | null`, so that you can differentiate the cases "nothing is used" and "symbol propagation didn't run"/"unkown".

**Comment by devongovett** [comment]
Should be fixed by #5728.

**Pull request closed without merging**
