### PR TITLE
Dev Server: serve files (including sourcemaps) from `dist/` folder

### LINKED ISSUE #5966: [2.0.0-beta.1] Source maps are not served
# 🐛 bug report

Source map requests are not intercepted by the bundle server, instead the index.html is loaded.

This prevents source maps from working of course!

## 🎛 Configuration (.babelrc, package.json, cli command)

Configs are in this gist: https://gist.github.com/richthegeek/e7de4375b24eb06ad554396747687db1

CLI command is `yarn start` which runs `parcel serve ./src/index.html`

## 🤔 Expected Behavior

Source maps should be loaded from the server and used by the browser.

## 😯 Current Behavior

Source map requests render the built index.html.

Screenshot 2021-03-05 at 14 26 25

## 💻 Code Sample

Ask if needed, sorry but I'm not sure what code would be useful to you here!

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-beta.1
| Node             | 14.15.1
| npm/Yarn         | 1.22.4
| Operating System | OSX 10.15.7

### PR DESCRIPTION
**Pull request by zowesiouff**
# ↪️ Pull Request

Instead of serving the `index` in case we don't find the file in the bundle, try to serve the raw file from the `dist/` folder. There are already multiple ways of serving the `index` already ( direct call or `path.extname(pathname) === ''` )

It should fix #5966 ( and the nebula of linked issues? )
As noted in #5972, if sourcemaps were in the bundle, this wouldn't be necessary but it sounds way more complex than simply blindly serving all of `dist`.

## 💻 Examples

integration test included

## 🚨 Test instructions

integration test included

## ✔️ PR Todo

- [X] Added/updated unit tests for this change
- [X] Filled out test instructions (In case there aren't any unit tests)
- [X] Included links to related issues/PRs

### CODE REVIEW

**Review by DeMoorJasper — APPROVED** [review]

**Review by typeofweb — APPROVED** [review]

**Comment by typeofweb** [comment]
Can we get this merged? 👯

**Comment by DeMoorJasper** [comment]
@mmiszy yes, was waiting on CI to finally work again, sometimes windows doesn't wanna work on azure devops

**Comment by typeofweb** [comment]
Thank you! Is there a chance to get this released under the `nightly` tag?

**Comment by mischnic** [comment]
That's going to happen automatically around 01:00 UTC.

**Comment by jgentes** [comment]
I'm still seeing this issue (no sourcemaps) with Parcel v2.0.0-beta.2 - is there a configuration option to enable sourcemaps?

If I revert to Parcel v1, sourcemaps work correctly (https://github.com/parcel-bundler/parcel/issues/6040)

**Comment by jgentes** [comment]
Scratch that, installing `"parcel": "^2.0.0-nightly.641"` did the trick!

**Comment by SheepReaper** [comment]
In case someone else stumbles here looking for the version this was fixed in...

`"parcel": "^2.0.0-nightly.631"` is the minimum version this is fixed in.

**Pull request merged**
