### PR TITLE
Module declarations must use "export declare" instead of "declare export".

### LINKED ISSUE #8079: Typescript namespace export produces invalid types
# 🐛 bug report

A typescript source file that has an exported namespace produces incorrect `.d.ts` types.
Consider a project with the following example typescript source file:

```
export namespace Repository {
    export function split(repo: string) {
        const parts = repo.split("/");
        return {
            team: parts[0],
            name: parts[1],
        };
    }
}
```

It produces the following invalid `index.d.ts` file:
```ts
declare export namespace Repository {
    function split(repo: string): {
        team: string;
        name: string;
    };
}

//# sourceMappingURL=index.d.ts.map
```

The `declare` and `export` keywords must be swapped according to the typescript error "'export' modifier must precede 'declare' modifier."

## 🎛 Configuration (.babelrc, package.json, cli command)

```json
{
    "name": "namespace-export",
    "source": "src/index.ts",
    "main": "dist/index.js",
    "module": "dist/index.mjs",
    "types": "dist/index.d.ts",
    "sideEffects": false,
    "scripts": {
        "build": "parcel build"
    },
    "devDependencies": {
        "@parcel/packager-ts": "^2.5.0",
        "@parcel/transformer-typescript-types": "^2.5.0",
        "parcel": "^2.5.0",
        "typescript": "^4.1.5"
    }
}
```

## 🤔 Expected Behavior

The produced types file should use `export declare` instead of `declare export` when exporting namespaces.

## 😯 Current Behavior

The produces types contains `declare export namespace ... { }`.

## 💻 Code Sample

Copy the example above to `src/index.ts`, write the content of `package.json`, run `npm i && npm run build`.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.5.0
| Node             | 16.14.2
| npm/Yarn         | 8.7.0
| Operating System | Windows 11

### PR DESCRIPTION
**Pull request by rmja**
# ↪️ Pull Request

This fixes https://github.com/parcel-bundler/parcel/issues/8079

## 🚨 Test instructions

I am completely new to parcel and I have not found a good place to write a test for this. Some help would be appreciated.

## ✔️ PR Todo

- [x] Added/updated unit tests for this change
- [ ] Filled out test instructions (In case there aren't any unit tests)
- [x] Included links to related issues/PRs

### CODE REVIEW

**Comment by mischnic** [comment]
The tests are here: https://github.com/parcel-bundler/parcel/blob/v2/packages/core/integration-tests/test/ts-types.js

So I'd add example for module/namespace export to the `index.ts` and `expected.d.ts` here:
https://github.com/parcel-bundler/parcel/tree/v2/packages/core/integration-tests/test/integration/ts-types/main
(or if it only happens with reexports, then https://github.com/parcel-bundler/parcel/blob/v2/packages/core/integration-tests/test/integration/ts-types/exporting/index.ts)

**Comment by rmja** [comment]
@mischnic I have now added a test that passes. The PR now also fixes #7983.

**Comment by mischnic** [comment]
You need to reformat shake.js with prettier (to make the lint CI job happy).

**Comment by rmja** [comment]
Lets hope that makes it happy:)

**Comment by mischnic** [comment]
> The PR now also fixes https://github.com/parcel-bundler/parcel/issues/7983.

But the test case you added probably doesn't cover that issue?

**Comment by rmja** [comment]
True, hang on.

**Comment by rmja** [comment]
@mischnic I have been unable to reproduce the bug when I run it as an integration test, but here is a minimal example that produces it.
https://github.com/rmja/unshift-issue

```ps
PS C:\Source\unshift-issue> npm run build

> build
> parcel build . ./augmenter

🚨 Build failed.

@parcel/transformer-typescript-types: Cannot read properties of undefined (reading 'unshift')

  TypeError: Cannot read properties of undefined (reading 'unshift')
  at visit (C:\Source\unshift-issue\node_modules\@parcel\transformer-typescript-types\lib\shake.js:60:24)
  at visitNodes (C:\Source\unshift-issue\node_modules\typescript\lib\typescript.js:87646:48)
  at Object.visitEachChild (C:\Source\unshift-issue\node_modules\typescript\lib\typescript.js:88126:56)
  at visit (C:\Source\unshift-issue\node_modules\@parcel\transformer-typescript-types\lib\shake.js:215:34)
  at visitNode (C:\Source\unshift-issue\node_modules\typescript\lib\typescript.js:87593:23)
  at Object.visitEachChild (C:\Source\unshift-issue\node_modules\typescript\lib\typescript.js:88123:222)
  at visit (C:\Source\unshift-issue\node_modules\@parcel\transformer-typescript-types\lib\shake.js:68:46)
  at visitNodes (C:\Source\unshift-issue\node_modules\typescript\lib\typescript.js:87646:48)
  at visitLexicalEnvironment (C:\Source\unshift-issue\node_modules\typescript\lib\typescript.js:87686:22)
  at Object.visitEachChild (C:\Source\unshift-issue\node_modules\typescript\lib\typescript.js:88234:55
```

It seems to be very similar to the test in https://github.com/parcel-bundler/parcel/tree/v2/packages/core/integration-tests/test/integration/ts-types/augmentation

**Comment by mischnic** [comment]
The test will work once you bump typescript in the monorepo. So remove the `typescript@>=3.0.0:` block in yarn.lock and rerun Yarn.

Shouldn't the fix rather be
```js
if(node.modifiers == null) node.modifiers = [];
node.modifiers.splice(...)
```

because currently the output is
```ts
module "original" {
    interface Person {
        name(): string;
    }
}
```
which I think is wrong?

Then you can also drop the `node.modifiers.length &&` part

**Comment by rmja** [comment]
@mischnic I think you are right. I modified the linke so that modifiers is assigned with an empty array if it is undefined.

**Comment by mischnic** [comment]
And please commit this change as well:

> The test will work once you upgrade typescript in the monorepo. So remove the typescript@>=3.0.0: block in yarn.lock and rerun Yarn.

**Comment by rmja** [comment]
Sorry about that. Tbh I did not know what you meant, but I think I found out:)

**Review by mischnic — APPROVED** [review]

**Pull request merged**
