### PR TITLE
Allow overriding elm compiler debugger with environmental variables

### PR DESCRIPTION
**Pull request by sklirg**
# ↪️ Pull Request

Adds an environmental variable to disable the Elm compiler because of bugs that can happen compile time with the debugger enabled (https://github.com/elm/compiler/issues/1851). 

This fix will make the build process work exactly as before unless you set the `PARCEL_ELM_DISABLE_DEBUG` environment variable to `1` or `true` (case-insensitive), in which case it will pass the debug flag as `false` through parcel to the build/compiler.

See #2626 and https://github.com/parcel-bundler/parcel/issues/2104#issuecomment-461707960 for more context.

## 💻 Examples

One of my Elm projects gets this error 100% of the time when starting the dev server (`parcel serve`) on cold cache, or 100% of the time when initiating a rebuild after starting it from cache.

To remedy this I currently monkey-patch the `ElmAsssets.js` file in my local node_modules to disable the debugger. Since more people are affected by this I figured I'd open a PR with my suggested fix. This supersedes and closes #2626 by adding a fix which does not break the workflow for current users and users of the debugger.

## 🚨 Test instructions

I've added a test case for the environmental override, and the previous tests pass. To test this fix, please see the examples in https://github.com/elm/compiler/issues/1851 and try them both with and without this fix.

## ✔️ PR Todo

- [x] Added/updated unit tests for this change
- [x] Filled out test instructions (In case there aren't any unit tests)
- [x] Included links to related issues/PRs

### CODE REVIEW

**Comment by sklirg** [comment]
I'm not sure why the tests fail only in node10 on Windows. They pass with node{6,8} on Windows, as well as node{6,8,10} on MacOS and Linux. These changes should not behave differently on specific OS-es or node versions...

**Comment by lzrski** [comment]
Seems like a duplicate of my  #2797. Your solution is more elegant and has test cases, so I favor it over mine. 👍

**Comment by n1k0** [comment]
Is there still any plan to land this? I would be nice being able to decide if we want to work with the Elm debugger or not, not only because of elm/compiler#1851 but also because some people don't use it at all while it gets in the way visually. Having an option to enable/disable it would be nice.

**Comment by adit-hotstar** [comment]
Please allow users to disable the Elm debugger. I'm currently developing an app for a device with a small screen, and the Elm debugger gets in the way of development. This is a serious issue for me.

This is a terrible design decision. I shouldn't be forced to use the Elm debugger if I don't want to. You should really allow users to choose whether or not they'd like to use a certain feature.

**Comment by devongovett** [comment]
Seems like this is something that should be in elm.json, or some other elm config file, not an environment variable.

**Comment by alex-tan** [comment]
I think this already works `PARCEL_ELM_DISABLE_DEBUG=true`

**Comment by alex-tan** [comment]
Weird I thought this PR was already merged in. Nevermind

**Comment by n1k0** [comment]
Any news with this? Do we plan to land this someday, or has the idea been entirely discarded? Would be nice to have some status update.

**Comment by DeMoorJasper** [comment]
This should be fixed in the new transformer for Parcel 2, gonna close this for now

**Comment by n1k0** [comment]
@DeMoorJasper why has this issue been closed? As far as I understand, the new transformer has not landed yet (#3351). Or maybe I missed something? If not, I suggest to reopen this issue for easier status tracking.

**Comment by DeMoorJasper** [comment]
I closed it because we were tracking elm improvements in multiple issues. I'll reopen it if you really want to

**Comment by n1k0** [comment]
Ah, I realize this is a PR, not an issue. So it's probably just fine to leave it closed. Sorry for the noise :)

**Pull request closed without merging**
