### PR TITLE
fix: opn is deprecated, use open instead

### PR DESCRIPTION
**Pull request by jamesgeorge007**
# ↪️ Pull Request
[opn](https://www.npmjs.com/package/opn) was renamed and deprecated to [open](https://www.npmjs.com/package/open).

## 💻 Examples
N/A

## 🚨 Test instructions
N/A

## ✔️ PR Todo

- [ ] Added/updated unit tests for this change
- [ ] Filled out test instructions (In case there aren't any unit tests)
- [ ] Included links to related issues/PRs

### CODE REVIEW

**Comment by jamesgeorge007** [comment]
cc @devongovett @DeMoorJasper

**Comment by jamesgeorge007** [comment]
@devongovett @DeMoorJasper `open` isn't compatible for node js below 6. Are you still planning to provide support for version 6 in the future releases :thinking:

**Comment by mischnic** [comment]
> Are you still planning to provide support for version 6 in the future releases 🤔

We will drop Node 6 support in Parcel 2. So this change won't happen in Parcel 1.

**Comment by jamesgeorge007** [comment]
@mischnic If that's the case, keeping it open for the `v2` release seems good right :thinking:

**Pull request closed without merging**
