### PR TITLE
add cache-dir option to cli

### LINKED ISSUE #709: [Feature] Make cache directory path configurable
Maybe I missed some information somewhere. It seems the `.cache` folder cannot be changed by configuration, that is something what should be possible.

### PR DESCRIPTION
**Pull request by DeMoorJasper**
Closes #709

### CODE REVIEW

**Comment by ekoeryanto** [comment]
why it still here?
Please merge it.

**Comment by devongovett** [comment]
what if we just call it `.parcel-cache` always, then it won't overwrite things?

**Comment by ekoeryanto** [comment]
@devongovett or ".cache/parcel"

**Comment by mohsen1** [comment]
`cache/parcel` will work with existing `.gitignore` rules

**Comment by devongovett** [comment]
I still think we should change the default so it conflicts less, but I merged anyway because I think it will be important e.g. for CI environments to be able to control the cache dir, for example if you wanted to put it outside a container in a shared location.

If someone wants to make a PR to change the default dir name, that would be great as well!

**Comment by devongovett** [comment]
released in v1.9.3.

**Pull request merged**
