### PR TITLE
Update dependency sharp to v0.32.1

### PR DESCRIPTION
**Pull request by smorimoto**
# ↪️ Pull Request

As the title says.

## 💻 Examples

N/A

## 🚨 Test instructions

CI is just enough.

## ✔️ PR Todo

- [ ] Added/updated unit tests for this change
- [ ] Filled out test instructions (In case there aren't any unit tests)
- [ ] Included links to related issues/PRs

### CODE REVIEW

**Comment by mischnic** [comment]
Are there any breaking changes regarding the configuration options? This sounds like that:

https://sharp.pixelplumbing.com/changelog#v0320---24th-march-2023:
> Replace GIF output `optimise` / `optimize` option with `reuse`.

**Comment by legobeat** [comment]
@mischnic This doesn't seem to affect the `optimi[sz]e(Coding|Scans)` options that are in use: https://sharp.pixelplumbing.com/api-output

So should be non-breaking from the perspective of `@parcel/transformer-image`?

**Comment by legobeat** [comment]
@smorimoto Needs rebase on `v2`.

**Comment by mischnic** [comment]
> So should be non-breaking from the perspective of @parcel/transformer-image?

In a `sharp.config.json` you could have `{"optimize": ...}` but that was renamed to `reuse` for GIF.

For example the https://sharp.pixelplumbing.com/api-output#gif

> rebase on v2.

No need, I can do that from the Github UI.

**Comment by devongovett** [comment]
If it's just a simple rename, maybe we could insulate the user from it by providing a backward compatibility layer for that option with a warning?

**Comment by smorimoto** [comment]
Sorry I'm so late. Well, actually some of the fixes were actually useful to us. Furthermore, it's a bit silly that Renovate PR fails every time because of Parcel. I think just warning is enough, but is that not enough?

**Comment by smorimoto** [comment]
- https://github.com/advisories/GHSA-j7hp-h8jx-5ppr
- https://github.com/lovell/sharp/security/advisories/GHSA-54xq-cgqr-rpm3

**Comment by smorimoto** [comment]
I will update this PR.

**Comment by mischnic** [comment]
We do need something like this:

> If it's just a simple rename, maybe we could insulate the user from it by providing a backward compatibility layer for that option with a warning?

**Comment by smorimoto** [comment]
In fact, here we can squash one thing, so it can be done in subsequent PR.

**Comment by akselinurmio** [comment]
Is there an issue open on updating the sharp? As far as I’m concerned, [GHSA-54xq-cgqr-rpm3](https://github.com/advisories/GHSA-54xq-cgqr-rpm3) is a valid vulnerability and needs resolving.

**Pull request closed without merging**
