### PR TITLE
Fix EntryResolver.resolveEntry infinite loop when entries look like globs

### PR DESCRIPTION
**Pull request by hacknlove**
# ↪️ Pull Request

https://github.com/parcel-bundler/parcel/issues/8519

## 💻 Examples

if you try to build any file whose path looks like a glob, like `/blog/[id].html` it will cause a infinite loop

## ✔️ PR Todo

~~I wasn't able to run test locally, I am having this error:~~

> ```
> /parcel/packages/core/core/src/AssetGraph.js: Cannot find module '@parcel/hash'
> ```

~~Even with v2 branch.~~

~~I couldn't find any solution. Maybe I need some guidance.~~

Also with the linter, It was erroring, but it was not showing any specific reason.

- [x] Added/updated unit tests for this change
- [ ] Filled out test instructions (In case there aren't any unit tests)
- [x] Included links to related issues/PRs

### CODE REVIEW

**Comment by mischnic** [comment]
> Cannot find module '@parcel/hash'

You need to have Rust installed and then run `yarn build-native` in the monorepo root.

**Comment by hacknlove** [comment]
I like better this last commit. I think it's simpler and faster, because it requires less stat checks operations.

But the previous one will do the job too.

**Comment by joshamaju** [comment]
Any chance on reviewing and merging this?

**Review by mischnic — APPROVED** [review]
Thanks!

**Pull request merged**
