### PR TITLE
Minify the prelude.js file as well.

### PR DESCRIPTION
**Pull request by ssuman**
Currently prelude.js file isn't being minified. This PR will address that issue by moving the minification process from JSAsset to JSPackager. #334

### CODE REVIEW

**Comment by ssuman** [comment]
Tests are successful locally. It failed here. Any idea ?

**Comment by devongovett** [comment]
Minification is done in JSAsset instead of JSPackager so that it can be done in parallel. This should be MUCH faster - not just because of the parallelism, but because minifying a bunch of small files is much faster than minifying one big file.

**Comment by devongovett** [comment]
To fix prelude.js not being minified, I'd suggest doing this as a build step before we publish to npm.

**Comment by nfantone** [comment]
@devongovett So, was this fixed after all? I was kinda waiting on this one. Do we have another issue to track progress?

**Comment by nfantone** [comment]
For anyone else interested in this, progress in being tracked on https://github.com/parcel-bundler/parcel/issues/334.

**Pull request closed without merging**
