### PR TITLE
[T-749] Offset sourcemaps when replacing bundle hashes

### PR DESCRIPTION
**Pull request by DeMoorJasper**
# ↪️ Pull Request

This PR fixes sourcemaps issues caused by hash ref replacement not offsetting the sourcemap.

## ✔️ PR Todo

- [x] Added/updated unit tests for this change
- [x] Filled out test instructions (In case there aren't any unit tests)
- [x] Included links to related issues/PRs

### CODE REVIEW

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>Kitchen Sink ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 8.97s | +17.00ms |
| Cached | 3.73s | +46.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/parcel.d5807e82.webp | 102.94kb | +0.00b | 351.00ms | +55.00ms ⚠️ |
| dist/modern/parcel.d5807e82.webp | 102.94kb | +0.00b | 423.00ms | +55.00ms ⚠️ |
| dist/modern/index.1964d1f6.js | 1.10kb | +0.00b | 3.14s | +223.00ms ⚠️ |
| dist/modern/index.html | 701.00b | +0.00b | 3.27s | +216.00ms ⚠️ |
| dist/modern/index.7bc22a8b.css | 77.00b | +0.00b | 3.09s | +204.00ms ⚠️ |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/modern/parcel.d5807e82.webp | 102.94kb | +0.00b | 264.00ms | +17.00ms ⚠️ |
| dist/modern/index.1964d1f6.js | 1.10kb | +0.00b | 408.00ms | -49.00ms 🚀 |
| dist/modern/index.html | 701.00b | +0.00b | 409.00ms | -48.00ms 🚀 |
| dist/modern/index.7bc22a8b.css | 77.00b | +0.00b | 408.00ms | -49.00ms 🚀 |

</p></details>

<details><summary>React HackerNews ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 34.02s | +1.77s ⚠️ |
| Cached | 3.71s | +38.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/NotFound.f8a0616d.js | 387.00b | +0.00b | 1.35s | +220.00ms ⚠️ |
| dist/logo.24c8bf9e.png | 274.00b | +0.00b | 132.00ms | -68.00ms 🚀 |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.js | 478.81kb | +0.00b | 294.00ms | +28.00ms ⚠️ |
| dist/PermalinkedComment.9c5ad065.js | 4.22kb | +0.00b | 294.00ms | +29.00ms ⚠️ |
| dist/UserProfile.c1927888.js | 1.62kb | +0.00b | 294.00ms | +29.00ms ⚠️ |
| dist/NotFound.f8a0616d.js | 387.00b | +0.00b | 172.00ms | -55.00ms 🚀 |
| dist/logo.24c8bf9e.png | 274.00b | +0.00b | 239.00ms | +44.00ms ⚠️ |

</p></details>

<details><summary>AtlasKit Editor ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 3.34m | +535.00ms |
| Cached | 8.05s | -58.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.accd8b81.js | 2.72mb | -6.00b 🚀 | 1.77m | +612.00ms |
| dist/popup.6c453e3c.js | 169.96kb | +0.00b | 44.01s | -24.20s 🚀 |
| dist/Modal.19ffed32.js | 41.27kb | +0.00b | 7.96s | +411.00ms ⚠️ |
| dist/component.54080a26.js | 22.50kb | +0.00b | 7.95s | +407.00ms ⚠️ |
| dist/dropzone.291ad844.js | 17.34kb | +0.00b | 1.15m | -36.70s 🚀 |
| dist/js.5733a017.js | 16.40kb | +0.00b | 7.95s | +409.00ms ⚠️ |
| dist/component.77c0f682.js | 6.05kb | +0.00b | 9.80s | -1.43s 🚀 |
| dist/EmojiPickerComponent.627aca6b.js | 3.58kb | +0.00b | 15.05s | +2.50s ⚠️ |
| dist/png-chunks-extract.a844fdb6.js | 3.41kb | +0.00b | 7.95s | +408.00ms ⚠️ |
| dist/Modal.0304b9ed.js | 3.08kb | +0.00b | 7.95s | +407.00ms ⚠️ |
| dist/16.290b4a43.js | 2.38kb | +0.00b | 2.71s | +486.00ms ⚠️ |
| dist/feedback.d5590b34.js | 1.64kb | +0.00b | 9.74s | -4.92s 🚀 |
| dist/workerHasher.fa198233.js | 1.54kb | +0.00b | 1.77m | +35.71s ⚠️ |
| dist/code.3dd71280.js | 1.38kb | +0.00b | 11.94s | +2.81s ⚠️ |
| dist/16.19c93285.js | 1.33kb | +0.00b | 9.86s | -1.38s 🚀 |
| dist/16.51049e2c.js | 1.32kb | +0.00b | 2.71s | +486.00ms ⚠️ |
| dist/16.436f097f.js | 1.21kb | +0.00b | 2.71s | +486.00ms ⚠️ |
| dist/16.b46ef690.js | 1.14kb | +0.00b | 2.71s | +486.00ms ⚠️ |
| dist/16.eafe1a11.js | 1.13kb | +0.00b | 9.80s | -1.43s 🚀 |
| dist/16.3920766f.js | 1.10kb | +0.00b | 2.71s | +485.00ms ⚠️ |
| dist/index.html | 119.00b | +0.00b | 8.79s | -1.28s 🚀 |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.accd8b81.js | 2.72mb | -6.00b 🚀 | 354.00ms | +14.00ms |
| dist/pdfRenderer.15a6a023.js | 1.11mb | -3.00b 🚀 | 640.00ms | +21.00ms |
| dist/EmojiPickerComponent.ae601247.js | 75.29kb | +0.00b | 558.00ms | -33.00ms 🚀 |
| dist/component.54080a26.js | 22.50kb | +0.00b | 614.00ms | +247.00ms ⚠️ |
| dist/DatePicker.0df05dac.js | 21.21kb | +0.00b | 558.00ms | -32.00ms 🚀 |
| dist/EmojiPickerComponent.7dc0ebd0.js | 18.23kb | +0.00b | 558.00ms | -33.00ms 🚀 |
| dist/component.77c0f682.js | 6.05kb | +0.00b | 405.00ms | +26.00ms ⚠️ |
| dist/EmojiPickerComponent.627aca6b.js | 3.58kb | +0.00b | 558.00ms | -33.00ms 🚀 |
| dist/16.290b4a43.js | 2.38kb | +0.00b | 381.00ms | -199.00ms 🚀 |
| dist/date.231500d2.js | 1.73kb | +0.00b | 482.00ms | +31.00ms ⚠️ |
| dist/16.d16f14ed.js | 1.73kb | +0.00b | 457.00ms | +44.00ms ⚠️ |
| dist/16.1b6ca79f.js | 1.66kb | +0.00b | 406.00ms | +27.00ms ⚠️ |
| dist/16.9ccb5b28.js | 1.38kb | +0.00b | 430.00ms | +27.00ms ⚠️ |
| dist/code.3dd71280.js | 1.38kb | +0.00b | 482.00ms | +31.00ms ⚠️ |
| dist/16.19c93285.js | 1.33kb | +0.00b | 406.00ms | +27.00ms ⚠️ |
| dist/16.c7751e34.js | 1.33kb | +0.00b | 429.00ms | +27.00ms ⚠️ |
| dist/16.51049e2c.js | 1.32kb | +0.00b | 614.00ms | +34.00ms ⚠️ |
| dist/16.18344f47.js | 1.31kb | +0.00b | 481.00ms | +31.00ms ⚠️ |
| dist/16.2c4c1846.js | 1.27kb | +0.00b | 458.00ms | +44.00ms ⚠️ |
| dist/16.d17ab186.js | 1.23kb | +0.00b | 458.00ms | +45.00ms ⚠️ |
| dist/16.436f097f.js | 1.21kb | +0.00b | 614.00ms | +33.00ms ⚠️ |
| dist/16.b4da0acb.js | 1.19kb | +0.00b | 458.00ms | +45.00ms ⚠️ |
| dist/16.02c68c4f.js | 1.18kb | +0.00b | 481.00ms | +30.00ms ⚠️ |
| dist/16.b46ef690.js | 1.14kb | +0.00b | 614.00ms | +33.00ms ⚠️ |
| dist/16.4e3b0235.js | 1.14kb | +0.00b | 430.00ms | +27.00ms ⚠️ |
| dist/16.9ba230ea.js | 1.13kb | +0.00b | 406.00ms | +27.00ms ⚠️ |
| dist/16.a37df53b.js | 1.13kb | +0.00b | 430.00ms | +27.00ms ⚠️ |
| dist/16.9adb4ec7.js | 1.13kb | +0.00b | 430.00ms | +27.00ms ⚠️ |
| dist/16.eafe1a11.js | 1.13kb | +0.00b | 405.00ms | +26.00ms ⚠️ |
| dist/16.3920766f.js | 1.10kb | +0.00b | 614.00ms | +33.00ms ⚠️ |
| dist/16.afcb09b6.js | 1.05kb | +0.00b | 458.00ms | +45.00ms ⚠️ |
| dist/action.9aa72b39.js | 1.00kb | +0.00b | 482.00ms | +31.00ms ⚠️ |
| dist/EmojiPickerComponent.2e54b9c6.js | 535.00b | +0.00b | 558.00ms | -33.00ms 🚀 |

</p></details>

<details><summary>Three.js x4 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/279815061926576652)**

**Comment by mischnic** [comment]
Do you have an example where sourcemaps were previously incorrect because of this?

**Comment by DeMoorJasper** [comment]
@mischnic no I don't have an example.

Will try and put together an example, although I'm sure this doesn't fix all issues though... it's just a first step towards proper sourcemaps

**Comment by DeMoorJasper** [comment]
closing this for now...

**Pull request closed without merging**
