### PR TITLE
Add support for HMR with elm-hot

### PR DESCRIPTION
**Pull request by ktosiek**
# ↪️ Pull Request

This PR adds integration with elm-hot - the HMR solution for Elm (at least I don't know about any other :-)). I've published this code before as a plugin, and after a suggestion from @domenkozar decided it would make more sense upstream.

## 💻 Examples

This will help when editing the app without changing the type of the app's model. Visual tweaks or testing the update logic should be much easier with working HMR.

## 🚨 Test instructions

Editing an Elm app (like changing a string) should cause the changes to be applied, without refreshing the page or changing the app's state.

## ✔️ PR Todo

- [x] Added/updated unit tests for this change
- [x] Filled out test instructions (In case there aren't any unit tests)
- [ ] Included links to related issues/PRs

### CODE REVIEW

**Comment by domenkozar** [comment]
It also probably needs elm-hot dependency? :)

**Comment by ktosiek** [comment]
Doesn't `localRequire` take care of installing dependencies?

**Comment by domenkozar** [comment]
Ah, could be. I wonder why no tests ran via CI.

**Comment by DeMoorJasper** [comment]
@ktosiek yes localRequire does that but probably a good idea to add it to devDeps to run tests a lil faster and reliable

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ktosiek** [comment]
@DeMoorJasper thank you, I've added it.
@domenkozar I guess because I've created the PR against the 1.x branch.

I'm not sure what the status is on 1.x vs 2.x, if the 1.x branch isn't developed anymore I'd be happy to rebase onto 2.x.

**Comment by DeMoorJasper** [comment]
@ktosiek v1.x is still being actively developed and maintained.

However the core team is currently mainly focusing on v2.x afaik.
It's still pretty far from being released as the latest stable version of parcel so contributions to parcel 1 are still very welcome :)

**Comment by DeMoorJasper** [comment]
@ktosiek I just saw why the tests aren't running properly.

The v1.x branch was a backup of the master branch before we moved to using a monorepo on the master branch.

Could you rebase this on the master branch? (as master is still v1.x)

**Comment by ktosiek** [comment]
Sure! I've assumed master is 2.x, because of the amount of changes :-)

**Comment by ktosiek** [comment]
I'm not sure what happened here, I've opened https://github.com/parcel-bundler/parcel/pull/2388 in place of this one.

**Pull request closed without merging**
