### PR TITLE
Fixes 3076: HMR update breaks in webworker

### LINKED ISSUE #2908: HMR Webworker: window isn't available
Hello, I'm currently getting an HMR error in my WebWorkers that seems to be related to a use of the `window` global in the hmr runtime [here](https://github.com/parcel-bundler/parcel/blob/636bb50baeae15730c3b91cd3b58b457c31f7200/packages/core/parcel-bundler/src/builtins/hmr-runtime.js#L63).   It wasn't clear to me if the fix was as simple as changing `window.location.reload()` to   `location.reload()` and  if there had been an unintentional regression introduced by #2676 so for now I'm just leaving this note -- any comments welcome.  thanks, nehal

_Originally posted by @habemus-papadum in https://github.com/parcel-bundler/parcel/issues/528#issuecomment-481274320_

### LINKED ISSUE #3076: HRM runtime calls `window.location.reload()`, breaks in in web worker context
# 🐛 bug report

HMR `update` events are currently causing `ReferenceError: window does not exist` in browser-targeted apps *that use web workers*.

This appears to be happening because `hrm-runtime.js` makes reference to the `window` global, which doesn't exist in a web worker context:

```javascript
if (handled) {
  console.clear();

  data.assets.forEach(function (asset) {
    hmrApply(global.parcelRequire, asset);
  });

  assetsToAccept.forEach(function (v) {
    hmrAcceptRun(v[0], v[1]);
  });
} else {
  window.location.reload(); 👈 But window doesn't exist in web worker context! 😭
}
```

## 🤔 Expected Behavior

No error should be encountered by web worker code when an HMR update occurs.

## 😯 Current Behavior

`ReferenceError: window does not exist`

## 💻 Code Sample

1. Clone [https://github.com/clintharris/parcel-hrm-bug-demo](https://github.com/clintharris/parcel-hrm-bug-demo)
1. `npm install && npm start`
1. Load http://localhost:1234, open browser JS console.
1. Edit `src/index.js` to trigger HMR `update`.
1. JS console error: `ReferenceError: window is not defined`

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.12.3
| Node             | 12.3
| npm/Yarn         | npm 6.4

### PR DESCRIPTION
**Pull request by clintharris**
# ↪️ Pull Request

Fixes #3076 by using a web worker-safe alternative to `window.reload()`.
Fixes #2908

## 🚨 Test instructions

1. Clone [https://github.com/clintharris/parcel-hrm-bug-demo](https://github.com/clintharris/parcel-hrm-bug-demo)
1. `npm install && npm start`
1. Load http://localhost:1234, open browser JS console.
1. Edit `src/index.js` to trigger HMR `update`.
1. JS console error: `ReferenceError: window is not defined`

## ✔️ PR Todo

- [ ] Added/updated unit tests for this change
- [ ] Filled out test instructions (In case there aren't any unit tests)
- [ ] Included links to related issues/PRs

### CODE REVIEW

**Comment by clintharris** [comment]
@mischnic any chance someone on the team could consider this for merging?

**Comment by stewart42** [comment]
I see this has been included in the tag `parcel-bundler@1.12.4-alpha.0` Any chance we can get a release for 1.2.4 soon even if it is in alpha?

**Comment by mischnic** [comment]
> I see this has been included in the tag parcel-bundler@1.12.4-alpha.0

This tag was created while publishing `2.0.0-alpha.0`, there is currently no `^1.12.0` release planned.

**Comment by stewart42** [comment]
@mischnic thanks for the quick reply. That is sad news, it would have been great to get some of these small fixes released while v2 is being worked on.

**Comment by mkg20001** [comment]
This bug has re-appeared in service workers

**Comment by mkg20001** [comment]
Oh wait, the fix wasn't released

I've made a tarball at: https://github.com/mkg20001/parcel/releases/download/backport-fix/parcel-bundler-1.12.4.tgz

**Comment by mischnic** [comment]
> Oh wait, the fix wasn't released

Also not in the release from yesterday?

**Comment by mkg20001** [comment]
Oh wait, didn't notice that one yet :sweat_smile:

**Pull request merged**
