### PR TITLE
Node forge update

### PR DESCRIPTION
**Pull request by DeMoorJasper**
This PR updates node-forge and the azure pipeline for parcel v1

### CODE REVIEW

**Review by w3bdesign — APPROVED** [review]

**Comment by GlenHughes** [comment]
Hi @DeMoorJasper, is there an ETA on this?

**Comment by mindctrl** [comment]
@DeMoorJasper need any help testing this? Getting notices about the vuln, and `npm audit fix --force` refuses to fix it.

**Comment by gustavocaspirro-mb** [comment]
@DeMoorJasper Hi, this PR will be merged?

**Comment by DeMoorJasper** [comment]
@gustavocaspirro-mb that's not up to me cc @devongovett

**Comment by gustavocaspirro-mb** [comment]
@devongovett helps us merging PR 😬  please

**Pull request merged**
