### PR TITLE
addURLDependency: use always relative path

### LINKED ISSUE #1801: Wrong relative path to URL assets when bundle lives in subdirectory
# 🐛 Bug Report

When two bundles in different directories with the same file name are generated, the directory structure is reflected in the output. This causes an issue with URL dependencies because their paths are relative to the current directory.

## 🎛 Configuration

Given the following directory structure:

```
assets
├── a
│   └── bundle.css
├── b
│   └── bundle.css
└── img
    └── foo.png
```

With the contents of `assets/a/bundle.css` being:

``` css
body {
    background-image: url('../img/foo.png');
}
```

And the following Parcel command:

```
parcel build --no-cache --no-source-maps 'assets/*/bundle.css'
```

The following directory tree is correctly generated:

```
dist
├── a
│   └── bundle.css
├── b
│   └── bundle.css
└── foo.d7b28491.png
```

So far so good. However...

## 🤔 Expected Behavior

I would expect the contents of `dist/a/bundle.css` to be either:

``` css
body{background-image:url(../foo.d7b28491.png)}
```

Or:

``` css
body{background-image:url(/foo.d7b28491.png)}
```

## 😯 Current Behavior

The contents of `dist/a/bundle.css` is currently:

``` css
body{background-image:url(foo.d7b28491.png)}
```

Which means the browser will request `/a/foo.png`, but the file is located at the web root – not in the "a" directory.

## 💁 Possible Solution

I'm really not familiar enough with Parcel to make an educated recommendation as to how is should be fixed, but I'm guessing the best way to fix the issue is by somehow making calculating the relative path to the URL asset from the bundle. So that (using the example code above), the output URL would be `url(../foo.[md5].png)`

Another possible solution is to join the URL with the publicURL option. This could be achieved by modifying the `Asset#addURLDependency()` method's return value, like so:

``` diff
+ const urlJoin = require('./utils/urlJoin');

...

- return URL.format(parsed);
+ return urlJoin(this.options.publicURL, URL.format(parsed));
```

This method seems to work, but as said before, I'm not familiar enough with Parcel to know if it's a viable solution. It does require modifying some tests, which indicates it could be a breaking change. Would love some feedback.

I have [made a commit](https://github.com/kalfheim/parcel/commit/b2233dc610576684b63728dcbb73ae63f42e673f) and will definitely create a PR if the solution is approved.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.9.7
| Node             | 10.7.0
| npm/Yarn         | Yarn 1.7.0
| Operating System | macOS 10.13.6

### PR DESCRIPTION
**Pull request by mischnic**
# ↪️ Pull Request

Fixes #1801
Previously rejected implementation: #1809

## 💻 Examples

```
assets
├── a
│   └── bundle.css
├── b
│   └── bundle.css
└── img
    └── foo.png
```
Running parcel with the two bundles.css as entry points, in the output
```
dist
├── a
│   └── bundle.css
├── b
│   └── bundle.css
└── foo.d7b28491.png
```
a/bundle.css would contain `url("foo.d7b28491.png")` (should be "../foo")

## ✔️ PR Todo

- [x] Added/updated unit tests for this change
- [x] Filled out test instructions (In case there aren't any unit tests)
- [x] Included links to related issues/PRs

### CODE REVIEW

**Comment by DeMoorJasper** [comment]
@mischnic just fyi the previous PR you linked just got closed because master had been force-pushed and Github automatically closed all open PRs, it had not been rejected.

**Comment by mischnic** [comment]
>just fyi the previous PR you linked just got closed because master had been force-pushed and Github automatically closed all open PRs, it had not been rejected.

Didn't compare the dates 😄 . But @devongovett wrote:
> I think it already gives a relative path. This makes the output more portable depending on where you move it to. Why does this not work?

The previous PR added the public url, this makes the relative path correct.

**Comment by rhurstdialpad** [comment]
This has broken CSS dependencies for me. For example, my fonts are stored in a /src/fonts away from my CSS which is stored in /src/css/fonts.css. Parcel correctly copies my fonts into the dist directory along with the generated CSS file (/dist/fonts.xxxxxx.css & /dist/my_font.xxxxxx.woff), but the final CSS file tries to load the fonts from a URL that includes the relative path from the original CSS file to the fonts directory (url('../fonts/my_font.xxxxxx.woff')), rather than the name of the file in the dist directory (url('my_font.xxxxxx.woff')). As such the parcel dev server cannot resolve the font files.

**Comment by rhurstdialpad** [comment]
This broke our build.

We have `--public-url` set to `/static/compiled/single`
Our fonts are in `/fonts` and our css is in `css/single`
Currently our css files that reference font files are ending up with a url to each font file that includes the public url and a path that seems to be the resolved path from the root dir and the relative path from the css file to the font file. The path from the css directory to the fonts directory is `../../fonts`. So in our case the font urls all look something like `/static/compliled/single/[dir outside project]/[dir outside project]/[font file].xxxxx.woff`. Obviously this is totally wrong, and as a the dev server 404s when trying to load the fonts.

**Comment by mischnic** [comment]
> We have `--public-url` set to `/static/compiled/single`.
Our fonts are in `/fonts` and our CSS is in `css/single`.

Is that second line referring to the url or your folder structure during development?
Could you please give an overview how both look like? Is this correct?
File system:
```
─ MyProject
  ├─ fonts
  │  └─ *.woff
  └─ css
     └─ single
        └─ *.css
```

Wanted output structure:
```
─ /static/compiled/single/
  ├─ *.woff
  └─ *.css
```
What does `dir outside project` mean exactly?


Otherwise, a very minimal reproduction would be helpful.

**Comment by rhurstdialpad** [comment]
That looks about right, with the exception of the output structure. `/static/compiled/single/` is the path I want the dev server to serve the assets on. My dist folder is the default.

When I say folder outside the project I mean just that. If my project is at /Users/Robert/Developer/MyProject, then the path is /static/compliled/single/Robert/Developer/[font file].xxxxx.woff.

**Pull request merged**
