### PR TITLE
JS runtime manifest

### PR DESCRIPTION
**Pull request by wbinnssmith**
This implements a manifest used by bundles using the JS runtime, allowing them to avoid writing the filename of external bundles into their own content. This prevents a cascade of content changes (a change in content of one bundle would update the content digest in its name, which would require a content change to its parents, and so on).

This is achieved by creating a mapping of short (16-character) bundle ids to bundle names in entry bundles. The bundles in this mapping are a subset of the entry bundle's subgraph, stopping when context changes (e.g. a page script including a worker script), descendants of non-js bundles, or when an inline bundle is encountered. This mapping is "registered" (merged into a singleton module-level object) as an entry asset side effect of running an entry bundle.

The other runtime code to load other bundles has been updated to always reference bundle ids, which is used to look up the bundle's name at runtime, avoiding a content change in "intermediate" bundles between one that changed and its entry bundle ancestors.

Computing the relative URL to the external bundle has also been moved to runtime, which required an implementation of `dirname()` and `relative()`.

To do:

* [x] Pass scope hoisting tests, where the registration side-effect seems to be happening after other entry asset code is run. cc @devongovett @mischnic
* [x] Pass output format tests
* [x] Implement a test that asserts that intermediate bundle names are not invalidated when a bundle's inner content changes between builds

### CODE REVIEW

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>packages/benchmarks/kitchen-sink ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 3.83s | -1.00ms |
| Cached | 3.37s | +121.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/parcel.d5807e82.webp | 102.94kb | +0.00b | 116.00ms | -44.00ms 🚀 |
| dist/index.js | 1.07kb | +1.75kb ⚠️ | 267.00ms | -44.00ms 🚀 |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/parcel.d5807e82.webp | 102.94kb | +0.00b | 2.00ms | -1.00ms 🚀 |
| dist/index.js | 1.07kb | +1.75kb ⚠️ | 6.00ms | -1.00ms 🚀 |

</p></details>

<details><summary>packages/benchmarks/react-hn ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 8.21s | +234.00ms |
| Cached | 3.31s | -112.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.js | 64.04kb | +397.00b ⚠️ | 1.14s | +59.00ms ⚠️ |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.js | 64.04kb | +397.00b ⚠️ | 366.00ms | +81.00ms ⚠️ |

</p></details>

<details><summary>packages/benchmarks/ak-editor ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 4.88s | +353.00ms ⚠️ |
| Cached | 3.57s | +393.00ms ⚠️ |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.js | 743.00b | +7.00b ⚠️ | 1.10s | +116.00ms ⚠️ |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.js | 743.00b | +7.00b ⚠️ | 64.00ms | +60.00ms ⚠️ |

</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/258027957081080329)**

**Comment by mischnic** [comment]
> Pass scope hoisting tests, where the registration side-effect seems to be happening after other entry asset code is run.

(Taking a look at the `scope-hoisting/es6/dynamic-import` test):
The order of the assets is determined here:
https://github.com/parcel-bundler/parcel/blob/8dc29d37664b24556ce0d2e91771b2ce30ae3f69/packages/shared/scope-hoisting/src/concat.js#L65-L99

I think adding a dependency from the asset with the dynamic import to the bundle manifest would maintain the order?

**Comment by wbinnssmith** [comment]
I've removed the draft state and this PR is ready for review 🙂

I addressed the issue with scope hoisting by changing the public `traverseBundle` and `traverseAssets` to respect the order reflected in the private `bundle.entryAssetIds`.

It now adds a new target descriptor and environment field `immutable`, which can currently be `nonentries` or `none`. In the future this will allow `all` for the namer to add content digests to all filenames. The namer currently doesn't use `none` currently as names are currently only based on the basename of entry assets and would collide.

If the environment's `immutable` value is `none`, no manifest register or resolve code is added, and instead the file names are written directly into runtime code.

cc @padmaia @devongovett @mischnic

**Comment by wbinnssmith** [comment]
This is good for a review @devongovett @mischnic @padmaia

**Pull request merged**
