### PR TITLE
Don't confuse workers with no-opt command line option

### PR DESCRIPTION
**Pull request by danieltroger**
# ↪️ Pull Request

Maybe fixes https://github.com/parcel-bundler/parcel/discussions/9237

## 💻 Examples

See https://github.com/parcel-bundler/parcel/discussions/9237

## 🚨 Test instructions

You can try setting up docker and node like described in the discussion above. But I don't see how this could hurt? Let's just try it and maybe it works.

## ✔️ PR Todo

- [ ] Added/updated unit tests for this change
- [X] Filled out test instructions (In case there aren't any unit tests)
- [X] Included links to related issues/PRs

### CODE REVIEW

**Comment by mischnic** [comment]
> You can try setting up docker and node like described in the discussion above. But I don't see how this could hurt? Let's just try it and maybe it works.

Or: set `NODE_OPTIONS="--opt"` which something in your setup does

**Comment by danieltroger** [comment]
> Or: set `NODE_OPTIONS="--opt"` which something in your setup does

I tried that, the problem is that it yields
`/Users/daniel/.nvm/versions/node/v20.5.0/bin/node: --opt is not allowed in NODE_OPTIONS`


And --no-opt

```
/Users/daniel/.nvm/versions/node/v20.5.0/bin/node: --no-opt is not allowed in NODE_OPTIONS
```

**Comment by mischnic** [comment]
I guess it has be injected in some other way then, e.g. by overriding the `node` binary on PATH or
```
$ node --opt
Welcome to Node.js v18.17.1.
Type ".help" for more information.
> process.execArgv
[ '--opt' ]
```

**Comment by danieltroger** [comment]
I manipulated my path and the argument is there when running node
```
daniel@mmmmmmmmmm utilishared % node                   
Welcome to Node.js v20.5.0.
Type ".help" for more information.
> process.execArgv
[ '--no-opt' ]
> 
```
but `yarn parcel build` still succeeds for me (suggesting that the option is not respected).
However, I did this change with a `yarn patch` and now my Dockerfile seems to get further.

EDIT: yup, my docker image builds successfully now 🎉

**Review by mischnic — APPROVED** [review]

**Pull request merged**
