### PR TITLE
TypeScriptAsset: Support baseUrl for module resolution

### PR DESCRIPTION
**Pull request by magcius**
# ↪️ Pull Request

TypeScript's compiler options allow for supplying a `baseUrl` where bare module imports will get resolved relative to. This adds support for `baseUrl` to Parcel.

## 💻 Examples

```json
{
    "compilerOptions": {
        "baseUrl": "./src"
    }
}
```

```ts
// src/A.ts
import { B } from 'B';
```

```ts
// src/B.ts
export class B {}
```

### CODE REVIEW

**Comment by magcius** [comment]
Test failure is existing, FYI.

**Comment by devongovett** [comment]
Thanks for your contribution. I'd like to wait until Parcel 2 to support this as we will have much better support for custom resolvers per-language, and are already planning a TypeScript resolver to implement the TS specific semantics.

**Comment by DeMoorJasper** [comment]
Gonna close this in favor of resolvers in Parcel 2

**Comment by youncccat** [comment]
Same problem in Parcel2

**Comment by mischnic** [comment]
-> https://github.com/parcel-bundler/parcel/issues/4936

**Pull request closed without merging**
