### PR TITLE
Wait for close event when writing bundles

### PR DESCRIPTION
**Pull request by mischnic**
# ↪️ Pull Request

I was getting "no such file or directory " when the bundle report was trying to read an bundle from the disk because the dist dir only contained 'index.js.68061.0.6'.

`NodeFS#createWriteStream` does the atomic renaming on `close`, but the `PackagerRunner` only waits for `finish`.

https://github.com/parcel-bundler/parcel/blob/619cbafbee2b677a11e03957a5389f60cfb4c482/packages/core/fs/src/NodeFS.js#L47

`finish` is fired before `close`

### Test instructions

Run `rm -rf dist/*; parcel build index.js --no-cache --detailed-report` multiple times. Before, that would occasionally result in:
```
✨ Built in 5.14s
[Error: ENOENT: no such file or directory, open '/Users/niklas/Desktop/will2/dist/index.js'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/niklas/Desktop/will2/dist/index.js'
}
```

### CODE REVIEW

**Comment by mischnic** [comment]
Don't know why all tests timeout, it works locally

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>Kitchen Sink ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 6.20s | -297.00ms |
| Cached | 2.28s | -30.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/parcel.d5807e82.webp | 102.94kb | +0.00b | 224.00ms | -73.00ms 🚀 |
| dist/modern/parcel.d5807e82.webp | 102.94kb | +0.00b | 224.00ms | -85.00ms 🚀 |
| dist/legacy/kitchen-sink.679578a5.js | 1.16kb | +0.00b | 1.43s | -215.00ms 🚀 |
| dist/modern/kitchen-sink.90de237b.js | 1.16kb | +0.00b | 571.00ms | -1.08s 🚀 |
| dist/legacy/index.html | 709.00b | +0.00b | 1.35s | +749.00ms ⚠️ |
| dist/modern/index.html | 709.00b | +0.00b | 1.35s | +750.00ms ⚠️ |
| dist/modern/styles.cda8c91b.css | 78.00b | +0.00b | 1.24s | -254.00ms 🚀 |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/parcel.d5807e82.webp | 102.94kb | +0.00b | 246.00ms | +34.00ms ⚠️ |
| dist/modern/parcel.d5807e82.webp | 102.94kb | +0.00b | 246.00ms | +35.00ms ⚠️ |

</p></details>

<details><summary>React HackerNews ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 9.30s | -31.00ms |
| Cached | 2.30s | +37.00ms |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/main/index.js | 66.80kb | +0.00b | 282.00ms | +41.00ms ⚠️ |
| dist/module/index.js | 37.47kb | +0.00b | 280.00ms | +40.00ms ⚠️ |

</p></details>

<details><summary>AtlasKit Editor 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

<details><summary>Three.js x4 🚨</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | **FAILED** | -0.00ms |
| Cached | **FAILED** | -0.00ms |

#### Cold Bundles

*No bundles found, this is probably a failed build...*
#### Cached Bundles

*No bundles found, this is probably a failed build...*
</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/264251901117202945)**

**Comment by mischnic** [comment]
It seemed like `initialStream` never fired `close` on CI, now it essentially does `Promise.all([pipedFinished, fsClosed])`

**Comment by mischnic** [comment]
Can someone reproduce this? I have a feeling that this only happened on Node 13 and works with 14 and 12.

**Comment by DeMoorJasper** [comment]
@mischnic I've ben able to reproduce this very reliably on my Mac, once I enabled autoDestroy it worked? According to the NodeJS docs this is the default option though so I'm kind of confused why this was neccessary anyway hope this does not have any side effects, tests seem to pass locally for me now.

**Comment by mischnic** [comment]
Somewhat related: I just got
```
$ PARCEL_BUNDLE_ANALYZER=1 parcel build .
ENOENT: no such file or directory, open '../dist/repl.HASH_REF_.......css'
```
I think we want 
```diff
diff --git packages/reporters/bundle-analyzer/src/BundleAnalyzerReporter.js packages/reporters/bundle-analyzer/src/BundleAnalyzerReporter.js
index df1d39e7..077f6537 100644
--- packages/reporters/bundle-analyzer/src/BundleAnalyzerReporter.js
+++ packages/reporters/bundle-analyzer/src/BundleAnalyzerReporter.js
@@ -22,7 +22,9 @@ export default new Reporter({
       Array<Bundle>,
     > = new DefaultMap(() => []);
     for (let bundle of event.bundleGraph.getBundles()) {
-      bundlesByTarget.get(bundle.target.name).push(bundle);
+      if (!bundle.isInline) {
+        bundlesByTarget.get(bundle.target.name).push(bundle);
+      }
     }
 
     let reportsDir = path.join(options.projectRoot, 'parcel-bundle-reports');
```
as well?

**Comment by DeMoorJasper** [comment]
@mischnic that's definitely supposed to exclude inline bundles

**Pull request merged**
