### PR TITLE
Upgrade Prettier to 1.19.1 and use all trailing commas

### PR DESCRIPTION
**Pull request by wbinnssmith**
This upgrades prettier to 1.19.1 and sets `trailingCommas` to `all`, with the exception of certain runtime files that aren't further processed by babel. These runtime files use only es5-compatible trailing commas.

Formatting is isolated to a single commit (b2534e5da8f0ac22b07dd6b6ccecd77b34ada17f) for ease of review.

Test Plan:

Verify the react-refresh demo runs in IE11 when IE11 is a part of the build target (to ensure no incompatible trailing commas are present in resulting browser code). Note: This required adding a promise polyfill from core-js and adding IE11 to the default browser targets.

### CODE REVIEW

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>packages/benchmarks/kitchen-sink ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 10.78s | -227.00ms |
| Cached | 9.51s | +106.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/parcel.ff215454.webp | 102.94kb | +0.00b | 224.00ms | +23.00ms ⚠️ |
| dist/modern/parcel.76ee4591.webp | 102.94kb | +0.00b | 224.00ms | +25.00ms ⚠️ |
| dist/legacy/index.js | 243.00b | +0.00b | 486.00ms | +33.00ms ⚠️ |
| dist/modern/index.js | 215.00b | +0.00b | 481.00ms | +33.00ms ⚠️ |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/index.js | 243.00b | +0.00b | 17.00ms | -1.00ms 🚀 |
| dist/modern/index.js | 215.00b | +0.00b | 12.00ms | -1.00ms 🚀 |
| dist/modern/index.css | 29.00b | +0.00b | 10.00ms | -1.00ms 🚀 |

</p></details>

<details><summary>packages/benchmarks/react-hn ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 15.37s | +230.00ms |
| Cached | 10.80s | -76.00ms |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/main/index.js | 34.00kb | +0.00b | 12.00ms | -4.00ms 🚀 |

</p></details>

<details><summary>packages/benchmarks/ak-editor ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 3.55m | +3.15s |
| Cached | 11.18s | -38.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.js | 2.33mb | +431.00b ⚠️ | 2.08m | +5.16s |
| dist/pdfRenderer.668ca09a.js | 1.13mb | +0.00b | 37.78s | -4.90s 🚀 |
| dist/smartMediaEditor.60646891.js | 601.42kb | +0.00b | 1.33m | -8.86s 🚀 |
| dist/Toolbar.b4bc0528.js | 105.37kb | +0.00b | 1.37m | -7.64s 🚀 |
| dist/EmojiPickerComponent.31eba2df.js | 105.35kb | +0.00b | 49.36s | -7.15s 🚀 |
| dist/media-viewer.05e7c9f7.js | 86.66kb | +0.00b | 7.77s | +567.00ms ⚠️ |
| dist/card.b7cd6948.js | 76.35kb | +0.00b | 7.77s | +568.00ms ⚠️ |
| dist/ui.4644d263.js | 73.69kb | +0.00b | 50.77s | -7.18s 🚀 |
| dist/smartMediaEditor.6a448478.js | 67.31kb | +0.00b | 1.04m | -7.99s 🚀 |
| dist/component.10b390dc.js | 46.17kb | +0.00b | 44.06s | -6.01s 🚀 |
| dist/popup.49173ea4.js | 44.40kb | +0.00b | 40.48s | -8.54s 🚀 |
| dist/popup.4eaf5454.js | 43.89kb | +0.00b | 42.98s | -2.62s 🚀 |
| dist/popup.0ccc1fc2.js | 40.68kb | +0.00b | 42.98s | -6.04s 🚀 |
| dist/popup.9050dea3.js | 37.83kb | +0.00b | 39.91s | -4.99s 🚀 |
| dist/DatePicker.3fed8988.js | 27.56kb | +0.00b | 48.09s | -6.40s 🚀 |
| dist/EmojiPickerComponent.7e355e17.js | 26.67kb | +0.00b | 48.09s | -6.41s 🚀 |
| dist/esm.f0029a4d.js | 25.71kb | +0.00b | 42.97s | -6.04s 🚀 |
| dist/workerHasher.d7e20c98.js | 11.56kb | +0.00b | 39.90s | -5.00s 🚀 |
| dist/EmojiTypeAheadComponent.1c09c30d.js | 10.44kb | +0.00b | 49.46s | -7.14s 🚀 |
| dist/card.f99e1597.js | 5.89kb | +0.00b | 14.77s | -2.36s 🚀 |
| dist/component.a26e593f.js | 5.62kb | +0.00b | 44.30s | -6.01s 🚀 |
| dist/index.css | 3.38kb | +0.00b | 1.40m | -7.34s 🚀 |
| dist/component.8fa44754.js | 3.38kb | +0.00b | 44.09s | -6.02s 🚀 |
| dist/feedback.4dda4a59.js | 2.93kb | +0.00b | 45.52s | -6.06s 🚀 |
| dist/EmojiUploadComponent.0460cc59.js | 2.91kb | +0.00b | 48.09s | -8.42s 🚀 |
| dist/component.ab65829f.js | 2.29kb | +0.00b | 44.30s | -6.01s 🚀 |
| dist/ResourcedEmojiComponent.2d80adbd.js | 2.25kb | +0.00b | 7.72s | +539.00ms ⚠️ |
| dist/media-picker-analytics-error-boundary.c660ebe7.js | 1.92kb | +0.00b | 43.03s | -6.02s 🚀 |
| dist/card.9520f336.js | 1.80kb | +0.00b | 14.77s | -2.36s 🚀 |
| dist/16.dcacbe5c.js | 1.69kb | +0.00b | 44.66s | -6.02s 🚀 |
| dist/date.cfe6153f.js | 1.63kb | +0.00b | 44.90s | -6.05s 🚀 |
| dist/16.de3f3184.js | 1.62kb | +0.00b | 44.47s | -6.00s 🚀 |
| dist/images.c60a97a9.js | 1.57kb | +0.00b | 44.99s | -6.05s 🚀 |
| dist/workerHasher.7f0e2d92.js | 1.48kb | +0.00b | 39.90s | -5.00s 🚀 |
| dist/workerHasher.30e330ec.js | 1.48kb | +0.00b | 50.12s | -7.15s 🚀 |
| dist/workerHasher.854262ce.js | 1.48kb | +0.00b | 50.12s | -7.18s 🚀 |
| dist/workerHasher.64914391.js | 1.48kb | +0.00b | 1.04m | -7.00s 🚀 |
| dist/status.e3ed4764.js | 1.35kb | +0.00b | 45.42s | -5.99s 🚀 |
| dist/list-number.dbe744df.js | 1.35kb | +0.00b | 45.12s | -6.04s 🚀 |
| dist/16.f54dac28.js | 1.34kb | +0.00b | 44.65s | -5.99s 🚀 |
| dist/16.8f0e8fe1.js | 1.29kb | +0.00b | 44.32s | -6.05s 🚀 |
| dist/16.43b62c01.js | 1.29kb | +0.00b | 44.47s | -6.00s 🚀 |
| dist/code.092e0137.js | 1.28kb | +0.00b | 44.89s | -6.02s 🚀 |
| dist/16.b17a4d30.js | 1.27kb | +0.00b | 44.80s | -6.03s 🚀 |
| dist/16.51bbc68e.js | 1.23kb | +0.00b | 44.79s | -6.00s 🚀 |
| dist/component.8351f228.js | 1.23kb | +0.00b | 44.06s | -6.01s 🚀 |
| dist/link.6fa27bb2.js | 1.20kb | +0.00b | 45.12s | -6.04s 🚀 |
| dist/heading6.3996fe48.js | 1.19kb | +0.00b | 45.51s | -6.04s 🚀 |
| dist/16.385d3ff5.js | 1.19kb | +0.00b | 44.79s | -6.01s 🚀 |
| dist/heading3.9fea5413.js | 1.18kb | +0.00b | 45.51s | -6.04s 🚀 |
| dist/16.b3ce4050.js | 1.16kb | +0.00b | 44.47s | -6.00s 🚀 |
| dist/16.e37bbe6b.js | 1.15kb | +0.00b | 44.79s | -6.01s 🚀 |
| dist/16.f7fe274a.js | 1.14kb | +0.00b | 44.89s | -6.02s 🚀 |
| dist/emoji.c4bc5355.js | 1.12kb | +0.00b | 44.99s | -6.05s 🚀 |
| dist/16.ac2ff83f.js | 1.10kb | +0.00b | 44.65s | -6.00s 🚀 |
| dist/16.4c652b29.js | 1.10kb | +0.00b | 44.49s | -6.02s 🚀 |
| dist/16.24165259.js | 1.09kb | +0.00b | 44.47s | -6.00s 🚀 |
| dist/16.74510c56.js | 1.09kb | +0.00b | 44.65s | -5.99s 🚀 |
| dist/16.97c5bdf9.js | 1.09kb | +0.00b | 44.65s | -5.99s 🚀 |
| dist/16.a79db876.js | 1.09kb | +0.00b | 44.30s | -6.01s 🚀 |
| dist/heading5.2f045997.js | 1.06kb | +0.00b | 45.51s | -6.04s 🚀 |
| dist/16.6f8ac62a.js | 1.05kb | +0.00b | 44.30s | -6.01s 🚀 |
| dist/card.aae6ebb9.js | 1.04kb | +0.00b | 14.77s | -2.37s 🚀 |
| dist/16.3e36da0b.js | 1.01kb | +0.00b | 44.78s | -6.01s 🚀 |
| dist/heading2.2194210a.js | 1.00kb | +0.00b | 45.45s | -6.01s 🚀 |
| dist/mention.9fdad24e.js | 981.00b | +0.00b | 45.12s | -6.04s 🚀 |
| dist/fallback.305c8864.js | 980.00b | +0.00b | 45.42s | -5.99s 🚀 |
| dist/heading4.63d1ca06.js | 976.00b | +0.00b | 45.51s | -6.04s 🚀 |
| dist/layout.6f66c2da.js | 962.00b | +0.00b | 45.00s | -6.06s 🚀 |
| dist/divider.160f3108.js | 940.00b | +0.00b | 44.99s | -6.05s 🚀 |
| dist/quote.88bfdca4.js | 936.00b | +0.00b | 45.31s | -6.01s 🚀 |
| dist/action.146450ba.js | 919.00b | +0.00b | 44.89s | -6.02s 🚀 |
| dist/decision.06254b93.js | 898.00b | +0.00b | 44.99s | -6.05s 🚀 |
| dist/panel-warning.59c8ef3f.js | 891.00b | +0.00b | 45.29s | -6.00s 🚀 |
| dist/list.4f623de3.js | 870.00b | +0.00b | 45.12s | -6.04s 🚀 |
| dist/heading1.65fb8482.js | 864.00b | +0.00b | 45.42s | -6.01s 🚀 |
| dist/panel-error.c2479698.js | 791.00b | +0.00b | 45.12s | -6.06s 🚀 |
| dist/panel.23cd7224.js | 788.00b | +0.00b | 45.29s | -6.01s 🚀 |
| dist/table.4ace5843.js | 780.00b | +0.00b | 45.42s | -5.99s 🚀 |
| dist/media-viewer-analytics-error-boundary.dd752a9e.js | 777.00b | +0.00b | 14.77s | -2.37s 🚀 |
| dist/panel-success.6a7b97d7.js | 728.00b | +0.00b | 45.29s | -6.00s 🚀 |
| dist/panel-note.5ff85bdc.js | 727.00b | +0.00b | 45.29s | -6.00s 🚀 |
| dist/simpleHasher.efc670cc.js | 446.00b | +0.00b | 39.90s | -5.00s 🚀 |
| dist/simpleHasher.f8edc084.js | 446.00b | +0.00b | 50.12s | -7.15s 🚀 |
| dist/simpleHasher.884d4eb6.js | 446.00b | +0.00b | 50.13s | -7.17s 🚀 |
| dist/simpleHasher.c5e45ebc.js | 446.00b | +0.00b | 1.04m | -7.00s 🚀 |
| dist/esm.976debcc.js | 178.00b | +0.00b | 7.67s | +529.00ms ⚠️ |
| dist/dropzone.976debcc.js | 177.00b | +1.00b ⚠️ | 2.08m | +1.26m ⚠️ |
| dist/clipboard.976debcc.js | 177.00b | +1.00b ⚠️ | 44.06s | -6.01s 🚀 |
| dist/browser.976debcc.js | 177.00b | +1.00b ⚠️ | 1.33m | +29.67s ⚠️ |
| dist/editorView.976debcc.js | 177.00b | -1.00b 🚀 | 42.98s | -44.61s 🚀 |
| dist/media-card-analytics-error-boundary.976debcc.js | 176.00b | -5.00b 🚀 | 44.89s | -1.24m 🚀 |
| dist/16.976debcc.js | 174.00b | -5.00b 🚀 | 44.06s | -6.85s 🚀 |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.js | 2.34mb | +431.00b ⚠️ | 471.00ms | +63.00ms ⚠️ |
| dist/smartMediaEditor.60646891.js | 601.42kb | +0.00b | 173.00ms | -21.00ms 🚀 |
| dist/Toolbar.b4bc0528.js | 105.38kb | +0.00b | 131.00ms | -7.00ms 🚀 |
| dist/EmojiPickerComponent.31eba2df.js | 105.35kb | +0.00b | 136.00ms | -8.00ms 🚀 |
| dist/ui.4644d263.js | 73.69kb | +0.00b | 133.00ms | -8.00ms 🚀 |
| dist/smartMediaEditor.6a448478.js | 67.31kb | +0.00b | 132.00ms | -7.00ms 🚀 |
| dist/popup.49173ea4.js | 44.40kb | +0.00b | 152.00ms | -10.00ms 🚀 |
| dist/popup.0ccc1fc2.js | 40.68kb | +0.00b | 151.00ms | -9.00ms 🚀 |
| dist/popup.9050dea3.js | 37.83kb | +0.00b | 154.00ms | -9.00ms 🚀 |
| dist/DatePicker.3fed8988.js | 27.56kb | +0.00b | 122.00ms | -11.00ms 🚀 |
| dist/EmojiPickerComponent.7e355e17.js | 26.67kb | +0.00b | 122.00ms | -11.00ms 🚀 |
| dist/js.5c3f5692.js | 16.54kb | +0.00b | 156.00ms | -8.00ms 🚀 |
| dist/workerHasher.d7e20c98.js | 11.56kb | +0.00b | 153.00ms | -8.00ms 🚀 |
| dist/EmojiTypeAheadComponent.1c09c30d.js | 10.44kb | +0.00b | 121.00ms | -11.00ms 🚀 |
| dist/card.f99e1597.js | 5.89kb | +0.00b | 156.00ms | -8.00ms 🚀 |
| dist/component.a26e593f.js | 5.62kb | +0.00b | 140.00ms | -16.00ms 🚀 |
| dist/index.css | 3.38kb | +0.00b | 100.00ms | -9.00ms 🚀 |
| dist/component.8fa44754.js | 3.38kb | +0.00b | 141.00ms | -15.00ms 🚀 |
| dist/png-chunks-extract.4dfdb705.js | 3.33kb | +0.00b | 155.00ms | -8.00ms 🚀 |
| dist/feedback.4dda4a59.js | 2.93kb | +0.00b | 123.00ms | -11.00ms 🚀 |
| dist/EmojiUploadComponent.0460cc59.js | 2.91kb | +0.00b | 122.00ms | -10.00ms 🚀 |
| dist/component.ab65829f.js | 2.29kb | +0.00b | 141.00ms | -15.00ms 🚀 |
| dist/media-picker-analytics-error-boundary.c660ebe7.js | 1.92kb | +0.00b | 151.00ms | -8.00ms 🚀 |
| dist/16.dcacbe5c.js | 1.69kb | +0.00b | 134.00ms | -9.00ms 🚀 |
| dist/date.cfe6153f.js | 1.63kb | +0.00b | 132.00ms | -9.00ms 🚀 |
| dist/16.de3f3184.js | 1.62kb | +0.00b | 138.00ms | -9.00ms 🚀 |
| dist/images.c60a97a9.js | 1.57kb | +0.00b | 130.00ms | -9.00ms 🚀 |
| dist/workerHasher.7f0e2d92.js | 1.48kb | +0.00b | 153.00ms | -9.00ms 🚀 |
| dist/workerHasher.30e330ec.js | 1.48kb | +0.00b | 121.00ms | -11.00ms 🚀 |
| dist/workerHasher.854262ce.js | 1.48kb | +0.00b | 121.00ms | -10.00ms 🚀 |
| dist/status.e3ed4764.js | 1.35kb | +0.00b | 126.00ms | -10.00ms 🚀 |
| dist/list-number.dbe744df.js | 1.35kb | +0.00b | 129.00ms | -9.00ms 🚀 |
| dist/16.8f0e8fe1.js | 1.29kb | +0.00b | 139.00ms | -8.00ms 🚀 |
| dist/16.43b62c01.js | 1.29kb | +0.00b | 137.00ms | -8.00ms 🚀 |
| dist/code.092e0137.js | 1.28kb | +0.00b | 132.00ms | -9.00ms 🚀 |
| dist/16.b17a4d30.js | 1.27kb | +0.00b | 133.00ms | -8.00ms 🚀 |
| dist/16.51bbc68e.js | 1.23kb | +0.00b | 134.00ms | -8.00ms 🚀 |
| dist/link.6fa27bb2.js | 1.20kb | +0.00b | 129.00ms | -10.00ms 🚀 |
| dist/heading6.3996fe48.js | 1.19kb | +0.00b | 124.00ms | -10.00ms 🚀 |
| dist/16.385d3ff5.js | 1.19kb | +0.00b | 134.00ms | -9.00ms 🚀 |
| dist/heading3.9fea5413.js | 1.18kb | +0.00b | 125.00ms | -9.00ms 🚀 |
| dist/16.b3ce4050.js | 1.16kb | +0.00b | 138.00ms | -8.00ms 🚀 |
| dist/16.e37bbe6b.js | 1.15kb | +0.00b | 133.00ms | -10.00ms 🚀 |
| dist/16.f7fe274a.js | 1.14kb | +0.00b | 133.00ms | -9.00ms 🚀 |
| dist/emoji.c4bc5355.js | 1.12kb | +0.00b | 131.00ms | -9.00ms 🚀 |
| dist/16.ac2ff83f.js | 1.10kb | +0.00b | 135.00ms | -9.00ms 🚀 |
| dist/16.4c652b29.js | 1.10kb | +0.00b | 137.00ms | -8.00ms 🚀 |
| dist/16.24165259.js | 1.09kb | +0.00b | 138.00ms | -8.00ms 🚀 |
| dist/16.97c5bdf9.js | 1.09kb | +0.00b | 136.00ms | -8.00ms 🚀 |
| dist/16.a79db876.js | 1.09kb | +0.00b | 139.00ms | -7.00ms 🚀 |
| dist/heading5.2f045997.js | 1.06kb | +0.00b | 124.00ms | -10.00ms 🚀 |
| dist/16.6f8ac62a.js | 1.05kb | +0.00b | 140.00ms | -15.00ms 🚀 |
| dist/16.3e36da0b.js | 1.01kb | +0.00b | 133.00ms | -9.00ms 🚀 |
| dist/heading2.2194210a.js | 1.00kb | +0.00b | 125.00ms | -9.00ms 🚀 |
| dist/mention.9fdad24e.js | 981.00b | +0.00b | 128.00ms | -10.00ms 🚀 |
| dist/fallback.305c8864.js | 980.00b | +0.00b | 126.00ms | -9.00ms 🚀 |
| dist/heading4.63d1ca06.js | 976.00b | +0.00b | 125.00ms | -10.00ms 🚀 |
| dist/layout.6f66c2da.js | 962.00b | +0.00b | 130.00ms | -9.00ms 🚀 |
| dist/divider.160f3108.js | 940.00b | +0.00b | 131.00ms | -9.00ms 🚀 |
| dist/quote.88bfdca4.js | 936.00b | +0.00b | 126.00ms | -10.00ms 🚀 |
| dist/action.146450ba.js | 919.00b | +0.00b | 132.00ms | -9.00ms 🚀 |
| dist/decision.06254b93.js | 898.00b | +0.00b | 131.00ms | -9.00ms 🚀 |
| dist/panel-warning.59c8ef3f.js | 891.00b | +0.00b | 127.00ms | -9.00ms 🚀 |
| dist/list.4f623de3.js | 870.00b | +0.00b | 128.00ms | -10.00ms 🚀 |
| dist/heading1.65fb8482.js | 864.00b | +0.00b | 126.00ms | -9.00ms 🚀 |
| dist/panel-error.c2479698.js | 791.00b | +0.00b | 128.00ms | -9.00ms 🚀 |
| dist/panel.23cd7224.js | 788.00b | +0.00b | 126.00ms | -10.00ms 🚀 |
| dist/table.4ace5843.js | 780.00b | +0.00b | 125.00ms | -10.00ms 🚀 |
| dist/panel-success.6a7b97d7.js | 728.00b | +0.00b | 127.00ms | -10.00ms 🚀 |
| dist/panel-note.5ff85bdc.js | 727.00b | +0.00b | 127.00ms | -10.00ms 🚀 |
| dist/simpleHasher.efc670cc.js | 446.00b | +0.00b | 153.00ms | -8.00ms 🚀 |
| dist/simpleHasher.f8edc084.js | 446.00b | +0.00b | 121.00ms | -10.00ms 🚀 |
| dist/esm.976debcc.js | 176.00b | +2.00b ⚠️ | 159.00ms | -7.00ms |
| dist/media-card-analytics-error-boundary.976debcc.js | 176.00b | +2.00b ⚠️ | 156.00ms | -8.00ms 🚀 |
| dist/dropzone.976debcc.js | 176.00b | +2.00b ⚠️ | 152.00ms | -7.00ms |
| dist/clipboard.976debcc.js | 176.00b | +2.00b ⚠️ | 151.00ms | -7.00ms |
| dist/browser.976debcc.js | 176.00b | +2.00b ⚠️ | 151.00ms | -7.00ms |
| dist/16.976debcc.js | 176.00b | +2.00b ⚠️ | 133.00ms | -8.00ms 🚀 |
| dist/editorView.976debcc.js | 176.00b | +2.00b ⚠️ | 124.00ms | -3.00ms |

</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/251054514353734154)**

**Comment by DeMoorJasper** [comment]
Do we really need trailing commas? Seems like a lot of file changes for something that's pretty minor and might even break runtimes on older browsers

**Comment by wbinnssmith** [comment]
Not treating the last object property/function parameter lines specially means that while editing, lines can be shifted without making changes to others. This also reduces diff size and provides a more accurate diff blame — appending a new property/parameter on its own line doesn't require a change to the prior line (adding a comma).

@mischnic @padmaia is this fine by you?

**Comment by mischnic** [comment]
👍 I'm not opposed

**Pull request merged**
