### PR TITLE
fix: just bundle for non-html entry

### LINKED ISSUE #1005: [RFC] Don't start dev server for Node bundling?
Currently, when you run parcel with `--target` set to `node`, it starts a static dev server on port `:1234`. This doesn't really make sense for Node bundling, since we don't expect the code to run in the browser.

Is anybody opposed to disabling the dev server for node bundling?

### PR DESCRIPTION
**Pull request by lili21**
fix #1005

### CODE REVIEW

**Comment by DeMoorJasper** [comment]
What about htm or something that gets transpiled to html?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lili21** [comment]
I can do that with parcel ?

**Comment by lili21** [comment]
any suggestion ?

**Comment by DeMoorJasper** [comment]
Just wondering, this isn't related to the issue? The issue was about never starting a dev server if target is not browser as that makes no sense.
But this wouldn't start a server even if the target is browser which does make sense even for js entryAssets (although in practise perhaps a very niche use-case, this is why `parcel watch` exists)

**Comment by devongovett** [comment]
I think there are valid use cases for running the server when the entry point isn't an HTML file. Maybe your HTML is served separately, or generated dynamically from a different server, for example.

**Pull request closed without merging**
