### PR TITLE
fix: use require.resolve when resolving default config

### PR DESCRIPTION
**Pull request by paul-soporan**
# ↪️ Pull Request

`2.0.0-nightly.396` regressed PnP support in https://github.com/parcel-bundler/parcel/pull/4927, by not using `require.resolve` to load the `defaultConfig` - `@parcel/config-default`: https://github.com/parcel-bundler/parcel/pull/4927/files#diff-57d3138ed35ffa967c184c701e6efea4R181.

Yarn's E2E tests caught this issue after `2.0.0-nightly.396` was released: https://github.com/yarnpkg/berry/runs/1097463270?check_suite_focus=true#step:5:157.

This was solved by using `require.resolve` to resolve `@parcel/config-default`, which causes it to be resolved on behalf of `parcel`. I can confirm that this change fixes the issue.

## 💻 Examples

```bash
cd $(mktemp -d)
yarn init -2y
yarn add parcel@2.0.0-nightly.396 @babel/core
echo "console.log('Hello World')" > index.js
yarn parcel build index.js
```

**Expected:** Build should succeed.
**Got:** `Error: Cannot find module '@parcel/config-default' `

## 🚨 Test instructions

Parcel's PnP test didn't catch this because it goes through `@parcel/test-utils` instead of the CLI. I've looked a bit into Parcel's testing infrastructure, but I couldn't find tests testing the actual CLI (In case they exist, I'd be happy to add a basic PnP CLI test).

## ✔️ PR Todo

- [ ] Added/updated unit tests for this change
- [x] Filled out test instructions (In case there aren't any unit tests)
- [x] Included links to related issues/PRs

### CODE REVIEW

**Comment by wbinnssmith** [comment]
cc @padmaia

**Comment by mischnic** [comment]
I think we actually want to try `packageManager.resolve` first and then fallback to `resolve` so that we use a user-installed version of `@parcel/config-default` if possible and otherwise fall back?

**Comment by paul-soporan** [comment]
Are there any advantages to using `packageManager.resolve` instead of `require.resolve('@parcel/config-default', { paths: [fs.cwd(), __dirname] })` (which also achieves the fallback without a `try / catch`)?

**Comment by mischnic** [comment]
Generally,  `packageManger` would also read from a potential MemoryFS as `inputFS`. Though in this case that will never be the case.

I didn't know about the `paths` option 😄  👍

**Comment by paul-soporan** [comment]
Done! Apparently the Flow server in VSCode decided to take a nap while I was developing. 😅

**Review by mischnic — APPROVED** [review]
Waiting for @padmaia to double check...

**Review by padmaia — APPROVED** [review]

**Pull request merged**
