### PR TITLE
Add a verbose and debug mode to parcel for better bug reports

### LINKED ISSUE #993: 🙋Add verbose logging mode
**Choose one:** is this a 🐛 bug report or 🙋 feature request?

🙋 feature request

It's impossible to debug an issue or to show anyone if I can't see what's happening. All logging messages are replaced one the build is done.

### 🎛 Configuration (.babelrc, package.json, cli command)

```sh
parcel watch
```

### 🤔 Expected Behavior

```sh
$ parcel watch --verbose
Server running at http://localhost:1234 
⏳  Building index.html...
⏳  Building index.js...
✨  Built in 3.78s.
⏳  Building index.js...
✨  Built in 0.78s.
⏳  Building index.html...
✨  Built in 0.1s.
```

### 😯 Current Behavior

```sh
$ parcel watch
Server running at http://localhost:1234 
✨  Built in 3.78s.
# what happened?! what did it do?
```

### 🔦 Context

Mostly for debugging purposes

### 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 1.6.2
| Node             | 8.6.0
| npm/Yarn         | 5.7.1
| Operating System | macOS 10.13.3

### LINKED ISSUE #1527: 🙋 Allow logger to be configured about appending vs. cleaning console
# 🙋 Development Logging without cleaning console
Currently when running Parcel in development mode, logger will clean up console on each build. It's usually desired to have a clean console but when integrating with other tools such as VSCode, it's desired to have output of logger concatenated to previous logs instead of clearing the console. VSCode uses output of a program in "tasks" to determine if a task is ready or not. With current setup VSCode is not capable of doing that. 

## 🤔 Expected Behavior
Have a config for logger (maybe level 4) where all logs persist 

## 😯 Current Behavior
Logger clears the console

## 🔦 Context
https://github.com/Microsoft/vscode/issues/6209#issuecomment-350814733
https://github.com/mohsen1/parcel-react-typescript-vscode

### PR DESCRIPTION
**Pull request by DeMoorJasper**
This PR adds 2 extra log modes, one verbose mode and debug mode

This way we can just ask to submit their build (debug) log to a bug report in case it's a private project

It will also help with debugging for anyone looking into the issues

logLevel 4 => Verbose
logLevel 5 => Debug/Log mode (creates a log file per build)

Debug log format: `parcel-debug-yyyy-mm-dd@hh:mm:ss.log`
Verbose line format: `[timestamp]: ...`

Closes #993 Closes #1527 
Related issue, that might benefit from this debug mode: #1331

### CODE REVIEW

**Comment by devongovett** [comment]
This would probably be useful, but I'm a little worried about performance of all of these extra function calls when it is not enabled. Did you do any perf testing?

**Comment by tmchng** [comment]
@devongovett Honestly I think right now parcel should focus on getting rid of critical bugs first (like #1331). 

This PR will be much needed so that people like myself who come across blocking bugs can help out more easily. Performance can come later, and users like myself can wait.

Parcel is a great tool, and it's frustrating that I now need to go back to webpack again due to random freezes.

**Comment by kjellski** [comment]
@devongovett I think @tmchng is right. We currently have absolutely no option to provide information on why the tool is breaking our builds. For me it suddenly hangs somewhere and then we're done. No way to find out. Going back to webpack seems the only way out currently...

And that's really sad, honestly... I'd like to help, but I can't.

**Comment by DeMoorJasper** [comment]
Please move discussion to #1834 or open a new issue

**Comment by DeMoorJasper** [comment]
@kjellski Might be related to sass if you're using that, see #1847

Feel free to hit me up on https://spectrum.chat/parcel if you need any help debugging or fixing the issue

**Pull request closed without merging**
