### PR TITLE
Separate `tmp` directory for each test to improve tests stability

### PR DESCRIPTION
**Pull request by CvX**
Previously, tests were writing and to `/test/[dist | input]`. That often lead to file access conflicts and required hacks like this: https://github.com/parcel-bundler/parcel/blob/fb472448886f8882c644c7832b6896836c167deb/test/utils.js#L10-L18

This PR changes tests so that each one writes to `/tmp/[random hash]/[dist | input]`. This change reduces the number of flaky tests to two (at least in my local dev environment):
1. "wasm --target=node should load a wasm file in parallel with a dynamic JS import" [test/wasm.js:70](https://github.com/CvX/parcel/blob/ee898fe2551629d2aac8783120f1986fcee20c03/test/wasm.js#L70)
2. "css should automatically install postcss plugins with yarn if needed" [test/css.js:254](https://github.com/CvX/parcel/blob/ee898fe2551629d2aac8783120f1986fcee20c03/test/css.js#L254)

I recognize that it's a quite large change, but it moves parcel closer to a green build on master and provides a foundation for future changes in this tests area, like parallel execution of test cases (plus, it slightly reduces amount of code: -43 lines! 😉).

### CODE REVIEW

**Comment by DeMoorJasper** [comment]
Duplicate of #881 ?

**Comment by DeMoorJasper** [comment]
@CvX why did u close this?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by CvX** [comment]
Sorry, should have commented before closing.

You're right, it is a duplicate of #881. I like how we've made pretty much the same changes to fix those issues. 😁

I'll review/comment on your PR and later, if necessary, I'll open a new PR targeting `test-folder-per-test` branch. 😃

**Comment by DeMoorJasper** [comment]
@CvX Sounds good, looking forward to your improvements

**Pull request closed without merging**
