### PR TITLE
add depedency function to watching  resources loaded by posthtml-include

### PR DESCRIPTION
**Pull request by easylogic**
This PR adds  depedency function for posthtml-include resources. 

This can be watching to  resources loaded by posthtml-include. 

refer to #488

### CODE REVIEW

**Comment by devongovett** [comment]
Hey thanks, this is great! Could you add a test?

**Comment by easylogic** [comment]
Okay, I'll add a test code and let you know.

**Comment by jdanyow** [comment]
This PR didn't work for me. The `addDependencyTo` object needed to be on the `posthtml-include` plugin's config.  Here's what worked for me:

```diff
async function getConfig(asset) {
  let config =
    asset.package.posthtml ||
    (await asset.getConfig([
      '.posthtmlrc',
      '.posthtmlrc.js',
      'posthtml.config.js'
    ]));
  if (!config && !asset.options.minify) {
    return;
  }

  config = config || {};
+  if (config.plugins && config.plugins['posthtml-include']) {
+    config.plugins['posthtml-include'].addDependencyTo = {
+      addDependency: function (src) {
+        asset.addDependency(src, { includedInParent: true });
+      }
+    };
+  }
  config.plugins = await loadPlugins(config.plugins, asset.name);
  config.skipParse = true;
  return config;
}
```

Open questions:

1. Should we put `addDependencyTo` on each plugin's config or specifically `posthtml-include`?  Seems like `posthtml-modules` and `posthtml-md` should be calling `addDependencyTo.addDependency` but they aren't (bug/missing feature).
2. Should we check whether the plugin config already has an `addDependencyTo` property and preserve/wrap it's `addDependency` function? Seems like overkill but worth thinking about.

**Comment by easylogic** [comment]
hi @jdanyow 

sorry for lately answer. 

addDependencyTo  config  is only exists in posthtml-include. 

In the example provided by Pascal Bundler, you can not bring posthtml-include as a property of your plugins.

refer to https://github.com/parcel-bundler/parcel/blob/master/test/integration/posthtml/.posthtmlrc.js 

so   I didn't use   config.plugins['posthtml-include']  property. 

i don't know  that how to check  posthtml-include module options. 
It also keeps failing in creating test codes for posthtml-include dependency watching

**Comment by jdanyow** [comment]
@easylogic are you still working on this? Want me to open another PR with the changes I mentioned earlier?

**Pull request closed without merging**
