### PR TITLE
Add support for excluding specific node_modules

### PR DESCRIPTION
**Pull request by devongovett**
Related: #144, #3305, #3753.

This adds support for excluding specific node_modules from a bundle. The inverse was already possible via `includeNodeModules` using the array syntax, but now it's possible to use object syntax to exclude specific node_modules in a certain target.

```json
{
  "targets": {
    "library": {
      "includeNodeModules": {
        "react": false
      }
    }
  }
}
```

#3753 proposed doing this via `peerDependencies`, but that doesn't allow specifying node modules to include/exclude per target. We may want to support it as a shortcut for `includeNodeModules` across all targets, however.

### CODE REVIEW

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>packages/benchmarks/kitchen-sink ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 7.12s | +411.00ms ⚠️ |
| Cached | 3.11s | -356.00ms 🚀 |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/parcel.ff215454.webp | 102.94kb | +0.00b | 166.00ms | -28.00ms 🚀 |
| dist/modern/parcel.76ee4591.webp | 102.94kb | +0.00b | 164.00ms | -28.00ms 🚀 |
| dist/legacy/index.js | 460.00b | +0.00b | 456.00ms | -105.00ms 🚀 |
| dist/modern/index.js | 452.00b | +0.00b | 451.00ms | -105.00ms 🚀 |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/parcel.ff215454.webp | 102.94kb | +0.00b | 17.00ms | +1.00ms ⚠️ |
| dist/modern/parcel.76ee4591.webp | 102.94kb | +0.00b | 16.00ms | +1.00ms ⚠️ |
| dist/legacy/index.js | 460.00b | +0.00b | 22.00ms | -64.00ms 🚀 |
| dist/modern/index.js | 452.00b | +0.00b | 16.00ms | -65.00ms 🚀 |
| dist/legacy/index.css | 29.00b | +0.00b | 16.00ms | +1.00ms ⚠️ |

</p></details>

<details><summary>packages/benchmarks/react-hn ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 10.11s | +191.00ms |
| Cached | 3.58s | -133.00ms |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/module/index.js | 34.33kb | +0.00b | 12.00ms | -389.00ms 🚀 |
| dist/main/index.js | 34.08kb | +0.00b | 17.00ms | -389.00ms 🚀 |

</p></details>

<details><summary>packages/benchmarks/ak-editor ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 3.22m | +1.41s |
| Cached | 5.62s | +90.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.js | 2.33mb | +4.00b ⚠️ | 1.83m | +3.21s |
| dist/pdfRenderer.85e56a51.js | 1.11mb | +0.00b | 36.50s | -28.75s 🚀 |
| dist/smartMediaEditor.678dca17.js | 602.09kb | +0.00b | 1.21m | -29.97s 🚀 |
| dist/popup.ab87d357.js | 259.28kb | +0.00b | 1.29m | +10.56s ⚠️ |
| dist/EmojiPickerComponent.6fc09ddc.js | 105.94kb | +0.00b | 44.41s | -29.38s 🚀 |
| dist/Toolbar.1699663e.js | 105.85kb | +0.00b | 1.21m | -31.08s 🚀 |
| dist/media-viewer.81fbeba4.js | 87.56kb | +0.00b | 8.49s | +2.42s ⚠️ |
| dist/card.c0473744.js | 76.88kb | +0.00b | 8.49s | +2.43s ⚠️ |
| dist/ui.c85d9c1b.js | 73.77kb | +0.00b | 58.29s | -29.07s 🚀 |
| dist/smartMediaEditor.25b0ed57.js | 67.38kb | +0.00b | 58.29s | -29.86s 🚀 |
| dist/component.10b390dc.js | 46.04kb | +0.00b | 39.74s | -30.09s 🚀 |
| dist/DatePicker.0242ec52.js | 27.54kb | +0.00b | 44.40s | -30.17s 🚀 |
| dist/EmojiPickerComponent.bcce358c.js | 24.31kb | +0.00b | 43.25s | -30.53s 🚀 |
| dist/popup.b8e50b5b.js | 22.04kb | +0.00b | 38.88s | -30.07s 🚀 |
| dist/popup.8dca552f.js | 21.51kb | +0.00b | 38.88s | -29.60s 🚀 |
| dist/popup.8d8f40ed.js | 20.52kb | +0.00b | 38.88s | -30.07s 🚀 |
| dist/js.16f29da2.js | 16.29kb | +0.00b | 1.26m | +11.57s ⚠️ |
| dist/popup.26e30eb7.js | 12.70kb | +0.00b | 38.88s | -29.60s 🚀 |
| dist/workerHasher.d7e20c98.js | 11.57kb | +0.00b | 44.99s | -30.02s 🚀 |
| dist/EmojiTypeAheadComponent.1c09c30d.js | 10.44kb | +0.00b | 44.99s | -29.74s 🚀 |
| dist/card.f99e1597.js | 5.92kb | +0.00b | 12.53s | -8.01s 🚀 |
| dist/component.a26e593f.js | 5.62kb | +0.00b | 39.95s | -29.95s 🚀 |
| dist/index.css | 3.38kb | +0.00b | 1.23m | -30.77s 🚀 |
| dist/component.8fa44754.js | 3.38kb | +0.00b | 39.95s | -29.88s 🚀 |
| dist/png-chunks-extract.3d8d8594.js | 3.33kb | +0.00b | 1.26m | +11.57s ⚠️ |
| dist/EmojiUploadComponent.0460cc59.js | 2.92kb | +0.00b | 44.99s | -29.58s 🚀 |
| dist/component.ab65829f.js | 2.30kb | +0.00b | 39.95s | -29.95s 🚀 |
| dist/ResourcedEmojiComponent.2d80adbd.js | 2.25kb | +0.00b | 8.39s | +2.38s ⚠️ |
| dist/media-picker-analytics-error-boundary.0f11d632.js | 1.85kb | +0.00b | 39.40s | -1.11m 🚀 |
| dist/card.2c902906.js | 1.73kb | +0.00b | 12.53s | -8.01s 🚀 |
| dist/16.dcacbe5c.js | 1.69kb | +0.00b | 40.32s | -29.99s 🚀 |
| dist/date.cfe6153f.js | 1.63kb | +0.00b | 40.49s | -29.96s 🚀 |
| dist/16.de3f3184.js | 1.63kb | +0.00b | 40.08s | -29.99s 🚀 |
| dist/images.c60a97a9.js | 1.57kb | +0.00b | 40.50s | -30.03s 🚀 |
| dist/feedback.01d7bcf7.js | 1.53kb | +0.00b | 43.25s | -29.23s 🚀 |
| dist/workerHasher.854262ce.js | 1.49kb | +0.00b | 44.99s | -30.02s 🚀 |
| dist/status.e3ed4764.js | 1.35kb | +0.00b | 40.72s | -30.02s 🚀 |
| dist/list-number.dbe744df.js | 1.35kb | +0.00b | 40.56s | -29.98s 🚀 |
| dist/16.f54dac28.js | 1.34kb | +0.00b | 40.19s | -30.03s 🚀 |
| dist/16.8f0e8fe1.js | 1.29kb | +0.00b | 40.08s | -29.90s 🚀 |
| dist/16.43b62c01.js | 1.29kb | +0.00b | 40.09s | -30.06s 🚀 |
| dist/code.092e0137.js | 1.28kb | +0.00b | 40.43s | -30.03s 🚀 |
| dist/16.b17a4d30.js | 1.27kb | +0.00b | 40.43s | -29.96s 🚀 |
| dist/16.51bbc68e.js | 1.24kb | +0.00b | 40.34s | -30.06s 🚀 |
| dist/component.8351f228.js | 1.23kb | +0.00b | 39.40s | -1.11m 🚀 |
| dist/link.6fa27bb2.js | 1.20kb | +0.00b | 40.56s | -29.98s 🚀 |
| dist/heading6.3996fe48.js | 1.19kb | +0.00b | 40.81s | -31.67s 🚀 |
| dist/16.385d3ff5.js | 1.19kb | +0.00b | 40.32s | -30.03s 🚀 |
| dist/heading3.9fea5413.js | 1.18kb | +0.00b | 40.81s | -30.04s 🚀 |
| dist/16.b3ce4050.js | 1.16kb | +0.00b | 40.08s | -29.99s 🚀 |
| dist/16.e37bbe6b.js | 1.15kb | +0.00b | 40.32s | -30.03s 🚀 |
| dist/16.f7fe274a.js | 1.14kb | +0.00b | 40.42s | -29.98s 🚀 |
| dist/emoji.c4bc5355.js | 1.12kb | +0.00b | 40.49s | -29.99s 🚀 |
| dist/16.ac2ff83f.js | 1.10kb | +0.00b | 40.20s | -30.11s 🚀 |
| dist/16.4c652b29.js | 1.10kb | +0.00b | 40.19s | -29.96s 🚀 |
| dist/16.24165259.js | 1.09kb | +0.00b | 40.08s | -29.99s 🚀 |
| dist/16.74510c56.js | 1.09kb | +0.00b | 40.19s | -30.03s 🚀 |
| dist/16.97c5bdf9.js | 1.09kb | +0.00b | 40.19s | -30.03s 🚀 |
| dist/16.a79db876.js | 1.09kb | +0.00b | 39.97s | -30.02s 🚀 |
| dist/heading5.2f045997.js | 1.07kb | +0.00b | 40.80s | -30.06s 🚀 |
| dist/16.6f8ac62a.js | 1.05kb | +0.00b | 39.95s | -29.95s 🚀 |
| dist/expand.13380081.js | 1.05kb | +0.00b | 43.25s | -29.23s 🚀 |
| dist/card.aae6ebb9.js | 1.04kb | +0.00b | 12.53s | -8.01s 🚀 |
| dist/16.3e36da0b.js | 1.01kb | +0.00b | 40.32s | -30.04s 🚀 |
| dist/heading2.2194210a.js | 1.00kb | +0.00b | 40.81s | -30.02s 🚀 |
| dist/mention.9fdad24e.js | 983.00b | +0.00b | 40.56s | -30.05s 🚀 |
| dist/fallback.305c8864.js | 982.00b | +0.00b | 40.72s | -30.03s 🚀 |
| dist/heading4.63d1ca06.js | 978.00b | +0.00b | 40.80s | -30.04s 🚀 |
| dist/layout.6f66c2da.js | 964.00b | +0.00b | 40.56s | -29.97s 🚀 |
| dist/divider.160f3108.js | 942.00b | +0.00b | 40.49s | -29.98s 🚀 |
| dist/quote.88bfdca4.js | 938.00b | +0.00b | 40.72s | -30.02s 🚀 |
| dist/action.146450ba.js | 921.00b | +0.00b | 40.42s | -30.01s 🚀 |
| dist/decision.06254b93.js | 900.00b | +0.00b | 40.49s | -29.98s 🚀 |
| dist/panel-warning.59c8ef3f.js | 893.00b | +0.00b | 40.62s | -30.05s 🚀 |
| dist/list.4f623de3.js | 872.00b | +0.00b | 40.56s | -30.00s 🚀 |
| dist/heading1.65fb8482.js | 866.00b | +0.00b | 40.72s | -30.11s 🚀 |
| dist/panel-error.c2479698.js | 793.00b | +0.00b | 40.62s | -29.99s 🚀 |
| dist/panel.23cd7224.js | 790.00b | +0.00b | 40.62s | -30.11s 🚀 |
| dist/table.4ace5843.js | 782.00b | +0.00b | 40.72s | -30.02s 🚀 |
| dist/media-viewer-analytics-error-boundary.dd752a9e.js | 779.00b | +0.00b | 12.53s | -8.01s 🚀 |
| dist/panel-success.6a7b97d7.js | 730.00b | +0.00b | 40.62s | -30.01s 🚀 |
| dist/panel-note.5ff85bdc.js | 729.00b | +0.00b | 40.62s | -30.01s 🚀 |
| dist/simpleHasher.884d4eb6.js | 450.00b | +0.00b | 44.99s | -42.36s 🚀 |
| dist/esm.976debcc.js | 180.00b | +0.00b | 8.32s | +2.34s ⚠️ |
| dist/dropzone.976debcc.js | 179.00b | +1.00b ⚠️ | 1.26m | -30.67s 🚀 |
| dist/clipboard.976debcc.js | 179.00b | +1.00b ⚠️ | 39.40s | -1.11m 🚀 |
| dist/browser.976debcc.js | 179.00b | +1.00b ⚠️ | 59.32s | -9.63s 🚀 |
| dist/editorView.976debcc.js | 179.00b | -1.00b 🚀 | 38.88s | -49.28s 🚀 |
| dist/media-card-analytics-error-boundary.976debcc.js | 178.00b | -5.00b 🚀 | 40.42s | -23.59s 🚀 |
| dist/16.976debcc.js | 176.00b | -5.00b 🚀 | 39.40s | -31.01s 🚀 |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.js | 2.34mb | +4.00b ⚠️ | 263.00ms | -2.00ms |
| dist/Toolbar.1699663e.js | 105.85kb | +0.00b | 106.00ms | -6.00ms 🚀 |
| dist/smartMediaEditor.25b0ed57.js | 67.38kb | +0.00b | 107.00ms | -6.00ms 🚀 |
| dist/DatePicker.0242ec52.js | 27.54kb | +0.00b | 108.00ms | -6.00ms 🚀 |
| dist/EmojiPickerComponent.bcce358c.js | 24.31kb | +0.00b | 108.00ms | -6.00ms 🚀 |
| dist/workerHasher.d7e20c98.js | 11.57kb | +0.00b | 106.00ms | -6.00ms 🚀 |
| dist/EmojiTypeAheadComponent.1c09c30d.js | 10.44kb | +0.00b | 107.00ms | -6.00ms 🚀 |
| dist/component.a26e593f.js | 5.62kb | +0.00b | 136.00ms | -7.00ms 🚀 |
| dist/component.8fa44754.js | 3.38kb | +0.00b | 137.00ms | -7.00ms 🚀 |
| dist/component.ab65829f.js | 2.30kb | +0.00b | 137.00ms | -7.00ms 🚀 |
| dist/16.dcacbe5c.js | 1.69kb | +0.00b | 130.00ms | -8.00ms 🚀 |
| dist/16.de3f3184.js | 1.63kb | +0.00b | 135.00ms | -7.00ms 🚀 |
| dist/16.f54dac28.js | 1.34kb | +0.00b | 132.00ms | -8.00ms 🚀 |
| dist/16.8f0e8fe1.js | 1.29kb | +0.00b | 135.00ms | -7.00ms 🚀 |
| dist/16.43b62c01.js | 1.29kb | +0.00b | 133.00ms | -8.00ms 🚀 |
| dist/component.8351f228.js | 1.23kb | +0.00b | 138.00ms | -7.00ms 🚀 |
| dist/16.b3ce4050.js | 1.16kb | +0.00b | 134.00ms | -8.00ms 🚀 |
| dist/16.ac2ff83f.js | 1.10kb | +0.00b | 132.00ms | -7.00ms 🚀 |
| dist/16.4c652b29.js | 1.10kb | +0.00b | 133.00ms | -8.00ms 🚀 |
| dist/16.24165259.js | 1.09kb | +0.00b | 134.00ms | -7.00ms 🚀 |
| dist/16.74510c56.js | 1.09kb | +0.00b | 133.00ms | -7.00ms 🚀 |
| dist/16.97c5bdf9.js | 1.09kb | +0.00b | 132.00ms | -8.00ms 🚀 |
| dist/16.a79db876.js | 1.09kb | +0.00b | 136.00ms | -7.00ms 🚀 |
| dist/16.6f8ac62a.js | 1.05kb | +0.00b | 136.00ms | -7.00ms 🚀 |
| dist/expand.13380081.js | 1.05kb | +0.00b | 109.00ms | -6.00ms 🚀 |
| dist/simpleHasher.884d4eb6.js | 450.00b | +0.00b | 106.00ms | -6.00ms 🚀 |
| dist/esm.976debcc.js | 178.00b | +2.00b ⚠️ | 146.00ms | -5.00ms |
| dist/media-card-analytics-error-boundary.976debcc.js | 178.00b | +2.00b ⚠️ | 142.00ms | -6.00ms |
| dist/dropzone.976debcc.js | 178.00b | +2.00b ⚠️ | 140.00ms | -5.00ms |
| dist/clipboard.976debcc.js | 178.00b | +2.00b ⚠️ | 139.00ms | -5.00ms |
| dist/browser.976debcc.js | 178.00b | +2.00b ⚠️ | 139.00ms | -6.00ms |
| dist/16.976debcc.js | 178.00b | +2.00b ⚠️ | 127.00ms | -4.00ms |
| dist/editorView.976debcc.js | 178.00b | +2.00b ⚠️ | 105.00ms | -5.00ms |

</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/256304031590253066)**

**Comment by DeMoorJasper** [comment]
I do think we should have a general exclude as well, with either a custom or peerDependency field.

**Comment by maximal** [comment]
How is this supposed to work for browser builds?

I’m using:
```json
{
	"browser": "web/dist/app.js",
	"source": "frontend/js/app.js",
	"targets": {
		"browser": {
			"includeNodeModules": {
				"jquery": false
			}
		}
	}
}
```
It builds with `require()`s.

But if I do (see #3963):
```json
{
	"default": "web/dist/app.js",
	"source": "frontend/js/app.js",
	"targets": {
		"default": {}
	},
}
```
Then it builds without `require()`s but fully ioncludes jQuery library.

How can I setup Parcel 2 to build for browser (without `require()`s) and without bundling external libraries simultaneously?

 * * *

Combination of:
```json
{
	"default": "web/dist/app.js",
	"source": "frontend/js/app.js",
	"targets": {
		"default": {
			"includeNodeModules": {
				"jquery": false
			}
		}
	}
}
```
yields:
```
yarn run v1.22.4
$ yarn run parcel build frontend/js/app.js
$ /home/maximal/project/project-name/node_modules/.bin/parcel build frontend/js/app.js
🚨 Build failed.
@parcel/packager-js: External modules are not supported when building for browser
/home/maximal/project/project-name/frontend/js/common.jquery.js:10:1
  9  | 
> 10 | import $ from 'jquery';
>    | ^^^^^^^^^^^^^^^^^^^^^^^
  11 | 
  12 | export function jQueryRun(document, window) {
⠸ Optimizing app.css...
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by mischnic** [comment]
@maximal

> How can I setup Parcel 2 to build for browser (without require()s) and without bundling external libraries simultaneously?

How else? How do you access the libraries then?

Do you want "globals"? https://github.com/parcel-bundler/parcel/issues/3305

**Comment by maximal** [comment]
@mischnic

I wish to use it like with an old v1 Parcel and its `parcel-plugin-externals`:

```json
{
```json
	"dependencies": {
		"bootstrap": "^4.4.1",
		"jquery": "^3.3.1",
		"popper.js": "^1.15.0"
	},
	"devDependencies": {
		"less": "^3.11.1",
		"parcel-bundler": "^1.12.4",
		"parcel-plugin-externals": "^0.2.0"
	},
	"browserslist": [
		"> 1%",
		"not dead"
	],
	"main": "web/dist/app.js",
	"source": "frontend/js/app.js",
	"externals": {
		"jquery": "jQuery",
		"bootstrap": true,
		"popper.js": true
	}
}
```

In my code I use `import $ from 'jquery'`, but it is not bundled when I build.

It works in v1, so I’m just wondering if this is possible in Parcel v2.

**Pull request merged**
