### PR TITLE
added version option to command description

### PR DESCRIPTION
**Pull request by philipodev**
Hi, awesome project you got there.

Noticed, when looking for it, there's no description in `--help` how to output the current version so i added it.

### CODE REVIEW

**Comment by philipodev** [comment]
@yeskunall hmm, you're right. no point in having the description in anything other than --help. i have commited changes for this. thanks

**Comment by devongovett** [comment]
`parcel --version` already works.

**Comment by philipodev** [comment]
@devongovett yes it does, but this PR simply adds it to the --help. I was personally looking for it when -v (lowercase) didn't work.

**Comment by yeskunall** [comment]
@philipodev with your current changes, won't this only work for the `serve` command? I'm just curious 😅

**Comment by philipodev** [comment]
@yeskunall yes, but parcel is using that command as `--help`. But if you type `parcel watch --help` you get the help for watch command and then I don't think printing the version option is relevant. :)

**Pull request merged**
