### PR TITLE
Persist and restore sourcemaps in Asset

### PR DESCRIPTION
**Pull request by wbinnssmith**
This fixes an issue where source maps were not properly persisted nor restored during the commit phase and constructor in Asset.

Test Plan: 
* yarn test for sourcemap integration tests
* run the kitchen sink example before, verify empty sourcemaps. Run it after, and verify source maps have content.

### CODE REVIEW

**Comment by mischnic** [comment]
Maybe add a test caser?

**Comment by wbinnssmith** [comment]
The sourcemaps tests should have caught this. @DeMoorJasper and I will look into this.

**Comment by DeMoorJasper** [comment]
Strangely enough the maps it produces actually look alright. Not entirely sure why the tests would fail. [test map](http://sokra.github.io/source-map-visualization/#base64,Ly8gbW9kdWxlcyBhcmUgZGVmaW5lZCBhcyBhbiBhcnJheQovLyBbIG1vZHVsZSBmdW5jdGlvbiwgbWFwIG9mIHJlcXVpcmVzIF0KLy8KLy8gbWFwIG9mIHJlcXVpcmVzIGlzIHNob3J0IHJlcXVpcmUgbmFtZSAtPiBudW1lcmljIHJlcXVpcmUKLy8KLy8gYW55dGhpbmcgZGVmaW5lZCBpbiBhIHByZXZpb3VzIGJ1bmRsZSBpcyBhY2Nlc3NlZCB2aWEgdGhlCi8vIG9yaWcgbWV0aG9kIHdoaWNoIGlzIHRoZSByZXF1aXJlIGZvciBwcmV2aW91cyBidW5kbGVzCgovLyBlc2xpbnQtZGlzYWJsZS1uZXh0LWxpbmUgbm8tZ2xvYmFsLWFzc2lnbgpwYXJjZWxSZXF1aXJlID0gZnVuY3Rpb24obW9kdWxlcywgY2FjaGUsIGVudHJ5LCBnbG9iYWxOYW1lKSB7CiAgLy8gU2F2ZSB0aGUgcmVxdWlyZSBmcm9tIHByZXZpb3VzIGJ1bmRsZSB0byB0aGlzIGNsb3N1cmUgaWYgYW55CiAgdmFyIHByZXZpb3VzUmVxdWlyZSA9IHR5cGVvZiBwYXJjZWxSZXF1aXJlID09PSAnZnVuY3Rpb24nICYmIHBhcmNlbFJlcXVpcmU7CiAgdmFyIG5vZGVSZXF1aXJlID0gdHlwZW9mIHJlcXVpcmUgPT09ICdmdW5jdGlvbicgJiYgcmVxdWlyZTsKCiAgZnVuY3Rpb24gbmV3UmVxdWlyZShuYW1lLCBqdW1wZWQpIHsKICAgIGlmICghY2FjaGVbbmFtZV0pIHsKICAgICAgaWYgKCFtb2R1bGVzW25hbWVdKSB7CiAgICAgICAgLy8gaWYgd2UgY2Fubm90IGZpbmQgdGhlIG1vZHVsZSB3aXRoaW4gb3VyIGludGVybmFsIG1hcCBvcgogICAgICAgIC8vIGNhY2hlIGp1bXAgdG8gdGhlIGN1cnJlbnQgZ2xvYmFsIHJlcXVpcmUgaWUuIHRoZSBsYXN0IGJ1bmRsZQogICAgICAgIC8vIHRoYXQgd2FzIGFkZGVkIHRvIHRoZSBwYWdlLgogICAgICAgIHZhciBjdXJyZW50UmVxdWlyZSA9CiAgICAgICAgICB0eXBlb2YgcGFyY2VsUmVxdWlyZSA9PT0gJ2Z1bmN0aW9uJyAmJiBwYXJjZWxSZXF1aXJlOwogICAgICAgIGlmICghanVtcGVkICYmIGN1cnJlbnRSZXF1aXJlKSB7CiAgICAgICAgICByZXR1cm4gY3VycmVudFJlcXVpcmUobmFtZSwgdHJ1ZSk7CiAgICAgICAgfQoKICAgICAgICAvLyBJZiB0aGVyZSBhcmUgb3RoZXIgYnVuZGxlcyBvbiB0aGlzIHBhZ2UgdGhlIHJlcXVpcmUgZnJvbSB0aGUKICAgICAgICAvLyBwcmV2aW91cyBvbmUgaXMgc2F2ZWQgdG8gJ3ByZXZpb3VzUmVxdWlyZScuIFJlcGVhdCB0aGlzIGFzCiAgICAgICAgLy8gbWFueSB0aW1lcyBhcyB0aGVyZSBhcmUgYnVuZGxlcyB1bnRpbCB0aGUgbW9kdWxlIGlzIGZvdW5kIG9yCiAgICAgICAgLy8gd2UgZXhoYXVzdCB0aGUgcmVxdWlyZSBjaGFpbi4KICAgICAgICBpZiAocHJldmlvdXNSZXF1aXJlKSB7CiAgICAgICAgICByZXR1cm4gcHJldmlvdXNSZXF1aXJlKG5hbWUsIHRydWUpOwogICAgICAgIH0KCiAgICAgICAgLy8gVHJ5IHRoZSBub2RlIHJlcXVpcmUgZnVuY3Rpb24gaWYgaXQgZXhpc3RzLgogICAgICAgIGlmIChub2RlUmVxdWlyZSAmJiB0eXBlb2YgbmFtZSA9PT0gJ3N0cmluZycpIHsKICAgICAgICAgIHJldHVybiBub2RlUmVxdWlyZShuYW1lKTsKICAgICAgICB9CgogICAgICAgIHZhciBlcnIgPSBuZXcgRXJyb3IoIkNhbm5vdCBmaW5kIG1vZHVsZSAnIiArIG5hbWUgKyAiJyIpOwogICAgICAgIGVyci5jb2RlID0gJ01PRFVMRV9OT1RfRk9VTkQnOwogICAgICAgIHRocm93IGVycjsKICAgICAgfQoKICAgICAgbG9jYWxSZXF1aXJlLnJlc29sdmUgPSByZXNvbHZlOwogICAgICBsb2NhbFJlcXVpcmUuY2FjaGUgPSB7fTsKCiAgICAgIHZhciBtb2R1bGUgPSAoY2FjaGVbbmFtZV0gPSBuZXcgbmV3UmVxdWlyZS5Nb2R1bGUobmFtZSkpOwoKICAgICAgbW9kdWxlc1tuYW1lXVswXS5jYWxsKAogICAgICAgIG1vZHVsZS5leHBvcnRzLAogICAgICAgIGxvY2FsUmVxdWlyZSwKICAgICAgICBtb2R1bGUsCiAgICAgICAgbW9kdWxlLmV4cG9ydHMsCiAgICAgICAgdGhpcwogICAgICApOwogICAgfQoKICAgIHJldHVybiBjYWNoZVtuYW1lXS5leHBvcnRzOwoKICAgIGZ1bmN0aW9uIGxvY2FsUmVxdWlyZSh4KSB7CiAgICAgIHJldHVybiBuZXdSZXF1aXJlKGxvY2FsUmVxdWlyZS5yZXNvbHZlKHgpKTsKICAgIH0KCiAgICBmdW5jdGlvbiByZXNvbHZlKHgpIHsKICAgICAgcmV0dXJuIG1vZHVsZXNbbmFtZV1bMV1beF0gfHwgeDsKICAgIH0KICB9CgogIGZ1bmN0aW9uIE1vZHVsZShtb2R1bGVOYW1lKSB7CiAgICB0aGlzLmlkID0gbW9kdWxlTmFtZTsKICAgIHRoaXMuYnVuZGxlID0gbmV3UmVxdWlyZTsKICAgIHRoaXMuZXhwb3J0cyA9IHt9OwogIH0KCiAgbmV3UmVxdWlyZS5pc1BhcmNlbFJlcXVpcmUgPSB0cnVlOwogIG5ld1JlcXVpcmUuTW9kdWxlID0gTW9kdWxlOwogIG5ld1JlcXVpcmUubW9kdWxlcyA9IG1vZHVsZXM7CiAgbmV3UmVxdWlyZS5jYWNoZSA9IGNhY2hlOwogIG5ld1JlcXVpcmUucGFyZW50ID0gcHJldmlvdXNSZXF1aXJlOwogIG5ld1JlcXVpcmUucmVnaXN0ZXIgPSBmdW5jdGlvbihpZCwgZXhwb3J0cykgewogICAgbW9kdWxlc1tpZF0gPSBbCiAgICAgIGZ1bmN0aW9uKHJlcXVpcmUsIG1vZHVsZSkgewogICAgICAgIG1vZHVsZS5leHBvcnRzID0gZXhwb3J0czsKICAgICAgfSwKICAgICAge30KICAgIF07CiAgfTsKCiAgZm9yICh2YXIgaSA9IDA7IGkgPCBlbnRyeS5sZW5ndGg7IGkrKykgewogICAgbmV3UmVxdWlyZShlbnRyeVtpXSk7CiAgfQoKICBpZiAoZW50cnkubGVuZ3RoKSB7CiAgICAvLyBFeHBvc2UgZW50cnkgcG9pbnQgdG8gTm9kZSwgQU1EIG9yIGJyb3dzZXIgZ2xvYmFscwogICAgLy8gQmFzZWQgb24gaHR0cHM6Ly9naXRodWIuY29tL0ZvcmJlc0xpbmRlc2F5L3VtZC9ibG9iL21hc3Rlci90ZW1wbGF0ZS5qcwogICAgdmFyIG1haW5FeHBvcnRzID0gbmV3UmVxdWlyZShlbnRyeVtlbnRyeS5sZW5ndGggLSAxXSk7CgogICAgLy8gQ29tbW9uSlMKICAgIGlmICh0eXBlb2YgZXhwb3J0cyA9PT0gJ29iamVjdCcgJiYgdHlwZW9mIG1vZHVsZSAhPT0gJ3VuZGVmaW5lZCcpIHsKICAgICAgbW9kdWxlLmV4cG9ydHMgPSBtYWluRXhwb3J0czsKCiAgICAgIC8vIFJlcXVpcmVKUwogICAgfSBlbHNlIGlmICh0eXBlb2YgZGVmaW5lID09PSAnZnVuY3Rpb24nICYmIGRlZmluZS5hbWQpIHsKICAgICAgZGVmaW5lKGZ1bmN0aW9uKCkgewogICAgICAgIHJldHVybiBtYWluRXhwb3J0czsKICAgICAgfSk7CgogICAgICAvLyA8c2NyaXB0PgogICAgfSBlbHNlIGlmIChnbG9iYWxOYW1lKSB7CiAgICAgIHRoaXNbZ2xvYmFsTmFtZV0gPSBtYWluRXhwb3J0czsKICAgIH0KICB9CgogIC8vIE92ZXJyaWRlIHRoZSBjdXJyZW50IHJlcXVpcmUgd2l0aCB0aGlzIG5ldyBvbmUKICByZXR1cm4gbmV3UmVxdWlyZTsKfSh7IjRkNGVmMzA4MTYzNTlmZTYwZjIzMjgwNDU5NzQ1YWVmIjpbZnVuY3Rpb24ocmVxdWlyZSxtb2R1bGUsZXhwb3J0cykgewpmdW5jdGlvbiBoZWxsb1dvcmxkKCkgewogIHJldHVybiAiaGVsbG8gd29ybGQiOwp9Cgptb2R1bGUuZXhwb3J0cyA9IGhlbGxvV29ybGQ7Cn0se31dfSx7fSxbIjRkNGVmMzA4MTYzNTlmZTYwZjIzMjgwNDU5NzQ1YWVmIl0sIG51bGwpCgovLyMgc291cmNlTWFwcGluZ1VSTD1pbmRleC5qcy5tYXAK,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInBhY2thZ2VzL2NvcmUvaW50ZWdyYXRpb24tdGVzdHMvdGVzdC9pbnRlZ3JhdGlvbi9zb3VyY2VtYXAvaW5kZXguanMiXSwibmFtZXMiOlsiaGVsbG9Xb3JsZCIsIm1vZHVsZSIsImV4cG9ydHMiXSwibWFwcGluZ3MiOiI7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztBQUFBLFNBQVNBLFVBQVQsR0FBc0I7QUFDcEIsU0FBTyxhQUFQO0FBQ0Q7O0FBRURDLE1BQU0sQ0FBQ0MsT0FBUCxHQUFpQkYsVUFBakIiLCJmaWxlIjoiaW5kZXguanMubWFwIiwic291cmNlUm9vdCI6Ii9fX3BhcmNlbF9zb3VyY2Vfcm9vdC8ifQ==,ZnVuY3Rpb24gaGVsbG9Xb3JsZCgpIHsKICByZXR1cm4gImhlbGxvIHdvcmxkIjsKfQoKbW9kdWxlLmV4cG9ydHMgPSBoZWxsb1dvcmxkOw==)

**Comment by mischnic** [comment]
A negative column position does seem suspicious
```
      AssertionError [ERR_ASSERTION]: mapping 'hello world' appears incorrect:
      + expected - actual

       {
      -  "column": -10
      +  "column": 10
         "line": 2
         "source": "packages/core/integration-tests/test/integration/sourcemap/index.js"
       }
```

**Comment by DeMoorJasper** [comment]
@mischnic yeah... just not sure where it’s coming from as the thing I linked doesn’t contain any negative columns. I’ll look into it a lil further though

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mischnic** [comment]
It's from the `checkSourceMapping` where the offset is calcuated

**Comment by DeMoorJasper** [comment]
@mischnic figured as much, it's a lot more sensitive than I thought. Needed to add quotes to `hello world` string to ensure it's an exact match with the mapping by Babel

**Pull request merged**
