### PR TITLE
fix: when the publicUrl is url not a path of os

### PR DESCRIPTION
**Pull request by fansenze**
#409  
#405 

if we do, i can make a pr next

### CODE REVIEW

**Comment by DeMoorJasper** [comment]
@fansenze some tests are failing, could you fix it so they pass?

**Comment by devongovett** [comment]
This breaks when the url has a path in it:

```javascript
> require('url').resolve('http://test.com/foo', 'bar')
'http://test.com/bar'
```

I'd expect `http://test.com/foo/bar`.

**Comment by fansenze** [comment]
@devongovett  
i fix and i write test

**Comment by devongovett** [comment]
Simplified slightly to just always use URL.parse and URL.format, and use posix path joining for the paths.

**Pull request merged**
