### PR TITLE
Fix optional chaining in astring conversion

### LINKED ISSUE #5627: [regression in parcel2] optional chaining is still used in the transpiled code of optional chaining
# 🐛 bug report

[optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) is broken and [it is not a babel bug](https://babel.dev/repl#?browsers=chrome%2032&build=&builtIns=false&spec=false&loose=false&code_lz=JYMwFAJg9gxgrgWwKYDsAuB-AdAIyhAT2wEc4kAnAgZSQBskY0pywAiLNJAZzVYEpswFCgoAVJAA80AAgC886awAWwfgG8AUNOkBDeuTRsA6kp1oA5F2lwADhn4BuDQF8NQA&debug=false&forceAllTransforms=false&shippedProposals=true&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Ctypescript&prettier=false&targets=&version=7.12.9&externalPlugins=)

## 🎛 Configuration (.babelrc, package.json, cli command)

Similar to #5555 except I tried to add `"@babel/plugin-proposal-optional-chaining"` to .babelrc in an attempt to fix it, **please just check the reproduction repo**

## 🤔 Expected Behavior

transpiled code is supposed to _not include `?.`_ when building for IE11, but it does.

**This is built with parcel `2.0.0-nightly.520+71264fe1` where it still works, notice it doesn't contain any ?.**

```
(function () {
  // ASSET: src/main.ts
  var $c897f61df880517db71e186672d4df37$var$_document, $c897f61df880517db71e186672d4df37$var$_document$body, $c897f61df880517db71e186672d4df37$var$_document$body$queryS;

  if ((($c897f61df880517db71e186672d4df37$var$_document = document) === null || $c897f61df880517db71e186672d4df37$var$_document === void 0 ? void 0 : ($c897f61df880517db71e186672d4df37$var$_document$body = $c897f61df880517db71e186672d4df37$var$_document.body) === null || $c897f61df880517db71e186672d4df37$var$_document$body === void 0 ? void 0 : ($c897f61df880517db71e186672d4df37$var$_document$body$queryS = $c897f61df880517db71e186672d4df37$var$_document$body.querySelector(".test")) === null || $c897f61df880517db71e186672d4df37$var$_document$body$queryS === void 0 ? void 0 : $c897f61df880517db71e186672d4df37$var$_document$body$queryS.innerText) === "hi") {
    alert("What's up??");
  }
})();
//# sourceMappingURL=ie11.js.map
```

## 😯 Current Behavior

```
(function () {
  // ASSET: src/main.ts
  var $c897f61df880517db71e186672d4df37$var$_document, $c897f61df880517db71e186672d4df37$var$_document$body, $c897f61df880517db71e186672d4df37$var$_document$body$queryS;
  if ((($c897f61df880517db71e186672d4df37$var$_document = document) === null || $c897f61df880517db71e186672d4df37$var$_document === void 0 ? void 0 : ($c897f61df880517db71e186672d4df37$var$_document$body = $c897f61df880517db71e186672d4df37$var$_document?.body) === null || $c897f61df880517db71e186672d4df37$var$_document$body === void 0 ? void 0 : ($c897f61df880517db71e186672d4df37$var$_document$body$queryS = $c897f61df880517db71e186672d4df37$var$_document$body?.querySelector(".test")) === null || $c897f61df880517db71e186672d4df37$var$_document$body$queryS === void 0 ? void 0 : $c897f61df880517db71e186672d4df37$var$_document$body$queryS?.innerText) === "hi") {
    alert("What's up?");
  }
})();

//# sourceMappingURL=ie11.js.map
```

I quote: `ent$body$queryS?.innerText) === "`
The `?.` throws a syntax error in IE11

## 💁 Possible Solution

Revert what made the issue appear

## 🔦 Context

I updated parcel to test if the MR mentioned in #5557 had fixed #5557 and was greeted with all my code stopping to work in IE11.

It is broken in this version: `2.0.0-nightly.524+97a7bfee` but it still works in `2.0.0-nightly.520+71264fe1`

## 💻 Code Sample

Reproduction "repo": [optional-chaining.zip](https://github.com/parcel-bundler/parcel/files/5802983/optional-chaining.zip)

```
if(document?.body?.querySelector(".test")?.innerText === "hi"){
  alert("What's up?");
}

```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Parcel           | 2.0.0-nightly.524+97a7bfee |
| Node             | v15.5.1 |
| npm/Yarn         | npm v7.3.0
| Operating System | macOS 10.13.6

### PR DESCRIPTION
**Pull request by mischnic**
# ↪️ Pull Request

Fixes #5627.
Example: `console.log(a?.b);`

After running `@babel/plugin-proposal-optional-chaining`, the `OptionalMemberExpression` is turned into a MemberExpression, but `optional` isn't removed. According to the [spec](https://github.com/babel/babel/blob/main/packages/babel-parser/ast/spec.md#memberexpression), this is fine because `MemberExpression` doesn't have an `optional` property. So we need to unset `optional` for `MemberExpression` node.

### CODE REVIEW

**Comment by parcel-benchmark** [comment]
## Benchmark Results
<details><summary>Kitchen Sink ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 2.33s | -132.00ms 🚀 |
| Cached | 440.00ms | -16.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/parcel.d5807e82.webp | 102.94kb | +0.00b | 484.00ms | +53.00ms ⚠️ |
| dist/modern/parcel.d5807e82.webp | 102.94kb | +0.00b | 463.00ms | -100.00ms 🚀 |
| dist/legacy/index.9ff7c523.js | 1.11kb | +0.00b | 485.00ms | +32.00ms ⚠️ |
| dist/modern/index.f81b5b4b.js | 1.11kb | +0.00b | 485.00ms | -86.00ms 🚀 |
| dist/legacy/index.html | 701.00b | +0.00b | 485.00ms | +29.00ms ⚠️ |
| dist/modern/index.html | 701.00b | +0.00b | 485.00ms | -82.00ms 🚀 |
| dist/modern/index.77ce15d4.css | 77.00b | +0.00b | 805.00ms | -42.00ms 🚀 |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/legacy/parcel.d5807e82.webp | 102.94kb | +0.00b | 63.00ms | +12.00ms ⚠️ |
| dist/modern/parcel.d5807e82.webp | 102.94kb | +0.00b | 42.00ms | -9.00ms 🚀 |
| dist/legacy/index.9ff7c523.js | 1.11kb | +0.00b | 63.00ms | -11.00ms 🚀 |
| dist/modern/index.f81b5b4b.js | 1.11kb | +0.00b | 63.00ms | -11.00ms 🚀 |
| dist/legacy/index.html | 701.00b | +0.00b | 66.00ms | +12.00ms ⚠️ |
| dist/modern/index.html | 701.00b | +0.00b | 42.00ms | -32.00ms 🚀 |
| dist/legacy/index.5859ab37.css | 77.00b | +0.00b | 63.00ms | +12.00ms ⚠️ |
| dist/modern/index.77ce15d4.css | 77.00b | +0.00b | 42.00ms | -32.00ms 🚀 |

</p></details>

<details><summary>React HackerNews ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 17.35s | +331.00ms |
| Cached | 7.14s | -323.00ms |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/PermalinkedComment.d85c0b32.js | 4.20kb | +0.00b | 813.00ms | +173.00ms ⚠️ |
| dist/UserProfile.854f4adc.js | 1.76kb | +0.00b | 813.00ms | +173.00ms ⚠️ |
| dist/NotFound.9195d8a0.js | 530.00b | +0.00b | 231.00ms | +68.00ms ⚠️ |
| dist/logo.24c8bf9e.png | 274.00b | +0.00b | 494.00ms | +48.00ms ⚠️ |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.js | 485.61kb | +0.00b | 82.00ms | +20.00ms ⚠️ |
| dist/PermalinkedComment.d85c0b32.js | 4.20kb | +0.00b | 81.00ms | +19.00ms ⚠️ |
| dist/UserProfile.854f4adc.js | 1.76kb | +0.00b | 81.00ms | +19.00ms ⚠️ |
| dist/NotFound.9195d8a0.js | 530.00b | +0.00b | 81.00ms | +42.00ms ⚠️ |
| dist/logo.24c8bf9e.png | 274.00b | +0.00b | 68.00ms | +17.00ms ⚠️ |

</p></details>

<details><summary>AtlasKit Editor ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 1.68m | -1.24s |
| Cached | 2.47s | -126.00ms 🚀 |

#### Cold Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/pdfRenderer.6d316c6f.js | 1.11mb | +0.00b | 33.68s | -2.61s 🚀 |
| dist/popup.4ddc9247.js | 169.25kb | +0.00b | 14.90s | +1.98s ⚠️ |
| dist/EmojiPickerComponent.00dbc417.js | 139.01kb | +0.00b | 8.49s | -1.04s 🚀 |
| dist/Toolbar.c45ebe5b.js | 99.35kb | +0.00b | 12.47s | -1.71s 🚀 |
| dist/card.63e17a92.js | 54.02kb | +0.00b | 7.78s | -427.00ms 🚀 |
| dist/card.72b48e9e.js | 51.77kb | +0.00b | 15.01s | +3.88s ⚠️ |
| dist/Modal.00b0c761.js | 39.18kb | +0.00b | 3.40s | -319.00ms 🚀 |
| dist/component.86f6e486.js | 30.82kb | +0.00b | 3.12s | +1.28s ⚠️ |
| dist/smartMediaEditor.20d1e78e.js | 16.85kb | +0.00b | 10.75s | -3.41s 🚀 |
| dist/dropzone.13367dd4.js | 16.06kb | +0.00b | 10.03s | -2.70s 🚀 |
| dist/ui.617a16c0.js | 14.21kb | +0.00b | 7.50s | -639.00ms 🚀 |
| dist/card.241fc843.js | 5.71kb | +0.00b | 8.37s | -1.37s 🚀 |
| dist/EmojiPickerComponent.d40ea3e1.js | 3.62kb | +0.00b | 7.25s | +1.83s ⚠️ |
| dist/index.10f02a5e.css | 3.46kb | +0.00b | 33.68s | -2.61s 🚀 |
| dist/Modal.29e822bf.js | 3.14kb | +0.00b | 933.00ms | -2.55s 🚀 |
| dist/16.41f46c2f.js | 2.49kb | +0.00b | 933.00ms | -883.00ms 🚀 |
| dist/ResourcedEmojiComponent.9812a721.js | 2.15kb | +0.00b | 7.40s | -640.00ms 🚀 |
| dist/card.a2f58842.js | 2.15kb | +0.00b | 9.96s | +1.27s ⚠️ |
| dist/16.8ab9c9cf.js | 1.86kb | +0.00b | 3.89s | +315.00ms ⚠️ |
| dist/browser.8d5afc2b.js | 1.82kb | +0.00b | 14.90s | +4.37s ⚠️ |
| dist/code.be6c45b5.js | 1.61kb | +0.00b | 4.11s | +416.00ms ⚠️ |
| dist/heading6.a29cffb2.js | 1.53kb | +0.00b | 5.26s | +1.15s ⚠️ |
| dist/16.fe7e09db.js | 1.46kb | +0.00b | 3.59s | +188.00ms ⚠️ |
| dist/16.7fc8af6d.js | 1.45kb | +0.00b | 933.00ms | -883.00ms 🚀 |
| dist/16.a4fa1a69.js | 1.34kb | +0.00b | 933.00ms | -883.00ms 🚀 |
| dist/16.55b14beb.js | 1.27kb | +0.00b | 933.00ms | -883.00ms 🚀 |
| dist/layout.61e66223.js | 1.27kb | +0.00b | 3.91s | -287.00ms 🚀 |
| dist/16.e83a0923.js | 1.26kb | +0.00b | 3.73s | +332.00ms ⚠️ |
| dist/component.5df34eb8.js | 1.23kb | +0.00b | 3.04s | -436.00ms 🚀 |
| dist/16.f1c68cda.js | 1.23kb | +0.00b | 3.04s | -437.00ms 🚀 |
| dist/panel-warning.96ab13ca.js | 1.21kb | +0.00b | 4.03s | -292.00ms 🚀 |
| dist/panel-error.aa8fc53d.js | 1.11kb | +0.00b | 4.33s | +429.00ms ⚠️ |
| dist/table.d445bf7f.js | 1.09kb | +0.00b | 4.44s | +449.00ms ⚠️ |
| dist/panel-success.26c394f0.js | 1.05kb | +0.00b | 4.03s | -292.00ms 🚀 |
| dist/media-picker-analytics-error-boundary.3e4d365d.js | 1003.00b | +0.00b | 9.28s | -3.45s 🚀 |
| dist/simpleHasher.042b95c1.js | 755.00b | +0.00b | 10.64s | -1.59s 🚀 |
| dist/index.html | 119.00b | +0.00b | 2.48s | +1.02s ⚠️ |

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/index.719b2cbc.js | 2.43mb | +0.00b | 461.00ms | -38.00ms 🚀 |
| dist/pdfRenderer.6d316c6f.js | 1.11mb | +0.00b | 506.00ms | -43.00ms 🚀 |
| dist/editorView.51048e78.js | 587.53kb | +0.00b | 528.00ms | -39.00ms 🚀 |
| dist/popup.ea7c08ef.js | 169.17kb | +0.00b | 517.00ms | -43.00ms 🚀 |
| dist/Toolbar.95f755eb.js | 99.27kb | +0.00b | 528.00ms | -39.00ms 🚀 |
| dist/media-viewer.f5985104.js | 72.78kb | +0.00b | 506.00ms | -43.00ms 🚀 |
| dist/card.ee3301bd.js | 53.93kb | +0.00b | 492.00ms | -63.00ms 🚀 |
| dist/card.b7089528.js | 51.68kb | +0.00b | 528.00ms | -32.00ms 🚀 |
| dist/component.86f6e486.js | 30.82kb | +0.00b | 462.00ms | +32.00ms ⚠️ |
| dist/component.7d43a56a.js | 22.54kb | +0.00b | 413.00ms | -29.00ms 🚀 |
| dist/DatePicker.28d662bb.js | 21.12kb | +0.00b | 484.00ms | -51.00ms 🚀 |
| dist/smartMediaEditor.2987dd07.js | 16.76kb | +0.00b | 528.00ms | -39.00ms 🚀 |
| dist/js.0a808d22.js | 16.55kb | +0.00b | 413.00ms | -28.00ms 🚀 |
| dist/dropzone.7a62a82e.js | 16.00kb | +0.00b | 528.00ms | -37.00ms 🚀 |
| dist/ui.617a16c0.js | 14.21kb | +0.00b | 492.00ms | -63.00ms 🚀 |
| dist/component.053770c1.js | 6.20kb | +0.00b | 413.00ms | -35.00ms 🚀 |
| dist/card.241fc843.js | 5.71kb | +0.00b | 506.00ms | -43.00ms 🚀 |
| dist/media-viewer.ebf61ecb.js | 4.01kb | +0.00b | 506.00ms | -49.00ms 🚀 |
| dist/png-chunks-extract.692b85d1.js | 3.55kb | +0.00b | 413.00ms | -29.00ms 🚀 |
| dist/EmojiPickerComponent.39b93682.js | 3.53kb | +0.00b | 492.00ms | -43.00ms 🚀 |
| dist/index.10f02a5e.css | 3.46kb | +0.00b | 530.00ms | -37.00ms 🚀 |
| dist/dropzone.840966d2.js | 3.44kb | +0.00b | 517.00ms | -43.00ms 🚀 |
| dist/Modal.29e822bf.js | 3.14kb | +0.00b | 403.00ms | -95.00ms 🚀 |
| dist/clipboard.7188d6f8.js | 2.97kb | +0.00b | 528.00ms | -37.00ms 🚀 |
| dist/16.41f46c2f.js | 2.49kb | +0.00b | 403.00ms | -27.00ms 🚀 |
| dist/ResourcedEmojiComponent.9812a721.js | 2.15kb | +0.00b | 492.00ms | -44.00ms 🚀 |
| dist/card.a2f58842.js | 2.15kb | +0.00b | 517.00ms | -38.00ms 🚀 |
| dist/date.5e8b4b49.js | 1.96kb | +0.00b | 448.00ms | -42.00ms 🚀 |
| dist/images.e479dcbe.js | 1.90kb | +0.00b | 451.00ms | -46.00ms 🚀 |
| dist/feedback.00d01eca.js | 1.86kb | +0.00b | 483.00ms | -51.00ms 🚀 |
| dist/16.8ab9c9cf.js | 1.86kb | +0.00b | 433.00ms | -27.00ms 🚀 |
| dist/browser.8d5afc2b.js | 1.82kb | +0.00b | 528.00ms | -32.00ms 🚀 |
| dist/16.aa2b1e8c.js | 1.79kb | +0.00b | 421.00ms | -27.00ms 🚀 |
| dist/workerHasher.087b011b.js | 1.75kb | +0.00b | 528.00ms | -32.00ms 🚀 |
| dist/list-number.cc386df7.js | 1.68kb | +0.00b | 455.00ms | -46.00ms 🚀 |
| dist/status.008ba29f.js | 1.68kb | +0.00b | 462.00ms | -49.00ms 🚀 |
| dist/code.be6c45b5.js | 1.61kb | +0.00b | 448.00ms | -42.00ms 🚀 |
| dist/link.f7c12162.js | 1.53kb | +0.00b | 451.00ms | -47.00ms 🚀 |
| dist/heading6.a29cffb2.js | 1.53kb | +0.00b | 483.00ms | -30.00ms 🚀 |
| dist/heading3.2326b3c4.js | 1.51kb | +0.00b | 484.00ms | -29.00ms 🚀 |
| dist/16.b19b33ca.js | 1.51kb | +0.00b | 433.00ms | -26.00ms 🚀 |
| dist/16.15d9f682.js | 1.46kb | +0.00b | 421.00ms | -27.00ms 🚀 |
| dist/16.fe7e09db.js | 1.46kb | +0.00b | 422.00ms | -76.00ms 🚀 |
| dist/emoji.c2ecc9d7.js | 1.45kb | +0.00b | 451.00ms | -46.00ms 🚀 |
| dist/16.7fc8af6d.js | 1.45kb | +0.00b | 403.00ms | -27.00ms 🚀 |
| dist/16.474c8276.js | 1.44kb | +0.00b | 439.00ms | -38.00ms 🚀 |
| dist/16.d49a0bb7.js | 1.40kb | +0.00b | 438.00ms | -38.00ms 🚀 |
| dist/heading5.fa40b79e.js | 1.40kb | +0.00b | 483.00ms | -30.00ms 🚀 |
| dist/expand.944ff7ce.js | 1.38kb | +0.00b | 483.00ms | -51.00ms 🚀 |
| dist/16.c4941d0d.js | 1.36kb | +0.00b | 438.00ms | -38.00ms 🚀 |
| dist/16.a4fa1a69.js | 1.34kb | +0.00b | 402.00ms | -28.00ms 🚀 |
| dist/heading2.fa6667ad.js | 1.33kb | +0.00b | 484.00ms | -29.00ms 🚀 |
| dist/16.ad29438e.js | 1.32kb | +0.00b | 438.00ms | -38.00ms 🚀 |
| dist/16.3d7a389d.js | 1.31kb | +0.00b | 447.00ms | -43.00ms 🚀 |
| dist/mention.539104d0.js | 1.29kb | +0.00b | 455.00ms | -52.00ms 🚀 |
| dist/heading4.45b46e5b.js | 1.29kb | +0.00b | 484.00ms | -29.00ms 🚀 |
| dist/Modal.760be919.js | 1.28kb | +0.00b | 413.00ms | -28.00ms 🚀 |
| dist/16.55b14beb.js | 1.27kb | +0.00b | 402.00ms | -29.00ms 🚀 |
| dist/layout.61e66223.js | 1.27kb | +0.00b | 451.00ms | -46.00ms 🚀 |
| dist/16.45835899.js | 1.27kb | +0.00b | 433.00ms | -26.00ms 🚀 |
| dist/16.e83a0923.js | 1.26kb | +0.00b | 421.00ms | -27.00ms 🚀 |
| dist/16.d315628f.js | 1.26kb | +0.00b | 433.00ms | -26.00ms 🚀 |
| dist/16.cc8ae77e.js | 1.26kb | +0.00b | 433.00ms | -26.00ms 🚀 |
| dist/16.71387abf.js | 1.26kb | +0.00b | 421.00ms | -27.00ms 🚀 |
| dist/divider.d62a9038.js | 1.25kb | +0.00b | 451.00ms | -46.00ms 🚀 |
| dist/quote.05e17876.js | 1.25kb | +0.00b | 462.00ms | -49.00ms 🚀 |
| dist/component.5df34eb8.js | 1.23kb | +0.00b | 461.00ms | -38.00ms 🚀 |
| dist/action.7545becf.js | 1.23kb | +0.00b | 447.00ms | -43.00ms 🚀 |
| dist/16.f1c68cda.js | 1.23kb | +0.00b | 462.00ms | -37.00ms 🚀 |
| dist/media-card-analytics-error-boundary.d5ccfa87.js | 1.23kb | +0.00b | 506.00ms | -43.00ms 🚀 |
| dist/decision.aa61b855.js | 1.21kb | +0.00b | 448.00ms | -42.00ms 🚀 |
| dist/panel-warning.96ab13ca.js | 1.21kb | +0.00b | 462.00ms | -49.00ms 🚀 |
| dist/16.8cd85281.js | 1.18kb | +0.00b | 438.00ms | -38.00ms 🚀 |
| dist/list.2f1b17d3.js | 1.18kb | +0.00b | 455.00ms | -46.00ms 🚀 |
| dist/panel-error.aa8fc53d.js | 1.11kb | +0.00b | 455.00ms | -52.00ms 🚀 |
| dist/panel.e409d6fe.js | 1.10kb | +0.00b | 462.00ms | -49.00ms 🚀 |
| dist/panel-success.26c394f0.js | 1.05kb | +0.00b | 462.00ms | -49.00ms 🚀 |
| dist/panel-note.0319a3fe.js | 1.05kb | +0.00b | 455.00ms | -53.00ms 🚀 |
| dist/media-picker-analytics-error-boundary.3e4d365d.js | 1003.00b | +0.00b | 517.00ms | -43.00ms 🚀 |
| dist/media-card-analytics-error-boundary.2e3e2b28.js | 999.00b | +0.00b | 492.00ms | -57.00ms 🚀 |
| dist/media-card-analytics-error-boundary.ece1d621.js | 999.00b | +0.00b | 528.00ms | -32.00ms 🚀 |
| dist/media-viewer-analytics-error-boundary.9e64afc6.js | 995.00b | +0.00b | 517.00ms | -38.00ms 🚀 |
| dist/simpleHasher.042b95c1.js | 755.00b | +0.00b | 528.00ms | -32.00ms 🚀 |
| dist/index.html | 119.00b | +0.00b | 401.00ms | -44.00ms 🚀 |

</p></details>

<details><summary>Three.js ✅</summary><p>

#### Timings

| Description | Time | Difference |
| --- | --- | --- |
| Cold | 12.11s | -79.00ms |
| Cached | 564.00ms | -21.00ms |

#### Cold Bundles

*No bundle changes detected.*

#### Cached Bundles

| Bundle | Size | Difference | Time | Difference |
| --- | --- | --- | --- | --- |
| dist/Three.js | 580.59kb | +0.00b | 89.00ms | -5.00ms 🚀 |

</p></details>

**[Click here to view a detailed benchmark overview.](https://benchmark.parceljs.org/benchmark/287596788938965516)**

**Review by devongovett — APPROVED** [review]

**Comment by mischnic** [comment]
This broke after https://github.com/parcel-bundler/parcel/pull/5640 because `OptionalMemberExpression`s were converted into `MemberExpression`s with `optional: true` in the `ArrowFunctionExpression ` visitor and then the `MemberExpression` visitor unset `optional` again.

**Review by devongovett — APPROVED** [review]
Ugh... should we maybe also open an issue on astring for this? Seems like they are making an unsafe assumption here.

**Review by aminya — APPROVED** [review]

**Comment by danieltroger** [comment]
Can this be merged now?

**Comment by mischnic** [comment]
Is this a considerable performance benefit from that? There are many cases where they're doing that (search for `[0] ===` in that file)

**Pull request merged**
