### PR TITLE
Fix a few typos

### PR DESCRIPTION
**Pull request by striezel**
This pull request fixes a few typos. No functional changes intended.

### CODE REVIEW

**Comment by mischnic** [comment]
Can you update the branch?

**Comment by striezel** [comment]
> Can you update the branch?

@mischnic Yes, done.

**Comment by mischnic** [comment]
And it's unfortunately already outdated again. Usually I can update it but you seem to have that disabled:

Bildschirm­foto 2023-05-10 um 22 35 29

**Comment by striezel** [comment]
> And it's unfortunately already outdated again.

Updated again.

Should the branch become outdated again, then feel free to just use the merge option that rebases the changes on top of `v2`. This should give the same result.

**Review by mischnic — APPROVED** [review]

**Pull request merged**
